//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.GSTP.GSTP {
    
    
    public partial class Danhsachtonghop {
        
        /// <summary>
        /// ltrMapjs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrMapjs;
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// lstHethong control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lstHethong;
        
        /// <summary>
        /// lbtBack control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lbtBack;
        
        /// <summary>
        /// liGSTP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liGSTP;
        
        /// <summary>
        /// btnGSTP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnGSTP;
        
        /// <summary>
        /// liQLA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liQLA;
        
        /// <summary>
        /// btnQLA control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnQLA;
        
        /// <summary>
        /// liGDT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liGDT;
        
        /// <summary>
        /// btnGDT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnGDT;
        
        /// <summary>
        /// liTCCB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTCCB;
        
        /// <summary>
        /// btnTDKT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnTDKT;
        
        /// <summary>
        /// liTDKT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liTDKT;
        
        /// <summary>
        /// btnTCCB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnTCCB;
        
        /// <summary>
        /// liQTHT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liQTHT;
        
        /// <summary>
        /// btnQTHT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton btnQTHT;
        
        /// <summary>
        /// lstUserName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lstUserName;
        
        /// <summary>
        /// lstHoten control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lstHoten;
        
        /// <summary>
        /// lkSignout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lkSignout;
        
        /// <summary>
        /// MenuLeft control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MenuLeft;
        
        /// <summary>
        /// cmd_MenuLeft_Home control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmd_MenuLeft_Home;
        
        /// <summary>
        /// cmd_MenuLeft_DanhGiaThamPhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmd_MenuLeft_DanhGiaThamPhan;
        
        /// <summary>
        /// cmd_MenuLeft_ThongKe control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmd_MenuLeft_ThongKe;
        
        /// <summary>
        /// cmd_MenuLeft_HDSD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton cmd_MenuLeft_HDSD;
        
        /// <summary>
        /// MenuLeft_ex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MenuLeft_ex;
        
        /// <summary>
        /// LinkButton1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton1;
        
        /// <summary>
        /// LinkButton2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton2;
        
        /// <summary>
        /// LinkButton3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton3;
        
        /// <summary>
        /// LinkButton4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton LinkButton4;
        
        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        
        /// <summary>
        /// ltrTenTP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrTenTP;
        
        /// <summary>
        /// ltrChucDanh control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrChucDanh;
        
        /// <summary>
        /// ltrToaAn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrToaAn;
        
        /// <summary>
        /// ltrQuyetDinhBoNhiem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrQuyetDinhBoNhiem;
        
        /// <summary>
        /// ddlDonVi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlDonVi;
        
        /// <summary>
        /// GiaiDoanXetXu_SoTham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl GiaiDoanXetXu_SoTham;
        
        /// <summary>
        /// ltr_ST_TongThuLy_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_TongThuLy_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_TongThuLy_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_TongThuLy_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_GiaiQuyet_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_GiaiQuyet_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_GiaiQuyet_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_GiaiQuyet_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_ST_GiaiQuyet_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_GiaiQuyet_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_GiaiQuyet_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_GiaiQuyet_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_ST_AnHuy_Sua_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_AnHuy_Sua_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_AnHuy_Sua_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_AnHuy_Sua_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_ST_AnHuy_Sua_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_AnHuy_Sua_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_AnHuy_Sua_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_AnHuy_Sua_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_ST_Chua_GQ_Nam_Hientai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Chua_GQ_Nam_Hientai;
        
        /// <summary>
        /// ltr_ST_Chua_GQ_Nam_Hientai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Chua_GQ_Nam_Hientai_Percent;
        
        /// <summary>
        /// ltr_ST_Chua_GQ_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Chua_GQ_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_Chua_GQ_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Chua_GQ_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_ST_QuaHan_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_QuaHan_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_QuaHan_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_QuaHan_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_RutKN_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_RutKN_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_RutKN_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_RutKN_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_HinhSu_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_HinhSu_TongThuLy;
        
        /// <summary>
        /// ltr_ST_HinhSu_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_HinhSu_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_ST_DanSu_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_DanSu_TongThuLy;
        
        /// <summary>
        /// ltr_ST_DanSu_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_DanSu_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_ST_HNGD_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_HNGD_TongThuLy;
        
        /// <summary>
        /// ltr_ST_HNGD_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_HNGD_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_ST_KDTM_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_KDTM_TongThuLy;
        
        /// <summary>
        /// ltr_ST_KDTM_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_KDTM_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_ST_HanhChinh_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_HanhChinh_TongThuLy;
        
        /// <summary>
        /// ltr_ST_HanhChinh_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_HanhChinh_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_ST_LaoDong_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_LaoDong_TongThuLy;
        
        /// <summary>
        /// ltr_ST_LaoDong_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_LaoDong_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_ST_Don_DaNhan_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Don_DaNhan_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_Don_DaNhan_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Don_DaNhan_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_DonThuly_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_DonThuly_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_DonThuly__Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_DonThuly__Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_DonXLK_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_DonXLK_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_DonXLK_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_DonXLK_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_Don_ChuaGiaiQuyet_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Don_ChuaGiaiQuyet_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_Don_ChuaGiaiQuyet_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Don_ChuaGiaiQuyet_Nam_Truoc;
        
        /// <summary>
        /// ltr_ST_Don_QuaHan_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Don_QuaHan_Nam_HienTai;
        
        /// <summary>
        /// ltr_ST_Don_QuaHan_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_ST_Don_QuaHan_Nam_Truoc;
        
        /// <summary>
        /// GiaiDoanXetXu_PhucTham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl GiaiDoanXetXu_PhucTham;
        
        /// <summary>
        /// ltr_PT_TongThuLy_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_TongThuLy_Nam_HienTai;
        
        /// <summary>
        /// ltr_PT_TongThuLy_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_TongThuLy_Nam_Truoc;
        
        /// <summary>
        /// ltr_PT_GiaiQuyet_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_GiaiQuyet_Nam_HienTai;
        
        /// <summary>
        /// ltr_PT_GiaiQuyet_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_GiaiQuyet_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_PT_GiaiQuyet_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_GiaiQuyet_Nam_Truoc;
        
        /// <summary>
        /// ltr_PT_GiaiQuyet_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_GiaiQuyet_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_PT_AnHuy_Sua_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_AnHuy_Sua_Nam_HienTai;
        
        /// <summary>
        /// ltr_PT_AnHuy_Sua_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_AnHuy_Sua_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_PT_AnHuy_Sua_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_AnHuy_Sua_Nam_Truoc;
        
        /// <summary>
        /// ltr_PT_AnHuy_Sua_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_AnHuy_Sua_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_PT_Chua_GQ_Nam_Hientai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_Chua_GQ_Nam_Hientai;
        
        /// <summary>
        /// ltr_PT_Chua_GQ_Nam_Hientai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_Chua_GQ_Nam_Hientai_Percent;
        
        /// <summary>
        /// ltr_PT_Chua_GQ_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_Chua_GQ_Nam_Truoc;
        
        /// <summary>
        /// ltr_PT_Chua_GQ_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_Chua_GQ_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_PT_QuaHan_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_QuaHan_Nam_HienTai;
        
        /// <summary>
        /// ltr_PT_QuaHan_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_QuaHan_Nam_Truoc;
        
        /// <summary>
        /// ltr_PT_RutKN_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_RutKN_Nam_HienTai;
        
        /// <summary>
        /// ltr_PT_RutKN_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_RutKN_Nam_Truoc;
        
        /// <summary>
        /// ltr_PT_HinhSu_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_HinhSu_TongThuLy;
        
        /// <summary>
        /// ltr_PT_HinhSu_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_HinhSu_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_PT_DanSu_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_DanSu_TongThuLy;
        
        /// <summary>
        /// ltr_PT_DanSu_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_DanSu_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_PT_HNGD_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_HNGD_TongThuLy;
        
        /// <summary>
        /// ltr_PT_HNGD_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_HNGD_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_PT_KDTM_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_KDTM_TongThuLy;
        
        /// <summary>
        /// ltr_PT_KDTM_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_KDTM_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_PT_HanhChinh_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_HanhChinh_TongThuLy;
        
        /// <summary>
        /// ltr_PT_HanhChinh_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_HanhChinh_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_PT_LaoDong_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_LaoDong_TongThuLy;
        
        /// <summary>
        /// ltr_PT_LaoDong_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_PT_LaoDong_TongGiaiQuyet;
        
        /// <summary>
        /// GiaiDoanXetXu_DonGDT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl GiaiDoanXetXu_DonGDT;
        
        /// <summary>
        /// ltr_Don_VuAn_DonDeNghi_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_DonDeNghi_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_VuAn_DonDeNghi_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_DonDeNghi_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_VuAn_8_1_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_8_1_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_VuAn_8_1_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_8_1_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_VuAn_ThoiHieu_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_ThoiHieu_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_VuAn_ThoiHieu_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_ThoiHieu_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_VuAn_GiaiQuyetXong_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_GiaiQuyetXong_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_VuAn_GiaiQuyetXong_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_GiaiQuyetXong_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_Don_VuAn_GiaiQuyetXong_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_GiaiQuyetXong_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_VuAn_GiaiQuyetXong_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_GiaiQuyetXong_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_Don_VuAn_ChuaXong_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_ChuaXong_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_VuAn_ChuaXong_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_ChuaXong_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_Don_VuAn_ChuaXong_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_ChuaXong_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_VuAn_ChuaXong_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_VuAn_ChuaXong_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_Don_Tong_DonDeNghi_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Tong_DonDeNghi_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_Tong_DonDeNghi_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Tong_DonDeNghi_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_Chuyen_Vu1_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Vu1_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_Chuyen_Vu1_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Vu1_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_Chuyen_Vu2_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Vu2_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_Chuyen_Vu2_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Vu2_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_Chuyen_Vu3_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Vu3_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_Chuyen_Vu3_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Vu3_Nam_Truoc;
        
        /// <summary>
        /// ltr_Don_Chuyen_Khac_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Khac_Nam_HienTai;
        
        /// <summary>
        /// ltr_Don_Chuyen_Khac_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_Don_Chuyen_Khac_Nam_Truoc;
        
        /// <summary>
        /// GiaiDoanXetXu_GDT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl GiaiDoanXetXu_GDT;
        
        /// <summary>
        /// ltr_XetXu_TongThuLy_Nam_Hientai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_TongThuLy_Nam_Hientai;
        
        /// <summary>
        /// ltr_XetXu_TongThuLy_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_TongThuLy_Nam_Truoc;
        
        /// <summary>
        /// ltr_XetXu_GiaiQuyetXong_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_GiaiQuyetXong_Nam_HienTai;
        
        /// <summary>
        /// ltr_XetXu_GiaiQuyetXong_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_GiaiQuyetXong_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_XetXu_GiaiQuyetXong_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_GiaiQuyetXong_Nam_Truoc;
        
        /// <summary>
        /// ltr_XetXu_GiaiQuyetXong_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_GiaiQuyetXong_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_XetXu_ChuaXong_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_ChuaXong_Nam_HienTai;
        
        /// <summary>
        /// ltr_XetXu_ChuaXong_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_ChuaXong_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_XetXu_ChuaXong_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_ChuaXong_Nam_Truoc;
        
        /// <summary>
        /// ltr_XetXu_ChuaXong_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_ChuaXong_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_XetXu_QuaHan_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_QuaHan_Nam_HienTai;
        
        /// <summary>
        /// ltr_XetXu_QuaHan_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_QuaHan_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_XetXu_QuaHan_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_QuaHan_Nam_Truoc;
        
        /// <summary>
        /// ltr_XetXu_QuaHan_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_QuaHan_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_XetXu_HinhSu_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_HinhSu_TongThuLy;
        
        /// <summary>
        /// ltr_XetXu_HinhSu_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_HinhSu_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_XetXu_DanSu_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_DanSu_TongThuLy;
        
        /// <summary>
        /// ltr_XetXu_DanSu_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_DanSu_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_XetXu_HNGD_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_HNGD_TongThuLy;
        
        /// <summary>
        /// ltr_XetXu_HNGD_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_HNGD_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_XetXu_KDTM_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_KDTM_TongThuLy;
        
        /// <summary>
        /// ltr_XetXu_KDTM_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_KDTM_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_XetXu_HanhChinh_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_HanhChinh_TongThuLy;
        
        /// <summary>
        /// ltr_XetXu_HanhChinh_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_HanhChinh_TongGiaiQuyet;
        
        /// <summary>
        /// ltr_XetXu_LaoDong_TongThuLy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_LaoDong_TongThuLy;
        
        /// <summary>
        /// ltr_XetXu_LaoDong_TongGiaiQuyet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_XetXu_LaoDong_TongGiaiQuyet;
        
        /// <summary>
        /// ThongkeThamPhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl ThongkeThamPhan;
        
        /// <summary>
        /// ltr_TP_DangCongTac_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_DangCongTac_Nam_HienTai;
        
        /// <summary>
        /// ltr_TP_DangCongTac_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_DangCongTac_Nam_Truoc;
        
        /// <summary>
        /// ltr_TP_NhiemKy_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_NhiemKy_Nam_HienTai;
        
        /// <summary>
        /// ltr_TP_NhiemKy_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_NhiemKy_Nam_Truoc;
        
        /// <summary>
        /// ltr_TP_DungXetXu_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_DungXetXu_Nam_HienTai;
        
        /// <summary>
        /// ltr_TP_DungXetXu_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_DungXetXu_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_TP_DungXetXu_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_DungXetXu_Nam_Truoc;
        
        /// <summary>
        /// ltr_TP_DungXetXu_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_DungXetXu_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_TP_KhieuNai_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_KhieuNai_Nam_HienTai;
        
        /// <summary>
        /// ltr_TP_KhieuNai_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_KhieuNai_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_TP_KhieuNai_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_KhieuNai_Nam_Truoc;
        
        /// <summary>
        /// ltr_TP_KhieuNai_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_KhieuNai_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_TP_AnHuy_Sua_Nam_HienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_AnHuy_Sua_Nam_HienTai;
        
        /// <summary>
        /// ltr_TP_AnHuy_Sua_Nam_HienTai_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_AnHuy_Sua_Nam_HienTai_Percent;
        
        /// <summary>
        /// ltr_TP_AnHuy_Sua_Nam_Truoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_AnHuy_Sua_Nam_Truoc;
        
        /// <summary>
        /// ltr_TP_AnHuy_Sua_Nam_Truoc_Percent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_AnHuy_Sua_Nam_Truoc_Percent;
        
        /// <summary>
        /// ltr_TP_AnHuy_Sua_QD120 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltr_TP_AnHuy_Sua_QD120;
        
        /// <summary>
        /// NoiDung_BanDo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl NoiDung_BanDo;
        
        /// <summary>
        /// ddlPhamvi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlPhamvi;
        
        /// <summary>
        /// state_list control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect state_list;
        
        /// <summary>
        /// ltrPie_Phamvi control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrPie_Phamvi;
        
        /// <summary>
        /// lbtCallDanhSachThamPhan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtCallDanhSachThamPhan;
        
        /// <summary>
        /// lbtCallPage2_SoTham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtCallPage2_SoTham;
        
        /// <summary>
        /// lbtCallPage2_PhucTham control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtCallPage2_PhucTham;
        
        /// <summary>
        /// lbtCallPage2_GDT control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtCallPage2_GDT;
        
        /// <summary>
        /// lbtCallPage2_BAQD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtCallPage2_BAQD;
        
        /// <summary>
        /// lbtCallPage2_BAQD_Public control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button lbtCallPage2_BAQD_Public;
        
        /// <summary>
        /// ltrBA_DaXetXu_NamHienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrBA_DaXetXu_NamHienTai;
        
        /// <summary>
        /// ltrBA_DaXetXu_NamTruoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrBA_DaXetXu_NamTruoc;
        
        /// <summary>
        /// ltrBA_KCKN_NamHienTai control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrBA_KCKN_NamHienTai;
        
        /// <summary>
        /// ltrBA_KCKN_NamTruoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal ltrBA_KCKN_NamTruoc;
        
        /// <summary>
        /// lbl_COLUMN_1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_1;
        
        /// <summary>
        /// lbl_COLUMN_2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_2;
        
        /// <summary>
        /// lbl_COLUMN_7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_7;
        
        /// <summary>
        /// lbl_COLUMN_8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_8;
        
        /// <summary>
        /// lbl_COLUMN_3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_3;
        
        /// <summary>
        /// lbl_COLUMN_4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_4;
        
        /// <summary>
        /// lbl_COLUMN_9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_9;
        
        /// <summary>
        /// lbl_COLUMN_10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_10;
        
        /// <summary>
        /// lbl_COLUMN_5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_5;
        
        /// <summary>
        /// lbl_COLUMN_6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_6;
        
        /// <summary>
        /// lbl_COLUMN_11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_11;
        
        /// <summary>
        /// lbl_COLUMN_12 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lbl_COLUMN_12;
    }
}
