B1. STOP ỨNG DỤNG (TRÁNH MẤT MÁT DỮ LIỆU VÀ ẢNH HƯỞNG ĐẾN NGƯỜI DÙNG)
B2. BACKUP TABLE
    CREATE TABLE GSCM.GDTTT_DON_BAK AS SELECT * FROM GSCM.GDTTT_DON;
B3. KIỂM TRA ĐỘ DÀI CỦA COLUMN (NOIDUNGDON NCLOB) CẦN CONVERT
 SELECT MAX (LENGTH (NOIDUNGDON)) MAX_LEN FROM GSCM.GDTTT_DON
 WHERE ROWNUM = 1; ---MAX=1736
B4. THÊM TRƯỜNG MỚI NOIDUNGDON_TMP CÓ LENGTH TỐI THIỂU >=MAX (LENGTH (NOIDUNGDON)) 
	ALTER TABLE GDTTT_DON ADD NOIDUNGDON_TMP VARCHAR2(2000);
B5. CHUYỂN ĐỔI DỮ LIỆU CONVERT TỪ TRƯỜNG CŨ SANG TRƯỜNG MỚI
	UPDATE GDTTT_DON SET NOIDUNGDON_TMP=SUBSTR(NOIDUNGDON,1,LENGTH(TRIM(NOIDUNGDON)));
	COMMIT;	
B6. XÓA COLUMN DỮ LIỆU CŨ NOIDUNGDON Ở DẠNG NCLOB	
	ALTER TABLE GSCM.GDTTT_DON DROP COLUMN NOIDUNGDON;
B7. RENAME COLUMN NOIDUNGDON_TMP
	ALTER TABLE GSCM.GDTTT_DON RENAME COLUMN  NOIDUNGDON_TMP TO NOIDUNGDON;
B8. START ỨNG DỤNG VÀ KIỂM TRA.
B9. XÓA TABLE BACKUP (NÊN ĐỂ MỘT THỜI GIAN SAU)
	DROP TABLE GDTTT_DON_BAK;