SELECT TT.STT,NULL AS "MÃ CỤC, CHI CỤC THA",TT.MA_TEN "TÊN CỤC, CHI CỤC THA",NULL "ĐỊA CHỈ CỤC, CHI CỤC THA"
,NULL "ĐIỆN THOẠI CỤC, CHI CỤC THA"
,TT.MA_DINH_DANH "MÃ ĐỊNH DANH",TT.SOTAIKHOANKB "SỐ TÀI KHẢN",TT.TENKHOBAC "TÊN KHO BẠC"
,TT.MAKHOBAC "MÃ KHO BẠC",TT.MALOAIHINHTHU "MÃ LOẠI HÌNH THU",TT.TENLOAIHINHTHU "TÊN LOẠI HÌNH THU"
,TT.EMAIL "Email"
,TT.ID,TT.MADONGBO FROM (
Select COUNT(*) OVER()COUNTALL,ROW_NUMBER() OVER (ORDER BY mn.ARRTHUTU) STT,mn.ID,mn.ARRSAPXEP,
    ((CASE (LENGTH(REPLACE(mn.ARRTHUTU,'/'))-1)/3 
        WHEN 2 THEN '..' WHEN 3 THEN'....' WHEN 4 THEN '......'
        WHEN 5 THEN '........' WHEN 6 THEN '..........' ELSE '' END) || MN.MA_TEN) as MA_TEN,
         ((CASE (LENGTH(REPLACE(mn.ARRTHUTU,'/'))-1)/3 
        WHEN 2 THEN '..' WHEN 3 THEN'....' WHEN 4 THEN '......'
        WHEN 5 THEN '........' WHEN 6 THEN '..........' ELSE '' END) || mn.TEN) as TEN,MN.DIACHI,mn.DIENTHOAI,mn.EMAIL
        ,mn.MADONGBO,mn.MA_DINH_DANH,mn.SOCAP
        ,LH.MA MALOAIHINHTHU,LH.TEN TENLOAIHINHTHU,TK.SOTK_KHOBAC SOTAIKHOANKB,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC
    from DM_DONVITHIHANHAN mn    
    LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=mn.ID
    LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
    where  1=(Case when 0=1 and mn.id=1 then 1 when 0=0 and (mn.ARRSAPXEP like ('0' ||'/%') or mn.ARRSAPXEP='0') then 1 else 0 End)
)TT
WHERE UPPER(TT.MA_TEN) NOT LIKE '%NHÓM%';

--SELECT * FROM DM_DONVITHIHANHAN ;
--SELECT * FROM DM_DONVITHIHANHAN WHERE id=526;
--SELECT * FROM DM_DONVITHIHANHAN WHERE UPPER(TEN) like '%HÀ NỘI%';
--
--SELECT * FROM DM_DONVITHIHANHAN WHERE (CAPCHAID=27 OR ID=27);
--
--SELECT * FROM DM_LOAIHINH_THU;
--SELECT * FROM DVCQG_THANH_TOAN;
--SELECT * FROM DM_THA_THANHTOAN;
--SELECT * FROM DM_TK_THANHTOAN;
  