   CREATE SEQUENCE  "C06_TOAAN_LAODONG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "C06_TOAAN_KDTM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "C06_TOAAN_HINHSU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "C06_TOAAN_HANHCHINH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "C06_TOAAN_DANSU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "C06_TOAAN_HINHSU_QD_THA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

   CREATE SEQUENCE  "C06_TOAAN_HINHSU_HISTORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
   
   
   CREATE TABLE "C06_TOAAN_DANSU_HISTORY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LYDO_THUHOI" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"NOIDUNG" CLOB NOT NULL ENABLE, 
	"DONGBOID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGUOITHUHOI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGAYTHUHOI" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   ) ;

     CREATE TABLE "C06_TOAAN_LAODONG_HISTORY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LYDO_THUHOI" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"NOIDUNG" CLOB NOT NULL ENABLE, 
	"DONGBOID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGUOITHUHOI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGAYTHUHOI" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   ) ;
   
   CREATE TABLE "C06_TOAAN_HANHCHINH_HISTORY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LYDO_THUHOI" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"NOIDUNG" CLOB NOT NULL ENABLE, 
	"DONGBOID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGUOITHUHOI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGAYTHUHOI" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   ) ;
   
     CREATE TABLE "C06_TOAAN_KDTM_HISTORY" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LYDO_THUHOI" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"NOIDUNG" CLOB NOT NULL ENABLE, 
	"DONGBOID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGUOITHUHOI" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NGAYTHUHOI" DATE NOT NULL ENABLE, 
	 PRIMARY KEY ("ID")
   ) ;



  CREATE TABLE "C06_TOAAN_DANSU" 
   (	"ID" NUMBER, 
	"SOBANANORQD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NGAYRABANAN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MADONVIRABANAN" VARCHAR2(255 CHAR), 
	"TENDONVIRABANAN" VARCHAR2(255 CHAR), 
	"BQD" VARCHAR2(255 CHAR), 
	"ANPHI" NUMBER(18,2), 
	"NGAYHIEULUCBA" VARCHAR2(255 CHAR), 
	"HOTENDUONGSU" VARCHAR2(255 CHAR), 
	"SOGIAYTODUONGSU" VARCHAR2(255 CHAR), 
	"NGAYSINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUOCTICHDUONGSU" VARCHAR2(500 BYTE), 
	"TENQUOCTICHDUONGSU" VARCHAR2(255 CHAR), 
	"MATHANHPHOTINHDUONGSU" VARCHAR2(255 BYTE), 
	"TENTHANHPHOTINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUANHUYENDUONGSU" VARCHAR2(200 CHAR), 
	"TENQUANHUYENDUONGSU" VARCHAR2(255 BYTE), 
	"MAPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"TENPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"DIACHIDUONGSU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIADS" VARCHAR2(255 BYTE) DEFAULT 'HIEU_LUC', 
	"GHICHU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIJOBSHARE" VARCHAR2(20 BYTE) DEFAULT '0', 
	"VUANID" NUMBER, 
	"DUONGSUID" NUMBER, 
	"NGAYGUI" DATE DEFAULT sysdate, 
	"TAIKHOANGUI" VARCHAR2(20 BYTE), 
	"NGAYDONGBO" DATE, 
	"TENVUAN" VARCHAR2(1000 BYTE), 
	"THULY" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CAPXX" VARCHAR2(200 BYTE), 
	"MAQUANHEPHAPLUAT" VARCHAR2(255 BYTE), 
	"TENQUANHEPHAPLUAT" VARCHAR2(1000 BYTE), 
	"MATUCACHTOTUNG" VARCHAR2(255 BYTE), 
	"TENTUCACHTOTUNG" VARCHAR2(255 BYTE), 
	"LOAIBAQD" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("ID")
   );
/
  CREATE OR REPLACE EDITIONABLE TRIGGER "C06_TOAAN_DANSU_TRG" 
BEFORE INSERT ON C06_TOAAN_DANSU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT C06_TOAAN_DANSU_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "C06_TOAAN_DANSU_TRG" ENABLE;

/


  CREATE TABLE "C06_TOAAN_HANHCHINH" 
   (	"ID" NUMBER, 
	"SOBANANORQD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NGAYRABANAN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MADONVIRABANAN" VARCHAR2(255 CHAR), 
	"TENDONVIRABANAN" VARCHAR2(255 CHAR), 
	"BQD" VARCHAR2(255 CHAR), 
	"MAQUANHEPHAPLUAT" VARCHAR2(255 CHAR), 
	"TENQUANHEPHAPLUAT" VARCHAR2(1000 CHAR), 
	"MATUCACHTOTUNG" VARCHAR2(255 CHAR), 
	"TENTUCACHTOTUNG" VARCHAR2(255 CHAR), 
	"ANPHI" NUMBER(18,2), 
	"NGAYHIEULUCBA" VARCHAR2(255 CHAR), 
	"HOTENDUONGSU" VARCHAR2(255 CHAR), 
	"SOGIAYTODUONGSU" VARCHAR2(255 CHAR), 
	"NGAYSINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUOCTICHDUONGSU" VARCHAR2(500 BYTE), 
	"TENQUOCTICHDUONGSU" VARCHAR2(255 CHAR), 
	"MATHANHPHOTINHDUONGSU" VARCHAR2(255 BYTE), 
	"TENTHANHPHOTINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUANHUYENDUONGSU" VARCHAR2(200 CHAR), 
	"TENQUANHUYENDUONGSU" VARCHAR2(255 BYTE), 
	"MAPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"TENPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"DIACHIDUONGSU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIAHC" VARCHAR2(255 BYTE) DEFAULT 'HIEU_LUC', 
	"GHICHU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIJOBSHARE" VARCHAR2(20 BYTE) DEFAULT '0', 
	"VUANID" NUMBER, 
	"DUONGSUID" NUMBER, 
	"NGAYGUI" DATE DEFAULT sysdate, 
	"TAIKHOANGUI" VARCHAR2(20 BYTE), 
	"NGAYDONGBO" DATE, 
	"TENVUAN" VARCHAR2(1000 BYTE), 
	"THULY" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CAPXX" VARCHAR2(50 BYTE), 
	"LOAIBAQD" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("ID")
     );

  CREATE OR REPLACE EDITIONABLE TRIGGER "C06_TOAAN_HANHCHINH_TRG" 
BEFORE INSERT ON C06_TOAAN_HANHCHINH 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT C06_TOAAN_HANHCHINH_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C06_TOAAN_HANHCHINH_TRG" ENABLE;
/


  CREATE TABLE "C06_TOAAN_HINHSU" 
   (	"ID" NUMBER, 
	"SOBANANORQD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NGAYRABANAN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MADONVIRABANAN" VARCHAR2(255 CHAR), 
	"TENDONVIRABANAN" VARCHAR2(255 CHAR), 
	"BQD" VARCHAR2(255 CHAR), 
	"DSTOIDANH" VARCHAR2(4000 CHAR), 
	"MAHINHPHATCHINH" VARCHAR2(255 CHAR), 
	"TENHINHPHATCHINH" VARCHAR2(255 CHAR), 
	"THAMSOHINHPHATCHINH" VARCHAR2(255 CHAR), 
	"DSHINHPHATBOSUNG" VARCHAR2(4000 CHAR), 
	"NGAYHIEULUCBA" VARCHAR2(255 CHAR), 
	"HOTENBICAO" VARCHAR2(255 CHAR), 
	"SOGIAYTOBICAO" VARCHAR2(255 CHAR), 
	"NGAYSINHBICAO" VARCHAR2(255 CHAR), 
	"MAQUOCTICHBICAO" VARCHAR2(500 BYTE), 
	"TENQUOCTICHBICAO" VARCHAR2(255 CHAR), 
	"MATHANHPHOTINHBICAO" VARCHAR2(255 BYTE), 
	"TENTHANHPHOTINHBICAO" VARCHAR2(255 CHAR), 
	"MAQUANHUYENBICAO" VARCHAR2(200 CHAR), 
	"TENQUANHUYENBICAO" VARCHAR2(255 BYTE), 
	"MAPHUONGXABICAO" VARCHAR2(255 BYTE), 
	"TENPHUONGXABICAO" VARCHAR2(255 BYTE), 
	"DIACHIBICAO" VARCHAR2(4000 BYTE), 
	"TRANGTHAIAHS" VARCHAR2(255 BYTE) DEFAULT 'HIEU_LUC', 
	"GHICHU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIJOBSHARE" VARCHAR2(20 BYTE) DEFAULT '0', 
	"VUANID" NUMBER, 
	"BICANID" NUMBER, 
	"NGAYGUI" DATE DEFAULT sysdate, 
	"TAIKHOANGUI" VARCHAR2(20 BYTE), 
	"NGAYDONGBO" DATE, 
	"TENVUAN" VARCHAR2(1000 BYTE), 
	"THULY" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 1, 
	"MADONGBOID" VARCHAR2(20 BYTE), 
	"CAPXX" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("ID")
   );


  CREATE TABLE "C06_TOAAN_KDTM" 
   (	"ID" NUMBER, 
	"SOBANANORQD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NGAYRABANAN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MADONVIRABANAN" VARCHAR2(255 CHAR), 
	"TENDONVIRABANAN" VARCHAR2(255 CHAR), 
	"BQD" VARCHAR2(255 CHAR), 
	"MAQUANHEPHAPLUAT" VARCHAR2(255 CHAR), 
	"TENQUANHEPHAPLUAT" VARCHAR2(1000 CHAR), 
	"MATUCACHTOTUNG" VARCHAR2(255 CHAR), 
	"TENTUCACHTOTUNG" VARCHAR2(255 CHAR), 
	"ANPHI" NUMBER(18,2), 
	"NGAYHIEULUCBA" VARCHAR2(255 CHAR), 
	"HOTENDUONGSU" VARCHAR2(255 CHAR), 
	"SOGIAYTODUONGSU" VARCHAR2(255 CHAR), 
	"NGAYSINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUOCTICHDUONGSU" VARCHAR2(500 BYTE), 
	"TENQUOCTICHDUONGSU" VARCHAR2(255 CHAR), 
	"MATHANHPHOTINHDUONGSU" VARCHAR2(255 BYTE), 
	"TENTHANHPHOTINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUANHUYENDUONGSU" VARCHAR2(200 CHAR), 
	"TENQUANHUYENDUONGSU" VARCHAR2(255 BYTE), 
	"MAPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"TENPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"DIACHIDUONGSU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIAKDTM" VARCHAR2(255 BYTE) DEFAULT 'HIEU_LUC', 
	"GHICHU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIJOBSHARE" VARCHAR2(20 BYTE) DEFAULT '0', 
	"VUANID" NUMBER, 
	"DUONGSUID" NUMBER, 
	"NGAYGUI" DATE DEFAULT sysdate, 
	"TAIKHOANGUI" VARCHAR2(20 BYTE), 
	"NGAYDONGBO" DATE, 
	"TENVUAN" VARCHAR2(1000 BYTE), 
	"THULY" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CAPXX" VARCHAR2(50 BYTE), 
	"LOAIBAQD" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("ID")
   );

  CREATE OR REPLACE EDITIONABLE TRIGGER "C06_TOAAN_KDTM_TRG" 
BEFORE INSERT ON C06_TOAAN_KDTM 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT C06_TOAAN_KDTM_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C06_TOAAN_KDTM_TRG" ENABLE;

/



  CREATE TABLE "C06_TOAAN_LAODONG" 
   (	"ID" NUMBER, 
	"SOBANANORQD" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NGAYRABANAN" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"MADONVIRABANAN" VARCHAR2(255 CHAR), 
	"TENDONVIRABANAN" VARCHAR2(255 CHAR), 
	"BQD" VARCHAR2(255 CHAR), 
	"MAQUANHEPHAPLUAT" VARCHAR2(255 CHAR), 
	"TENQUANHEPHAPLUAT" VARCHAR2(1000 CHAR), 
	"MATUCACHTOTUNG" VARCHAR2(255 CHAR), 
	"TENTUCACHTOTUNG" VARCHAR2(255 CHAR), 
	"ANPHI" NUMBER(18,2), 
	"NGAYHIEULUCBA" VARCHAR2(255 CHAR), 
	"HOTENDUONGSU" VARCHAR2(255 CHAR), 
	"SOGIAYTODUONGSU" VARCHAR2(255 CHAR), 
	"NGAYSINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUOCTICHDUONGSU" VARCHAR2(500 BYTE), 
	"TENQUOCTICHDUONGSU" VARCHAR2(255 CHAR), 
	"MATHANHPHOTINHDUONGSU" VARCHAR2(255 BYTE), 
	"TENTHANHPHOTINHDUONGSU" VARCHAR2(255 CHAR), 
	"MAQUANHUYENDUONGSU" VARCHAR2(200 CHAR), 
	"TENQUANHUYENDUONGSU" VARCHAR2(255 BYTE), 
	"MAPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"TENPHUONGXADUONGSU" VARCHAR2(255 BYTE), 
	"DIACHIDUONGSU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIALD" VARCHAR2(255 BYTE) DEFAULT 'HIEU_LUC', 
	"GHICHU" VARCHAR2(4000 BYTE), 
	"TRANGTHAIJOBSHARE" VARCHAR2(20 BYTE) DEFAULT '0', 
	"VUANID" NUMBER, 
	"DUONGSUID" NUMBER, 
	"NGAYGUI" DATE DEFAULT sysdate, 
	"TAIKHOANGUI" VARCHAR2(20 BYTE), 
	"NGAYDONGBO" DATE, 
	"TENVUAN" VARCHAR2(1000 BYTE), 
	"THULY" VARCHAR2(1000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CAPXX" VARCHAR2(50 BYTE), 
	"LOAIBAQD" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("ID")
   )  ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "C06_TOAAN_LAODONG_TRG" 
BEFORE INSERT ON C06_TOAAN_LAODONG 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT C06_TOAAN_LAODONG_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "C06_TOAAN_LAODONG_TRG" ENABLE;
/


  CREATE TABLE "C06_TOAAN_HINHSU_HISTORY" 
   (	"ID" NUMBER, 
	"LYDO_THUHOI" VARCHAR2(1000 CHAR), 
	"NOIDUNG" CLOB, 
	"C06_AHS_ID" NUMBER, 
	"NGUOITHUHOI" VARCHAR2(20 BYTE), 
	"NGAYTHUHOI" DATE, 
	 PRIMARY KEY ("ID")
  ) ;
