--------------------------------------------------------
--  DDL for Package Body PACKAGE_UPDATE_DATA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "GSCM"."PACKAGE_UPDATE_DATA" AS

    /*DELETE_DATA_AHS_SOTHAM_BANAN_DIEU_CHITIET - Xóa dữ liệu dư thừa ở bảng AHS_SOTHAM_BANAN_DIEU_CHITIET qua các trường BICANID, VUANID*/
    PROCEDURE DELETE_DATA_AHS_SOTHAM_BANAN_DIEU_CHITIET
    ( 
        curReturn OUT sys_refcursor
    )
    IS 
    BEGIN
        DELETE FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE TOIDANHID = 0;

        FOR ITEM IN (SELECT CT.ID, CT.BICANID
                     FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
                        LEFT JOIN AHS_BICANBICAO BC ON BC.ID = CT.BICANID
                     WHERE NOT EXISTS(SELECT 'X' FROM AHS_BICANBICAO BC WHERE BC.ID = CT.BICANID))
        LOOP
            DELETE FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE ID = ITEM.ID;
        END LOOP;

        COMMIT;

        OPEN curReturn FOR SELECT 1 FROM DUAL;
    END DELETE_DATA_AHS_SOTHAM_BANAN_DIEU_CHITIET;

    /*UPDATE_AHS_SOTHAM_BANAN_DIEU_CHITIET - Update các trường VUANID,TENTOIDANH,ISMAIN */
    PROCEDURE UPDATE_AHS_SOTHAM_BANAN_DIEU_CHITIET
    ( 
        curReturn OUT sys_refcursor
    )
    IS 
      VVUANID NUMBER;
      VBANANID NUMBER;
      VCHECK NUMBER;

      VTOIDANH_TEN VARCHAR(4000);
      VTOIDANH_LOAI NUMBER;

    BEGIN

       -- Insert bổ sung các tội danh thiếu
       FOR ITEM IN (SELECT * 
                    FROM (  SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM
                            FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
                            WHERE CT.TOIDANHID != 0
                            GROUP BY CT.BICANID)
                    WHERE SUM = 0)
       LOOP

           FOR ITEMS IN (SELECT CT.BICANID, DM.CAPCHAID, DM.LOAI
                         FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
                            INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI != 2
                         WHERE CT.BICANID = ITEM.BICANID
                         ORDER BY DM.LOAI DESC)
           LOOP
               VCHECK := 0;

               SELECT COUNT('X') INTO VCHECK
               FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
               WHERE CT.BICANID = ITEM.BICANID AND CT.TOIDANHID = ITEMS.CAPCHAID;

               IF(VCHECK = 0) THEN
                   INSERT INTO AHS_SOTHAM_BANAN_DIEU_CHITIET (BICANID, TOIDANHID, DIEULUATID, ISCHANGE, LOAIHINHPHAT, HINHPHATID, ISMAIN) 
                                                      VALUES (ITEM.BICANID, ITEMS.CAPCHAID, 7, 0, 0, 0, 0);
               END IF;

           END LOOP;

           /*Chạy lần 2 để không bỏ sót trường hợp LOAI = 4*/
           FOR ITEMS IN (SELECT CT.BICANID, DM.CAPCHAID, DM.LOAI
           FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
              INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI != 2
           WHERE CT.BICANID = ITEM.BICANID
           ORDER BY DM.LOAI DESC)
           LOOP
               VCHECK := 0;

               SELECT COUNT('X') INTO VCHECK
               FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
               WHERE CT.BICANID = ITEM.BICANID AND CT.TOIDANHID = ITEMS.CAPCHAID;

               IF(VCHECK = 0) THEN
                   INSERT INTO AHS_SOTHAM_BANAN_DIEU_CHITIET (BICANID, TOIDANHID, DIEULUATID, ISCHANGE, LOAIHINHPHAT, HINHPHATID, ISMAIN) 
                                                      VALUES (ITEM.BICANID, ITEMS.CAPCHAID, 7, 0, 0, 0, 0);
               END IF;

           END LOOP;
       END LOOP;


        -- Update AHS_SOTHAM_BANAN_DIEU_CHITIET.ISMAIN nếu NULL thì SET ISMAIN = 0       
       FOR ITEM IN (SELECT CT.ID FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT WHERE CT.ISMAIN IS NULL)
       LOOP
            UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET ISMAIN = 0 WHERE ID = ITEM.ID; 
       END LOOP;      



       -- Update VUANID, BANANID, TENTOIDANH bảng AHS_SOTHAM_BANAN_DIEU_CHITIET
       FOR ITEM IN (SELECT * FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE TOIDANHID != 0)
       LOOP

           VCHECK :=0 ; VVUANID := 0; VBANANID:= 0;

           SELECT COUNT('X') INTO VCHECK FROM AHS_BICANBICAO BC WHERE ITEM.BICANID = BC.ID;                     
           IF(VCHECK > 0) THEN 

               SELECT BC.VUANID, BA.ID INTO VVUANID, VBANANID
               FROM AHS_BICANBICAO BC 
                   LEFT JOIN AHS_SOTHAM_BANAN BA ON BA.VUANID = BC.VUANID
               WHERE ITEM.BICANID = BC.ID;

               UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET VUANID = VVUANID, BANANID = VBANANID WHERE ID = ITEM.ID;                       
           END IF;  

           VCHECK :=0; VTOIDANH_TEN:= '';

           SELECT COUNT('X') INTO VCHECK FROM DM_BOLUAT_TOIDANH DM WHERE DM.ID = ITEM.TOIDANHID;
            IF (VCHECK > 0) THEN 
                SELECT DM.TENTOIDANH INTO VTOIDANH_TEN FROM DM_BOLUAT_TOIDANH DM WHERE DM.ID = ITEM.TOIDANHID;
                UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET TENTOIDANH = VTOIDANH_TEN WHERE ID = ITEM.ID; 
            END IF;

       END LOOP;

       -- Update AHS_SOTHAM_BANAN_DIEU_CHITIET.ISMAIN nếu bị cáo không có tội danh chính thì SET tội danh chính cho bị cáo
       FOR ITEM IN (SELECT BICANID
                    FROM (SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM 
                          FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT 
                          WHERE CT.TOIDANHID != 0
                          GROUP BY CT.BICANID) 
                    WHERE SUM = 0)
       LOOP

            FOR ITEMS IN (SELECT CT.ID 
                          FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
                              INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI = 2
                          WHERE BICANID = ITEM.BICANID ORDER BY CT.ID)
            LOOP
                UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET ISMAIN = 1 WHERE ID = ITEMS.ID; 
            END LOOP;

       END LOOP;

       COMMIT;

       OPEN curReturn FOR SELECT 1 FROM DUAL;
    END UPDATE_AHS_SOTHAM_BANAN_DIEU_CHITIET;


    /*DELETE_DATA_AHS_SOTHAM_CAOTRANG_DIEULUAT - Xóa dữ liệu dư thừa ở bảng AHS_SOTHAM_CAOTRANG_DIEULUAT qua các trường BICANID, VUANID*/
    PROCEDURE DELETE_DATA_AHS_SOTHAM_CAOTRANG_DIEULUAT
    ( 
        curReturn OUT sys_refcursor
    )
    IS 
    BEGIN
        DELETE FROM AHS_SOTHAM_CAOTRANG_DIEULUAT WHERE BICANID = 0;

        FOR ITEM IN (SELECT CT.ID, CT.BICANID
                     FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT
                        LEFT JOIN AHS_BICANBICAO BC ON BC.ID = CT.BICANID
                     WHERE NOT EXISTS(SELECT 'X' FROM AHS_BICANBICAO BC WHERE BC.ID = CT.BICANID))
        LOOP
            DELETE FROM AHS_SOTHAM_CAOTRANG_DIEULUAT WHERE ID = ITEM.ID;
        END LOOP;

        COMMIT;

        OPEN curReturn FOR SELECT 1 FROM DUAL;
    END DELETE_DATA_AHS_SOTHAM_CAOTRANG_DIEULUAT;

    /*UPDATE_AHS_SOTHAM_CAOTRANG_DIEULUAT - Update các trường VUANID */
    PROCEDURE UPDATE_AHS_SOTHAM_CAOTRANG_DIEULUAT
    ( 
        curReturn OUT sys_refcursor
    )
    IS 
      VVUANID NUMBER;
      VCHECK NUMBER;

    BEGIN
    -- KIỂM TRA BỊ CAN CÓ 2 VUANID
--    SELECT BCID, CC FROM (
--SELECT DISTINCT(BICANID) BCID, count(DISTINCT(VUANID)) CC
--FROM AHS_SOTHAM_CAOTRANG_DIEULUAT 
--WHERE BICANID != 0
--group by BICANID)
--WHERE CC >= 2;
--
-- KIỂM TRA TỒN TẠI CỦA BỊ CÁO 
--SELECT BICANID FROM AHS_SOTHAM_CAOTRANG_DIEULUAT WHERE NOT EXISTS (SELECT ID FROM AHS_BICANBICAO);
  
       -- Update VUANID bảng AHS_SOTHAM_CAOTRANG_DIEULUAT
       FOR ITEM IN (SELECT * FROM AHS_SOTHAM_CAOTRANG_DIEULUAT)
       LOOP

           VCHECK :=0 ; VVUANID := 0;

           SELECT COUNT('X') INTO VCHECK FROM AHS_BICANBICAO BC WHERE ITEM.BICANID = BC.ID;                     
           IF(VCHECK > 0) THEN 

               SELECT BC.VUANID INTO VVUANID
               FROM AHS_BICANBICAO BC 
               WHERE ITEM.BICANID = BC.ID;

               UPDATE AHS_SOTHAM_CAOTRANG_DIEULUAT SET VUANID = VVUANID WHERE BICANID = ITEM.BICANID;                       
           END IF;  

           VCHECK :=0;
       END LOOP;



--SELECT BCTD.BICANID, BCTD.TENTOIDANH, BCTD.LOAI
--FROM (SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM, DM.TENTOIDANH, DM.LOAI
--      FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT 
--          INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI = 2
--      WHERE CT.TOIDANHID != 0
--      GROUP BY CT.BICANID, DM.TENTOIDANH, DM.LOAI) BCTD
--WHERE SUM = 0;


       -- Update AHS_SOTHAM_CAOTRANG_DIEULUAT.ISMAIN nếu bị cáo không có tội danh chính thì SET tội danh chính cho bị cáo
       FOR ITEM IN (SELECT BICANID
                    FROM (SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM 
                          FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT 
                          WHERE CT.TOIDANHID != 0
                          GROUP BY CT.BICANID) 
                    WHERE SUM = 0)
       LOOP

            FOR ITEMS IN (SELECT CT.ID 
                          FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT
                              INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI = 2
                          WHERE BICANID = ITEM.BICANID ORDER BY CT.ID)
            LOOP
                UPDATE AHS_SOTHAM_CAOTRANG_DIEULUAT SET ISMAIN = 1 WHERE ID = ITEMS.ID; 
            END LOOP;

       END LOOP;


       COMMIT;

       OPEN curReturn FOR SELECT 1 FROM DUAL;
    END UPDATE_AHS_SOTHAM_CAOTRANG_DIEULUAT;




END PACKAGE_UPDATE_DATA;
