create or replace PACKAGE BODY PKG_DASHBOARD_GDT_APP AS
PROCEDURE DASHBOARD_GDT_CREATE_DATA
 AS    
    V_SYSDATE DATE;V_COUNTS NUMBER;
    V_KQLOAI NUMBER; V_SOTHULYXX VARCHAR2(512);V_NGAYTHULYXX DATE;
BEGIN
    DELETE DASHBOARD_GDT;COMMIT;
    -----
    SELECT SYSDATE INTO V_SYSDATE FROM DUAL; 
    FOR item in (
           SELECT  a.id DONID,a.toaanid,a.CD_TA_DONVIID PHONGBANID,v.LOAIAN
           ,DECODE(v.BAQD_CAPXETXU,4,v.so_qdgdt,3,v.SOANPHUCTHAM,2,v.SOANSOTHAM,v.SOANPHUCTHAM) SOBA
           ,DECODE(v.BAQD_CAPXETXU,4,to_char(v.NGAYQD,'dd/MM/yyyy'),2,to_char(v.NGAYXUSOTHAM,'dd/MM/yyyy'),to_char(v.NGAYXUPHUCTHAM,'dd/MM/yyyy')) NGAYBA
           ,DECODE(v.BAQD_CAPXETXU,4,v.TOAQDID,3,v.TOAPHUCTHAMID,2,v.ToaAnSoTham,v.SOANPHUCTHAM)TOAXX
           ,v.BAQD_CAPXETXU CAPXX,a.LOAIDON
           ,a.TL_SO SOTHULY-- if loai don =4 thi se day vao SOTHULYXX
           ,a.TL_NGAY NGAYTHULY
           ,a.DONGKHIEUNAI NGUOIGUIDON,a.NGUOIGUI_DIACHI DIACHI
           ,a.LOAICONGVAN THUOCDON,a.THAMPHANID,null NGAYTRINH,null NGAYYKIEN
           ,DECODE(v.LOAIAN,1,DECODE(HS_TLD.LOAI,NULL,NULL,0)||DECODE(HS_KN.LOAI,NULL,NULL,1)
           ,DECODE(TLD_DS.LOAI,NULL,NULL,0)||DECODE(KN_DS.LOAI,NULL,NULL,1)||DECODE(XD_DS.LOAI,NULL,NULL,2) ) KQLOAI --if loaidon=4 then KQLOAI=1
           ,DECODE(v.LOAIAN,1,HS_TLD.SO||HS_KN.SO,TLD_DS.SO||KN_DS.SO||XD_DS.SO)KQSO
           ,DECODE(v.LOAIAN,1,HS_TLD.NGAY||HS_KN.NGAY,TLD_DS.NGAY||KN_DS.NGAY||XD_DS.NGAY)KQNGAY
           ,v.XXGDTTT_SOQD  SOQDXX
           ,v.XXGDTTT_NGAYQD NGAYQDXX
           ,ct.CANBOID CHUTOA
           ,NULL NGAYDONGBO
           ,DECODE(v.NGUYENDON,NULL,ND.NGUYENDON_ND,v.NGUYENDON) NGUYENDON
           ,decode(v.loaian,1,DECODE(v.BIDON,NULL,HSKN.BICAO,v.BIDON),DECODE(v.BIDON,NULL,BD.BIDON_BD,v.BIDON)) BIDON
           ,decode(Trim(v.QHPL_TEXT),null,qhpl.TENQHPL,v.QHPL_TEXT) QUANHEPL
           , NULL THAMTRAVIENID, NULL LANHDAO, NULL VUANID, NULL DUTHAONGAYTRINH, 
           NULL DUTHAOLOAIKQ, NULL DUTHAO_NOIDUNG, NULL SOTHULYXX, NULL NGAYTHULYXX
           FROM GDTTT_DON a
           LEFT JOIN GDTTT_VUAN V ON A.VUVIECID=V.ID
           left join GDTTT_DM_QHPL qhpl on v.QHPL_DINHNGHIAID=qhpl.ID
                       LEFT JOIN (SELECT  KN.VUANID,LISTAGG(DS.TENDUONGSU, '<br/>') WITHIN GROUP (ORDER BY DS.TENDUONGSU  DESC)  BICAO
                                FROM GDTTT_VUAN_DS_KN KN
                                LEFT JOIN GDTTT_VUAN_DUONGSU DS ON DS.ID=KN.BICAOID
                                LEFT JOIN GDTTT_VUAN_DUONGSU DSS ON DSS.ID=KN.NGUOIKHIEUNAIID
                                GROUP BY KN.VUANID
                            )HSKN ON HSKN.VUANID=V.ID
           left join gdttt_vuan v on a.VUVIECID=v.id  
           LEFT JOIN (SELECT  DS.VUANID,LISTAGG(DS.TENDUONGSU, '<br/>') WITHIN GROUP (ORDER BY DS.TENDUONGSU  DESC)  NGUYENDON_ND
                        FROM GDTTT_VUAN_DUONGSU DS
                        WHERE DS.TUCACHTOTUNG='NGUYENDON' 
                        GROUP BY DS.VUANID
                )ND ON ND.VUANID=V.ID     
           LEFT JOIN (SELECT  DS.VUANID,LISTAGG(DS.TENDUONGSU, '<br/>') WITHIN GROUP (ORDER BY DS.TENDUONGSU  DESC)  BIDON_BD
                    FROM GDTTT_VUAN_DUONGSU DS
                    WHERE DS.TUCACHTOTUNG='BIDON' 
                    GROUP BY DS.VUANID
            )BD ON BD.VUANID=V.ID 
           left join(select HD.* FROM GDTTT_VuAn_XXGDTT_HoiDong HD where NVL(HD.IsChuToa,0)=1)ct on ct.VUANID=v.id
           LEFT JOIN (SELECT TT.DONID,SUBSTR(TT.SO,0,instr(TT.SO,',') - 1)SO,SUBSTR(TT.NGAY,0,instr(TT.NGAY,',') - 1)NGAY,SUBSTR(TT.LOAI,0,1)LOAI FROM (
                      select TK.DONID,LISTAGG(TK.SO,',')WITHIN GROUP (ORDER BY ID DESC)SO
                      ,LISTAGG(TK.NGAY,',')WITHIN GROUP (ORDER BY ID DESC)NGAY
                       ,LISTAGG(TK.TYPETB,',')WITHIN GROUP (ORDER BY ID DESC)LOAI
                      from GDTTT_DON_TRALOI TK WHERE  TK.TYPETB=3 AND TK.DONID!=0 group by TK.DONID  )TT
                     ) HS_TLD ON HS_TLD.DONID=A.ID
             LEFT JOIN (SELECT TT.DONID,SUBSTR(TT.SO,0,instr(TT.SO,',') - 1)SO,SUBSTR(TT.NGAY,0,instr(TT.NGAY,',') - 1)NGAY,SUBSTR(TT.LOAI,0,1)LOAI FROM (
                      select TK.DONID,LISTAGG(TK.SO,',')WITHIN GROUP (ORDER BY ID DESC)SO
                      ,LISTAGG(TK.NGAY,',')WITHIN GROUP (ORDER BY ID DESC)NGAY
                      ,LISTAGG(TK.TYPETB,',')WITHIN GROUP (ORDER BY ID DESC)LOAI
                      from GDTTT_DON_TRALOI TK WHERE  TK.TYPETB=4 AND TK.DONID!=0 group by TK.DONID  )TT
                     ) HS_KN ON HS_KN.DONID=A.ID   
             LEFT JOIN (SELECT TT.DONID,SUBSTR(TT.SO,0,instr(TT.SO,',') - 1)SO,SUBSTR(TT.NGAY,0,instr(TT.NGAY,',') - 1)NGAY,SUBSTR(TT.LOAI,0,1)LOAI FROM (
                      select TK.DONID,LISTAGG(TK.SO,',')WITHIN GROUP (ORDER BY ID DESC)SO
                      ,LISTAGG(TK.NGAY,',')WITHIN GROUP (ORDER BY ID DESC)NGAY
                      ,LISTAGG(TK.LOAI,',')WITHIN GROUP (ORDER BY ID DESC)LOAI
                      from  GDTTT_VUAN_KETQUA_DON TK WHERE TK.LOAI=0 AND TK.TRANGTHAI=1 AND TK.DONID!=0
                      group by TK.DONID)TT
                     )TLD_DS  ON TLD_DS.DONID=A.ID      
             LEFT JOIN (SELECT TT.DONID,SUBSTR(TT.SO,0,instr(TT.SO,',') - 1)SO,SUBSTR(TT.NGAY,0,instr(TT.NGAY,',') - 1)NGAY,SUBSTR(TT.LOAI,0,1)LOAI FROM (
                      select TK.DONID,LISTAGG(TK.SO,',')WITHIN GROUP (ORDER BY ID DESC)SO
                      ,LISTAGG(TK.NGAY,',')WITHIN GROUP (ORDER BY ID DESC)NGAY
                      ,LISTAGG(TK.LOAI,',')WITHIN GROUP (ORDER BY ID DESC)LOAI
                      from  GDTTT_VUAN_KETQUA_DON TK WHERE TK.LOAI=1 AND TK.TRANGTHAI=1 AND TK.DONID!=0
                      group by TK.DONID)TT
                     )KN_DS  ON KN_DS.DONID=A.ID    
              LEFT JOIN (SELECT TT.DONID,SUBSTR(TT.SO,0,instr(TT.SO,',') - 1)SO,SUBSTR(TT.NGAY,0,instr(TT.NGAY,',') - 1)NGAY,SUBSTR(TT.LOAI,0,1)LOAI FROM (
                      select TK.DONID,LISTAGG(TK.SO,',')WITHIN GROUP (ORDER BY ID DESC)SO
                      ,LISTAGG(TK.NGAY,',')WITHIN GROUP (ORDER BY ID DESC)NGAY
                      ,LISTAGG(TK.LOAI,',')WITHIN GROUP (ORDER BY ID DESC)LOAI
                      from  GDTTT_VUAN_KETQUA_DON TK WHERE TK.LOAI=2 AND TK.TRANGTHAI=1 AND TK.DONID!=0
                      group by TK.DONID)TT
                     )XD_DS  ON XD_DS.DONID=A.ID   
          WHERE (a.ISTHULY=1 or a.LOAIDON=4)
          AND v.LOAIAN in(1,2,3,4,5,6,7)
    )
    LOOP
      -------------
        IF(item.LOAIDON=4)THEN
            V_KQLOAI:=1;V_SOTHULYXX:=item.SOTHULY;V_NGAYTHULYXX:=item.NGAYTHULY;
        ELSE
            V_KQLOAI:=item.KQLOAI;V_SOTHULYXX:=item.SOTHULYXX;V_NGAYTHULYXX:=item.NGAYTHULYXX;
        END IF;    
       -------------
          insert into DASHBOARD_GDT
                        (DONID,TOAANID,PHONGBANID,LOAIAN,SOBA,NGAYBA,TOAXX,CAPXX,LOAIDON,SOTHULY,NGAYTHULY,NGUOIGUIDON,DIACHI,THUOCDON,THAMPHANID,NGAYTRINH,NGAYYKIEN
                        ,KQLOAI,KQSO,KQNGAY,SOQDXX,NGAYQDXX,CHUTOA,NGAYDONGBO,NGUYENDON,BIDON,QUANHEPL,THAMTRAVIENID,LANHDAO,VUANID,DUTHAONGAYTRINH,DUTHAOLOAIKQ,DUTHAO_NOIDUNG
                        ,SOTHULYXX,NGAYTHULYXX)
                        values 
                        (item.DONID,item.TOAANID,item.PHONGBANID,item.LOAIAN,item.SOBA,item.NGAYBA,item.TOAXX,item.CAPXX,item.LOAIDON,item.SOTHULY,item.NGAYTHULY,item.NGUOIGUIDON,item.DIACHI,item.THUOCDON,item.THAMPHANID,item.NGAYTRINH,item.NGAYYKIEN
                        ,V_KQLOAI,item.KQSO,item.KQNGAY,item.SOQDXX,item.NGAYQDXX,item.CHUTOA,V_SYSDATE,item.NGUYENDON,item.BIDON,item.QUANHEPL,item.THAMTRAVIENID,item.LANHDAO,item.VUANID,item.DUTHAONGAYTRINH,item.DUTHAOLOAIKQ,item.DUTHAO_NOIDUNG
                        ,V_SOTHULYXX,V_NGAYTHULYXX);
             COMMIT;          
    END LOOP;
END;
END PKG_DASHBOARD_GDT_APP;