--------------------------------------------------------
--  DDL for Package Body PKG_DVCQG_APP
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_DVCQG_APP" AS
PROCEDURE THANH_TOAN_UP
(
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2
)
AS
V_COUNTS NUMBER;V_COUNTS_TP NUMBER;V_SOTHONGBAO VARCHAR2(100);V_NGAYTHONGBAO DATE;V_TAMUNGANPHI NUMBER;V_DUONGSU_ID NUMBER;V_DUONGSU_IDS VARCHAR2(250);
  BEGIN 
        IF(V_MALOAIVUVIEC='2') THEN
            SELECT SOTHONGBAO,NGAYTHONGBAO,TAMUNGANPHI,DUONGSU_ID INTO V_SOTHONGBAO,V_NGAYTHONGBAO,V_TAMUNGANPHI,V_DUONGSU_ID FROM ADS_ANPHI WHERE ID=V_ANPHI_ID;
            -----------DVCQG_THANH_TOAN
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC 
            AND TRANGTHAITHANHTOAN=0;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOTHONGBAO=V_SOTHONGBAO,
                NGAYTHONGBAO=V_NGAYTHONGBAO,
                TONGTIEN=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
           END IF;
           ---------------TUPHAP_ANPHI
           SELECT COUNT(*)INTO V_COUNTS_TP FROM TUPHAP_ANPHI TP
           LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
           WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
           IF(V_COUNTS_TP=1)THEN 
                UPDATE TUPHAP_ANPHI 
                SET ANPHI=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='3') THEN
            SELECT SOTHONGBAO,NGAYTHONGBAO,TAMUNGANPHI,DUONGSU_ID,DUONGSU_IDS INTO V_SOTHONGBAO,V_NGAYTHONGBAO,V_TAMUNGANPHI,V_DUONGSU_ID,V_DUONGSU_IDS FROM AHN_ANPHI WHERE ID=V_ANPHI_ID;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC 
            AND TRANGTHAITHANHTOAN=0;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOTHONGBAO=V_SOTHONGBAO,
                NGAYTHONGBAO=V_NGAYTHONGBAO,
                TONGTIEN=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID,
                DUONGSU_IDS=V_DUONGSU_IDS
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
           END IF;
           ---------------
           SELECT COUNT(*)INTO V_COUNTS_TP FROM TUPHAP_ANPHI TP
           LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
           WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
           IF(V_COUNTS_TP=1)THEN 
                UPDATE TUPHAP_ANPHI 
                SET ANPHI=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID,
                DUONGSU_IDS=V_DUONGSU_IDS
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='4') THEN
           SELECT SOTHONGBAO,NGAYTHONGBAO,TAMUNGANPHI,DUONGSU_ID INTO V_SOTHONGBAO,V_NGAYTHONGBAO,V_TAMUNGANPHI,V_DUONGSU_ID FROM AKT_ANPHI WHERE ID=V_ANPHI_ID;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC 
            AND TRANGTHAITHANHTOAN=0;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOTHONGBAO=V_SOTHONGBAO,
                NGAYTHONGBAO=V_NGAYTHONGBAO,
                TONGTIEN=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
              END IF;  
              ---------------
           SELECT COUNT(*)INTO V_COUNTS_TP FROM TUPHAP_ANPHI TP
           LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
           WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
           IF(V_COUNTS_TP=1)THEN 
                UPDATE TUPHAP_ANPHI 
                SET ANPHI=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='5') THEN
            SELECT SOTHONGBAO,NGAYTHONGBAO,TAMUNGANPHI,DUONGSU_ID INTO V_SOTHONGBAO,V_NGAYTHONGBAO,V_TAMUNGANPHI,V_DUONGSU_ID FROM ALD_ANPHI WHERE ID=V_ANPHI_ID;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC 
            AND TRANGTHAITHANHTOAN=0;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOTHONGBAO=V_SOTHONGBAO,
                NGAYTHONGBAO=V_NGAYTHONGBAO,
                 TONGTIEN=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
             END IF;   
             ---------------
               SELECT COUNT(*)INTO V_COUNTS_TP FROM TUPHAP_ANPHI TP
               LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
               WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
               IF(V_COUNTS_TP=1)THEN 
                UPDATE TUPHAP_ANPHI 
                SET ANPHI=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='6') THEN
            SELECT SOTHONGBAO,NGAYTHONGBAO,TAMUNGANPHI,DUONGSU_ID,DUONGSU_IDS INTO V_SOTHONGBAO,V_NGAYTHONGBAO,V_TAMUNGANPHI,V_DUONGSU_ID,V_DUONGSU_IDS FROM AHC_ANPHI WHERE ID=V_ANPHI_ID;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC 
            AND TRANGTHAITHANHTOAN=0;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOTHONGBAO=V_SOTHONGBAO,
                NGAYTHONGBAO=V_NGAYTHONGBAO,
                TONGTIEN=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID,
                DUONGSU_IDS=V_DUONGSU_IDS
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
            END IF;    
            ---------------
           SELECT COUNT(*)INTO V_COUNTS_TP FROM TUPHAP_ANPHI TP
           LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
           WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
           IF(V_COUNTS_TP=1)THEN 
                UPDATE TUPHAP_ANPHI 
                SET ANPHI=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID,
                DUONGSU_IDS=V_DUONGSU_IDS
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='7') THEN
           SELECT SOTHONGBAO,NGAYTHONGBAO,TAMUNGANPHI,DUONGSU_ID INTO V_SOTHONGBAO,V_NGAYTHONGBAO,V_TAMUNGANPHI,V_DUONGSU_ID FROM APS_ANPHI WHERE ID=V_ANPHI_ID;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC 
            AND TRANGTHAITHANHTOAN=0;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOTHONGBAO=V_SOTHONGBAO,
                NGAYTHONGBAO=V_NGAYTHONGBAO,
                TONGTIEN=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
            END IF;    
            ---------------
           SELECT COUNT(*)INTO V_COUNTS_TP FROM TUPHAP_ANPHI TP
           LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
           WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
           IF(V_COUNTS_TP=1)THEN 
                UPDATE TUPHAP_ANPHI 
                SET ANPHI=V_TAMUNGANPHI,
                DUONGSU_ID=V_DUONGSU_ID
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        END IF;
  END THANH_TOAN_UP;
 PROCEDURE THANH_TOAN_UP_FROM_THADS
(
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2
)
AS
V_COUNTS NUMBER;V_SOBIENLAI VARCHAR2(255);V_NGAYTHONGBAO DATE;V_TAMUNGANPHI NUMBER;V_DUONGSU_ID NUMBER;V_DUONGSU_IDS VARCHAR2(250);
  BEGIN 
        IF(V_MALOAIVUVIEC='2') THEN
            SELECT SOBIENLAI INTO V_SOBIENLAI FROM TUPHAP_ANPHI WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC; 
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOBIENLAI=V_SOBIENLAI,
                TRANGTHAITHANHTOAN=1
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='3') THEN
           SELECT SOBIENLAI INTO V_SOBIENLAI FROM TUPHAP_ANPHI WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;

            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOBIENLAI=V_SOBIENLAI,
                TRANGTHAITHANHTOAN=1
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
           END IF;
        ELSIF(V_MALOAIVUVIEC='4') THEN
           SELECT SOBIENLAI INTO V_SOBIENLAI FROM TUPHAP_ANPHI WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOBIENLAI=V_SOBIENLAI,
                TRANGTHAITHANHTOAN=1
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
              END IF;  
        ELSIF(V_MALOAIVUVIEC='5') THEN
           SELECT SOBIENLAI INTO V_SOBIENLAI FROM TUPHAP_ANPHI WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET TRANGTHAITHANHTOAN=1
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
             END IF;   
        ELSIF(V_MALOAIVUVIEC='6') THEN
            SELECT SOBIENLAI INTO V_SOBIENLAI FROM TUPHAP_ANPHI WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC; 
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOBIENLAI=V_SOBIENLAI,
                TRANGTHAITHANHTOAN=1
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            END IF;    
        ELSIF(V_MALOAIVUVIEC='7') THEN
           SELECT SOBIENLAI INTO V_SOBIENLAI FROM TUPHAP_ANPHI WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            -----------
            SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC; 
            IF(V_COUNTS=1)THEN 
                UPDATE DVCQG_THANH_TOAN 
                SET SOBIENLAI=V_SOBIENLAI,
                TRANGTHAITHANHTOAN=1
                WHERE ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
            END IF;    
        END IF;
  END THANH_TOAN_UP_FROM_THADS;
PROCEDURE THANH_TOAN_IN_ANPHI
(
   V_MAGIAIDOAN IN NUMBER,
   V_DONID IN NUMBER,
   V_DONXULY_ID IN NUMBER,
   V_ANPHI_ID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2,
   V_DS_IDS IN VARCHAR2
)
AS
  V_COUNTS NUMBER;V_COUNTS_MATB NUMBER;V_MA_THONGBAO VARCHAR2(255):=NULL;DVTHA_ID NUMBER;v_count_ds NUMBER:=0;V_COUNT_TP NUMBER; V_ID NUMBER;
  BEGIN 
   select instr(V_DS_IDS,',') into v_count_ds from dual;
  ---------------------
  SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE  TT.ANPHI_ID=V_ANPHI_ID AND TT.DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND MAGIAIDOAN=V_MAGIAIDOAN;
      IF(V_COUNTS=0)THEN
       -----------
        V_MA_THONGBAO := PKG_DVCQG_APP.CREATE_MA_TB_RANDOM(V_MA_THONGBAO);
       -----------
        V_ID:=DVCQG_THANH_TOAN_SEQ.NEXTVAL;
        --------------
        IF(V_MALOAIVUVIEC='2') THEN
        FOR item_tp IN 
                    (
                        SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                        ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                        ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
                        ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
                        ,REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,TK.TEN_TK_THUHUONG
                        FROM ADS_ANPHI AI 
                        INNER JOIN ADS_DON DO ON AI.DONID=DO.ID     
                        INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                        INNER JOIN ADS_DON_DUONGSU DU ON  AI.DUONGSU_ID=DU.ID    --AI.DONID=DU.DONID cũ
                        --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                        INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                        LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                        LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
                        LEFT JOIN ADS_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
--                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
--                        LEFT JOIN ADS_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
                        LEFT JOIN (SELECT QD.DONID FROM ADS_SOTHAM_QUYETDINH  QD 
                                    INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                        LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                        LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                        WHERE --AI.MAGIAIDOAN=V_MAGIAIDOAN AND 
                        --DU.TUCACHTOTUNG_MA='NGUYENDON' --TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
                        --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
                        --AND 
                        AI.TAMUNGANPHI !=0 
                        AND AI.ID=V_ANPHI_ID
                   )
            LOOP
            IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                INSERT INTO DVCQG_THANH_TOAN
                    (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                    ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                    ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,MAGIAIDOAN,DUONGSU_ID,TEN_TK_THUHUONG)
                    VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                    ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                    ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,V_MAGIAIDOAN,item_tp.DUONGSU_ID,item_tp.TEN_TK_THUHUONG);
              ---------------------
               SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                   IF(V_COUNT_TP=0)THEN
                    INSERT INTO TUPHAP_ANPHI 
                    (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                     NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                     ANPHI_ID,DUONGSU_ID,DVCQG_TT_ID)
                     VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                    SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                    V_ANPHI_ID,item_tp.DUONGSU_ID,V_ID);
                    END IF;
               END IF;
            END LOOP;
         ELSIF (V_MALOAIVUVIEC='3') THEN   
                IF(v_count_ds=0)THEN
                    FOR item_tp IN 
                                (
                                    SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                                    ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                                    ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
                                    ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
                                    , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,AI.DUONGSU_IDS,TK.TEN_TK_THUHUONG
                                    FROM AHN_ANPHI AI 
                                    INNER JOIN AHN_DON DO ON AI.DONID=DO.ID     
                                    INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                                    INNER JOIN AHN_DON_DUONGSU DU ON  AI.DUONGSU_IDS=DU.ID--;  AI.DUONGSU_IDS like DU.ID || '%'   --AI.DONID=DU.DONID cũ
                                    --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                                    INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                                    LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                                    LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
                                    LEFT JOIN AHN_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
            --                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
            --                      LEFT JOIN AHN_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
                                    LEFT JOIN (SELECT QD.DONID FROM AHN_SOTHAM_QUYETDINH  QD 
                                                INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                                    LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                                    LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                                    WHERE --DU.TUCACHTOTUNG_MA='NGUYENDON' --TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
                                    --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
                                    --AND 
                                    REPLACE(AI.TAMUNGANPHI,'.') !=0 
                                    AND AI.ID=V_ANPHI_ID AND ROWNUM = 1
                               )
                        LOOP
                          IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                            INSERT INTO DVCQG_THANH_TOAN
                                (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                                ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                                ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,DUONGSU_IDS,TEN_TK_THUHUONG)
                                VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                                ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                                ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.DUONGSU_IDS,item_tp.TEN_TK_THUHUONG);
                               ---------------------
                              SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                               IF(V_COUNT_TP=0)THEN
                                INSERT INTO TUPHAP_ANPHI 
                                (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                                 NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                                 ANPHI_ID,DUONGSU_ID,DVCQG_TT_ID)
                                 VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                                SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                                V_ANPHI_ID,item_tp.DUONGSU_ID,V_ID);
                                END IF;
                         END IF;
                        END LOOP;
               ELSIF(v_count_ds>0)THEN      
                   FOR item_tp IN 
                                (
                                    SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                                    ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                                    ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,AP.TENDUONGSU HOTENNGUOINOP
                                    ,NULL SOCMNDNGUOINOP,NULL DIACHINGUOINOP,NULL HUYENNGUOINOP,NULL TINHNGUOINOP
                                    , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,AI.DUONGSU_IDS,TK.TEN_TK_THUHUONG
                                    FROM AHN_ANPHI AI 
                                    INNER JOIN AHN_DON DO ON AI.DONID=DO.ID     
                                    INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                                    INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                                    LEFT JOIN ( SELECT LISTAGG(HN.TENDUONGSU,', ') WITHIN GROUP (ORDER BY HN.TENDUONGSU) TENDUONGSU,DU.ANPHI_ID
                                               FROM AHN_ANPHI_DUONGSU DU LEFT JOIN AHN_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                                               GROUP BY DU.ANPHI_ID
                                             )AP ON AP.ANPHI_ID=AI.ID
                                    LEFT JOIN AHN_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                                    LEFT JOIN (SELECT QD.DONID FROM AHN_SOTHAM_QUYETDINH  QD 
                                                INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                                    LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                                    LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                                    WHERE  REPLACE(AI.TAMUNGANPHI,'.') !=0 
                                    AND AI.ID=V_ANPHI_ID AND ROWNUM = 1
                               )
                        LOOP
                          IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                            INSERT INTO DVCQG_THANH_TOAN
                                (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                                ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                                ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,DUONGSU_IDS,TEN_TK_THUHUONG)
                                VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                                ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                                ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.DUONGSU_IDS,item_tp.TEN_TK_THUHUONG);
                                --------------------------
                               SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TP.DUONGSU_IDS=item_tp.DUONGSU_IDS;
                               IF(V_COUNT_TP=0)THEN
                                INSERT INTO TUPHAP_ANPHI 
                                (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                                 NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                                 ANPHI_ID,DUONGSU_IDS,DVCQG_TT_ID)
                                 VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                                SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                                V_ANPHI_ID,item_tp.DUONGSU_IDS,V_ID);
                                END IF;

                         END IF;
                        END LOOP;
              END IF;  
          ELSIF (V_MALOAIVUVIEC='4') THEN   
         FOR item_tp IN 
                    (
                        SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                        ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                        ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
                        ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
                        , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,TK.TEN_TK_THUHUONG
                        FROM AKT_ANPHI AI 
                        INNER JOIN AKT_DON DO ON AI.DONID=DO.ID     
                        INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                        INNER JOIN AKT_DON_DUONGSU DU ON  AI.DUONGSU_ID=DU.ID    --AI.DONID=DU.DONID cũ
                        --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                        INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                        LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                        LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
                        LEFT JOIN AKT_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
--                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
--                      LEFT JOIN AKT_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
                        LEFT JOIN (SELECT QD.DONID FROM AKT_SOTHAM_QUYETDINH  QD 
                                    INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                        LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                        LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                        WHERE --DU.TUCACHTOTUNG_MA='NGUYENDON' --AND TD.BIEUMAUID=67--TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
                        --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
                        --AND 
                        REPLACE(AI.TAMUNGANPHI,'.') !=0 
                        AND AI.ID=V_ANPHI_ID
                   )
            LOOP
               IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                    INSERT INTO DVCQG_THANH_TOAN
                        (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                        ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                        ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,TEN_TK_THUHUONG)
                        VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                        ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                        ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.TEN_TK_THUHUONG);
                        ----------------
                      SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                       IF(V_COUNT_TP=0)THEN
                        INSERT INTO TUPHAP_ANPHI 
                        (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                         NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                         ANPHI_ID,DUONGSU_ID,DVCQG_TT_ID)
                         VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                        SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                        V_ANPHI_ID,item_tp.DUONGSU_ID,V_ID);
                        END IF;
             END IF;
            END LOOP;
          ELSIF (V_MALOAIVUVIEC='5') THEN   
         FOR item_tp IN 
                    (
                        SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                        ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                        ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
                        ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
                        , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,TK.TEN_TK_THUHUONG
                         FROM ALD_ANPHI AI 
                        INNER JOIN ALD_DON DO ON AI.DONID=DO.ID     
                        INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                        INNER JOIN ALD_DON_DUONGSU DU ON  AI.DUONGSU_ID=DU.ID    --AI.DONID=DU.DONID cũ
                        --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                        INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                        LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                        LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
                        LEFT JOIN ALD_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
--                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
--                      LEFT JOIN ALD_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
                        LEFT JOIN (SELECT QD.DONID FROM ALD_SOTHAM_QUYETDINH  QD 
                                    INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                        LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                        LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                        WHERE --DU.TUCACHTOTUNG_MA='NGUYENDON' --AND TD.BIEUMAUID=67--TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
                        --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
                        --AND 
                        REPLACE(AI.TAMUNGANPHI,'.') !=0 
                        AND AI.ID=V_ANPHI_ID
                   )
            LOOP
             IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                    INSERT INTO DVCQG_THANH_TOAN
                        (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                        ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                        ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,TEN_TK_THUHUONG)
                        VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                        ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                        ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.TEN_TK_THUHUONG);
                          ----------------
                       SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                       IF(V_COUNT_TP=0)THEN
                        INSERT INTO TUPHAP_ANPHI 
                        (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                         NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                         ANPHI_ID,DUONGSU_ID,DVCQG_TT_ID)
                         VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                        SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                        V_ANPHI_ID,item_tp.DUONGSU_ID,V_ID);
                        END IF;
             END IF;
            END LOOP;
      ELSIF (V_MALOAIVUVIEC='6') THEN   
     IF(v_count_ds=0)THEN
                    FOR item_tp IN 
                                (
                                    SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                                    ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                                    ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
                                    ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
                                    , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,AI.DUONGSU_IDS,TK.TEN_TK_THUHUONG
                                    FROM AHC_ANPHI AI 
                                    INNER JOIN AHC_DON DO ON AI.DONID=DO.ID     
                                    INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                                    INNER JOIN AHC_DON_DUONGSU DU ON  AI.DUONGSU_IDS=DU.ID--;  AI.DUONGSU_IDS like DU.ID || '%'   --AI.DONID=DU.DONID cũ
                                    --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                                    INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                                    LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                                    LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
                                    LEFT JOIN AHC_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
            --                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
            --                      LEFT JOIN AHC_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
                                    LEFT JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
                                                INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                                    LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                                    LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                                    WHERE --DU.TUCACHTOTUNG_MA='NGUYENDON' --AND TD.BIEUMAUID=67--TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
                                    --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
                                    --AND 
                                    REPLACE(AI.TAMUNGANPHI,'.') !=0 
                                    AND AI.ID=V_ANPHI_ID AND ROWNUM = 1
                               )
                        LOOP
                          IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                            INSERT INTO DVCQG_THANH_TOAN
                                (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                                ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                                ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,DUONGSU_IDS,TEN_TK_THUHUONG)
                                VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                                ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                                ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.DUONGSU_IDS,item_tp.TEN_TK_THUHUONG);
                           ----------------
                             SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                               IF(V_COUNT_TP=0)THEN
                                INSERT INTO TUPHAP_ANPHI 
                                (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                                 NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                                 ANPHI_ID,DUONGSU_ID,DVCQG_TT_ID)
                                 VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                                SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                                V_ANPHI_ID,item_tp.DUONGSU_ID,V_ID);
                                END IF;
                         END IF;
                        END LOOP;
               ELSIF(v_count_ds>0)THEN      
                   FOR item_tp IN 
                                (
                                    SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                                    ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                                    ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,AP.TENDUONGSU HOTENNGUOINOP
                                    ,NULL SOCMNDNGUOINOP,NULL DIACHINGUOINOP,NULL HUYENNGUOINOP,NULL TINHNGUOINOP
                                    , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,AI.DUONGSU_IDS,TK.TEN_TK_THUHUONG
                                    FROM AHC_ANPHI AI 
                                    INNER JOIN AHC_DON DO ON AI.DONID=DO.ID     
                                    INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                                    INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                                    LEFT JOIN ( SELECT LISTAGG(HN.TENDUONGSU,', ') WITHIN GROUP (ORDER BY HN.TENDUONGSU) TENDUONGSU,DU.ANPHI_ID
                                               FROM AHC_ANPHI_DUONGSU DU LEFT JOIN AHC_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                                               GROUP BY DU.ANPHI_ID
                                             )AP ON AP.ANPHI_ID=AI.ID
                                    LEFT JOIN AHC_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                                    LEFT JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
                                                INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                                    LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                                    LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                                    WHERE  REPLACE(AI.TAMUNGANPHI,'.') !=0 
                                    AND AI.ID=V_ANPHI_ID AND ROWNUM = 1
                               )
                        LOOP
                          IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                            INSERT INTO DVCQG_THANH_TOAN
                                (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                                ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                                ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,DUONGSU_IDS,TEN_TK_THUHUONG)
                                VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                                ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                                ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.DUONGSU_IDS,item_tp.TEN_TK_THUHUONG);
                                --------------------
                            SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                               IF(V_COUNT_TP=0)THEN
                                INSERT INTO TUPHAP_ANPHI 
                                (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                                 NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                                 ANPHI_ID,DUONGSU_IDS,DVCQG_TT_ID)
                                 VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                                SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                                V_ANPHI_ID,item_tp.DUONGSU_IDS,V_ID);
                                END IF;
                         END IF;
                        END LOOP;
              END IF;  
--        FOR item_tp IN 
--                    (
--                        SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
--                        ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
--                        ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
--                        ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
--                        , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,AI.DUONGSU_IDS,TK.TEN_TK_THUHUONG
--                        FROM AHC_ANPHI AI 
--                        INNER JOIN AHC_DON DO ON AI.DONID=DO.ID     
--                        INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
--                        INNER JOIN AHC_DON_DUONGSU DU ON instr(','|| AI.DUONGSU_IDS||',',','|| DU.ID||',')>0   --AI.DONID=DU.DONID cũ
--                        --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
--                        INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
--                        LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
--                        LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
--                        LEFT JOIN AHC_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
----                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
----                      LEFT JOIN AHC_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
--                        LEFT JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
--                                    INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
--                        LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
--                        LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
--                        WHERE --DU.TUCACHTOTUNG_MA='NGUYENDON' --AND TD.BIEUMAUID=67--TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
--                        --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
--                        --AND 
--                        REPLACE(AI.TAMUNGANPHI,'.') !=0 
--                        AND AI.ID=V_ANPHI_ID AND ROWNUM = 1
--                   )
--            LOOP
--             IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
--                    INSERT INTO DVCQG_THANH_TOAN
--                        (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
--                        ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
--                        ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,DUONGSU_IDS,TEN_TK_THUHUONG)
--                        VALUES (DVCQG_THANH_TOAN_SEQ.NEXTVAL,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
--                        ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
--                        ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.DUONGSU_IDS,item_tp.TEN_TK_THUHUONG);
--             END IF;
--            END LOOP;
          ELSIF (V_MALOAIVUVIEC='7') THEN   
        FOR item_tp IN 
                    (
                        SELECT DX.ID DONXULY_ID,AI.ID ANPHI_ID,AI.DONID,THA.ID DONVITHA_ID,LH.MA MALOAIHINHTHU,TO_CHAR(DO.MAVUVIEC)MAVUVIEC,TK.SOTK_KHOBAC SOTAIKHOANKB
                        ,TK.MA_KHOBAC MAKHOBAC,TK.TENTK_KHOBAC TENKHOBAC,THA.MA_DINH_DANH MACHICUC,THA.MA_TEN TENCHICUC
                        ,AI.NGAYTHONGBAO,AI.SOTHONGBAO,TN.MA_TEN TENTOATHONGBAO,LH.TEN TENLOAIHINHTHU,DU.TENDUONGSU HOTENNGUOINOP
                        ,DU.SOCMND SOCMNDNGUOINOP,DU.TAMTRUCHITIET DIACHINGUOINOP,HC.TEN HUYENNGUOINOP,HC1.TEN TINHNGUOINOP
                        , REPLACE(AI.TAMUNGANPHI,'.') TONGTIEN,AI.DUONGSU_ID,TK.TEN_TK_THUHUONG
                        FROM APS_ANPHI AI 
                        INNER JOIN APS_DON DO ON AI.DONID=DO.ID     
                        INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                        INNER JOIN APS_DON_DUONGSU DU ON  AI.DUONGSU_ID=DU.ID    --AI.DONID=DU.DONID cũ
                        --INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                        INNER JOIN DM_DONVITHIHANHAN THA ON THA.ARRTOAANID=TN.ID
                        LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                        LEFT JOIN DM_HANHCHINH HC1 ON DU.TAMTRUTINHID=HC1.ID
                        LEFT JOIN APS_DON_XULY DX ON DX.DONID=AI.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
--                      LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
--                      LEFT JOIN APS_FILE FL ON FL.DONID=AI.DONID AND FL.BIEUMAUID=67
                        LEFT JOIN (SELECT QD.DONID FROM APS_SOTHAM_QUYETDINH  QD 
                                    INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                        LEFT JOIN DM_TK_THANHTOAN TK ON TK.THA_ID=THA.ID
                        LEFT JOIN DM_LOAIHINH_THU LH ON LH.ID=TK.MA_LOAIHINHTHU
                        WHERE --DU.TUCACHTOTUNG_MA='NGUYENDON' --AND TD.BIEUMAUID=67--TD.BIEUMAUID=67 --Thông báo nộp tiền tạm ứng án phí
                        --AND DU.ISDAIDIEN = 1 --AND FL.TENFILE IS NOT NULL
                        --AND 
                        REPLACE(AI.TAMUNGANPHI,'.') !=0 
                        AND AI.ID=V_ANPHI_ID
                   )
            LOOP
            IF(item_tp.SOTAIKHOANKB IS NOT NULL) THEN
                    INSERT INTO DVCQG_THANH_TOAN
                        (ID,MA_THONGBAO,DONID,TONGDATID,DONXULY_ID,ANPHI_ID,MALOAIVUVIEC,DONVITHA_ID,MALOAIHINHTHU,MAVUVIEC,SOTAIKHOANKB
                        ,MAKHOBAC,TENKHOBAC,MACHICUC,TENCHICUC,NGAYTHONGBAO,SOTHONGBAO,TENTOATHONGBAO,TENLOAIHINHTHU
                        ,HOTENNGUOINOP,SOCMNDNGUOINOP,DIACHINGUOINOP,HUYENNGUOINOP,TINHNGUOINOP,TONGTIEN,NGAY_TAO,DUONGSU_ID,TEN_TK_THUHUONG)
                        VALUES (V_ID,V_MA_THONGBAO,item_tp.DONID,NULL,item_tp.DONXULY_ID,item_tp.ANPHI_ID,V_MALOAIVUVIEC,item_tp.DONVITHA_ID,item_tp.MALOAIHINHTHU,item_tp.MAVUVIEC
                        ,item_tp.SOTAIKHOANKB,item_tp.MAKHOBAC,item_tp.TENKHOBAC,item_tp.MACHICUC,item_tp.TENCHICUC,item_tp.NGAYTHONGBAO,item_tp.SOTHONGBAO,item_tp.TENTOATHONGBAO,item_tp.TENLOAIHINHTHU
                        ,item_tp.HOTENNGUOINOP,item_tp.SOCMNDNGUOINOP,item_tp.DIACHINGUOINOP,item_tp.HUYENNGUOINOP,item_tp.TINHNGUOINOP,item_tp.TONGTIEN,SYSDATE,item_tp.DUONGSU_ID,item_tp.TEN_TK_THUHUONG);
                     ----------------
                    SELECT COUNT(*)INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.VUVIECID=item_tp.DONID  AND TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC;
                       IF(V_COUNT_TP=0)THEN
                        INSERT INTO TUPHAP_ANPHI 
                        (ID,MALOAIVUVIEC,VUVIECID,SOBIENLAI,ANPHI,VBTONGDATID,DONVI_THUTIEN_ID,
                         NGAYTAO,NGUOITAO,NGUOITAOID,NGUOITHUTIEN,NOP_ISNGUYENDON,NOP_HOTEN,NOP_GIOITINH,NOP_NAMSINH,NOP_CMND,NOP_TEL,NOP_EMAIL,NOP_DIACHI,
                         ANPHI_ID,DUONGSU_ID,DVCQG_TT_ID)
                         VALUES (TUPHAP_ANPHI_SEQ.NEXTVAL,V_MALOAIVUVIEC,item_tp.DONID,NULL,item_tp.TONGTIEN,NULL,item_tp.DONVITHA_ID,
                        SYSDATE,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
                        V_ANPHI_ID,item_tp.DUONGSU_ID,V_ID);
                        END IF;
             END IF;
            END LOOP;
      END IF;
     ------------  
       END IF;   
  END THANH_TOAN_IN_ANPHI;
FUNCTION CREATE_MA_TB_RANDOM
(
  V_MA_THONGBAO OUT VARCHAR2
) 
RETURN VARCHAR2
AS
    V_COUNTS_MATB NUMBER;V_MA_TB VARCHAR2(255):=NULL;
BEGIN
    SELECT  DBMS_RANDOM.STRING('x',10) INTO V_MA_TB FROM DUAL;
    SELECT CASE WHEN EXISTS (SELECT 1 FROM DVCQG_THANH_TOAN DVC WHERE  DVC.MA_THONGBAO = V_MA_TB) 
           THEN 1  ELSE 0 END INTO V_COUNTS_MATB FROM DUAL;
    -----------
    IF(V_COUNTS_MATB=1)THEN
         V_MA_THONGBAO:=PKG_DVCQG_APP.CREATE_MA_TB_RANDOM(V_MA_THONGBAO);
    ELSIF(V_COUNTS_MATB=0)THEN
         V_MA_THONGBAO:=V_MA_TB;     
    END IF;
  RETURN V_MA_THONGBAO;
END CREATE_MA_TB_RANDOM; 
PROCEDURE TT_REMOVE_TONGDAT
( 
  V_TONGDAT_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
)
IS  
V_COUNTS NUMBER(20);
BEGIN
     V_VALUE:=0;
     SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.TONGDATID=V_TONGDAT_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC
      and TRANGTHAITHANHTOAN=1;--AND EXISTS(SELECT 'X' FROM DVCQG_GIAODICH GD WHERE GD.THANH_TOAN_ID=TT.ID)
     IF(V_COUNTS=0)THEN --update khi chưa phát sinh giao dịch
         UPDATE DVCQG_THANH_TOAN TT
         SET TONGDATID=NULL
         WHERE TT.TONGDATID=V_TONGDAT_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC;
         V_VALUE:=1;
    END IF;
END TT_REMOVE_TONGDAT;
PROCEDURE THANH_TOAN_DELETE_XLY
( 
  V_DONXULY_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
)
IS  
V_COUNTS NUMBER;V_ID_TT NUMBER;V_COUNT_TT NUMBER;V_COUNT_TP NUMBER;
BEGIN
     V_VALUE:=0;
     -------------
     SELECT COUNT(*) INTO V_COUNT_TT FROM DVCQG_THANH_TOAN TT  WHERE TT.DONXULY_ID=V_DONXULY_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
     ----------------
    IF(V_COUNT_TT=1)THEN 
         SELECT TT.ID INTO V_ID_TT FROM DVCQG_THANH_TOAN TT   WHERE TT.DONXULY_ID=V_DONXULY_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
         ---------
         DELETE DVCQG_GIAODICH TT
         WHERE TT.THANH_TOAN_ID=V_ID_TT;
    END IF;
    SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT WHERE TT.DONXULY_ID=V_DONXULY_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0
    AND EXISTS(SELECT 'X' FROM DVCQG_GIAODICH GD WHERE GD.THANH_TOAN_ID=TT.ID);
     IF(V_COUNTS=0)THEN 
        DELETE DVCQG_THANH_TOAN TT
        WHERE TT.DONXULY_ID=V_DONXULY_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC  AND TRANGTHAITHANHTOAN=0;
         ---------
         SELECT COUNT(*) INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TP.DVCQG_TT_ID=V_ID_TT;
            IF(V_COUNT_TP=1)THEN
             DELETE TUPHAP_ANPHI TP
             WHERE  TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TP.DVCQG_TT_ID=V_ID_TT;
             END IF;
        V_VALUE:=1;
     END IF;    
END THANH_TOAN_DELETE_XLY;
PROCEDURE THANH_TOAN_DELETE_ANPHI
( 
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
)
IS  
V_COUNTS NUMBER;V_DUONGSUIDS VARCHAR2(250);V_ID_TT NUMBER;V_COUNT_TT NUMBER;V_COUNT_TP NUMBER;
BEGIN
     V_VALUE:=0;
     SELECT COUNT(*) INTO V_COUNT_TT FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
     ---------------------
    IF(V_COUNT_TT=1)THEN 
         SELECT TT.ID INTO V_ID_TT FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0;
         DELETE DVCQG_GIAODICH TT
         WHERE TT.THANH_TOAN_ID=V_ID_TT;
    END IF;
        SELECT COUNT(*) INTO V_COUNTS FROM DVCQG_THANH_TOAN TT  WHERE TT.ANPHI_ID=V_ANPHI_ID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND TRANGTHAITHANHTOAN=0
        AND EXISTS(SELECT 'X' FROM DVCQG_GIAODICH GD WHERE GD.THANH_TOAN_ID=TT.ID);
    IF(V_COUNTS=0)THEN
         DELETE DVCQG_THANH_TOAN TT
         WHERE TT.ANPHI_ID=V_ANPHI_ID AND TT.MALOAIVUVIEC=V_MALOAIVUVIEC AND TT.TRANGTHAITHANHTOAN=0;
         SELECT COUNT(*) INTO V_COUNT_TP FROM TUPHAP_ANPHI TP WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TP.DVCQG_TT_ID=V_ID_TT;
            IF(V_COUNT_TP=1)THEN
             DELETE TUPHAP_ANPHI TP
             WHERE TP.ANPHI_ID=V_ANPHI_ID AND TP.MALOAIVUVIEC=V_MALOAIVUVIEC AND TP.DVCQG_TT_ID=V_ID_TT;
             END IF;
         V_VALUE:=1;
    END IF;

END THANH_TOAN_DELETE_ANPHI;
  ----------------------------
PROCEDURE THANH_TOAN_UP_TONGDAT
(
   V_TONGDAT_ID IN NUMBER,
   V_DUONGSUID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2
)
AS
     V_DONID NUMBER;V_COUNT NUMBER;
  BEGIN 
        IF(V_MALOAIVUVIEC='2') THEN
            SELECT TD.DONID INTO V_DONID FROM ADS_TONGDAT_DOITUONG OT
            INNER JOIN ADS_TONGDAT TD ON TD.ID=OT.TONGDATID
            WHERE TD.ID=V_TONGDAT_ID AND OT.DUONGSUID=V_DUONGSUID;
            --------------------
            SELECT COUNT(*) INTO V_COUNT FROM DVCQG_THANH_TOAN TT
            WHERE tt.donid=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            IF(V_COUNT=1)THEN
            UPDATE DVCQG_THANH_TOAN 
            SET TONGDATID=V_TONGDAT_ID
            WHERE DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
             END IF;
        ELSIF(V_MALOAIVUVIEC='3') THEN
            SELECT TD.DONID INTO V_DONID FROM AHN_TONGDAT_DOITUONG OT
            INNER JOIN AHN_TONGDAT TD ON TD.ID=OT.TONGDATID
            WHERE TD.ID=V_TONGDAT_ID AND OT.DUONGSUID=V_DUONGSUID;
            ------------------
            SELECT COUNT(*) INTO V_COUNT FROM DVCQG_THANH_TOAN TT
            WHERE tt.donid=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND instr(','||DUONGSU_IDS||',',','||V_DUONGSUID||',')>0;
            IF(V_COUNT=1)THEN
            UPDATE DVCQG_THANH_TOAN 
            SET TONGDATID=V_TONGDAT_ID
            WHERE DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND instr(','||DUONGSU_IDS||',',','||V_DUONGSUID||',')>0;
            END IF;

        ELSIF(V_MALOAIVUVIEC='4') THEN
            SELECT TD.DONID INTO V_DONID FROM AKT_TONGDAT_DOITUONG OT
            INNER JOIN AKT_TONGDAT TD ON TD.ID=OT.TONGDATID
            WHERE TD.ID=V_TONGDAT_ID AND OT.DUONGSUID=V_DUONGSUID;
            ------------------
            SELECT COUNT(*) INTO V_COUNT FROM DVCQG_THANH_TOAN TT
            WHERE tt.donid=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            IF(V_COUNT=1)THEN
            UPDATE DVCQG_THANH_TOAN 
            SET TONGDATID=V_TONGDAT_ID
            WHERE DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            END IF;
        ELSIF(V_MALOAIVUVIEC='5') THEN
            SELECT TD.DONID INTO V_DONID FROM ALD_TONGDAT_DOITUONG OT
            INNER JOIN ALD_TONGDAT TD ON TD.ID=OT.TONGDATID
            WHERE TD.ID=V_TONGDAT_ID AND OT.DUONGSUID=V_DUONGSUID;
            --------------
            SELECT COUNT(*) INTO V_COUNT FROM DVCQG_THANH_TOAN TT
            WHERE tt.donid=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            IF(V_COUNT=1)THEN
            UPDATE DVCQG_THANH_TOAN 
            SET TONGDATID=V_TONGDAT_ID
            WHERE DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            END IF;
        ELSIF(V_MALOAIVUVIEC='6') THEN
            SELECT TD.DONID INTO V_DONID FROM AHC_TONGDAT_DOITUONG OT
            INNER JOIN AHC_TONGDAT TD ON TD.ID=OT.TONGDATID
            WHERE TD.ID=V_TONGDAT_ID AND OT.DUONGSUID=V_DUONGSUID;
            -----------------
            SELECT COUNT(*) INTO V_COUNT FROM DVCQG_THANH_TOAN TT
            WHERE tt.donid=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND instr(','||DUONGSU_IDS||',',','||V_DUONGSUID||',')>0;
            ---------------
            IF(V_COUNT=1)THEN
            UPDATE DVCQG_THANH_TOAN 
            SET TONGDATID=V_TONGDAT_ID
            WHERE DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND instr(','||DUONGSU_IDS||',',','||V_DUONGSUID||',')>0;
            END IF;
        ELSIF(V_MALOAIVUVIEC='7') THEN
            SELECT TD.DONID INTO V_DONID FROM APS_TONGDAT_DOITUONG OT
            INNER JOIN APS_TONGDAT TD ON TD.ID=OT.TONGDATID
            WHERE TD.ID=V_TONGDAT_ID AND OT.DUONGSUID=V_DUONGSUID;
            ----------------------------
            SELECT COUNT(*) INTO V_COUNT FROM DVCQG_THANH_TOAN TT
            WHERE tt.donid=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            IF(V_COUNT=1)THEN
            UPDATE DVCQG_THANH_TOAN 
            SET TONGDATID=V_TONGDAT_ID
            WHERE DONID=V_DONID AND MALOAIVUVIEC=V_MALOAIVUVIEC AND DUONGSU_ID=V_DUONGSUID;
            END IF;
    END IF;
  END THANH_TOAN_UP_TONGDAT;
PROCEDURE RESET_SEQUENCE_QUTO
AS
  BEGIN 
  EXECUTE IMMEDIATE 'ALTER SEQUENCE MA_THONGBAO_SEQ RESTART START WITH 1';
  END RESET_SEQUENCE_QUTO;
END PKG_DVCQG_APP;
