--------------------------------------------------------
--  DDL for Package Body PKG_STPT_NHAPAN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "GSCM"."PKG_STPT_NHAPAN" AS

--An dan su
  PROCEDURE ADS_UPDATE
(
    v_DonGocID in number,
    v_DonConID in number,
    curReturn out sys_refcursor
) AS
  BEGIN
    UPDATE ADS_SOTHAM_QUYETDINH SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE ADS_DON_THAMGIATOTUNG SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE ADS_DON_XULY SET DON_XULYID = v_DonGocID WHERE DON_XULYID = v_DonConID;
    UPDATE ADS_DON_TAILIEU SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE ADS_ANPHI SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE DON_KHAC SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 2;
    UPDATE DON_TIEPNHAN SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 2;
    UPDATE DON_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 2;
    UPDATE DON_DUONGSU_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 2;
  END ADS_UPDATE;

--An hon nhan gia dinh
    PROCEDURE AHN_UPDATE
(
    v_DonGocID in number,
    v_DonConID in number,
    curReturn out sys_refcursor
) AS
  BEGIN
    UPDATE AHN_SOTHAM_QUYETDINH SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE AHN_DON_THAMGIATOTUNG SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    --UPDATE AHN_DON_DUONGSU SET DONID = v_DonGocID, ISDAIDIEN_DONCHITIET = ISDAIDIEN, ISDONCHITIET = 1, ISDAIDIEN = 0 WHERE DONID = v_DonConID;
    UPDATE AHN_DON_XULY SET DON_XULYID = v_DonGocID WHERE DON_XULYID = v_DonConID;
    UPDATE AHN_DON_TAILIEU SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE AHN_ANPHI SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE DON_KHAC SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 3;
    UPDATE DON_TIEPNHAN SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 3;
    UPDATE DON_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 3;
    UPDATE DON_DUONGSU_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 3;
  END AHN_UPDATE;

  --An kinh doanh thuong mai
    PROCEDURE AKT_UPDATE
(
    v_DonGocID in number,
    v_DonConID in number,
    curReturn out sys_refcursor
) AS
  BEGIN
    UPDATE AKT_SOTHAM_QUYETDINH SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE AKT_DON_THAMGIATOTUNG SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    --UPDATE AKT_DON_DUONGSU SET DONID = v_DonGocID, ISDAIDIEN_DONCHITIET = ISDAIDIEN, ISDONCHITIET = 1, ISDAIDIEN = 0 WHERE DONID = v_DonConID;
    UPDATE AKT_DON_XULY SET DON_XULYID = v_DonGocID WHERE DON_XULYID = v_DonConID;
    UPDATE AKT_DON_TAILIEU SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE AKT_ANPHI SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE DON_KHAC SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 4;
    UPDATE DON_TIEPNHAN SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 4;
    UPDATE DON_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 4;
    UPDATE DON_DUONGSU_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 4;
  END AKT_UPDATE;

  --An lao dong
    PROCEDURE ALD_UPDATE
(
    v_DonGocID in number,
    v_DonConID in number,
    curReturn out sys_refcursor
) AS
  BEGIN
    UPDATE ALD_SOTHAM_QUYETDINH SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE ALD_DON_THAMGIATOTUNG SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    --UPDATE ALD_DON_DUONGSU SET DONID = v_DonGocID, ISDAIDIEN_DONCHITIET = ISDAIDIEN, ISDONCHITIET = 1, ISDAIDIEN = 0 WHERE DONID = v_DonConID;
    UPDATE ALD_DON_XULY SET DON_XULYID = v_DonGocID WHERE DON_XULYID = v_DonConID;
    UPDATE ALD_DON_TAILIEU SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE ALD_ANPHI SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE DON_KHAC SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 5;
    UPDATE DON_TIEPNHAN SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 5;
    UPDATE DON_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 5;
    UPDATE DON_DUONGSU_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 5;
  END ALD_UPDATE;

  --An hanh chinh
    PROCEDURE AHC_UPDATE
(
    v_DonGocID in number,
    v_DonConID in number,
    curReturn out sys_refcursor
) AS
  BEGIN
    UPDATE AHC_SOTHAM_QUYETDINH SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE AHC_DON_THAMGIATOTUNG SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    --UPDATE AHC_DON_DUONGSU SET DONID = v_DonGocID, ISDAIDIEN_DONCHITIET = ISDAIDIEN, ISDONCHITIET = 1, ISDAIDIEN = 0 WHERE DONID = v_DonConID;
    UPDATE AHC_DON_XULY SET DON_XULYID = v_DonGocID WHERE DON_XULYID = v_DonConID;
    UPDATE AHC_DON_TAILIEU SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE AHC_ANPHI SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE DON_KHAC SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 6;
    UPDATE DON_TIEPNHAN SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 6;
    UPDATE DON_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 6;
    UPDATE DON_DUONGSU_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 6;
  END AHC_UPDATE;

  --An pha san
    PROCEDURE APS_UPDATE
(
    v_DonGocID in number,
    v_DonConID in number,
    curReturn out sys_refcursor
) AS
  BEGIN
    UPDATE APS_SOTHAM_QUYETDINH SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE APS_DON_THAMGIATOTUNG SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    --UPDATE APS_DON_DUONGSU SET DONID = v_DonGocID, ISDAIDIEN_DONCHITIET = ISDAIDIEN, ISDONCHITIET = 1, ISDAIDIEN = 0 WHERE DONID = v_DonConID;
    UPDATE APS_DON_XULY SET DON_XULYID = v_DonGocID WHERE DON_XULYID = v_DonConID;
    UPDATE APS_DON_TAILIEU SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE APS_ANPHI SET DONID = v_DonGocID WHERE DONID = v_DonConID;
    UPDATE DON_KHAC SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 7;
    UPDATE DON_TIEPNHAN SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 7;
    UPDATE DON_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIANID = 7;
    UPDATE DON_DUONGSU_CHITIET SET DONID = v_DonGocID WHERE DONID = v_DonConID AND LOAIAN = 7;
  END APS_UPDATE;

END PKG_STPT_NHAPAN;
