--------------------------------------------------------
--  DDL for Package Body PKG_QUANTRI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_QUANTRI" AS
PROCEDURE  QT_NHOM_HOME_GET
( 
    v_CHUONGTRINHID in number,
    v_NHOMID in number,
    curReturn OUT sys_refcursor
)
IS 
BEGIN
    OPEN curReturn FOR
    SELECT DN.* FROM QT_NHOMNGUOIDUNG_HOME DN  
    WHERE DN.CHUONGTRINHID=v_CHUONGTRINHID AND DN.NHOMID=v_NHOMID;

END QT_NHOM_HOME_GET;
PROCEDURE  QT_NHOM_HOME_IN_UP
( 
    v_CHUONGTRINHID in number,
    v_NHOMID in number,
    v_XEM in number,
    v_XEM_ALL in number
)
IS 
   V_TOTAL number;v_ID number;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM QT_NHOMNGUOIDUNG_HOME DN WHERE DN.CHUONGTRINHID=v_CHUONGTRINHID AND DN.NHOMID=v_NHOMID;
    IF(V_TOTAL=0) THEN
         insert into QT_NHOMNGUOIDUNG_HOME 
            (ID,NHOMID,CHUONGTRINHID,XEM,XEM_ALL)
         values (QT_NHOMNGUOIDUNG_HOME_SEQ.nextval,v_NHOMID,v_CHUONGTRINHID,v_XEM,v_XEM_ALL);
    ELSE
        SELECT DN.ID INTO v_ID FROM QT_NHOMNGUOIDUNG_HOME DN WHERE DN.CHUONGTRINHID=v_CHUONGTRINHID AND DN.NHOMID=v_NHOMID;
            UPDATE QT_NHOMNGUOIDUNG_HOME 
            SET XEM = v_XEM,
                XEM_ALL=v_XEM_ALL
            WHERE ID = v_ID;
    END IF;
END QT_NHOM_HOME_IN_UP;
PROCEDURE  QT_NHOM_ISHOME_GET
( 
    v_NHOMID in number,
    curReturn OUT sys_refcursor
)
IS 
BEGIN
    OPEN curReturn FOR
    SELECT DN.* FROM QT_NHOMNGUOIDUNG_ISHOME DN  
    WHERE DN.NHOMID=v_NHOMID;
END QT_NHOM_ISHOME_GET;
PROCEDURE  QT_NHOM_ISHOME_IN_UP
( 
    v_NHOMID in number,
    v_VIEW_TK in number
)
IS 
   V_TOTAL number;v_ID number;
BEGIN
    SELECT COUNT(*) INTO V_TOTAL FROM QT_NHOMNGUOIDUNG_ISHOME DN WHERE  DN.NHOMID=v_NHOMID;
    IF(V_TOTAL=0) THEN
         insert into QT_NHOMNGUOIDUNG_ISHOME 
            (ID,NHOMID,VIEW_TK)
         values (QT_NHOMNGUOIDUNG_ISHOME_SEQ.nextval,v_NHOMID,v_VIEW_TK);
    ELSE
        SELECT DN.ID INTO v_ID FROM QT_NHOMNGUOIDUNG_ISHOME DN WHERE  DN.NHOMID=v_NHOMID;
            UPDATE QT_NHOMNGUOIDUNG_ISHOME 
            SET VIEW_TK = v_VIEW_TK
            WHERE ID = v_ID;
    END IF;
END QT_NHOM_ISHOME_IN_UP;
END PKG_QUANTRI;
