--------------------------------------------------------
--  File created - Thursday-January-11-2024   
--------------------------------------------------------
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\COMMON_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PACKAGE_UPDATE_DATA.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PCA_PKG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_ADS_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_AHC_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_AHN_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_AHS_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_AKT_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_ALD_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_APS_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_BAOCAO_CA_QLTA.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_BC_GQ_DONDN_GDTTT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_BC_GQ_DONDN_GDTTT_TEST.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_CC_HCTP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_CHUYEN_NHAN_AN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_COVID.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_COVID_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_COVID_HETHONG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DONCHOXL.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DONVI_REPORT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DON_GHEP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DUONGSU_ANPHI.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DVCQG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DVCQG_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DVCQG_THADS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_DVCQ_SEARCH_THUCONG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTTT_KNTP_CC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_APP_CACC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_APP_CACC_DN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_APP_CACC_GET.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_BAOCAO.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_BAOCAO_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_CC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_DON_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_GET.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_BC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_BC_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_BC_CC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_BC_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_PHATHANH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_HCTP_QUANLYSO.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_TUHINH_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_VUAN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_VUAN_INBC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_VUAN_TEST.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_VUAN_TK.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GDTTT_VUAN_TUHINH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GET_PUBLIC_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_DELETE.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_DONTHULY.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_REPORT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_REPORT_HS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_SOTHULY.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_SOTHULY_HINHSU.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_SOTHULY_PHUCTHAM.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_GSTP_SOTHULY_SOTHAM.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_HCTP_PHATHANH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_HCTP_TRUNG_GIAN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_HOSO_PT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_LOAD_DM_QDVUAN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_LOAD_DM_QDVUAN_KETTHUC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_LOAD_PAGE_KHANGCAO_ST.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP_HANHCHINH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP_HNGD.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP_HS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP_KINHTE.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_PCTP_LAODONG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_QLA_TH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_QLHS_STPT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_QUANTRI.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_ADS_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_AHC_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_AHN_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_AHS_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_AHS_GS2.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_AKT_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_ALD_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_APP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_APS_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_BAQD.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_DANHSACH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_DS_BC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_DS_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_EXT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_HANHCHINH.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_HINHTHUCXETXU.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_HNGD.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_HS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_HS_TONGHOPHINHPHAT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_KINHTE.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_LAODONG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_NHAPAN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_PS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_QLCS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_SEARCH_ALL.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_SEARCH_BC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_XLHC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_STPT_YCBS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_THA.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_THA_GS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_TOANCAU_STPT_EXT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_TUPHAP_ANPHI.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_TUPHAP_ANPHI_DVCQG.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_TUPHAP_QUANTRI.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_TUPHAP_REPORT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VANTHU_DEN.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VGDKT_BAOCAO.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VGDKT_BAOCAO_TK.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VGDKT_BAOCAO_TT.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VGDKT_BAOCAO_TUANVNA.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VGDKT_BAOCAO_VA.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\PKG_VGDKT_BAOCAO_VA_CC.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\UYTHACTUPHAP.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\VT_PKG_STPT_DS.sql
@C:\Project_anhvh\GIAMSAT_Random\update_qlta\gscm_app_git\WEB\WEB.GSTP\PACKAGES_SQL\GSCM_PDBSPCEXA\SPEAC\VT_PKG_STPT_DS_1809.sql
