--------------------------------------------------------
--  DDL for Package PKG_LOAD_DM_QDVUAN_KETTHUC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_LOAD_DM_QDVUAN_KETTHUC" AS

--------------LOAD DROPDOWNLIST QUYẾT ĐỊNH KẾT THÚC-------------
PROCEDURE DM_QUYETDINH_VUAN_SOTHAM_KETTHUC
(
    VLOAIAN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE DM_QUYETDINH_VUAN_PHUCTHAM_KETTHUC
(
    VLOAIAN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

-------------LOAD QUYẾT ĐỊNH DGLIST------------
PROCEDURE DGLIST_BAQD_QUYETDINH_KETTHUC_ST
(
    VLOAIAN VARCHAR2,
    VDONID NUMBER,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE DGLIST_BAQD_QUYETDINH_KETTHUC_PT
(
    VLOAIAN VARCHAR2,
    VDONID NUMBER,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE ADS_DM_QUYETDINH_VUAN_PTQDK
    (
        curReturn OUT SYS_REFCURSOR
    ) ; 
END PKG_LOAD_DM_QDVUAN_KETTHUC;
