--------------------------------------------------------
--  DDL for Package PKG_DUONGSU_ANPHI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_DUONGSU_ANPHI" AS 

PROCEDURE ADS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE AHC_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE AHN_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE AKT_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE ALD_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE APS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE ADS_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE AKT_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE ALD_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE APS_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE CHECK_ADS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE CHECK_AHC_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE CHECK_AHN_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE CHECK_AKT_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE CHECK_ALD_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE CHECK_APS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
END PKG_DUONGSU_ANPHI;
