--------------------------------------------------------
--  DDL for Package PKG_TUPHAP_ANPHI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_TUPHAP_ANPHI" AS 
FUNCTION TC_DANHSACH_ANPHI 
(
  V_GET_CHIL IN VARCHAR2 DEFAULT NULL, 
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL, 
  V_TT_TRUCTUYEN IN VARCHAR2 DEFAULT NULL, 
  V_DATE_FROM IN VARCHAR2 DEFAULT NULL,  
  V_DATE_TO IN VARCHAR2 DEFAULT NULL, 
  V_STATUS IN NVARCHAR2 DEFAULT NULL,
  V_USERNAME IN NVARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID IN NVARCHAR2 DEFAULT NULL,
  vTuKhoaBasic IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	int,
  PageSize	in	int
)RETURN SYS_REFCURSOR;
FUNCTION TC_DANHSACH_ANPHI_IN_DS 
(
  V_GET_CHIL IN VARCHAR2 DEFAULT NULL, 
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL, 
  V_TT_TRUCTUYEN IN VARCHAR2 DEFAULT NULL, 
  V_DATE_FROM IN VARCHAR2 DEFAULT NULL,  
  V_DATE_TO IN VARCHAR2 DEFAULT NULL, 
  V_STATUS IN NVARCHAR2 DEFAULT NULL,
  V_USERNAME IN NVARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID IN NVARCHAR2 DEFAULT NULL,
  vTuKhoaBasic IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	int,
  PageSize	in	int
)
RETURN SYS_REFCURSOR;
FUNCTION LOAD_EDIT
(
    V_MA_THONGBAO IN VARCHAR2 DEFAULT NULL,
    V_MALOAIVUVIEC IN VARCHAR2 DEFAULT NULL,
    V_USERNAME IN VARCHAR2 DEFAULT NULL,
    V_DONID  IN NUMBER,
    V_DS_ID  IN VARCHAR2 DEFAULT NULL,
    V_DS_IDS  IN VARCHAR2 DEFAULT NULL
)RETURN SYS_REFCURSOR;
FUNCTION GET_SOLUONG
(
  V_USERNAME IN VARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
)RETURN SYS_REFCURSOR;
PROCEDURE CREATE_SOBIENLAI_APP (
        V_DONVITHA_ID  IN NUMBER,
        CURRETURN OUT SYS_REFCURSOR
    );
END PKG_TUPHAP_ANPHI;
