--------------------------------------------------------
--  DDL for Package PKG_GET_PUBLIC_APP
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_GET_PUBLIC_APP" AS 
 FUNCTION PUBLIC_COURT_DETAIL
(
 V_COURT_ID	VARCHAR2 DEFAULT NULL,
 V_TYPE VARCHAR2 DEFAULT NULL,
  PageIndex	in	int,
  PageSize	in	int  
 ) RETURN SYS_REFCURSOR;
FUNCTION COUNT_OF_TYPE
(
  V_COURT_ID	VARCHAR2 DEFAULT NULL
 ) RETURN SYS_REFCURSOR;
  FUNCTION PUBLIC_GSTP_HOME
(
 V_COURT_ID	VARCHAR2 DEFAULT NULL,--ma dong bo
 V_STAFFS  VARCHAR2 DEFAULT NULL--ma dong bo
 ) RETURN SYS_REFCURSOR;
FUNCTION PUBLIC_JUDGE_COUNT_FOUR
( 
  VV_STAFFS  VARCHAR2 DEFAULT NULL,
  V_DATE_FROM VARCHAR2 DEFAULT NULL, 
  V_DATE_TO VARCHAR2 DEFAULT NULL
 ) RETURN SYS_REFCURSOR ;
END PKG_GET_PUBLIC_APP;
