--------------------------------------------------------
--  DDL for Package PKG_GSTP_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_GSTP_DELETE" AS 

FUNCTION HISTORY_DELETE_HOSO_AN_SOTHAM_VUANID
(
   in_VUANID IN NUMBER,
  in_LOAIANID IN NUMBER,
  in_NGUOIXOAID IN VARCHAR2,
  in_TAIKHOANXOA IN VARCHAR2,
  in_TENCHUCNANG IN VARCHAR2,
  in_HANHDONG     IN VARCHAR2,
  in_OBJECT     IN CLOB
)RETURN NUMBER;
FUNCTION DELETE_DATA_AHS_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_ADS_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_AHN_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_AKT_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_ALD_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_AHC_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_APS_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_XLHC_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_BY_TOAANID
(
  in_TOAANID IN NVARCHAR2,
  in_TOAANCAPCON IN BOOLEAN,
  out_RESULT OUT NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_BY_LOAIAN
(
  in_LOAIAN IN NVARCHAR2,
  out_RESULT OUT NVARCHAR2
) RETURN NUMBER;

FUNCTION DELETE_DATA_BY_VUANID
(
  in_VUANID IN NVARCHAR2,
  in_LOAIAN IN NVARCHAR2,
  out_RESULT OUT NVARCHAR2
) RETURN NUMBER;

END PKG_GSTP_DELETE;
