--------------------------------------------------------
--  DDL for Package PKG_TUPHAP_REPORT
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_TUPHAP_REPORT" AS 
FUNCTION GET_DONVI_BC
(
 v_capxx in varchar2,
 v_object_select in varchar2
)
RETURN SYS_REFCURSOR;
FUNCTION GET_DONVI_TINH
(
 V_CAPCHAID in varchar2
)
RETURN SYS_REFCURSOR;
FUNCTION GET_REPORT_THADS
(
  V_TT_TRUCTUYEN IN VARCHAR2 DEFAULT NULL, 
  v_Names NVARCHAR2 DEFAULT NULL,
  V_OPTIONS IN NUMBER,
  V_DATE_FROM IN VARCHAR2 DEFAULT NULL,  
  V_DATE_TO IN VARCHAR2 DEFAULT NULL, 
  V_DONVITHA_ID IN NVARCHAR2 DEFAULT NULL,
  V_CAP_THA IN VARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR;
END PKG_TUPHAP_REPORT;
