--------------------------------------------------------
--  DDL for Package PKG_TUPHAP_ANPHI_DVCQG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_TUPHAP_ANPHI_DVCQG" AS 
PROCEDURE GET_FILE_ATTACH
  (

     V_MA_THONGBAO IN VARCHAR2 DEFAULT NULL ,
     V_FILE_NAME OUT VARCHAR2,
     ITEMS_CURSOR OUT SYS_REFCURSOR
  );
PROCEDURE  INSERT_DUONGSU_AHN_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_AHN
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_AHN
( 
  V_ANPHI_ID IN NUMBER
);
PROCEDURE  INSERT_DUONGSU_AHC_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_AHC
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_AHC
( 
  V_ANPHI_ID IN NUMBER
);
PROCEDURE CHECK_DELETE_ANPHI
( 
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
);
END PKG_TUPHAP_ANPHI_DVCQG;
