--------------------------------------------------------
--  DDL for Package PKG_PCTP_HNGD
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_PCTP_HNGD" AS
PROCEDURE PCTP_INS_UP
(
    V_TRANGTHAI IN VARCHAR2,
    V_THAMPHANGQ_ID IN VARCHAR2,
    V_DONID	IN VARCHAR2,
    V_NGAYPHANCONGTP	IN VARCHAR2,
    V_THAM_PHAN_ID	IN VARCHAR2,
    V_NGAYPHANCONGLD	IN VARCHAR2,
    V_PHANCONGLD_ID	IN VARCHAR2,
    V_CAPXX	IN VARCHAR2,
    V_NGUOITAO IN VARCHAR2,
    V_COUNTS OUT NUMBER,
    V_THONGBAO	OUT VARCHAR2
);
 PROCEDURE DON_SEARCH
( 
    V_CAP_XET_XU_LOGIN  IN VARCHAR2,
    V_TEN_VU_AN IN VARCHAR2, 
    V_QHPL IN VARCHAR2, 
    V_MA_VU_AN IN VARCHAR2, 
    V_TENDUONGSU IN VARCHAR2,
    V_CAPXX IN VARCHAR2,
    V_TOAAN_ID IN VARCHAR2, 
    V_TINHTRANG_THULY IN VARCHAR2,
    V_NGAYTHULY_TU IN VARCHAR2,
    V_NGAYTHULY_DEN IN VARCHAR2,
    V_SOTHULY IN VARCHAR2,
    V_THAMPHAN_ID IN VARCHAR2, 
    V_TINHTRANG_GIAIQUYET IN VARCHAR2,
    V_TUNGAY IN VARCHAR2,
    V_DENNGAY IN VARCHAR2,
    V_KETQUA IN VARCHAR2,
    V_SO_QD IN VARCHAR2,
    V_NGAY_QD IN VARCHAR2,
    V_THUKY_ID IN VARCHAR2, 
    V_THOIHAN_GQ IN VARCHAR2, 
    V_LOAIDON IN VARCHAR2, 
    V_PT_RKINHNGHIEM IN VARCHAR2, 
    V_GQDON IN VARCHAR2, 
    Page_Index in	int,
    Page_Size	in	int, 
    curReturn OUT sys_refcursor
);
--FUNCTION DON_SEARCH_PRINT_OLD
--( 
--    V_CAP_XET_XU_LOGIN  IN VARCHAR2,
--    V_TEN_VU_AN IN VARCHAR2, 
--    V_QHPL IN VARCHAR2, 
--    V_MA_VU_AN IN VARCHAR2, 
--    V_TENDUONGSU IN VARCHAR2,
--    V_CAPXX IN VARCHAR2,
--    V_TOAAN_ID IN VARCHAR2, 
--    V_TINHTRANG_THULY IN VARCHAR2,
--    V_NGAYTHULY_TU IN VARCHAR2,
--    V_NGAYTHULY_DEN IN VARCHAR2,
--    V_SOTHULY IN VARCHAR2,
--    V_THAMPHAN_ID IN VARCHAR2, 
--    V_TINHTRANG_GIAIQUYET IN VARCHAR2,
--    V_TUNGAY IN VARCHAR2,
--    V_DENNGAY IN VARCHAR2,
--    V_KETQUA IN VARCHAR2,
--    V_SO_QD IN VARCHAR2,
--    V_NGAY_QD IN VARCHAR2,
--    V_THUKY_ID IN VARCHAR2, 
--    V_THOIHAN_GQ IN VARCHAR2, 
--    V_LOAIDON IN VARCHAR2, 
--    V_PT_RKINHNGHIEM IN VARCHAR2, 
--    V_GQDON IN VARCHAR2, 
--    Page_Index in	int,
--    Page_Size	in	int
--)RETURN SYS_REFCURSOR;
FUNCTION DON_SEARCH_PRINT
( 
    V_CAP_XET_XU_LOGIN  IN VARCHAR2,
    V_TEN_VU_AN IN VARCHAR2, 
    V_QHPL IN VARCHAR2, 
    V_MA_VU_AN IN VARCHAR2, 
    V_TENDUONGSU IN VARCHAR2,
    V_CAPXX IN VARCHAR2,
    V_TOAAN_ID IN VARCHAR2, 
    V_TINHTRANG_THULY IN VARCHAR2,
    V_NGAYTHULY_TU IN VARCHAR2,
    V_NGAYTHULY_DEN IN VARCHAR2,
    V_SOTHULY IN VARCHAR2,
    V_THAMPHAN_ID IN VARCHAR2, 
    V_TINHTRANG_GIAIQUYET IN VARCHAR2,
    V_TUNGAY IN VARCHAR2,
    V_DENNGAY IN VARCHAR2,
    V_KETQUA IN VARCHAR2,
    V_SO_QD IN VARCHAR2,
    V_NGAY_QD IN VARCHAR2,
    V_THUKY_ID IN VARCHAR2, 
    V_THOIHAN_GQ IN VARCHAR2, 
    V_LOAIDON IN VARCHAR2, 
    V_PT_RKINHNGHIEM IN VARCHAR2, 
    V_GQDON IN VARCHAR2, 
    Page_Index in	int,
    Page_Size	in	int
)RETURN SYS_REFCURSOR;
FUNCTION DON_SEARCH_PRINT_ITEM
( 
    V_CAP_XET_XU_LOGIN  IN VARCHAR2,
    V_TEN_VU_AN IN VARCHAR2, 
    V_QHPL IN VARCHAR2, 
    V_MA_VU_AN IN VARCHAR2, 
    V_TENDUONGSU IN VARCHAR2,
    V_CAPXX IN VARCHAR2,
    V_TOAAN_ID IN VARCHAR2, 
    V_TINHTRANG_THULY IN VARCHAR2,
    V_NGAYTHULY_TU IN VARCHAR2,
    V_NGAYTHULY_DEN IN VARCHAR2,
    V_SOTHULY IN VARCHAR2,
    V_THAMPHAN_ID IN VARCHAR2, 
    V_TINHTRANG_GIAIQUYET IN VARCHAR2,
    V_TUNGAY IN VARCHAR2,
    V_DENNGAY IN VARCHAR2,
    V_KETQUA IN VARCHAR2,
    V_SO_QD IN VARCHAR2,
    V_NGAY_QD IN VARCHAR2,
    V_THUKY_ID IN VARCHAR2, 
    V_THOIHAN_GQ IN VARCHAR2, 
    V_LOAIDON IN VARCHAR2, 
    V_PT_RKINHNGHIEM IN VARCHAR2, 
    V_GQDON IN VARCHAR2, 
    Page_Index in	int,
    Page_Size	in	int
)RETURN SYS_REFCURSOR;
END PKG_PCTP_HNGD;
