--------------------------------------------------------
--  DDL for Package PKG_COVID_HETHONG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_COVID_HETHONG" AS
FUNCTION UPDATE_NGUOISUDUNG
RETURN SYS_REFCURSOR;
FUNCTION TAO_DS_USER_EXPORT_01
RETURN SYS_REFCURSOR;
FUNCTION EDIT_USER_TRUNG_TEMP_01
RETURN SYS_REFCURSOR;
FUNCTION TAO_USER_NOT_IN_QLCB
RETURN SYS_REFCURSOR;
FUNCTION COVID_DM_CANBO_INSERT
RETURN SYS_REFCURSOR;
FUNCTION EDIT_USER_TRUNG_TEMP
RETURN SYS_REFCURSOR;
FUNCTION TAO_DS_USER_EXPORT
RETURN SYS_REFCURSOR;
FUNCTION EDIT_COVID_DMCANBO
RETURN SYS_REFCURSOR;
FUNCTION TAO_PHONGBAN
RETURN SYS_REFCURSOR;
FUNCTION TAO_DV_TRUCTHUOC
RETURN SYS_REFCURSOR;
FUNCTION EDIT_USER_TRUNG
RETURN SYS_REFCURSOR;
FUNCTION TAO_USER
RETURN SYS_REFCURSOR;
FUNCTION BO_DAU_TIENG_VIET
(
p_string VARCHAR2
)
RETURN VARCHAR2;
END PKG_COVID_HETHONG;
