--------------------------------------------------------
--  DDL for Package PKG_LOAD_PAGE_KHANGCAO_ST
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_LOAD_PAGE_KHANGCAO_ST" AS

PROCEDURE DANHSACH_KHANGCAO_BANAN
(
    VLOAIAN VARCHAR2,
    VDONID NUMBER,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE DANHSACH_KHANGCAO_QUYETDINH
(
    VLOAIAN VARCHAR2,
    VDONID NUMBER,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE DANHSACH_KHANGCAO_QUYETDINH_KHAC
(
    VLOAIAN VARCHAR2,
    VDONID NUMBER,
    curReturn OUT SYS_REFCURSOR
);

END PKG_LOAD_PAGE_KHANGCAO_ST;
