--------------------------------------------------------
--  DDL for Package PKG_VANTHU_DEN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_VANTHU_DEN" AS 
PROCEDURE  VT_HUY_NHAN_IN_DELETE
( 
  V_VANBANDEN_ID IN VARCHAR2
);
PROCEDURE VT_DEN_INS_UP
    (
    V_ID	in	NUMBER,
    V_LOAI_VB	in	NUMBER,
    V_SODEN	in	NUMBER,
    V_NGAY_DEN	in	DATE,
    V_NGUOI_GUI_BT	in	VARCHAR2,
    V_DIACHI_GUI_BT	in	VARCHAR2,
    V_NGAY_BT	in	DATE,
    V_NOI_NHAN	in	NUMBER,
    V_NGUOI_NHAN	in	NUMBER,
    V_GHICHU	in	VARCHAR2,
    V_SO_VB	in	VARCHAR2,
    V_NGAY_VB	in	DATE,
    V_NOIDUNG_VB	in	VARCHAR2,
    V_SOLUONG_DON	in	NUMBER,

    V_LOAI_GDTTTT	in	NUMBER, 
    V_BAQD_CHECK_DON	in	NUMBER,
    V_LOAI_AN_DON	in	NUMBER,
    V_CAP_XX_DON	in	NUMBER,
    V_SO_BAQD_DON	in	VARCHAR2,
    V_NGAY_BAQD_DON	in	DATE,
    V_TOAAN_BAQD_DON in	NUMBER,

    V_BIDON	in	VARCHAR2,
    V_NGUYENDON	in	VARCHAR2,
    V_QHPL_DS	in	VARCHAR2,
    V_QHPL_HS in	NUMBER,
    V_SOLUONG_GAM in	NUMBER,

    V_SO_CV	in	VARCHAR2,
    V_NGAY_CV	in	DATE,
    V_DONVICHUYEN_CV	in	VARCHAR2,
    V_NOIDUNG_CV	in	VARCHAR2,

    V_DVXULY_ID_DON	in	NUMBER,
    V_CANBONHAN_ID	in	NUMBER,
    V_NGAY_GIAO_DON	in	DATE,

    V_SO_HS	in	VARCHAR2,
    V_NGAY_HS	in	DATE,
    V_DONVICHUYEN_HS	in	NUMBER,
    V_GHICHU_HS	in	VARCHAR2,
    V_NGUOI_TAO	in	VARCHAR2,
    V_TOAANID	in	NUMBER,
    V_NGUON_DEN	in	NUMBER,
    V_MABD	in	VARCHAR2,
    V_NGUOIDUNGDON in	VARCHAR2,
    V_DIACHI_NDD in	VARCHAR2,
    V_DOMAT_ID in	VARCHAR2,
    V_DO_KHAN_ID in	VARCHAR2,
    V_DIACHI_GUI_BT_ID	in	NUMBER,
    V_DIACHI_NDD_ID	in	NUMBER,
    V_ID_VBDH IN NUMBER
    );
 PROCEDURE  DM_PHONGBAN_LIST
(
  V_TOAANID IN VARCHAR2,
  V_PHONGBAN_ID IN VARCHAR2,
  V_LOAI_COMBO  IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);   
PROCEDURE  LANH_DAO_LIST
(
  V_TOAANID IN VARCHAR2,
  V_PHONGBANID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
); 
PROCEDURE  CANBO_LIST_BY_PHONGBAN
(
  V_TOAANID IN VARCHAR2,
  V_PHONGBANID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE SODEN_GET
(
  V_TOAANID IN VARCHAR2,
  V_PHONGBANID IN VARCHAR2,
  V_LOAI_VB IN VARCHAR2,
  V_SODEN OUT NUMBER
);
 PROCEDURE  VT_VANBANDEN_SEARCH
( 
    V_TOAANID in	VARCHAR2,
    V_NGUON_DEN in	VARCHAR2,
    V_NGUOIDUNGDON in	VARCHAR2,
    V_LOAI_AN_DON in	VARCHAR2,
    V_TOAAN_BAQD_DON in	VARCHAR2,
    V_SO_BAQD_DON  in	VARCHAR2,
    V_NGAY_BAQD_DON  in	VARCHAR2,
    V_NGUOI_TAO in	VARCHAR2,
    -----------
    V_PHONGBAN_ID in	VARCHAR2,
    -----------
    V_LOAI_VB	in	VARCHAR2,
    V_NOI_NHAN	in	VARCHAR2,
    V_NGUOI_NHAN in	VARCHAR2,
    V_SODEN_TU	in	VARCHAR2,
    V_SODEN_DEN	in	VARCHAR2,
    V_ID	in	VARCHAR2,
    V_LOAI_NGAY in VARCHAR2,
    V_NGAY_FROM	in VARCHAR2,
    V_NGAY_TO	in VARCHAR2,
    V_NGUOI_GUI_BT	in	VARCHAR2,
    V_DIACHI_GUI_BT	in	VARCHAR2,
    V_GHICHU	in	VARCHAR2,
    V_TRANGTHAICHUYEN in	VARCHAR2,
    -----------
    PageIndex	in	int,
    PageSize	in	int,  
    curReturn OUT sys_refcursor
);
PROCEDURE  VT_VANBANDEN_BY_ID
(
    V_ID  in NUMBER,
    curReturn OUT sys_refcursor
);
PROCEDURE  VT_CHUYEN_NHAN_BY_DONID
(
    V_DonID  in NUMBER,
    curReturn OUT sys_refcursor
);
PROCEDURE  VBD_LOAD_ID
    ( 
      V_TOAANID IN VARCHAR2,
      V_ID IN VARCHAR2,
      curReturn OUT sys_refcursor
    );
PROCEDURE  DM_LOAIAN_LIST
    ( 
      curReturn OUT sys_refcursor
    );
PROCEDURE  VT_DEN_DELETE
    ( 
      V_ID IN VARCHAR2
    );
PROCEDURE VT_CHUYEN_INS
    (
        V_VANBANDEN_ID  in  NUMBER,
        V_DONVI_CHUYEN_ID in  NUMBER,
        V_CANBO_CHUYEN_ID in  NUMBER
    );
PROCEDURE  VT_HUY_CHUYEN
    ( 
       V_VANBANDEN_ID IN VARCHAR2,
       V_CANBO_NHAN_ID OUT VARCHAR2
    );    
PROCEDURE VT_NHAN_INS_UP
    (
        V_TOAANID in NUMBER,
        V_VANBANDEN_ID  in  NUMBER,
        V_CANBO_NHAN_ID in  NUMBER,
        V_USERNAME_NHAN IN VARCHAR2
    );
PROCEDURE  VT_HUY_NHAN
    ( 
      V_VANBANDEN_ID IN VARCHAR2,
      V_TRANG_THAI_XLY OUT VARCHAR2
    );  
 PROCEDURE VT_DAXULY_UP
    (
        V_GDTTT_DON_ID IN VARCHAR2
    );  
PROCEDURE VT_VANBANDEN_BY_ID_VBDH
    (
        V_ID_VBDH IN NUMBER,
        CurReturn OUT sys_refcursor
    );
PROCEDURE VT_CHUYENNHAN_BY_VANBANDEN_ID
    (
        V_VANBANDEN_ID IN NUMBER,
        CurReturn OUT sys_refcursor
    );
PROCEDURE TRANG_THAI_XLY_UP
    (
        V_ID IN NUMBER,
        V_TRANG_THAI_XLY IN NUMBER
    );
END PKG_VANTHU_DEN;
