--------------------------------------------------------
--  DDL for Package PKG_STPT_HINHTHUCXETXU
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_STPT_HINHTHUCXETXU" AS 

FUNCTION BAOCAO_XETXUTRUCTUYEN
(
    vDonViID  IN number,
    V_TUNGAY IN VARCHAR2,
    V_DENNGAY IN VARCHAR2,
    v_TOAANID in VARCHAR2
)RETURN SYS_REFCURSOR;

PROCEDURE DANHSACH_CAPNHAT_HINHTHUCXETXU
( 
    VTOAANID IN NUMBER,
    VLOAIAN IN NUMBER,
    VTRANGTHAI IN NUMBER,
    VCHUTOAID IN NUMBER,
    VBAQDTUNGAY VARCHAR2,
    VBAQDDENNGAY VARCHAR2,
    curReturn OUT sys_refcursor
);
END PKG_STPT_HINHTHUCXETXU;
