--------------------------------------------------------
--  DDL for Package PKG_STPT_QUANLY_SOTHULY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_STPT_QUANLY_SOTHULY" AS 

PROCEDURE GET_LATEST_DATE_IN_SOTHULY
(
  in_MAGIAIDOAN IN NUMBER,
  in_LOAIAN IN NUMBER,
  in_TOAAN_ID IN NUMBER,
  in_NGAYTHULY IN VARCHAR2,
  CURRETURN               OUT   SYS_REFCURSOR
);

PROCEDURE GET_STPT_QUANLY_SOTHULY_THEONGAY_SOTHAM
(
  in_MAGIAIDOAN IN NUMBER,
  in_LOAIAN IN NUMBER,
  in_TOAAN_ID IN NUMBER,
  in_NGAYTHULY IN VARCHAR2,
  CURRETURN               OUT   SYS_REFCURSOR
);

PROCEDURE GET_STPT_QUANLY_SOTHULY_THEONGAY_PHUCTHAM
(
  in_MAGIAIDOAN IN NUMBER,
  in_LOAIAN IN NUMBER,
  in_TOAAN_ID IN NUMBER,
  in_NGAYTHULY IN VARCHAR2,
  CURRETURN               OUT   SYS_REFCURSOR
);

PROCEDURE UPDATE_STPT_QUANLY_SOTHULY_THEOSOTHULYVANAM
(
  in_MAGIAIDOAN IN NUMBER,
  in_LOAIAN IN NUMBER,
  in_TOAAN_ID IN NUMBER,
  in_NGAYTHULY IN VARCHAR2,
  in_SOTHULY IN VARCHAR2,
  CURRETURN               OUT   SYS_REFCURSOR
);

END PKG_STPT_QUANLY_SOTHULY;

/
