--------------------------------------------------------
--  DDL for Package PKG_DASHBOARD_BAOCAO
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_DASHBOARD_BAOCAO" AS 

FUNCTION DASHBOARD_M1_TATC_BAOCAO
(
  VTOAANID IN NUMBER,
  VTHAMPHANID  IN NUMBER,
  VTUNGAY IN DATE,
  VDENNGAY IN DATE
)RETURN SYS_REFCURSOR;

FUNCTION DASHBOARD_M1_TPTATC_BAOCAO
(
  VTOAANID IN NUMBER,
  VTHAMPHANID  IN NUMBER,
  VTUNGAY IN DATE,
  VDENNGAY IN DATE
)
RETURN SYS_REFCURSOR;

END PKG_DASHBOARD_BAOCAO;

/
