--------------------------------------------------------
--  DDL for Package PKG_STPT_SEARCH_BC
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_STPT_SEARCH_BC" AS
FUNCTION THSL_XX
(
    V_CANBO_TK_ID  IN VARCHAR2,
    V_LANHDAO_TK_ID  IN VARCHAR2,
    V_CAP_XET_XU_LOGIN  IN VARCHAR2,
    V_TOAAN_ID in varchar2, 
    V_TUNGAY IN VARCHAR2,
    V_DENNGAY IN VARCHAR2,
    V_LOAIAN_ID IN VARCHAR2
)RETURN SYS_REFCURSOR;
 FUNCTION TL_XX_TRINHTU_PT
(
    V_CANBO_TK_ID  IN VARCHAR2,
    V_LANHDAO_TK_ID  IN VARCHAR2,
    V_CAP_XET_XU_LOGIN  IN VARCHAR2,
    V_TOAAN_ID in varchar2, 
    V_TUNGAY IN VARCHAR2,
    V_DENNGAY IN VARCHAR2,
    V_LOAIAN_ID IN VARCHAR2
)RETURN SYS_REFCURSOR;
END PKG_STPT_SEARCH_BC;

/
