--------------------------------------------------------
--  DDL for Package PKG_DASHBOARD_PT_APP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_DASHBOARD_PT_APP" AS 
PROCEDURE DASHBOARD_CREATE_DATA_ADS_PT;
PROCEDURE DASHBOARD_CREATE_DATA_AHN_PT;
PROCEDURE DASHBOARD_CREATE_DATA_AKT_PT;
PROCEDURE DASHBOARD_CREATE_DATA_ALD_PT;
PROCEDURE DASHBOARD_CREATE_DATA_AHC_PT;
PROCEDURE DASHBOARD_CREATE_DATA_APS_PT;
END PKG_DASHBOARD_PT_APP;

/
