create or replace NONEDITIONABLE PACKAGE        "PKG_DVCQG_APP" AS 
PROCEDURE THANH_TOAN_UP
(
  V_ANPHI_ID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2
);
 PROCEDURE THANH_TOAN_UP_FROM_THADS
(
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2
);
PROCEDURE CHECK_THANH_TOAN_IN_ANPHI
(
   V_MAGIAIDOAN IN NUMBER,
   V_DONID IN NUMBER,
   V_DONXULY_ID IN NUMBER,
   V_ANPHI_ID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2,
   V_DS_IDS IN VARCHAR2,
   ITEMS_CURSOR OUT SYS_REFCURSOR
);
PROCEDURE THANH_TOAN_IN_ANPHI
(
   V_MAGIAIDOAN IN NUMBER,
   V_DONID IN NUMBER,
   V_DONXULY_ID IN NUMBER,
   V_ANPHI_ID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2,
   V_DS_IDS IN VARCHAR2
);
FUNCTION CREATE_MA_TB_RANDOM
(
  V_MA_THONGBAO OUT VARCHAR2
) 
RETURN  VARCHAR2;
PROCEDURE TT_REMOVE_TONGDAT
( 
  V_TONGDAT_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
);
PROCEDURE THANH_TOAN_DELETE_XLY
( 
  V_DONXULY_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
);
PROCEDURE THANH_TOAN_DELETE_ANPHI
( 
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
);
PROCEDURE THANH_TOAN_UP_TONGDAT
(
   V_TONGDAT_ID IN NUMBER,
   V_DUONGSUID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2
);
PROCEDURE THANH_TOAN_UP_TONGDAT_RE
(
   V_TONGDAT_ID IN VARCHAR2,
   V_DONID IN NUMBER,
   V_MALOAIVUVIEC IN VARCHAR2
);
END PKG_DVCQG_APP;