--------------------------------------------------------
--  DDL for Package PKG_GS_HOAGIAI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_GS_HOAGIAI" AS 

    LOAIAN_ADS CONSTANT NUMBER:=2;
    LOAIAN_AHN CONSTANT NUMBER:=3;
    LOAIAN_AKT CONSTANT NUMBER:=4;
    LOAIAN_ALD CONSTANT NUMBER:=5;
    LOAIAN_AHC CONSTANT NUMBER:=6;
  /* TODO enter package declarations (types, exceptions, methods etc) here */
    PROCEDURE GETLIST_THONGBAO (
        V_HGDON   IN NUMBER,
        V_LOAIAN  IN NUMBER,
        CURRETURN OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_GIAONHANDON (
        V_HGDON   IN NUMBER,
        V_LOAIAN  IN NUMBER,
        CURRETURN OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_PHANCONGTHAMPHAN (
        V_HGDON IN NUMBER,
        PAGE_INDEX IN INT,
        PAGE_SIZE  IN INT,
        CURRETURN  OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_GHINHANKETQUAHOAGIAI (
        V_VUVIECID IN NUMBER,
        V_LOAIANID IN NUMBER,
        PAGE_INDEX IN INT,
        PAGE_SIZE  IN INT,
        CURRETURN  OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_HOAGIAIQUYETDINH (
        V_VUVIECID IN NUMBER,
        V_LOAIANID IN NUMBER,
        PAGE_INDEX IN INT,
        PAGE_SIZE  IN INT,
        CURRETURN  OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_DUONGSU (
        V_VUVIECID IN NUMBER,
        V_LOAIANID IN NUMBER,
        CURRETURN  OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_DENGHIKIENNGHI (
        V_VUVIECID IN NUMBER,
        V_LOAIANID IN NUMBER,
        CURRETURN  OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_KETQUA_DENGHIKIENNGHI (
        V_VUVIECID IN NUMBER,
        V_LOAIANID IN NUMBER,
        CURRETURN  OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_VU_VIEC_KQDNKN (
        V_TOALOGIN  IN NUMBER,
        V_LOAIANID  IN NUMBER,
        V_MAVUVIEC  IN VARCHAR2,
        V_TENVUVIEC IN VARCHAR2,
        V_TUNGAY    IN VARCHAR2,
        V_DENNGAY   IN VARCHAR2,
        V_TINHTRANG IN NUMBER,
        PAGE_INDEX  IN NUMBER,
        PAGE_SIZE   IN NUMBER,
        CURRETURN   OUT SYS_REFCURSOR
    );

    FUNCTION GETLIST_DUONGSU_ITEM (
        V_VUVIECID IN NUMBER,
        V_LOAIANID IN NUMBER
    ) RETURN T_GS_DUONGSU;

    PROCEDURE GETLIST_THONGBAO_DUONGSU (
        VTHONGBAOID IN NUMBER,
        CURRETURN   OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_THONGBAO_KETQUA (
        V_HGDON   IN NUMBER,
        V_LOAIAN  IN NUMBER,
        CURRETURN OUT SYS_REFCURSOR
    );

    PROCEDURE GETLIST_DUONGSU_THONGBAO (
        V_VUVIECID   IN NUMBER,
        V_LOAIANID   IN NUMBER,
        V_THONGBAOID IN NUMBER,
        CURRETURN    OUT SYS_REFCURSOR
    );

END PKG_GS_HOAGIAI;

/
