--------------------------------------------------------
--  DDL for Package PKG_TUPHAP_ANPHI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_TUPHAP_ANPHI" AS
PROCEDURE ANPHI_FILE_UPD_XOA
( 
    V_LOAIAN in varchar2,
    V_ANPHI_ID  in number,
    V_ACTION varchar2, --- A Thêm mới, S Thay thế, X Xóa file    
    V_COUNT_TL OUT number
);
PROCEDURE ANPHI_FILE_UPD
( 
    V_LOAIAN in varchar2,
    V_ANPHI_ID  in number,
    V_FILE_NAME  in varchar2,
    V_FILE_DATA  blob,
    V_FILE_TYLE  varchar2,
    V_ACTION varchar2 ---A Thêm mới, S Thay thế, X Xóa file 
);
PROCEDURE GET_ANPHI_FILE
  (
     V_LOAI_AN IN VARCHAR2 DEFAULT NULL ,
     V_ANPHI_ID in number,
     V_FILE_NAME OUT VARCHAR2,
     ITEMS_CURSOR OUT SYS_REFCURSOR
  ) ;
PROCEDURE GET_THONGBAO_AP_FILE
  (
     V_LOAI_AN IN VARCHAR2 DEFAULT NULL ,
     V_FILEID in NUMBER,
     V_TENFILE OUT VARCHAR2,
     ITEMS_CURSOR OUT SYS_REFCURSOR
  );
FUNCTION TC_DANHSACH_ANPHI 
(
  V_TRANG_THAI IN VARCHAR2 DEFAULT NULL, 
  V_FILE_THA IN VARCHAR2 DEFAULT NULL, 
  V_GET_CHIL IN VARCHAR2 DEFAULT NULL, 
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL, 
  V_TT_TRUCTUYEN IN VARCHAR2 DEFAULT NULL, 
  V_DATE_FROM IN VARCHAR2 DEFAULT NULL,  
  V_DATE_TO IN VARCHAR2 DEFAULT NULL, 
  V_STATUS IN NVARCHAR2 DEFAULT NULL,
  V_USERNAME IN NVARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID IN NVARCHAR2 DEFAULT NULL,
  vTuKhoaBasic IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	int,
  PageSize	in	int
)RETURN SYS_REFCURSOR;

FUNCTION TC_DANHSACH_ANPHI_QLTA
(
  V_FILE_THA IN VARCHAR2 DEFAULT NULL, 
  V_GET_CHIL IN VARCHAR2 DEFAULT NULL, 
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL, 
  V_TT_TRUCTUYEN IN VARCHAR2 DEFAULT NULL, 
  V_DATE_FROM IN VARCHAR2 DEFAULT NULL,  
  V_DATE_TO IN VARCHAR2 DEFAULT NULL, 
  V_STATUS IN NVARCHAR2 DEFAULT NULL,
  V_USERNAME IN NVARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID IN NVARCHAR2 DEFAULT NULL,
  vTuKhoaBasic IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	int,
  PageSize	in	int
)RETURN SYS_REFCURSOR;

FUNCTION TC_DANHSACH_ANPHI_IN_DS 
(
  V_GET_CHIL IN VARCHAR2 DEFAULT NULL, 
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL, 
  V_TT_TRUCTUYEN IN VARCHAR2 DEFAULT NULL, 
  V_DATE_FROM IN VARCHAR2 DEFAULT NULL,  
  V_DATE_TO IN VARCHAR2 DEFAULT NULL, 
  V_STATUS IN NVARCHAR2 DEFAULT NULL,
  V_USERNAME IN NVARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID IN NVARCHAR2 DEFAULT NULL,
  vTuKhoaBasic IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	int,
  PageSize	in	int
)
RETURN SYS_REFCURSOR;

FUNCTION LOAD_EDIT
(
    V_MA_THONGBAO IN VARCHAR2 DEFAULT NULL,
    V_MALOAIVUVIEC IN VARCHAR2 DEFAULT NULL,
    V_USERNAME IN VARCHAR2 DEFAULT NULL,
    V_DONID  IN NUMBER,
    V_DS_ID  IN VARCHAR2 DEFAULT NULL,
    V_DS_IDS  IN VARCHAR2 DEFAULT NULL
)RETURN SYS_REFCURSOR;
FUNCTION GET_SOLUONG
(
  V_USERNAME IN VARCHAR2 DEFAULT NULL,
  V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
)RETURN SYS_REFCURSOR;
PROCEDURE CREATE_SOBIENLAI_APP (
        V_DONVITHA_ID  IN NUMBER,
        CURRETURN OUT SYS_REFCURSOR
    );
END PKG_TUPHAP_ANPHI;

/
