--------------------------------------------------------
--  DDL for Package PKG_GSTP_SOTHULY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_GSTP_SOTHULY" AS 

	/*1 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC DÂN SỰ PHÚC THẨM*/
--	PROCEDURE FILL_DANSU_PHUCTHAM
--	(
--		v_ARRAY IN OUT T_DANSU_PHUCTHAM
--	);

	/*2 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ ÁN HÀNH CHÍNH SƠ THẨM*/


	/*3 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ ÁN HÀNH CHÍNH PHÚC THẨM*/
--	PROCEDURE FILL_HANHCHINH_PHUCTHAM
--	(
--		v_ARRAY IN OUT T_HANHCHINH_PHUCTHAM
--	);

	/*4 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ ÁN HÀNH CHÍNH GIÁM ĐỐC THẨM, TÁI THẨM*/
	PROCEDURE FILL_HANHCHINH_GDTTT
	(
		v_ARRAY IN OUT T_HANHCHINH_GDTTT
	);

	/*5 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC LAO ĐỘNG GIÁM ĐỐC THẨM, TÁI THẨM*/
	PROCEDURE FILL_LAODONG_GDTTT
	(
		v_ARRAY IN OUT T_LAODONG_GDTTT
	);

	/*6 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC LAO ĐỘNG PHÚC THẨM*/
--	PROCEDURE FILL_LAODONG_PHUCTHAM
--	(
--		v_ARRAY IN OUT T_LAODONG_PHUCTHAM
--	);

	/*7 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC LAO ĐỘNG SƠ THẨM*/


	/*8 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC KINH DOANH THƯƠNG MẠI GIÁM ĐỐC THẨM, TÁI THẨM*/
	PROCEDURE FILL_KINHTE_GDTTT
	(
		v_ARRAY IN OUT T_KINHTE_GDTTT
	);

	/*10 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC KINH DOANH THƯƠNG MẠI SƠ THẨM*/


	/*11 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC HÔN NHÂN VÀ GIA ĐÌNH GIÁM ĐỐC THẨM, TÁI THẨM*/
	PROCEDURE FILL_HONNHAN_GDTTT
	(
		v_ARRAY IN OUT T_HONNHAN_GDTTT
	);

	/*13 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC HÔN NHÂN VÀ GIA ĐÌNH SƠ THẨM*/


	/*14 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC DÂN SỰ GIÁM ĐỐC THẨM, TÁI THẨM*/
	PROCEDURE FILL_DANSU_GDTTT
	(
		v_ARRAY IN OUT T_DANSU_GDTTT
	);

/*15 - SỔ THỤ LÝ VÀ KẾT QỦA GIẢI QUYẾT CÁC VỤ VIỆC DÂN SỰ SƠ THẨM*/

	/*16 - SỔ THỤ LÝ VÀ KẾT QUẢ GIẢI QUYẾT CÁC VỤ ÁN HÌNH SỰ SƠ THẨM*/
--	PROCEDURE FILL_HINHSU_SOTHAM
--	(
--		v_ARRAY IN OUT T_HINHSU_SOTHAM
--	);

	/*17 - SỔ THỤ LÝ VÀ KẾT QUẢ GIẢI QUYẾT CÁC VỤ ÁN HÌNH SỰ PHÚC THẨM*/
--	PROCEDURE FILL_HINHSU_PHUCTHAM
--	(
--		v_ARRAY IN OUT T_HINHSU_PHUCTHAM
--	);

	/*18 - SỔ THỤ LÝ VÀ KẾT QUẢ GIẢI QUYẾT CÁC VỤ ÁN HÌNH SỰ GIÁM ĐỐC THẨM, TÁI THẨM*/
	PROCEDURE FILL_HINHSU_GDTTT
	(
		v_ARRAY IN OUT T_HINHSU_GDTTT
	);

	/*19 - SỔ THEO DÕI SỐ BẢN ÁN, QUYẾT ĐỊNH VỀ HÌNH SỰ*/
	PROCEDURE FILL_HINHSU_BAQD
	(
		v_ARRAY IN OUT T_HINHSU_BAQD
	);

	/*20 - SỔ THEO DÕI NGƯỜI BỊ KẾT ÁN PHẠT TÙ ĐANG TẠI NGOẠI*/
	PROCEDURE FILL_HINHSU_TAINGOAI
	(
		v_ARRAY IN OUT T_HINHSU_TAINGOAI
	);

	/*21 - SỔ THỤ LÝ VÀ THEO DÕI VIỆC RA QUYẾT ĐỊNH THI HÀNH ÁN HÌNH SỰ*/
	PROCEDURE FILL_HINHSU_QDTHA
	(
		v_ARRAY IN OUT T_HINHSU_QDTHA
	);

	/*22 - SỔ THEO DÕI MIỄN, GIẢM THỜI HẠN CHẤP HÀNH HÌNH PHẠT TÙ VÀ MIỄN, GIẢM ÁN PHÍ TIỀN PHẠT*/
	PROCEDURE FILL_HINHSU_MIENGIAM
	(
		v_ARRAY IN OUT T_HINHSU_MIENGIAM
	);

	/*23 - SỔ THỤ LÝ VÀ KẾT QUẢ GIẢI QUYẾT CÁC VỤ ÁN HÌNH SỰ SƠ THẨM*/
--	PROCEDURE FILL_HINHSU_SOTHAM_2
--	(
--		v_ARRAY IN OUT T_HINHSU_SOTHAM_2
--	);

	/*24 - SỔ THỤ LÝ VÀ KẾT QUẢ GIẢI QUYẾT YÊU CẦU TUYÊN BỐ PHÁ SẢN*/


	/*============================================================================================*/


--	PROCEDURE SO_DANSU_PHUCTHAM
--	(
--		 in_TOAANID IN NUMBER,
--		 in_TOAANCAPCON IN NVARCHAR2,
--		 in_NGAYBATDAU IN NVARCHAR2,
--		 in_NGAYKETTHUC IN NVARCHAR2,
--		 curReturn OUT SYS_REFCURSOR
--	);

	PROCEDURE SO_DANSU_GDTTT
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);


--	PROCEDURE SO_HANHCHINH_PHUCTHAM
--	(
--		 in_TOAANID IN NUMBER,
--		 in_TOAANCAPCON IN NVARCHAR2,
--		 in_NGAYBATDAU IN NVARCHAR2,
--		 in_NGAYKETTHUC IN NVARCHAR2,
--		 curReturn OUT SYS_REFCURSOR
--	);

	PROCEDURE SO_HANHCHINH_GDTTT
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);



--	PROCEDURE SO_LAODONG_PHUCTHAM
--	(
--		 in_TOAANID IN NUMBER,
--		 in_TOAANCAPCON IN NVARCHAR2,
--		 in_NGAYBATDAU IN NVARCHAR2,
--		 in_NGAYKETTHUC IN NVARCHAR2,
--		 curReturn OUT SYS_REFCURSOR
--	);

	PROCEDURE SO_LAODONG_GDTTT
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);



	PROCEDURE SO_KINHTE_GDTTT
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);



	PROCEDURE SO_HONNHAN_GDTTT
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);

--	PROCEDURE SO_HINHSU_SOTHAM
--	(
--		 in_TOAANID IN NUMBER,
--		 in_TOAANCAPCON IN NVARCHAR2,
--		 in_NGAYBATDAU IN NVARCHAR2,
--		 in_NGAYKETTHUC IN NVARCHAR2,
--		 curReturn OUT SYS_REFCURSOR
--	);
--
--	PROCEDURE SO_HINHSU_SOTHAM_2
--	(
--		 in_TOAANID IN NUMBER,
--		 in_TOAANCAPCON IN NVARCHAR2,
--		 in_NGAYBATDAU IN NVARCHAR2,
--		 in_NGAYKETTHUC IN NVARCHAR2,
--		 curReturn OUT SYS_REFCURSOR
--	);

--	PROCEDURE SO_HINHSU_PHUCTHAM
--	(
--		 in_TOAANID IN NUMBER,
--		 in_TOAANCAPCON IN NVARCHAR2,
--		 in_NGAYBATDAU IN NVARCHAR2,
--		 in_NGAYKETTHUC IN NVARCHAR2,
--		 curReturn OUT SYS_REFCURSOR
--	);

	PROCEDURE SO_HINHSU_GDTTT
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);

	PROCEDURE SO_HINHSU_BAQD
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);

	PROCEDURE SO_HINHSU_TAINGOAI
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);

	PROCEDURE SO_HINHSU_QDTHA
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);

	PROCEDURE SO_HINHSU_MIENGIAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);



END PKG_GSTP_SOTHULY;

/
