--------------------------------------------------------
--  DDL for Package PKG_STPT_DELETE_SOTHULY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_STPT_DELETE_SOTHULY" AS 

FUNCTION LICHSU_XOA_SOTHULY_ST
(
  in_MAGIAIDOAN IN NUMBER,
  in_DONID IN NUMBER,
  in_THULYID IN NUMBER,
  in_LOAIANID IN NUMBER,
  in_NGUOIXOAID IN VARCHAR2,
  in_TAIKHOANXOA IN VARCHAR2,
  in_LYDO IN VARCHAR2
)RETURN NUMBER;

FUNCTION LICHSU_XOA_SOTHULY_PT
(
  in_MAGIAIDOAN IN NUMBER,
  in_DONID IN NUMBER,
  in_THULYID IN NUMBER,
  in_LOAIANID IN NUMBER,
  in_NGUOIXOAID IN VARCHAR2,
  in_TAIKHOANXOA IN VARCHAR2,
  in_LYDO IN VARCHAR2
)RETURN NUMBER;

END PKG_STPT_DELETE_SOTHULY;

/
