--------------------------------------------------------
--  DDL for Package PKG_BAN_GIAO_AN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_BAN_GIAO_AN" AS 

  /* TODO enter package declarations (types, exceptions, methods etc) here */ 

-- [ADS] LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE ADS_VUAN_BANGIAO_MAPPING_GET_AN_BAN_GIAO (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [ADS] LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE ADS_VUAN_BANGIAO_MAPPING_GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [ADS] NHẬN BÀN GIAO
PROCEDURE ADS_VUAN_BANGIAO_MAPPING_NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);
-- [ADS] KIỂM TRA THAY ĐỔI
PROCEDURE ADS_VUAN_BANGIAO_MAPPING_KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);
-- [ADS] TRẢ LẠI
PROCEDURE ADS_VUAN_BANGIAO_MAPPING_TRALAI (
    p_ID IN NUMBER
);

-- [AHS] LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE AHS_VUAN_BANGIAO_MAPPING_GET_AN_BAN_GIAO (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [AHS] LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE AHS_VUAN_BANGIAO_MAPPING_GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [AHS] NHẬN BÀN GIAO
PROCEDURE AHS_VUAN_BANGIAO_MAPPING_NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);
-- [AHS] KIỂM TRA THAY ĐỔI
PROCEDURE AHS_VUAN_BANGIAO_MAPPING_KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);
-- [AHS] TRẢ LẠI
PROCEDURE AHS_VUAN_BANGIAO_MAPPING_TRALAI (
    p_ID IN NUMBER
);


 -- [AHN] LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE AHN_VUAN_BANGIAO_MAPPING_GET_AN_BAN_GIAO (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [AHN] LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE AHN_VUAN_BANGIAO_MAPPING_GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [AHN] NHẬN BÀN GIAO
PROCEDURE AHN_VUAN_BANGIAO_MAPPING_NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);
-- [AHN] KIỂM TRA THAY ĐỔI
PROCEDURE AHN_VUAN_BANGIAO_MAPPING_KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);
-- [AHN] TRẢ LẠI
PROCEDURE AHN_VUAN_BANGIAO_MAPPING_TRALAI (
    p_ID IN NUMBER
);

 -- [KDTM] LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE KDTM_VUAN_BANGIAO_MAPPING_GET_AN_BAN_GIAO (
        p_LOAIANID IN varchar2,
        p_TOAANID IN NUMBER,
        p_MAVUVIEC IN varchar2,
        p_THULYTUNGAY IN date,
        p_THULYDENNGAY IN date,
        p_TINHTRANGTHULY IN nvarchar2,
        p_THAMPHANGIAIQUYET IN nvarchar2,
        p_TENVUAN IN nvarchar2,    
        p_TRANGTHAIGIAIQUYET IN nvarchar2,    
        p_CAPXETXU IN nvarchar2,  
        p_TRANGTHAI IN NVARCHAR2,
        p_CURSOR OUT SYS_REFCURSOR
    );
-- [KDTM] LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE KDTM_VUAN_BANGIAO_MAPPING_GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [KDTM] NHẬN BÀN GIAO
PROCEDURE AKDTM_VUAN_BANGIAO_MAPPING_NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);
-- [KDTM] KIỂM TRA THAY ĐỔI
PROCEDURE KDTM_VUAN_BANGIAO_MAPPING_KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);
-- [KDTM] TRẢ LẠI
PROCEDURE KDTM_VUAN_BANGIAO_MAPPING_TRALAI (
    p_ID IN NUMBER
);

PROCEDURE VUAN_BANGIAO_MAPPING_ADD (
    p_TOAANGIAOID            IN NUMBER,
    p_TOAANGIAOTEN           IN VARCHAR2,
    p_TOAANNHANID            IN NUMBER,
    p_TOAANNHANTEN           IN VARCHAR2,
    p_VUVIECID               IN VARCHAR2,
    p_VUVIECLOAI             IN VARCHAR2,
    p_VUVIECMA               IN VARCHAR2,
    p_VUVIECTEN              IN VARCHAR2,
    p_NGUOIGIAOID            IN VARCHAR2,
    p_NGUOIGIAOTEN           IN VARCHAR2,
    p_NGUOINHANID            IN VARCHAR2,
    p_NGUOINHANTEN           IN VARCHAR2,
    p_LYDOMA                 IN VARCHAR2,
    p_NGAYGIAO               IN DATE,
    p_ISQUYETDINHCHUYEN      IN NUMBER,
    p_SOQUYETDINH            IN VARCHAR2,
    p_NGAYQUYETDINH          IN DATE,
    p_NGUOIKY                IN VARCHAR2,
    p_TRANGTHAI              IN VARCHAR2,
    p_GHICHU                 IN VARCHAR2,
    p_TRANGTHAIGIAIQUYET     IN VARCHAR2
);

PROCEDURE VUAN_BANGIAO_MAPPING_EDIT (
    p_ID                      IN NUMBER,
    p_TOAANGIAOID            IN NUMBER,
    p_TOAANGIAOTEN           IN VARCHAR2,
    p_TOAANNHANID            IN NUMBER,
    p_TOAANNHANTEN           IN VARCHAR2,
    p_VUVIECID               IN VARCHAR2,
    p_VUVIECMA               IN VARCHAR2,
    p_VUVIECTEN              IN VARCHAR2,
    p_NGUOIGIAOID            IN VARCHAR2,
    p_NGUOIGIAOTEN           IN VARCHAR2,
    p_NGUOINHANID            IN VARCHAR2,
    p_NGUOINHANTEN           IN VARCHAR2,
    p_LYDOMA                 IN VARCHAR2,
    p_NGAYGIAO               IN DATE,
    p_ISQUYETDINHCHUYEN      IN NUMBER,
    p_SOQUYETDINH            IN VARCHAR2,
    p_NGAYQUYETDINH          IN DATE,
    p_NGUOIKY                IN VARCHAR2,
    p_TRANGTHAI              IN VARCHAR2,
    p_GHICHU                 IN VARCHAR2
);

PROCEDURE VUAN_BANGIAO_MAPPING_DELETE (
    p_ID               IN NUMBER
);

PROCEDURE VUAN_BANGIAO_MAPPING_CHANGE_STATUS (
    p_ID IN NUMBER,
    p_TRANGTHAI IN VARCHAR2
);

-- [AHC] LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE AHC_VUAN_BANGIAO_MAPPING_GET_AN_BAN_GIAO (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [AHC] LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE AHC_VUAN_BANGIAO_MAPPING_GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [AHC] NHẬN BÀN GIAO
PROCEDURE AHC_VUAN_BANGIAO_MAPPING_NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);
-- [AHC] KIỂM TRA THAY ĐỔI
PROCEDURE AHC_VUAN_BANGIAO_MAPPING_KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);
-- [AHC] TRẢ LẠI
PROCEDURE AHC_VUAN_BANGIAO_MAPPING_TRALAI (
    p_ID IN NUMBER
);

-- [ALD] LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE ALD_VUAN_BANGIAO_MAPPING_GET_AN_BAN_GIAO (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [ALD] LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE ALD_VUAN_BANGIAO_MAPPING_GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);
-- [ALD] NHẬN BÀN GIAO
PROCEDURE ALD_VUAN_BANGIAO_MAPPING_NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);
-- [ALD] KIỂM TRA THAY ĐỔI
PROCEDURE ALD_VUAN_BANGIAO_MAPPING_KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);
-- [ALD] TRẢ LẠI
PROCEDURE ALD_VUAN_BANGIAO_MAPPING_TRALAI (
    p_ID IN NUMBER
);


END PKG_BAN_GIAO_AN;

/
