--------------------------------------------------------
--  DDL for Package PKG_GSTP_SOTHULY_SOTHAM
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_GSTP_SOTHULY_SOTHAM" AS
PROCEDURE SO_DANSU_SOTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);
    PROCEDURE FILL_DANSU_SOTHAM
	(
		v_ARRAY IN OUT T_DANSU_SOTHAM
	);
   PROCEDURE SO_HONNHAN_SOTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	) ; 
    	PROCEDURE FILL_HONNHAN_SOTHAM
	(
		v_ARRAY IN OUT T_HONNHAN_SOTHAM
	);
    PROCEDURE SO_KINHTE_SOTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);  
    PROCEDURE FILL_KINHTE_SOTHAM
	(
		v_ARRAY IN OUT T_KINHTE_SOTHAM
	);
    PROCEDURE SO_LAODONG_SOTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);
    PROCEDURE FILL_LAODONG_SOTHAM
	(
		v_ARRAY IN OUT T_LAODONG_SOTHAM
	);
        PROCEDURE SO_HANHCHINH_SOTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);
    PROCEDURE FILL_HANHCHINH_SOTHAM
	(
		v_ARRAY IN OUT T_HANHCHINH_SOTHAM
	) ;
    PROCEDURE SO_PHASAN_SOTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);
    	/*24 - SỔ THỤ LÝ VÀ KẾT QUẢ GIẢI QUYẾT YÊU CẦU TUYÊN BỐ PHÁ SẢN*/
	PROCEDURE FILL_PHASAN_SOTHAM
	(
		v_ARRAY IN OUT T_PHASAN_SOTHAM
	);
END PKG_GSTP_SOTHULY_SOTHAM;

/
