CREATE OR REPLACE PACKAGE GSCM.PKG_DVCQG_VNEID_HN
AS
-- Package header
PROCEDURE THONGBAO_TONGDAT_VNEID_THULY_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE TONGDAT_VNEID_THONGTINDON_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE TONGDAT_VNEID_GIAIQUYETDON_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_ST_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE THONGBAO_TONGDAT_VNEID_QDVUVIEC_ST_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE TONGDAT_VNEID_THULY_PT_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_QDVUVIEC_PT_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_PT_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_QUYETDINH_ST_HN
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
END PKG_DVCQG_VNEID_HN;