--------------------------------------------------------
--  DDL for Package PKG_TUPHAP_QLA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_TUPHAP_QLA" AS 
PROCEDURE CHECK_ENABLE
(
  V_ID IN NUMBER,
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL
);
PROCEDURE CHECK_ENABLE_THULY
(
  V_DONID IN NUMBER,
  V_LOAI_AN IN VARCHAR2 DEFAULT NULL
);
PROCEDURE GET_ENABLE_ANPHI
  (
     V_ANPHI_ID IN NUMBER,   
     V_LOAI_AN IN VARCHAR2 DEFAULT NULL ,  
     ITEMS_CURSOR OUT SYS_REFCURSOR
  );
END PKG_TUPHAP_QLA;

/
