CREATE OR REPLACE PACKAGE GSCM.PKG_DVCQG_VNEID_LD
AS
-- Package header
PROCEDURE THONGBAO_TONGDAT_VNEID_THULY_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    curReturn OUT SYS_REFCURSOR
) ;
PROCEDURE THONGBAO_TONGDAT_VNEID_QDVUVIEC_ST_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE TONGDAT_VNEID_THULY_PT_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_QDVUVIEC_PT_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_PT_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE TONGDAT_VNEID_THONGTINDON_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE TONGDAT_VNEID_GIAIQUYETDON_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_ST_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
) ;

PROCEDURE THONGBAO_TONGDAT_VNEID_QUYETDINH_ST_LD
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
END PKG_DVCQG_VNEID_LD;