--------------------------------------------------------
--  DDL for Package PKG_TUPHAP_ANPHI_JOB
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_TUPHAP_ANPHI_JOB" AS 
PROCEDURE GET_SOLUONG_JOB
;
 PROCEDURE GET_SOLUONG_JOB_APP
    (
     V_USERNAME IN VARCHAR2 DEFAULT NULL,
     V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
    );
FUNCTION GET_SOLUONG_CREATE_DATA
(
V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR;

END PKG_TUPHAP_ANPHI_JOB;

/
