create or replace PACKAGE        "PKG_TUPHAP_ANPHI_DVCQG" AS 
PROCEDURE GET_THANH_TOAN_BY_MA
  (

     V_MA_THONGBAO IN VARCHAR2 DEFAULT NULL ,    
     ITEMS_CURSOR OUT SYS_REFCURSOR
  );
PROCEDURE GET_FILE_ATTACH
  (

     V_MA_THONGBAO IN VARCHAR2 DEFAULT NULL ,
     V_FILE_NAME OUT VARCHAR2,
     ITEMS_CURSOR OUT SYS_REFCURSOR
  );
PROCEDURE  INSERT_DUONGSU_AHN_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_AHN
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_AHN
( 
  V_ANPHI_ID IN NUMBER
);
PROCEDURE  INSERT_DUONGSU_AHC_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_AHC
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_AHC
( 
  V_ANPHI_ID IN NUMBER
);
-- VNPT Lê Bá Thọ khai báo hàm thêm dương sự cho ADS
PROCEDURE  INSERT_DUONGSU_ADS_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_ADS
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_ADS
( 
  V_ANPHI_ID IN NUMBER
);
-------------------------
-- VNPT Lê Bá Thọ khai báo hàm thêm dương sự cho ALD
PROCEDURE  INSERT_DUONGSU_ALD_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_ALD
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_ALD
( 
  V_ANPHI_ID IN NUMBER
);
-------------------------
-- VNPT Lê Bá Thọ khai báo hàm thêm dương sự cho AKT
PROCEDURE  INSERT_DUONGSU_AKT_ALL;
PROCEDURE  INSERT_DATA_DUONGSU_AKT
(
  V_ANPHI_ID NUMBER
);
PROCEDURE DELETE_DATA_DUONGSU_AKT
( 
  V_ANPHI_ID IN NUMBER
);
-------------------------
PROCEDURE CHECK_DELETE_ANPHI
( 
  V_ANPHI_ID IN NUMBER,
  V_MALOAIVUVIEC IN VARCHAR2,
  V_VALUE OUT NUMBER
);
PROCEDURE DVCQG_FILE_BIENLAI_UP
( 
    V_DVCQG_TT_ID in number,
    V_FILE_ATTACH   IN   BLOB,
    V_ERROR_CODE OUT VARCHAR2,
    V_MESSAGE OUT VARCHAR2
);
PROCEDURE GET_URL_DVC_THANHTOAN
  (
     V_DVCQG_TT_ID IN VARCHAR2,    
     ITEMS_CURSOR OUT SYS_REFCURSOR
  );    
END PKG_TUPHAP_ANPHI_DVCQG;