--------------------------------------------------------
--  DDL for Package PKG_STPT_KHANGCAOQUAHAN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_STPT_KHANGCAOQUAHAN" AS

PROCEDURE SOTHULY_GETMAXTT
(   
    VTOAANID        IN NUMBER,
    VLOAIKHANGCAO   IN NUMBER,
    VNGAYTHULY      VARCHAR2,
	CURRETURN    OUT       SYS_REFCURSOR
);

PROCEDURE SOTHULY_GETMAXTT_CHECK
( 
    VTOAANID IN NUMBER,
    VLOAIKHANGCAO   IN NUMBER,
    VSOTHULY        IN VARCHAR2,
    VNGAYTHULY      IN VARCHAR2,
	CURRETURN       OUT SYS_REFCURSOR
);

PROCEDURE SOQUYETDINH_GETMAXTT
(   
    VTOAANID        IN NUMBER,
    VNGAYQUYETDINH      VARCHAR2,
	CURRETURN    OUT       SYS_REFCURSOR
);

PROCEDURE SOQUYETDINH_GETMAXTT_CHECK
( 
    VTOAANID IN NUMBER,
    VSOQUYETDINH        IN VARCHAR2,
    VNGAYQUYETDINH      IN VARCHAR2,
	CURRETURN       OUT SYS_REFCURSOR
);

PROCEDURE        "KHANGCAOQUAHAN_HDXX_GETBYID" 
( 
    VDONID          IN NUMBER,
    VTHULYID        IN NUMBER,
    VLOAIAN         IN NUMBER,
    VID_HDXX        IN NUMBER,
	CURRETURN       OUT SYS_REFCURSOR
);

PROCEDURE        "KHANGCAOQUAHAN_QUYETDINH_GETLAST" 
( 
    VDONID          IN NUMBER,
    VTHULYID        IN NUMBER,
    VLOAIAN         IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE        "KHANGCAOQUAHAN_HDXX_GETLIST" 
( 
    VDONID IN NUMBER,
    VTHULYID IN NUMBER,
    VLOAIAN IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE        "KHANGCAOQUAHAN_THULY_GETLAST" 
( 
    VDONID IN NUMBER,
    VLOAIAN IN NUMBER,
    VKHANGCAOID     IN NUMBER,
	CURRETURN OUT SYS_REFCURSOR
);

END PKG_STPT_KHANGCAOQUAHAN;

/
