--------------------------------------------------------
--  DDL for Package PKG_GSTP_SOTHULY_PHUCTHAM
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_GSTP_SOTHULY_PHUCTHAM" AS 


PROCEDURE SO_DANSU_PHUCTHAM
(
     in_TOAANID IN NUMBER,
     in_TOAANCAPCON IN NVARCHAR2,
     in_NGAYBATDAU IN NVARCHAR2,
     in_NGAYKETTHUC IN NVARCHAR2,
     curReturn OUT SYS_REFCURSOR
);
PROCEDURE FILL_DANSU_PHUCTHAM
(
    v_ARRAY IN OUT T_DANSU_PHUCTHAM
);

PROCEDURE SO_HONNHAN_PHUCTHAM
(
     in_TOAANID IN NUMBER,
     in_TOAANCAPCON IN NVARCHAR2,
     in_NGAYBATDAU IN NVARCHAR2,
     in_NGAYKETTHUC IN NVARCHAR2,
     curReturn OUT SYS_REFCURSOR
);
PROCEDURE FILL_HONNHAN_PHUCTHAM
(
    v_ARRAY IN OUT T_HONNHAN_PHUCTHAM
);  

PROCEDURE SO_KINHTE_PHUCTHAM
	(
		 in_TOAANID IN NUMBER,
		 in_TOAANCAPCON IN NVARCHAR2,
		 in_NGAYBATDAU IN NVARCHAR2,
		 in_NGAYKETTHUC IN NVARCHAR2,
		 curReturn OUT SYS_REFCURSOR
	);
PROCEDURE FILL_KINHTE_PHUCTHAM
(
    v_ARRAY IN OUT T_KINHTE_PHUCTHAM
);

PROCEDURE SO_HANHCHINH_PHUCTHAM
(
     in_TOAANID IN NUMBER,
     in_TOAANCAPCON IN NVARCHAR2,
     in_NGAYBATDAU IN NVARCHAR2,
     in_NGAYKETTHUC IN NVARCHAR2,
     curReturn OUT SYS_REFCURSOR
);
PROCEDURE FILL_HANHCHINH_PHUCTHAM
(
    v_ARRAY IN OUT T_HANHCHINH_PHUCTHAM
);

PROCEDURE SO_LAODONG_PHUCTHAM
(
     in_TOAANID IN NUMBER,
     in_TOAANCAPCON IN NVARCHAR2,
     in_NGAYBATDAU IN NVARCHAR2,
     in_NGAYKETTHUC IN NVARCHAR2,
     curReturn OUT SYS_REFCURSOR
);
PROCEDURE FILL_LAODONG_PHUCTHAM
(
    v_ARRAY IN OUT T_LAODONG_PHUCTHAM
);

END PKG_GSTP_SOTHULY_PHUCTHAM;

/
