CREATE OR REPLACE PACKAGE GSCM.PKG_BAN_GIAO_AN_BPXLHC 
  AS

-- LẤY DANH SÁCH CÓ THỂ BÀN GIAO
PROCEDURE GET_AN_BAN_GIAO (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);

-- LẤY DANH SÁCH CHỜ DUYỆT
PROCEDURE GETS_CHONHAN (
    p_LOAIANID IN varchar2,
    p_TOAANID IN NUMBER,
    p_MAVUVIEC IN varchar2,
    p_THULYTUNGAY IN date,
    p_THULYDENNGAY IN date,
    p_TINHTRANGTHULY IN nvarchar2,
    p_THAMPHANGIAIQUYET IN nvarchar2,
    p_TENVUAN IN nvarchar2,    
    p_TRANGTHAIGIAIQUYET IN nvarchar2,    
    p_CAPXETXU IN nvarchar2,  
    p_TRANGTHAI IN NVARCHAR2,
    p_CURSOR OUT SYS_REFCURSOR
);

-- NHẬN BÀN GIAO
PROCEDURE NHAN (
    p_ID IN NUMBER,
    p_VUVIECID IN NUMBER,
    p_TOAANNHANID IN NUMBER,
    p_NGAYNHAN IN DATE
);

-- KIỂM TRA THAY ĐỔI
PROCEDURE KTTHAYDOI (
        p_ID IN NUMBER,
        p_result OUT NUMBER,
        p_message OUT VARCHAR2
);

-- TRẢ LẠI
PROCEDURE TRALAI (
    p_ID IN NUMBER
);

END PKG_BAN_GIAO_AN_BPXLHC;