--------------------------------------------------------
--  DDL for Package PKG_COVID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE "GSCM"."PKG_COVID" AS
FUNCTION  QT_NGUOIDUNG_SEARCH
( 
  V_DONVIID IN VARCHAR2,
  V_PHONGBANID IN	VARCHAR2,
  V_USERNAME IN VARCHAR2,
  V_HOTEN IN VARCHAR2 
)
RETURN SYS_REFCURSOR;
PROCEDURE DM_CANBO_SEARCH 
(
  vDV_TRUCTHUOC in varchar2,
  vPhongbanID in varchar2,
  vChucDanhID in varchar2,
  vChucVuID in varchar2,
  v_TrangThaiCongTac in varchar2,
  v_KeySearch in varchar2,
  CurrPageIndex in number,
  PageSize in number,
  CurReturn OUT sys_refcursor
);
PROCEDURE  DM_DATAITEM_GETBYGROUPNAME
( vGroupName in nvarchar2,
	curReturn    OUT       sys_refcursor
);
FUNCTION THONGKE_F_HOTEN
(
  V_CANBOID IN NVARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR;
FUNCTION THONGKE_F
(
  V_CANBOID IN NVARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR;
FUNCTION COVID_DANGKY_DS 
(
  V_CANBOID IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	NUMBER,
  PageSize	in	NUMBER
)
RETURN SYS_REFCURSOR;
PROCEDURE GET_NHOMQUYEN_ID
(    
  V_ID	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_ALL_NHOMQUYEN
(    
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_BY_USERNAME
(    
  V_USERNAME	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_USERBYID
(    
  V_USERID	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_DONVI_FULL
(    
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_PHONGBAN
(    
 V_TRUCTHUOC_ID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_DV_TRUCTHUOC
(    
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_CANBO_MA
(    
  V_MACANBO	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_CANBO_ID
(    
  V_ID	IN	NUMBER,
  CurReturn OUT sys_refcursor 
);
PROCEDURE GET_CANBO_DV_PB
(    
  V_DV_TRUCTHUOC	IN	VARCHAR2,
  V_PHONGBANID IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
);
PROCEDURE DELETE_CANBO_ID
(    
  V_ID	IN	NUMBER,
  V_THONGBAO OUT VARCHAR2
);
PROCEDURE DELETE_NGUOIDUNG_ID
(    
  V_ID	IN	NUMBER,
  V_THONGBAO OUT VARCHAR2
);
PROCEDURE USERS_CHANGE_PASSWORD
(    
  V_USERNAME	IN	VARCHAR2,
  V_PASSWORD IN	VARCHAR2
);
PROCEDURE USERS_CHANGE_PASSWORD_BYID
(    
  V_ID	IN	VARCHAR2,
  V_USERNAME	IN	VARCHAR2,
  V_PASSWORD IN	VARCHAR2
);
PROCEDURE UPDATE_USER_INFOR
(    
  V_CANBO_ID	IN	VARCHAR2,
  V_SODIENTHOAI IN	VARCHAR2,
  V_EMAIL  IN	VARCHAR2,
  V_DONVI_ID      IN	VARCHAR2,
  V_DIACHI      IN	VARCHAR2
);
PROCEDURE COVID_NGUOIDUNG_INS_UP
(
    V_ID	IN	NUMBER,
    V_USERNAME	IN	VARCHAR2,
    V_PASSWORD	IN	VARCHAR2,
    V_HOTEN	IN	VARCHAR2,
    V_CANBOID	IN	NUMBER,
    V_HIEULUC	IN	NUMBER,
    V_DIENTHOAI	IN	VARCHAR2,
    V_EMAIL	IN	VARCHAR2,
    V_NGUOITAO	IN	VARCHAR2,
    V_NGAYTAO	IN	DATE,
    V_NHOM_ND_ID	IN	NUMBER,
    V_DV_TRUCTHUOC	IN	NUMBER,
    V_PHONGBANID	IN	NUMBER,
    V_THONGBAO OUT VARCHAR2
);
PROCEDURE COVID_DM_CANBO_INS_UP
    (
        v_ID	in	NUMBER,
        v_TOAANID	in	NUMBER,
        v_MACANBO	in	VARCHAR2,
        v_HOTEN	in	VARCHAR2,
        v_SOCMND	in	VARCHAR2,
        v_HIEULUC	in	NUMBER,
        v_CHUCDANHID	in	NUMBER,
        v_CHUCVUID	in	NUMBER,
        v_DIACHI	in	VARCHAR2,
        v_NGAYNHANCONGTAC	in	DATE,
        v_NGAYSINH	in	DATE,
        v_SODIENTHOAI	in	VARCHAR2,
        v_NGAYTAO	in	DATE,
        v_NGUOITAO	in	VARCHAR2,
        v_NGAYBONHIEM	in	DATE,
        v_NGAYKETTHUC	in	DATE,
        v_GIOITINH	in	NUMBER,
        v_PHONGBANID	in	NUMBER,
        v_DV_TRUCTHUOC	in	NUMBER
    );
PROCEDURE COVID_DANGKY_INS_UP
 (
    V_ID	        IN	NUMBER,
    V_CANBOID	    IN	NUMBER,
    V_TOAANID	    IN	NUMBER,
    V_DV_TRUCTHUOC	IN	NUMBER,
    V_PHONGBANID	IN	NUMBER,
    V_SOT	        IN	NUMBER,
    V_HO	        IN	NUMBER,
    V_KHO_THO	    IN	NUMBER,
    V_DAU_HONG	    IN	NUMBER,
    V_NON_BUON_NON	IN	NUMBER,
    V_TIEU_CHAY	    IN	NUMBER,
    V_XUAT_HUYET_ND	IN	NUMBER,
    V_NOIBAN_ND	    IN	NUMBER,
    V_TIEPXUCGAN_BN	IN	NUMBER,
    V_XACDINH_F	    IN	VARCHAR2,
    V_TT_CACHLY     IN VARCHAR2,
    V_CACHLY_TUNGAY IN DATE,
    V_CACHLY_DENGAY IN DATE,
    V_LICHSU	    IN	VARCHAR2,
    V_GHICHU	    IN	VARCHAR2,
    V_NGUOITAO	    IN	VARCHAR2,
    V_NGUOISUA	    IN	VARCHAR2,
    V_SODIENTHOAI   IN	VARCHAR2,
    V_EMAIL         IN	VARCHAR2,
    V_DONVI_ID      IN	VARCHAR2,
    V_DIACHI      IN	VARCHAR2
 );
PROCEDURE  USER_LOGIN
(
  V_USERNAME in VARCHAR2,
  V_PASSWORD in VARCHAR2,
  CurReturn OUT sys_refcursor 
);
END PKG_COVID;
