--------------------------------------------------------
--  DDL for Package PKG_DASHBOARD_ST_APP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_DASHBOARD_ST_APP" AS 
PROCEDURE DASHBOARD_CREATE_DATA_ADS_ST;
PROCEDURE DASHBOARD_CREATE_DATA_AHN_ST;
PROCEDURE DASHBOARD_CREATE_DATA_AKT_ST;
PROCEDURE DASHBOARD_CREATE_DATA_ALD_ST;
PROCEDURE DASHBOARD_CREATE_DATA_AHC_ST;
PROCEDURE DASHBOARD_CREATE_DATA_APS_ST;
END PKG_DASHBOARD_ST_APP;

/
