--------------------------------------------------------
--  DDL for Package PKG_STPT_CHITIETVUAN_DANHSACHBICAO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_STPT_CHITIETVUAN_DANHSACHBICAO" AS 

PROCEDURE AHS_STPT_CHITIETVUAN_DANHSACHBICAO
(   
      VCAPXETXU IN NUMBER, -- Sơ thẩm - 2, Phúc thẩm - 3
      VVUANID IN NUMBER,
      PAGEINDEX	IN	INT,
      PAGESIZE	IN	INT,
      CURRETURN OUT SYS_REFCURSOR
);

PROCEDURE AHS_STPT_CHITIETVUAN_DANHSACHKHANGCAO
(   
      VCAPXETXU IN NUMBER, -- Sơ thẩm - 2, Phúc thẩm - 3
      VVUANID IN NUMBER,
      PAGEINDEX	IN	INT,
      PAGESIZE	IN	INT,
      CURRETURN OUT SYS_REFCURSOR
);

PROCEDURE AHS_STPT_CHITIETVUAN_DANHSACHKHANGNGHI
(   
      VCAPXETXU IN NUMBER, -- Sơ thẩm - 2, Phúc thẩm - 3
      VVUANID IN NUMBER,
      PAGEINDEX	IN	INT,
      PAGESIZE	IN	INT,
      CURRETURN OUT SYS_REFCURSOR
);

END PKG_STPT_CHITIETVUAN_DANHSACHBICAO;

/
