--------------------------------------------------------
--  DDL for Package PKG_BPXLHC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_BPXLHC" 
AS
-- Package header

PROCEDURE XLHC_PHUCTHAM_THULY_GETLIST_V2
( vDONID in number,
	curReturn OUT sys_refcursor
);

PROCEDURE XLHC_SOTHAM_QUYETDINH_GETLIST
( vDONID in number,
	curReturn    OUT       sys_refcursor
);
PROCEDURE XLHC_DON_TGTT_GETLIST_V2
( vDONID in number,
	curReturn    OUT       sys_refcursor
);
 PROCEDURE XLHC_PT_KCQUAHAN_V2
(
  vDonViID in number,
  vMaVuViec in varchar2, 
  vTenVuViec in varchar2,
  vTuNgay in date,
  vDenNgay in date,
  vTrangThai in number,
  vPageIndex in int,
  vPageSize in int,
  curReturn OUT sys_refcursor
);
 PROCEDURE XLHC_SOTHAM_THULY_GETLIST_V2
( vDONID in number,
	curReturn    OUT       sys_refcursor
);
 PROCEDURE XLHC_DON_XULY_GETBYDONID_V2
(
   CurrDonID in int,   
	 PageIndex	in	int,
	 PageSize	in	int,
	 curReturn    OUT   sys_refcursor
);
PROCEDURE XLHC_DONXIN_HOAN_MIEN_GETLIST_V2
(
    CurrDonID   IN  NUMBER, 
    pVaiTro     IN  VARCHAR2,  
	PageIndex	IN	NUMBER,
	PageSize	IN	NUMBER,
	curReturn   OUT   sys_refcursor
);

PROCEDURE XLHC_ST_KCKN_TINHTRANG_GETLIST_V2
( 
	vDonID IN NUMBER,
	curReturn OUT sys_refcursor
);
PROCEDURE HOANMIEN_SOTHAM_HDXX_GETLIST 
(   vDONID IN number,
    vLOAIAN IN number,
    vDONHOANMIEN_ID IN number,
	curReturn OUT sys_refcursor
);
PROCEDURE XLHC_ST_KCKN_TINHTRANG_GETLIST
( vDonID in number,
	curReturn OUT sys_refcursor
);

PROCEDURE UPSERT_HOANMIEN_SOTHAM_HDXX (
		N_ID  			IN NUMBER,
		N_DONID 		IN NUMBER,
		V_MAVAITRO 		IN VARCHAR2,
		N_CANBOID 		IN NUMBER,
		V_HOTEN			IN VARCHAR2,
		D_NGAYPHANCONG  IN DATE,
		D_NGAYNHANPHANCONG IN DATE,
		D_NGAYTHAMGIA 	IN DATE,
		D_NGAYKETTHUC 	IN DATE,
		N_NGUOIPHANCONGID IN NUMBER,
		N_DUKHUYET		IN NUMBER,
		V_NGUOITAO 		IN NVARCHAR2,
		D_NGAYTAO 		IN DATE,
		V_NGUOISUA 		IN NVARCHAR2, 
		D_NGAYSUA 		IN DATE,
		N_LOAIAN 		IN NUMBER,
		N_DON_XIN_HOAN_MIEN_ID 	IN NUMBER,
        N_TOA_GIAIQUYET_ID 	IN NUMBER,
		OUT_ID OUT NUMBER
);

PROCEDURE GET_HOANMIEN_SOTHAM_HDXX_BY_ID (
	N_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE DELETE_HOANMIEN_SOTHAM_HDXX_BY_ID (
	N_ID IN NUMBER
);

PROCEDURE GET_HOANMIEN_SOTHAM_HDXX_BY_DON_HOANMIEN (
	P_DON_HOANMIEN_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE GET_HOANMIEN_SOTHAM_HDXX_BY_DON_VAITRO (
	N_DONID IN NUMBER,
	N_DON_HOANMIEN_ID IN NUMBER,
	V_MAVAITRO IN VARCHAR2,
	N_LOAIAN IN NUMBER,
	N_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE GET_DONXINHOANMIEN_THULY_BY_HOAN_MIEN_ID(
	N_DON_XIN_HOAN_MIEN_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE GET_DONXINHOANMIEN_THULY_BY_DONID_HOAN_MIEN_ID(
	N_DONID IN NUMBER,
	N_LOAIAN IN NUMBER,
	N_DON_XIN_HOAN_MIEN_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE GET_DONXINHOANMIEN_THULY_BY_SOTHULY_ID(
	N_SOTHULY IN NUMBER,
	N_LOAIAN IN NUMBER,
	N_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE UPSERT_DONXINHOANMIEN_THULY(
	N_ID IN NUMBER,
	N_LOAIAN IN NUMBER,
	N_DONID IN NUMBER,
	N_TOAANID IN NUMBER,
	N_DON_XIN_HOAN_MIEN_ID IN NUMBER,
	N_SOTHULY IN NUMBER,
	D_NGAYTHULY IN DATE,
	N_NGUOITHULYID IN NUMBER,
	D_NGAYTAO IN DATE,
	D_NGAYSUA IN DATE,
	V_NGUOITAO IN VARCHAR2,
	V_NGUOISUA IN VARCHAR2,
	OUT_ID OUT NUMBER
);

PROCEDURE DELETE_DONXINHOANMIEN_THULY_BY_ID (
	N_ID IN NUMBER
);

PROCEDURE GET_DONXINHOANMIEN_THULY_BY_SOTHULY_NGAYTHULY(
	N_LOAIAN IN NUMBER,
	D_NGAYTHULY_START IN DATE,
	D_NGAYTHULY_END IN DATE,
	curReturn OUT sys_refcursor
);

PROCEDURE GET_XLHC_DON_GIAIDOAN_BY_DONID (
	N_VUANID IN NUMBER,
	curReturn OUT sys_refcursor
);

PROCEDURE GET_HOANMIEN_SOTHAM_HDXX_BY_CONDITION (
	P_DON_ID IN NUMBER,
	P_DON_HOANMIEN_ID IN NUMBER,
	P_CANBO_ID IN NUMBER,
	P_LOAIAN IN NUMBER,
	P_ID IN NUMBER,
	curReturn OUT sys_refcursor
);

END PKG_BPXLHC;

/
