CREATE OR REPLACE PACKAGE GSCM.PKG_DVCQG_VNEID_KT
AS
-- Package header
PROCEDURE THONGBAO_TONGDAT_VNEID_THULY_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE THONGBAO_TONGDAT_VNEID_QDVUVIEC_ST_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE TONGDAT_VNEID_THULY_PT_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_QDVUVIEC_PT_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_PT_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE TONGDAT_VNEID_THONGTINDON_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE TONGDAT_VNEID_GIAIQUYETDON_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_ST_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_QUYETDINH_ST_KT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
END PKG_DVCQG_VNEID_KT;