--------------------------------------------------------
--  DDL for Package PKG_BAOCAO_CA_QLTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_BAOCAO_CA_QLTA" AS


FUNCTION TONGDONVISUDUNG_QLTA
(
    V_DATE_TO VARCHAR2
)RETURN SYS_REFCURSOR;

FUNCTION TONGTHULY_QLTA
(
    V_DATE_FROM VARCHAR2 DEFAULT NULL,
    V_DATE_TO VARCHAR2 DEFAULT NULL
)RETURN SYS_REFCURSOR;


END PKG_BAOCAO_CA_QLTA;

/
