CREATE OR REPLACE PACKAGE GSCM.PKG_DVCQG_VNEID_HS
AS
-- Package header
PROCEDURE THONGBAO_TONGDAT_VNEID_QD_ST
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_ST
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_QD_PT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);

PROCEDURE THONGBAO_TONGDAT_VNEID_BANAN_PT
(
    V_LOAIVUVIEC IN NUMBER,
    V_TONGDAT IN NUMBER,
    V_DOITUONGID IN NUMBER,
    V_FILENAME IN VARCHAR2,
    curReturn OUT SYS_REFCURSOR
);
END PKG_DVCQG_VNEID_HS;