--------------------------------------------------------
--  DDL for Package PKG_KHOBAQD
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GSCM"."PKG_KHOBAQD" AS 

FUNCTION INSERT_DULIEU_DONGBO
(   
    v_DONID IN NUMBER,
    v_LINHVUC IN VARCHAR2,
    v_CAPXX IN NUMBER,
    v_LOAIBAQD IN NUMBER,
    v_IDBAQD IN NUMBER,
    v_QUANHEPHAPLUATID IN NUMBER,
    v_SOBAQD IN VARCHAR2,
    v_NGAYBAQD IN Date,
    v_NGAYHIEULUCBAQD IN Date,
    v_MACQ IN VARCHAR2,
    v_COQUANQD IN VARCHAR2,
    v_TAIKHOANTAO IN VARCHAR2,
    v_MAVANBAN IN VARCHAR2,
    v_TOAANID IN NUMBER,
    v_DSBAQDLIENQUAN IN VARCHAR2,
    v_SOTHULY IN VARCHAR2,
    v_THAMPHAN IN VARCHAR2,
    v_LOAIQDHN IN VARCHAR2,
    v_TRANGTHAIBAQD IN NUMBER,
    P_Json IN CLOB
)RETURN NUMBER;

FUNCTION INSERT_DULIEU_DUONGSU_DONGBO
(   
    v_KHOBAQDID IN NUMBER,
    p_TAIKHOANTAO IN VARCHAR2,
    P_Json IN CLOB
)RETURN NUMBER;

FUNCTION HUYCHUYEN_DULIEU_DONGBO
(   
    p_KHOBAQDID IN NUMBER
)RETURN NUMBER;

FUNCTION HUYCHUYEN_DULIEU_DUONGSU
(   
    p_KHOBAQDID IN NUMBER,
    p_KHOBAQDID_OLD IN NUMBER,
    p_DUONGSUID IN NUMBER
)RETURN NUMBER;


FUNCTION THUHOI_DULIEU_DUONGSU
(   
    p_KHOBAQDID IN NUMBER,
    p_TAIKHOANTAO IN VARCHAR2,
    p_LYDO IN VARCHAR2,
    p_DUONGSUID IN NUMBER
)RETURN NUMBER;

FUNCTION THUHOI_DULIEU_DONGBO
(   
    p_KHOBAQDID IN NUMBER,
    p_TAIKHOANTAO IN VARCHAR2,
    p_LYDO IN VARCHAR2
)RETURN NUMBER;

FUNCTION GUILAI_DULIEU_DUONGSU_DONGBO
(   
    p_KHOBAQDID IN NUMBER,
    p_TAIKHOANTAO IN VARCHAR2,
    p_KHOBAQDID_NEW IN NUMBER,
    p_DUONGSUID IN NUMBER,
    P_Json IN CLOB
)RETURN NUMBER;

PROCEDURE GET_LICH_SU_DULIEU_DONGBO
(  
    p_KHOBAQDID IN NUMBER,
    
    Page_Index in	int,
    Page_Size	in	int,
    curReturn OUT sys_refcursor
);

FUNCTION GUILAI_DULIEU_DONGBO
(   
    p_KHOBAQDID IN NUMBER,
    v_DONID IN NUMBER,
    v_LINHVUC IN VARCHAR2,
    v_CAPXX IN NUMBER,
    v_LOAIBAQD IN NUMBER,
    v_IDBAQD IN NUMBER,
    v_QUANHEPHAPLUATID IN NUMBER,
    v_SOBAQD IN VARCHAR2,
    v_NGAYBAQD IN Date,
    v_NGAYHIEULUCBAQD IN Date,
    v_MACQ IN VARCHAR2,
    v_COQUANQD IN VARCHAR2,
    v_TAIKHOANTAO IN VARCHAR2,
    v_MAVANBAN IN VARCHAR2,
    v_TOAANID IN NUMBER,
    v_DSBAQDLIENQUAN IN VARCHAR2,
    v_SOTHULY IN VARCHAR2,
    v_THAMPHAN IN VARCHAR2,
    v_LOAIQDHN IN VARCHAR2,
    v_TRANGTHAIBAQD IN NUMBER,
    P_Json IN CLOB
)RETURN NUMBER;

PROCEDURE GET_PAGING_DUONGSU_DONGBO
(  
    p_KHOBAQDID IN NUMBER,
    p_DONID IN NUMBER,
    p_LINHVUC IN VARCHAR2,
    p_Search IN VARCHAR2,
    p_TRANGTHAIDONGBO IN NUMBER,
    Page_Index in	int,
    Page_Size	in	int,
    curReturn OUT sys_refcursor
);

END PKG_KHOBAQD;

/
