--------------------------------------------------------
--  DDL for Package Body PACKAGE_UPDATE_DATA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "GSCM"."PACKAGE_UPDATE_DATA" AS


    PROCEDURE UPDATE_DATA_AHS_TONGHOPHINHPHAT_ST
    ( 
        curReturn OUT sys_refcursor
    )
    IS 
        V_CURSOR sys_refcursor;
    
        vVUANID	    NUMBER;
        vBICAOID	NUMBER;
        vTOAANID_ST	NUMBER;
        vTOAANID_PT	NUMBER;
        vHINHPHAT_ST	VARCHAR2(4000 BYTE);
        vHINHPHAT_PT	VARCHAR2(4000 BYTE);
        vTONGHOPHINHPHAT	VARCHAR2(4000 BYTE);
        vNGAYSUA	DATE;
        vNGUOISUA	VARCHAR2(255 BYTE);
        vNGAYTAO	DATE;
        vNGUOITAO	VARCHAR2(255 BYTE);
        vHP_TANGGIAM	NUMBER;
        vTENTOIDANH_ST	VARCHAR2(1000 BYTE);
        vTENTOIDANH_PT	VARCHAR2(1000 BYTE);
        
        VCHECK_UPDATE_OR_INSERT NUMBER;
    BEGIN
        
        -- CẬP NHẬT TỔNG HỢP SƠ THẨM
        FOR ITEM IN (SELECT BC.ID BICAOID, NVL(BC.VUANID,QD.VUANID) VUANID, NVL(BA.TOAANID,QD.DONVIID) TOAANID 
                            ,NVL(BA.NGUOITAO,QD.NGUOITAO) NGUOITAO, NVL(BA.NGAYTAO,QD.NGAYTAO) NGAYTAO 
                     FROM AHS_BICANBICAO BC
                        LEFT JOIN AHS_SOTHAM_BANAN BA ON BA.VUANID = BC.VUANID
                        LEFT JOIN (SELECT VA.ID, VA.VUANID, VA.DONVIID, VA.NGAYTAO, VA.NGUOITAO FROM AHS_SOTHAM_QUYETDINH_VUAN VA
                                        INNER JOIN DM_QD_QUYETDINH DMQD ON DMQD.ID = VA.QUYETDINHID AND dmqd.ket_thuc = 1) QD ON QD.VUANID = BC.VUANID
                     WHERE (BA.ID IS NOT NULL OR QD.ID IS NOT NULL)
                    )
        LOOP
            vVUANID	    := NULL;
            vBICAOID	:= NULL;
            vTOAANID_ST	:= NULL;
            vTOAANID_PT	:= NULL;
            vHINHPHAT_ST	:= NULL;
            vHINHPHAT_PT	:= NULL;
            vTONGHOPHINHPHAT	:= NULL;
            vNGAYSUA	:= NULL;
            vNGUOISUA	:= NULL;
            vNGAYTAO	:= NULL;
            vNGUOITAO	:= NULL;
            vHP_TANGGIAM	:= NULL;
            vTENTOIDANH_ST	:= NULL;
            vTENTOIDANH_PT	:= NULL; 
        
            vVUANID := ITEM.VUANID;
            vBICAOID := ITEM.BICAOID;
            vTOAANID_ST := ITEM.TOAANID;
            
            vNGAYTAO := ITEM.NGAYTAO;
            vNGUOITAO := ITEM.NGUOITAO;
            
            BEGIN
            
                PKG_STPT_AHS_TONGHOPHINHPHAT.AHS_TONGHOPHINHPHAT_ST(vVUANID,vBICAOID,V_CURSOR);
                LOOP FETCH V_CURSOR INTO vHINHPHAT_ST;
                EXIT WHEN V_CURSOR%NOTFOUND;
                END LOOP;
                CLOSE V_CURSOR;
                
            EXCEPTION
                WHEN NO_DATA_FOUND THEN vHINHPHAT_ST := NULL;
            END;
            
            BEGIN
            
                SELECT CT.TENTOIDANH INTO vTENTOIDANH_ST
                FROM (SELECT ROW_NUMBER() OVER (ORDER BY CT.ID) RN, CT.TENTOIDANH
                      FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
                        INNER JOIN AHS_SOTHAM_BANAN BA ON BA.ID = CT.BANANID AND BA.VUANID = vVUANID
                      WHERE CT.BICANID = vBICAOID AND 
                      CT.ISMAIN = 1) CT
                      WHERE CT.RN = 1;
                
            EXCEPTION
                WHEN NO_DATA_FOUND THEN vTENTOIDANH_ST := NULL;
            END;
            
            VCHECK_UPDATE_OR_INSERT := 0;
            SELECT COUNT(*) INTO VCHECK_UPDATE_OR_INSERT FROM AHS_TONGHOPHINHPHAT HP WHERE HP.BICAOID = vBICAOID AND HP.VUANID = vVUANID;
            IF(VCHECK_UPDATE_OR_INSERT > 0) THEN
            
                    UPDATE AHS_TONGHOPHINHPHAT
                    SET HINHPHAT_ST = vHINHPHAT_ST, TENTOIDANH_ST = vTENTOIDANH_ST, TOAANID_ST = vTOAANID_ST
                    WHERE BICAOID = vBICAOID AND VUANID = vVUANID;
            
                ELSE
                
                    Insert into AHS_TONGHOPHINHPHAT (ID,VUANID,BICAOID,HINHPHAT_ST,HINHPHAT_PT,TONGHOPHINHPHAT,NGAYSUA,NGUOISUA,NGAYTAO,NGUOITAO,HP_TANGGIAM,TENTOIDANH_ST,TENTOIDANH_PT,TOAANID_ST,TOAANID_PT)
                    Values (AHS_TONGHOPHINHPHAT_SEQ.NEXTVAL,vVUANID,vBICAOID,vHINHPHAT_ST,vHINHPHAT_PT,vTONGHOPHINHPHAT,vNGAYSUA,vNGUOISUA,vNGAYTAO,vNGUOITAO,vHP_TANGGIAM,vTENTOIDANH_ST,vTENTOIDANH_PT,vTOAANID_ST,vTOAANID_PT);
 
            END IF;
        
            
        END LOOP;
        
       COMMIT;
       OPEN curReturn FOR SELECT 1 FROM DUAL;
    END UPDATE_DATA_AHS_TONGHOPHINHPHAT_ST;
    

    PROCEDURE UPDATE_DATA_AHS_TONGHOPHINHPHAT_PT
    ( 
        curReturn OUT sys_refcursor
    )
    IS 
        V_CURSOR sys_refcursor;
    
        vVUANID	    NUMBER;
        vBICAOID	NUMBER;
        vTOAANID_ST	NUMBER;
        vTOAANID_PT	NUMBER;
        vHINHPHAT_ST	VARCHAR2(4000 BYTE);
        vHINHPHAT_PT	VARCHAR2(4000 BYTE);
        vTONGHOPHINHPHAT	VARCHAR2(4000 BYTE);
        vNGAYSUA	DATE;
        vNGUOISUA	VARCHAR2(255 BYTE);
        vNGAYTAO	DATE;
        vNGUOITAO	VARCHAR2(255 BYTE);
        vHP_TANGGIAM	NUMBER;
        vTENTOIDANH_ST	VARCHAR2(1000 BYTE);
        vTENTOIDANH_PT	VARCHAR2(1000 BYTE);
        
        VCHECK_UPDATE_OR_INSERT NUMBER;
    BEGIN

            vVUANID	    := NULL;
            vBICAOID	:= NULL;
            vTOAANID_ST	:= NULL;
            vTOAANID_PT	:= NULL;
            vHINHPHAT_ST	:= NULL;
            vHINHPHAT_PT	:= NULL;
            vTONGHOPHINHPHAT	:= NULL;
            vNGAYSUA	:= NULL;
            vNGUOISUA	:= NULL;
            vNGAYTAO	:= NULL;
            vNGUOITAO	:= NULL;
            vHP_TANGGIAM	:= NULL;
            vTENTOIDANH_ST	:= NULL;
            vTENTOIDANH_PT	:= NULL; 
        
        
        -- CẬP NHẬT TỔNG HỢP PHÚC THẨM
        FOR ITEM IN (SELECT BC.ID BICAOID, NVL(BC.VUANID,QD.VUANID) VUANID, NVL(BA.TOAANID,QD.DONVIID) TOAANID 
                            ,NVL(BA.NGUOITAO,QD.NGUOITAO) NGUOITAO, NVL(BA.NGAYTAO,QD.NGAYTAO) NGAYTAO 
                     FROM AHS_BICANBICAO BC
                        LEFT JOIN AHS_PHUCTHAM_BANAN BA ON BA.VUANID = BC.VUANID
                        LEFT JOIN (SELECT VA.ID, VA.VUANID, VA.DONVIID, VA.NGAYTAO, VA.NGUOITAO FROM AHS_PHUCTHAM_QUYETDINH_VUAN VA
                                        INNER JOIN DM_QD_QUYETDINH DMQD ON DMQD.ID = VA.QUYETDINHID AND dmqd.ket_thuc = 1) QD ON QD.VUANID = BC.VUANID
                     WHERE (BA.ID IS NOT NULL OR QD.ID IS NOT NULL)
                    )
        LOOP
            vVUANID	    := NULL;
            vBICAOID	:= NULL;
            vTOAANID_PT	:= NULL;
            
            vHINHPHAT_PT	:= NULL;
            
            vNGAYTAO	:= NULL;
            vNGUOITAO	:= NULL;
            
            vTENTOIDANH_PT	:= NULL;
            vTONGHOPHINHPHAT := NULL;
            
            vVUANID := ITEM.VUANID;
            vBICAOID := ITEM.BICAOID;
            vTOAANID_PT := ITEM.TOAANID;
            
            vNGAYTAO := ITEM.NGAYTAO;
            vNGUOITAO := ITEM.NGUOITAO;
            
            BEGIN
            
                PKG_STPT_AHS_TONGHOPHINHPHAT.AHS_TONGHOPHINHPHAT_PT(vVUANID,vBICAOID,V_CURSOR);
                LOOP FETCH V_CURSOR INTO vHINHPHAT_PT;
                EXIT WHEN V_CURSOR%NOTFOUND;
                END LOOP;
                CLOSE V_CURSOR;
            
            EXCEPTION
                WHEN NO_DATA_FOUND THEN vHINHPHAT_PT := NULL;
            END;   
            
            BEGIN
            
                PKG_STPT_AHS_TONGHOPHINHPHAT.AHS_TONGHOPHINHPHAT_SOSANH(vVUANID,vBICAOID,V_CURSOR);
                LOOP FETCH V_CURSOR INTO vTONGHOPHINHPHAT;
                EXIT WHEN V_CURSOR%NOTFOUND;
                END LOOP;
                CLOSE V_CURSOR;
            
            EXCEPTION
                WHEN NO_DATA_FOUND THEN vTONGHOPHINHPHAT := NULL;
            END;   
            
            BEGIN
                SELECT CT.TENTOIDANH INTO vTENTOIDANH_PT
                FROM (SELECT ROW_NUMBER() OVER (ORDER BY CT.ID) RN, CT.TENTOIDANH
                      FROM AHS_PHUCTHAM_BANAN_DIEU_CT CT
                        INNER JOIN AHS_PHUCTHAM_BANAN BA ON BA.ID = CT.BANANID AND BA.VUANID = vVUANID
                      WHERE CT.BICANID = vBICAOID AND 
                      CT.ISMAIN = 1) CT
                      WHERE CT.RN = 1;
                      
            EXCEPTION
                WHEN NO_DATA_FOUND THEN vTENTOIDANH_PT := NULL;
            END;
            
            VCHECK_UPDATE_OR_INSERT := 0;
            SELECT COUNT(*) INTO VCHECK_UPDATE_OR_INSERT FROM AHS_TONGHOPHINHPHAT HP WHERE HP.BICAOID = vBICAOID AND HP.VUANID = vVUANID;
            IF(VCHECK_UPDATE_OR_INSERT > 0) THEN
            
                    UPDATE AHS_TONGHOPHINHPHAT
                    SET HINHPHAT_PT = vHINHPHAT_PT, TENTOIDANH_PT = vTENTOIDANH_PT, TOAANID_PT = vTOAANID_PT, TONGHOPHINHPHAT = vTONGHOPHINHPHAT
                    WHERE BICAOID = vBICAOID AND VUANID = vVUANID;
            
                ELSE
                
                    Insert into AHS_TONGHOPHINHPHAT (ID,VUANID,BICAOID,HINHPHAT_ST,HINHPHAT_PT,TONGHOPHINHPHAT,NGAYSUA,NGUOISUA,NGAYTAO,NGUOITAO,HP_TANGGIAM,TENTOIDANH_ST,TENTOIDANH_PT,TOAANID_ST,TOAANID_PT)
                    Values (AHS_TONGHOPHINHPHAT_SEQ.NEXTVAL,vVUANID,vBICAOID,vHINHPHAT_ST,vHINHPHAT_PT,vTONGHOPHINHPHAT,vNGAYSUA,vNGUOISUA,vNGAYTAO,vNGUOITAO,vHP_TANGGIAM,vTENTOIDANH_ST,vTENTOIDANH_PT,vTOAANID_ST,vTOAANID_PT);
 
            END IF;
        
            
        END LOOP;        
     
       COMMIT;
       OPEN curReturn FOR SELECT 1 FROM DUAL;
    END UPDATE_DATA_AHS_TONGHOPHINHPHAT_PT;


 
-- 
--   PROCEDURE XOATHULYTHUA
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--        LAST_ID_THULY NUMBER;
--    BEGIN
--        --DANSU
--        FOR ITEM IN (SELECT * FROM (SELECT DISTINCT(DONID) DONID, COUNT(DONID) CT FROM ADS_SOTHAM_THULY 
--                                    GROUP BY DONID)
--                     WHERE CT > 1)
--        LOOP
--
--            LAST_ID_THULY := 0;
--
--            SELECT ID INTO LAST_ID_THULY 
--            FROM (SELECT DISTINCT DONID, FIRST_VALUE(ID) OVER (PARTITION BY DONID ORDER BY NGAYTHULY DESC, NGAYTAO DESC) AS ID
--                      FROM  ADS_SOTHAM_THULY
--                      WHERE DONID = ITEM.DONID);
--
--            DELETE FROM ADS_SOTHAM_THULY WHERE DONID = ITEM.DONID AND ID != LAST_ID_THULY;
--
--        END LOOP;
--
--        --HONNHAN
--        FOR ITEM IN (SELECT * FROM (SELECT DISTINCT(DONID) DONID, COUNT(DONID) CT FROM AHN_SOTHAM_THULY 
--                                    GROUP BY DONID)
--                     WHERE CT > 1)
--        LOOP
--
--            LAST_ID_THULY := 0;
--
--            SELECT ID INTO LAST_ID_THULY 
--            FROM (SELECT DISTINCT DONID, FIRST_VALUE(ID) OVER (PARTITION BY DONID ORDER BY NGAYTHULY DESC, NGAYTAO DESC) AS ID
--                      FROM  AHN_SOTHAM_THULY
--                      WHERE DONID = ITEM.DONID);
--
--            DELETE FROM AHN_SOTHAM_THULY WHERE DONID = ITEM.DONID AND ID != LAST_ID_THULY;
--
--        END LOOP;
--
--        --KINHTE
--        FOR ITEM IN (SELECT * FROM (SELECT DISTINCT(DONID) DONID, COUNT(DONID) CT FROM AKT_SOTHAM_THULY 
--                                    GROUP BY DONID)
--                     WHERE CT > 1)
--        LOOP
--
--            LAST_ID_THULY := 0;
--
--            SELECT ID INTO LAST_ID_THULY 
--            FROM (SELECT DISTINCT DONID, FIRST_VALUE(ID) OVER (PARTITION BY DONID ORDER BY NGAYTHULY DESC, NGAYTAO DESC) AS ID
--                      FROM  AKT_SOTHAM_THULY
--                      WHERE DONID = ITEM.DONID);
--
--            DELETE FROM AKT_SOTHAM_THULY WHERE DONID = ITEM.DONID AND ID != LAST_ID_THULY;
--
--        END LOOP;
--
--        --HANHCHINH
--        FOR ITEM IN (SELECT * FROM (SELECT DISTINCT(DONID) DONID, COUNT(DONID) CT FROM AHC_SOTHAM_THULY 
--                                    GROUP BY DONID)
--                     WHERE CT > 1)
--        LOOP
--
--            LAST_ID_THULY := 0;
--
--            SELECT ID INTO LAST_ID_THULY 
--            FROM (SELECT DISTINCT DONID, FIRST_VALUE(ID) OVER (PARTITION BY DONID ORDER BY NGAYTHULY DESC, NGAYTAO DESC) AS ID
--                      FROM  AHC_SOTHAM_THULY
--                      WHERE DONID = ITEM.DONID);
--
--            DELETE FROM AHC_SOTHAM_THULY WHERE DONID = ITEM.DONID AND ID != LAST_ID_THULY;
--
--        END LOOP;
--
--        --LAODONG
--        FOR ITEM IN (SELECT * FROM (SELECT DISTINCT(DONID) DONID, COUNT(DONID) CT FROM ALD_SOTHAM_THULY 
--                                    GROUP BY DONID)
--                     WHERE CT > 1)
--        LOOP
--
--            LAST_ID_THULY := 0;
--
--            SELECT ID INTO LAST_ID_THULY 
--            FROM (SELECT DISTINCT DONID, FIRST_VALUE(ID) OVER (PARTITION BY DONID ORDER BY NGAYTHULY DESC, NGAYTAO DESC) AS ID
--                      FROM  ALD_SOTHAM_THULY
--                      WHERE DONID = ITEM.DONID);
--
--            DELETE FROM ALD_SOTHAM_THULY WHERE DONID = ITEM.DONID AND ID != LAST_ID_THULY;
--
--        END LOOP;
--
--        --PHASAN
--        FOR ITEM IN (SELECT * FROM (SELECT DISTINCT(DONID) DONID, COUNT(DONID) CT FROM APS_SOTHAM_THULY 
--                                    GROUP BY DONID)
--                     WHERE CT > 1)
--        LOOP
--
--            LAST_ID_THULY := 0;
--
--            SELECT ID INTO LAST_ID_THULY 
--            FROM (SELECT DISTINCT DONID, FIRST_VALUE(ID) OVER (PARTITION BY DONID ORDER BY NGAYTHULY DESC, NGAYTAO DESC) AS ID
--                      FROM  APS_SOTHAM_THULY
--                      WHERE DONID = ITEM.DONID);
--
--            DELETE FROM APS_SOTHAM_THULY WHERE DONID = ITEM.DONID AND ID != LAST_ID_THULY;
--
--        END LOOP;
--
--        COMMIT;
--
--        OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END XOATHULYTHUA;
--
--
--
--  PROCEDURE UPDATE_DUONGSUIDS_ANPHI_AHN
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--        FIRSTVALUE VARCHAR(10);
--        SECONDVALUE VARCHAR(10);
--        VCONVERTED VARCHAR(100);
--    BEGIN
--
---- Test dữ liệu
----select D.ID, D.DUONGSU_IDS
----from AHN_ANPHI D
----where REGEXP_COUNT(D.DUONGSU_IDS, ',') = 1;
----
----select COUNT(D.ID)
----from AHN_ANPHI D
----where REGEXP_COUNT(D.DUONGSU_IDS, ',') = 1;
----
----select D.ID, D.DUONGSU_IDS--, REGEXP_SUBSTR(D.DUONGSU_IDS, '[^,]+$'), REGEXP_SUBSTR(D.DUONGSU_IDS,'[^,]+',1,1) 
----from AHN_ANPHI D
----where REGEXP_COUNT(D.DUONGSU_IDS, ',') = 2;
--
--
--
--        FOR ITEM IN(SELECT D.ID, D.DUONGSU_IDS FROM AHN_ANPHI D WHERE REGEXP_COUNT(D.DUONGSU_IDS, ',') = 1)
--        LOOP
--            FIRSTVALUE := NULL;
--            SECONDVALUE := NULL;
--            VCONVERTED := NULL;
--
--            SELECT REGEXP_SUBSTR(ITEM.DUONGSU_IDS, '[^,]+$') ,  REGEXP_SUBSTR(ITEM.DUONGSU_IDS,'[^,]+',1,1) INTO FIRSTVALUE, SECONDVALUE
--            FROM DUAL;
--
--            IF(TO_NUMBER(FIRSTVALUE) > TO_NUMBER(SECONDVALUE)) THEN
--                VCONVERTED := SECONDVALUE || ',' || FIRSTVALUE;
--            ELSE
--                VCONVERTED := FIRSTVALUE || ',' || SECONDVALUE;
--            END IF;
--
--
--            UPDATE AHN_ANPHI SET DUONGSU_IDS = VCONVERTED WHERE ID = ITEM.ID;
--
--        END LOOP;
--
--        COMMIT;
--
--        OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END UPDATE_DUONGSUIDS_ANPHI_AHN;
--
--
--    PROCEDURE INSERT_THULYID_SOTHAM
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--        VTHULYID NUMBER;
--    BEGIN
--
----        ALTER TABLE AHS_SOTHAM_BANAN            ADD THULYID NUMBER;
----        ALTER TABLE AHS_SOTHAM_QUYETDINH_VUAN   ADD THULYID NUMBER;
----        ALTER TABLE AHS_SOTHAM_HDXX             ADD THULYID NUMBER;
----        ALTER TABLE AHS_SOTHAM_QUYETDINH_BICAN  ADD THULYID NUMBER;
--
----        FOR ITEM IN(SELECT * FROM (SELECT VUANID,COUNT(DISTINCT (ID)) AS COUNTA
----                                   FROM AHS_SOTHAM_THULY
----                                   GROUP BY VUANID)
----                                   WHERE COUNTA = 1)
----        LOOP
----            SELECT ID INTO VTHULYID
----            FROM AHS_SOTHAM_THULY
----            WHERE VUANID = ITEM.VUANID;
----
----            UPDATE AHS_SOTHAM_BANAN SET THULYID = VTHULYID WHERE VUANID = ITEM.VUANID AND THULYID IS NULL;
----            UPDATE AHS_SOTHAM_QUYETDINH_VUAN SET THULYID = VTHULYID WHERE VUANID = ITEM.VUANID AND THULYID IS NULL;
----            UPDATE AHS_SOTHAM_HDXX SET THULYID = VTHULYID WHERE VUANID = ITEM.VUANID AND THULYID IS NULL;
----            UPDATE AHS_SOTHAM_QUYETDINH_BICAN SET THULYID = VTHULYID WHERE VUANID = ITEM.VUANID AND THULYID IS NULL;
----
----            VTHULYID := 0;
----        END LOOP;
--
--        FOR ITEM IN (SELECT * FROM AHS_SOTHAM_BANAN WHERE THULYID IS NULL OR THULYID = 0 )
--        LOOP
--
--            SELECT CASE WHEN EXISTS (
--                          SELECT 1 FROM AHS_SOTHAM_THULY WHERE VUANID = ITEM.VUANID AND ITEM.NGAYBANAN >= NGAYTHULY
--                        ) THEN 1 ELSE 0 END 
--            INTO VTHULYID
--            FROM DUAL;
--
--            IF (VTHULYID > 0) THEN
--                SELECT C.ID INTO VTHULYID
--                FROM (
--                    SELECT 
--                        DISTINCT TL.VUANID,
--                        FIRST_VALUE(TL.ID) OVER (PARTITION BY TL.VUANID ORDER BY TL.NGAYTHULY DESC, TL.ID DESC) AS ID
--                    FROM GSCM.AHS_SOTHAM_THULY TL
--                    WHERE ITEM.NGAYBANAN >= TL.NGAYTHULY AND TL.VUANID = ITEM.VUANID
--                ) C;
--
--                UPDATE AHS_SOTHAM_BANAN SET THULYID = VTHULYID WHERE ID = ITEM.ID;
--                COMMIT;
--            END IF;
--
--            VTHULYID := 0;
--        END LOOP;
--
--        FOR ITEM IN (SELECT * FROM AHS_SOTHAM_QUYETDINH_VUAN WHERE THULYID IS NULL OR THULYID = 0 )
--        LOOP
--
--            SELECT CASE WHEN EXISTS (
--                          SELECT 1 FROM AHS_SOTHAM_THULY WHERE VUANID = ITEM.VUANID AND ITEM.NGAYQD >= NGAYTHULY
--                        ) THEN 1 ELSE 0 END 
--            INTO VTHULYID
--            FROM DUAL;
--
--            IF (VTHULYID > 0) THEN
--
--                SELECT C.ID INTO VTHULYID
--                FROM (
--                    SELECT 
--                        DISTINCT TL.VUANID,
--                        FIRST_VALUE(TL.ID) OVER (PARTITION BY TL.VUANID ORDER BY TL.NGAYTHULY DESC, TL.ID DESC) AS ID
--                    FROM GSCM.AHS_SOTHAM_THULY TL
--                    WHERE ITEM.NGAYQD >= TL.NGAYTHULY AND TL.VUANID = ITEM.VUANID
--                ) C;
--
--                UPDATE AHS_SOTHAM_QUYETDINH_VUAN SET THULYID = VTHULYID WHERE ID = ITEM.ID;
--            END IF;
--
--            VTHULYID := 0;
--        END LOOP;        
--
--        FOR ITEM IN (SELECT * FROM AHS_SOTHAM_HDXX WHERE THULYID IS NULL OR THULYID = 0 )
--        LOOP
--
--            SELECT CASE WHEN EXISTS (
--                          SELECT 1 FROM AHS_SOTHAM_THULY WHERE VUANID = ITEM.VUANID AND ITEM.NGAYPHANCONG >= NGAYTHULY
--                        ) THEN 1 ELSE 0 END 
--            INTO VTHULYID
--            FROM DUAL;
--
--            IF (VTHULYID > 0) THEN
--
--                SELECT C.ID INTO VTHULYID
--                FROM (
--                    SELECT 
--                        DISTINCT TL.VUANID,
--                        FIRST_VALUE(TL.ID) OVER (PARTITION BY TL.VUANID ORDER BY TL.NGAYTHULY DESC, TL.ID DESC) AS ID
--                    FROM GSCM.AHS_SOTHAM_THULY TL
--                    WHERE ITEM.NGAYPHANCONG >= TL.NGAYTHULY AND TL.VUANID = ITEM.VUANID
--                ) C;
--                UPDATE AHS_SOTHAM_HDXX SET THULYID = VTHULYID WHERE ID = ITEM.ID;
--
--            END IF;
--
--            VTHULYID := 0;
--        END LOOP;               
--
--        FOR ITEM IN (SELECT * FROM AHS_SOTHAM_QUYETDINH_BICAN WHERE THULYID IS NULL OR THULYID = 0 )
--        LOOP
--
--            SELECT CASE WHEN EXISTS (
--                          SELECT 1 FROM AHS_SOTHAM_THULY WHERE VUANID = ITEM.VUANID AND ITEM.NGAYQD >= NGAYTHULY
--                        ) THEN 1 ELSE 0 END 
--            INTO VTHULYID
--            FROM DUAL;
--
--            IF (VTHULYID > 0) THEN
--
--                SELECT C.ID INTO VTHULYID
--                FROM (
--                    SELECT 
--                        DISTINCT TL.VUANID,
--                        FIRST_VALUE(TL.ID) OVER (PARTITION BY TL.VUANID ORDER BY TL.NGAYTHULY DESC, TL.ID DESC) AS ID
--                    FROM GSCM.AHS_SOTHAM_THULY TL
--                    WHERE ITEM.NGAYQD >= TL.NGAYTHULY AND TL.VUANID = ITEM.VUANID
--                ) C;
--                UPDATE AHS_SOTHAM_QUYETDINH_BICAN SET THULYID = VTHULYID WHERE ID = ITEM.ID;
--
--            END IF;
--
--            VTHULYID := 0;
--        END LOOP;
--
--
--
--        COMMIT;
--
--        OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END INSERT_THULYID_SOTHAM;
--
--    /* CONVERT_DATA_KHANGCAOQUAHAN - Chuyển dữ liêu từ bảng %_SOTHAM_KHANGCAO qua bảng KHANGCAOQUAHAN_% */
--    PROCEDURE CONVERT_DATA_KHANGCAOQUAHAN
--    ( 
--        curReturn OUT sys_refcursor
--    )        
--    IS 
--        VTHULY_ID NUMBER;
--        COUNTHS NUMBER DEFAULT 0;
--        COUNTDS NUMBER DEFAULT 0;
--        COUNTHN NUMBER DEFAULT 0;
--        COUNTKT NUMBER DEFAULT 0;
--        COUNTLD NUMBER DEFAULT 0;
--        COUNTHC NUMBER DEFAULT 0;
--    BEGIN
--        /* * Kiểm tra số kháng cáo quá hạn đã được giải quyết
--           * Số lượng vụ án/việc tương đương với số lượng được đổ vào bảng KHANGCAOQUAHAN_QUYETDINH theo từng loại án
--
--        SELECT COUNT('X')FROM Ahs_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1 AND GQ_ISCHAPNHAN IS NOT NULL ;
--        SELECT COUNT('X')FROM Ads_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1 AND GQ_ISCHAPNHAN IS NOT NULL ;
--        SELECT COUNT('X')FROM Ahn_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1 AND GQ_ISCHAPNHAN IS NOT NULL ;
--        SELECT COUNT('X')FROM Akt_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1 AND GQ_ISCHAPNHAN IS NOT NULL ;
--        SELECT COUNT('X')FROM Ald_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1 AND GQ_ISCHAPNHAN IS NOT NULL ;
--        SELECT COUNT('X')FROM Ahc_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1 AND GQ_ISCHAPNHAN IS NOT NULL ;
--        */
--
--
--        DELETE FROM KHANGCAOQUAHAN_THULY WHERE ID > 0;
--        DELETE FROM KHANGCAOQUAHAN_HDXX WHERE ID > 0;
--        DELETE FROM KHANGCAOQUAHAN_QUYETDINH WHERE ID > 0;
--
--
--        FOR ITEM IN (SELECT * FROM AHS_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1)
--        LOOP
--
--            IF(ITEM.GQ_ISCHAPNHAN IS NOT NULL) THEN
--
--                INSERT INTO KHANGCAOQUAHAN_THULY (LOAIAN, DONID, TOAANID, KHANGCAOID, NGAYTAO, NGUOITAO, LOAIKHANGCAO) 
--                                          VALUES (1, ITEM.VUANID, ITEM.GQ_TOAANID, ITEM.ID, ITEM.NGAYTAO, NVL(ITEM.NGUOISUA, ITEM.NGUOITAO) ||  ' - CONVERT', ITEM.LOAIKHANGCAO)
--                                          RETURNING ID INTO VTHULY_ID;
--
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (1, ITEM.VUANID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHAN',ITEM.GQ_THAMPHANID,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (1, ITEM.VUANID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX' ,ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (1, ITEM.VUANID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX',ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--
--                INSERT INTO KHANGCAOQUAHAN_QUYETDINH (LOAIAN, DONID, THULYID, TOAANID, KETQUA,  NGAYGIAIQUYET, GHICHU, NGAYTAO, NGUOITAO ) 
--                                         VALUES (1, ITEM.VUANID, VTHULY_ID, ITEM.GQ_TOAANID,  ITEM.GQ_ISCHAPNHAN, ITEM.GQ_NGAY, ITEM.GQ_GHICHU, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');                        
--                COUNTHS := COUNTHS +1;
--            END IF;  
--
--        END LOOP;        
--
--        FOR ITEM IN (SELECT * FROM ADS_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1)
--        LOOP
--
--            IF(ITEM.GQ_ISCHAPNHAN IS NOT NULL) THEN
--
--                INSERT INTO KHANGCAOQUAHAN_THULY (LOAIAN, DONID, TOAANID, KHANGCAOID, NGAYTAO, NGUOITAO, LOAIKHANGCAO) 
--                                          VALUES (2, ITEM.DONID, ITEM.GQ_TOAANID, ITEM.ID, ITEM.NGAYTAO, NVL(ITEM.NGUOISUA, ITEM.NGUOITAO) ||  ' - CONVERT', ITEM.LOAIKHANGCAO)
--                                          RETURNING ID INTO VTHULY_ID;
--
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (2, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHAN',ITEM.GQ_THAMPHANID,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (2, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX' ,ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (2, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX',ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--
--                INSERT INTO KHANGCAOQUAHAN_QUYETDINH (LOAIAN, DONID, THULYID, TOAANID, KETQUA,  NGAYGIAIQUYET, GHICHU, NGAYTAO, NGUOITAO ) 
--                                         VALUES (2, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID,  ITEM.GQ_ISCHAPNHAN, ITEM.GQ_NGAY, ITEM.GQ_GHICHU, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');                        
--                COUNTDS := COUNTDS +1;
--            END IF;  
--
--        END LOOP;
--
--        FOR ITEM IN (SELECT * FROM AHN_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1)
--        LOOP
--
--            IF(ITEM.GQ_ISCHAPNHAN IS NOT NULL) THEN
--
--                INSERT INTO KHANGCAOQUAHAN_THULY (LOAIAN, DONID, TOAANID, KHANGCAOID, NGAYTAO, NGUOITAO, LOAIKHANGCAO) 
--                                          VALUES (3, ITEM.DONID, ITEM.GQ_TOAANID, ITEM.ID, ITEM.NGAYTAO, NVL(ITEM.NGUOISUA, ITEM.NGUOITAO) ||  ' - CONVERT', ITEM.LOAIKHANGCAO)
--                                          RETURNING ID INTO VTHULY_ID;
--
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (3, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHAN',ITEM.GQ_THAMPHANID,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (3, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX' ,ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (3, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX',ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--
--                INSERT INTO KHANGCAOQUAHAN_QUYETDINH (LOAIAN, DONID, THULYID, TOAANID, KETQUA,  NGAYGIAIQUYET, GHICHU, NGAYTAO, NGUOITAO ) 
--                                         VALUES (3, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID,  ITEM.GQ_ISCHAPNHAN, ITEM.GQ_NGAY, ITEM.GQ_GHICHU, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');                        
--                COUNTHN := COUNTHN +1;
--            END IF;  
--
--        END LOOP;
--
--        FOR ITEM IN (SELECT * FROM AKT_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1)
--        LOOP
--
--            IF(ITEM.GQ_ISCHAPNHAN IS NOT NULL) THEN
--
--                INSERT INTO KHANGCAOQUAHAN_THULY (LOAIAN, DONID, TOAANID, KHANGCAOID, NGAYTAO, NGUOITAO, LOAIKHANGCAO) 
--                                          VALUES (4, ITEM.DONID, ITEM.GQ_TOAANID, ITEM.ID, ITEM.NGAYTAO, NVL(ITEM.NGUOISUA, ITEM.NGUOITAO) ||  ' - CONVERT', ITEM.LOAIKHANGCAO)
--                                          RETURNING ID INTO VTHULY_ID;
--
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (4, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHAN',ITEM.GQ_THAMPHANID,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (4, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX' ,ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (4, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX',ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--
--                INSERT INTO KHANGCAOQUAHAN_QUYETDINH (LOAIAN, DONID, THULYID, TOAANID, KETQUA,  NGAYGIAIQUYET, GHICHU, NGAYTAO, NGUOITAO ) 
--                                         VALUES (4, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID,  ITEM.GQ_ISCHAPNHAN, ITEM.GQ_NGAY, ITEM.GQ_GHICHU, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');                        
--                COUNTKT := COUNTKT +1;
--            END IF;
--        END LOOP;
--
--        FOR ITEM IN (SELECT * FROM ALD_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1)
--        LOOP
--
--            IF(ITEM.GQ_ISCHAPNHAN IS NOT NULL) THEN
--
--                INSERT INTO KHANGCAOQUAHAN_THULY (LOAIAN, DONID, TOAANID, KHANGCAOID, NGAYTAO, NGUOITAO, LOAIKHANGCAO) 
--                                          VALUES (5, ITEM.DONID, ITEM.GQ_TOAANID, ITEM.ID, ITEM.NGAYTAO, NVL(ITEM.NGUOISUA, ITEM.NGUOITAO) ||  ' - CONVERT', ITEM.LOAIKHANGCAO)
--                                          RETURNING ID INTO VTHULY_ID;
--
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (5, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHAN',ITEM.GQ_THAMPHANID,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (5, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX' ,ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (5, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX',ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--
--                INSERT INTO KHANGCAOQUAHAN_QUYETDINH (LOAIAN, DONID, THULYID, TOAANID, KETQUA,  NGAYGIAIQUYET, GHICHU, NGAYTAO, NGUOITAO ) 
--                                         VALUES (5, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID,  ITEM.GQ_ISCHAPNHAN, ITEM.GQ_NGAY, ITEM.GQ_GHICHU, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');                        
--                COUNTLD := COUNTLD +1;
--            END IF;
--        END LOOP;
--
--        FOR ITEM IN (SELECT * FROM AHC_SOTHAM_KHANGCAO WHERE ISQUAHAN = 1)
--        LOOP
--
--            IF(ITEM.GQ_ISCHAPNHAN IS NOT NULL) THEN
--
--                INSERT INTO KHANGCAOQUAHAN_THULY (LOAIAN, DONID, TOAANID, KHANGCAOID, NGAYTAO, NGUOITAO, LOAIKHANGCAO) 
--                                          VALUES (6, ITEM.DONID, ITEM.GQ_TOAANID, ITEM.ID, ITEM.NGAYTAO, NVL(ITEM.NGUOISUA, ITEM.NGUOITAO) ||  ' - CONVERT', ITEM.LOAIKHANGCAO)
--                                          RETURNING ID INTO VTHULY_ID;
--
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (6, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHAN',ITEM.GQ_THAMPHANID,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (6, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX' ,ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--                INSERT INTO KHANGCAOQUAHAN_HDXX (LOAIAN,DONID, THULYID, TOAANID, MAVAITRO,CANBOID,HIEULUC,NGAYTAO,NGUOITAO)
--                                         VALUES (6, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID, 'THAMPHANHDXX',ITEM.GQ_THAMPHANID_1,1, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');
--
--                INSERT INTO KHANGCAOQUAHAN_QUYETDINH (LOAIAN, DONID, THULYID, TOAANID, KETQUA,  NGAYGIAIQUYET, GHICHU, NGAYTAO, NGUOITAO ) 
--                                         VALUES (6, ITEM.DONID, VTHULY_ID, ITEM.GQ_TOAANID,  ITEM.GQ_ISCHAPNHAN, ITEM.GQ_NGAY, ITEM.GQ_GHICHU, ITEM.NGAYTAO , ITEM.NGUOITAO ||  ' - CONVERT');                        
--                COUNTHC := COUNTHC +1;
--            END IF;
--        END LOOP;
--
--        COMMIT;
--
--        OPEN curReturn FOR SELECT COUNTHS, COUNTDS ,COUNTHN ,COUNTKT ,COUNTLD ,COUNTHC  FROM DUAL;
--    END CONVERT_DATA_KHANGCAOQUAHAN;
--
--
--
--    /*DELETE_DATA_AHS_SOTHAM_BANAN_DIEU_CHITIET - Xóa dữ liệu dư thừa ở bảng AHS_SOTHAM_BANAN_DIEU_CHITIET qua các trường BICANID, VUANID*/
--    PROCEDURE DELETE_DATA_AHS_SOTHAM_BANAN_DIEU_CHITIET
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--    BEGIN
--        DELETE FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE TOIDANHID = 0;
--
--        FOR ITEM IN (SELECT CT.ID, CT.BICANID
--                     FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--                        LEFT JOIN AHS_BICANBICAO BC ON BC.ID = CT.BICANID
--                     WHERE NOT EXISTS(SELECT 'X' FROM AHS_BICANBICAO BC WHERE BC.ID = CT.BICANID))
--        LOOP
--            DELETE FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE ID = ITEM.ID;
--        END LOOP;
--
--        COMMIT;
--
--        OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END DELETE_DATA_AHS_SOTHAM_BANAN_DIEU_CHITIET;
--
--    /*UPDATE_AHS_SOTHAM_BANAN_DIEU_CHITIET - Update các trường VUANID,TENTOIDANH,ISMAIN */
--    PROCEDURE UPDATE_AHS_SOTHAM_BANAN_DIEU_CHITIET
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--      VVUANID NUMBER;
--      VBANANID NUMBER;
--      VCHECK NUMBER;
--
--      VTOIDANH_TEN VARCHAR(4000);
--      VTOIDANH_LOAI NUMBER;
--
--    BEGIN
--
--       -- Insert bổ sung các tội danh thiếu
--       FOR ITEM IN (SELECT * 
--                    FROM (  SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM
--                            FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--                            WHERE CT.TOIDANHID != 0
--                            GROUP BY CT.BICANID)
--                    WHERE SUM = 0)
--       LOOP
--
--           FOR ITEMS IN (SELECT CT.BICANID, DM.CAPCHAID, DM.LOAI
--                         FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--                            INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI != 2
--                         WHERE CT.BICANID = ITEM.BICANID
--                         ORDER BY DM.LOAI DESC)
--           LOOP
--               VCHECK := 0;
--
--               SELECT COUNT('X') INTO VCHECK
--               FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--               WHERE CT.BICANID = ITEM.BICANID AND CT.TOIDANHID = ITEMS.CAPCHAID;
--
--               IF(VCHECK = 0) THEN
--                   INSERT INTO AHS_SOTHAM_BANAN_DIEU_CHITIET (BICANID, TOIDANHID, DIEULUATID, ISCHANGE, LOAIHINHPHAT, HINHPHATID, ISMAIN) 
--                                                      VALUES (ITEM.BICANID, ITEMS.CAPCHAID, 7, 0, 0, 0, 0);
--               END IF;
--
--           END LOOP;
--
--           /*Chạy lần 2 để không bỏ sót trường hợp LOAI = 4*/
--           FOR ITEMS IN (SELECT CT.BICANID, DM.CAPCHAID, DM.LOAI
--           FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--              INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI != 2
--           WHERE CT.BICANID = ITEM.BICANID
--           ORDER BY DM.LOAI DESC)
--           LOOP
--               VCHECK := 0;
--
--               SELECT COUNT('X') INTO VCHECK
--               FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--               WHERE CT.BICANID = ITEM.BICANID AND CT.TOIDANHID = ITEMS.CAPCHAID;
--
--               IF(VCHECK = 0) THEN
--                   INSERT INTO AHS_SOTHAM_BANAN_DIEU_CHITIET (BICANID, TOIDANHID, DIEULUATID, ISCHANGE, LOAIHINHPHAT, HINHPHATID, ISMAIN) 
--                                                      VALUES (ITEM.BICANID, ITEMS.CAPCHAID, 7, 0, 0, 0, 0);
--               END IF;
--
--           END LOOP;
--       END LOOP;
--
--
--        -- Update AHS_SOTHAM_BANAN_DIEU_CHITIET.ISMAIN nếu NULL thì SET ISMAIN = 0       
--       FOR ITEM IN (SELECT CT.ID FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT WHERE CT.ISMAIN IS NULL)
--       LOOP
--            UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET ISMAIN = 0 WHERE ID = ITEM.ID; 
--       END LOOP;      
--
--
--
--       -- Update VUANID, BANANID, TENTOIDANH bảng AHS_SOTHAM_BANAN_DIEU_CHITIET
--       FOR ITEM IN (SELECT * FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE TOIDANHID != 0)
--       LOOP
--
--           VCHECK :=0 ; VVUANID := 0; VBANANID:= 0;
--
--           SELECT COUNT('X') INTO VCHECK FROM AHS_BICANBICAO BC WHERE ITEM.BICANID = BC.ID;                     
--           IF(VCHECK > 0) THEN 
--
--               SELECT BC.VUANID, BA.ID INTO VVUANID, VBANANID
--               FROM AHS_BICANBICAO BC 
--                   LEFT JOIN AHS_SOTHAM_BANAN BA ON BA.VUANID = BC.VUANID
--               WHERE ITEM.BICANID = BC.ID;
--
--               UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET VUANID = VVUANID, BANANID = VBANANID WHERE ID = ITEM.ID;                       
--           END IF;  
--
--           VCHECK :=0; VTOIDANH_TEN:= '';
--
--           SELECT COUNT('X') INTO VCHECK FROM DM_BOLUAT_TOIDANH DM WHERE DM.ID = ITEM.TOIDANHID;
--            IF (VCHECK > 0) THEN 
--                SELECT DM.TENTOIDANH INTO VTOIDANH_TEN FROM DM_BOLUAT_TOIDANH DM WHERE DM.ID = ITEM.TOIDANHID;
--                UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET TENTOIDANH = VTOIDANH_TEN WHERE ID = ITEM.ID; 
--            END IF;
--
--       END LOOP;
--
--       -- Update AHS_SOTHAM_BANAN_DIEU_CHITIET.ISMAIN nếu bị cáo không có tội danh chính thì SET tội danh chính cho bị cáo
--       FOR ITEM IN (SELECT BICANID
--                    FROM (SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM 
--                          FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT 
--                          WHERE CT.TOIDANHID != 0
--                          GROUP BY CT.BICANID) 
--                    WHERE SUM = 0)
--       LOOP
--
--            FOR ITEMS IN (SELECT CT.ID 
--                          FROM AHS_SOTHAM_BANAN_DIEU_CHITIET CT
--                              INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI = 2
--                          WHERE BICANID = ITEM.BICANID ORDER BY CT.ID)
--            LOOP
--                UPDATE AHS_SOTHAM_BANAN_DIEU_CHITIET SET ISMAIN = 1 WHERE ID = ITEMS.ID; 
--            END LOOP;
--
--       END LOOP;
--
--       COMMIT;
--
--       OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END UPDATE_AHS_SOTHAM_BANAN_DIEU_CHITIET;
--
--
--    /*DELETE_DATA_AHS_SOTHAM_CAOTRANG_DIEULUAT - Xóa dữ liệu dư thừa ở bảng AHS_SOTHAM_CAOTRANG_DIEULUAT qua các trường BICANID, VUANID*/
--    PROCEDURE DELETE_DATA_AHS_SOTHAM_CAOTRANG_DIEULUAT
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--    BEGIN
--        DELETE FROM AHS_SOTHAM_CAOTRANG_DIEULUAT WHERE BICANID = 0;
--
--        FOR ITEM IN (SELECT CT.ID, CT.BICANID
--                     FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT
--                        LEFT JOIN AHS_BICANBICAO BC ON BC.ID = CT.BICANID
--                     WHERE NOT EXISTS(SELECT 'X' FROM AHS_BICANBICAO BC WHERE BC.ID = CT.BICANID))
--        LOOP
--            DELETE FROM AHS_SOTHAM_CAOTRANG_DIEULUAT WHERE ID = ITEM.ID;
--        END LOOP;
--
--        COMMIT;
--
--        OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END DELETE_DATA_AHS_SOTHAM_CAOTRANG_DIEULUAT;
--
--    /*UPDATE_AHS_SOTHAM_CAOTRANG_DIEULUAT - Update các trường VUANID */
--    PROCEDURE UPDATE_AHS_SOTHAM_CAOTRANG_DIEULUAT
--    ( 
--        curReturn OUT sys_refcursor
--    )
--    IS 
--      VVUANID NUMBER;
--      VCHECK NUMBER;
--
--    BEGIN
--       -- Update VUANID bảng AHS_SOTHAM_CAOTRANG_DIEULUAT
--       FOR ITEM IN (SELECT * FROM AHS_SOTHAM_CAOTRANG_DIEULUAT)
--       LOOP
--
--           VCHECK :=0 ; VVUANID := 0;
--
--           SELECT COUNT('X') INTO VCHECK FROM AHS_BICANBICAO BC WHERE ITEM.BICANID = BC.ID;                     
--           IF(VCHECK > 0) THEN 
--
--               SELECT BC.VUANID INTO VVUANID
--               FROM AHS_BICANBICAO BC 
--               WHERE ITEM.BICANID = BC.ID;
--
--               UPDATE AHS_SOTHAM_CAOTRANG_DIEULUAT SET VUANID = VVUANID WHERE BICANID = ITEM.BICANID;                       
--           END IF;  
--
--           VCHECK :=0;
--       END LOOP;
--
--       -- Update AHS_SOTHAM_CAOTRANG_DIEULUAT.ISMAIN nếu bị cáo không có tội danh chính thì SET tội danh chính cho bị cáo
--       FOR ITEM IN (SELECT BICANID
--                    FROM (SELECT DISTINCT(CT.BICANID) BICANID, SUM(CT.ISMAIN) SUM 
--                          FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT 
--                          WHERE CT.TOIDANHID != 0
--                          GROUP BY CT.BICANID) 
--                    WHERE SUM = 0)
--       LOOP
--
--            FOR ITEMS IN (SELECT CT.ID 
--                          FROM AHS_SOTHAM_CAOTRANG_DIEULUAT CT
--                              INNER JOIN DM_BOLUAT_TOIDANH DM ON DM.ID = CT.TOIDANHID AND DM.LOAI = 2
--                          WHERE BICANID = ITEM.BICANID ORDER BY CT.ID)
--            LOOP
--                UPDATE AHS_SOTHAM_CAOTRANG_DIEULUAT SET ISMAIN = 1 WHERE ID = ITEMS.ID; 
--            END LOOP;
--
--       END LOOP;
--
--
--
--       OPEN curReturn FOR SELECT 1 FROM DUAL;
--    END UPDATE_AHS_SOTHAM_CAOTRANG_DIEULUAT;
--
--


END PACKAGE_UPDATE_DATA;

/
