--------------------------------------------------------
--  DDL for Package Body PKG_STPT_DELETE_SOTHULY
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_STPT_DELETE_SOTHULY" AS


FUNCTION LICHSU_XOA_SOTHULY_ST
(
  in_MAGIAIDOAN IN NUMBER,
  in_DONID IN NUMBER,
  in_THULYID IN NUMBER,
  in_LOAIANID IN NUMBER,
  in_NGUOIXOAID IN VARCHAR2,
  in_TAIKHOANXOA IN VARCHAR2,
  in_LYDO IN VARCHAR2
  
) RETURN NUMBER AS
	v_ERROR         VARCHAR2(4000):='';
	vMAVUVIEC       VARCHAR2(500):=''; 
    vTENVUVIEC      VARCHAR2(500):='';
    vTENTOAAN       VARCHAR2(500):=''; 
    vTOAAN_ID       number:=null;
    VVUANID         NUMBER;

    VSOTHULY        VARCHAR(25);
    VNGAYTHULY      DATE;

    in_TENCHUCNANG  VARCHAR2(1000):='';
    in_OBJECT       clob;

BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA

    SELECT LOAI_AN_TEN || ' Thụ lý sơ thẩm' INTO in_TENCHUCNANG
    FROM DM_LOAIAN WHERE ID = in_LOAIANID;


    IF (in_LOAIANID = 1) THEN

            SELECT JSON_OBJECT(TL.*), TL.VUANID, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, VSOTHULY, VNGAYTHULY
            FROM AHS_SOTHAM_THULY TL
            WHERE ID = in_THULYID;

            SELECT  D.TOAANID, d.MAVUAN, d.TENVUAN, T.TEN into vTOAAN_ID, vMAVUVIEC, vTENVUVIEC, vTENTOAAN
            FROM AHS_VUAN d 
                LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
        ELSIF (in_LOAIANID = 2) THEN

            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM ADS_SOTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM ADS_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
    ELSIF (in_LOAIANID = 3) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM AHN_SOTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM AHN_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
    ELSIF (in_LOAIANID = 4) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM AKT_SOTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM AKT_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
     ELSIF (in_LOAIANID = 5) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM ALD_SOTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM ALD_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
     ELSIF (in_LOAIANID = 6) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM AHC_SOTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM AHC_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
     ELSIF (in_LOAIANID = 7) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM APS_SOTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM APS_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
    END IF;

	SAVEPOINT P2;

	-- Lưu thong tin co ban Hô so án xoa
    INSERT INTO LICHSU_XOA_SOTHULY 
                   (LOAIAN,MAVUVIEC,TENVUVIEC,TENTOAAN,TOAAN_ID,
                   TAIKHOANXOA,NGUOIXOA,NGAYXOA,NOIDUNG,TENCHUCNANG,HANHDONG,LYDO,NGAYTHULY, SOTHULY, DONID, MAGIAIDOAN) 
            values (in_LOAIANID,vMAVUVIEC,vTENVUVIEC,vTENTOAAN,vTOAAN_ID,
                    in_TAIKHOANXOA,in_NGUOIXOAID,SYSDATE,in_OBJECT,in_TENCHUCNANG,2,in_LYDO, VNGAYTHULY, VSOTHULY, VVUANID,in_MAGIAIDOAN);

	RETURN 1;

EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR ADS: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P2;
	RETURN -1;	

END;

FUNCTION LICHSU_XOA_SOTHULY_PT
(
  in_MAGIAIDOAN IN NUMBER,
  in_DONID IN NUMBER,
  in_THULYID IN NUMBER,
  in_LOAIANID IN NUMBER,
  in_NGUOIXOAID IN VARCHAR2,
  in_TAIKHOANXOA IN VARCHAR2,
  in_LYDO IN VARCHAR2

) RETURN NUMBER AS
	v_ERROR         VARCHAR2(4000):='';
	vMAVUVIEC       VARCHAR2(500):=''; 
    vTENVUVIEC      VARCHAR2(500):='';
    vTENTOAAN       VARCHAR2(500):=''; 
    vTOAAN_ID       number:=null;
    VVUANID         NUMBER;

    VSOTHULY        VARCHAR(25);
    VNGAYTHULY      DATE;

    in_TENCHUCNANG VARCHAR2(1000):='';
    in_OBJECT      clob;

BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA

    SELECT LOAI_AN_TEN || ' Thụ lý phúc thẩm' INTO in_TENCHUCNANG
    FROM DM_LOAIAN WHERE ID = in_LOAIANID;


    IF (in_LOAIANID = 1) THEN

            SELECT TL.TOAANID, JSON_OBJECT(TL.*), TL.VUANID, TL.SOTHULY, TL.NGAYTHULY INTO vTOAAN_ID, in_OBJECT, VVUANID, VSOTHULY, VNGAYTHULY
            FROM AHS_PHUCTHAM_THULY TL
            WHERE ID = in_THULYID;

            SELECT  d.MAVUAN, d.TENVUAN, T.TEN into  vMAVUVIEC, vTENVUVIEC, vTENTOAAN
            FROM AHS_VUAN d 
                LEFT JOIN DM_TOAAN t on t.id = d.TOAPHUCTHAMID
            WHERE d.ID = VVUANID;
        ELSIF (in_LOAIANID = 2) THEN

            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM ADS_PHUCTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM ADS_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
    ELSIF (in_LOAIANID = 3) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM AHN_PHUCTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM AHN_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
    ELSIF (in_LOAIANID = 4) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM AKT_PHUCTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM AKT_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
     ELSIF (in_LOAIANID = 5) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM ALD_PHUCTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM ALD_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
     ELSIF (in_LOAIANID = 6) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM AHC_PHUCTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM AHC_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
     ELSIF (in_LOAIANID = 7) THEN
            SELECT JSON_OBJECT(TL.*), TL.DONID, TL.TOAANID, DMTA.TEN, TL.SOTHULY, TL.NGAYTHULY INTO in_OBJECT, VVUANID, vTOAAN_ID, vTENTOAAN, VSOTHULY, VNGAYTHULY
            FROM APS_PHUCTHAM_THULY TL
                LEFT JOIN DM_TOAAN DMTA ON DMTA.ID = TL.TOAANID
            WHERE TL.ID = in_THULYID;

            SELECT d.MAVUVIEC, d.TENVUVIEC into vMAVUVIEC, vTENVUVIEC
            FROM APS_DON d 
                  LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
            WHERE d.ID = VVUANID;
    END IF;

	SAVEPOINT P1;

	-- Lưu thong tin co ban Hô so án xoa
    INSERT INTO LICHSU_XOA_SOTHULY 
                   (LOAIAN,MAVUVIEC,TENVUVIEC,TENTOAAN,TOAAN_ID,
                   TAIKHOANXOA,NGUOIXOA,NGAYXOA,NOIDUNG,TENCHUCNANG,HANHDONG, NGAYTHULY, SOTHULY, DONID, MAGIAIDOAN, LYDO) 
            values (in_LOAIANID,vMAVUVIEC,vTENVUVIEC,vTENTOAAN,vTOAAN_ID,
                    in_TAIKHOANXOA,in_NGUOIXOAID,SYSDATE,in_OBJECT,in_TENCHUCNANG,2, VNGAYTHULY, VSOTHULY, VVUANID,in_MAGIAIDOAN, in_LYDO);

	RETURN 1;

EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR ADS: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	

END;




END PKG_STPT_DELETE_SOTHULY;

/
