--------------------------------------------------------
--  DDL for Package Body PKG_COVID
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "PKG_COVID" AS
FUNCTION  QT_NGUOIDUNG_SEARCH
( 
  V_DONVIID IN VARCHAR2,
  V_PHONGBANID IN	VARCHAR2,
  V_USERNAME IN VARCHAR2,
  V_HOTEN IN VARCHAR2 
)
RETURN SYS_REFCURSOR
IS 
    V_CURSOR sys_refcursor;
BEGIN
        OPEN V_CURSOR FOR 
            SELECT NULL LOAIUSER,T.TEN_ALIAS TENDONVI,NH.NAME TENNHOMNSD,PB.TENPHONGBAN,NSD.*
            FROM COVID_NGUOISUDUNG NSD
            INNER JOIN COVID_DV_TRUCTHUOC T ON NSD.DV_TRUCTHUOC=T.ID
            LEFT JOIN COVID_DM_CANBO CB ON CB.ID=NSD.CANBOID
            LEFT JOIN COVID_PHONGBAN PB ON PB.ID=CB.PHONGBANID
            LEFT JOIN COVID_NHOM_ND NH ON NH.ID=NSD.NHOM_ND_ID
            WHERE (V_DONVIID IS NULL OR (NSD.DV_TRUCTHUOC=V_DONVIID))
                AND (V_PHONGBANID IS NULL OR CB.PHONGBANID=V_PHONGBANID)
                AND (V_USERNAME IS NULL OR UPPER(NSD.USERNAME) LIKE '%'||UPPER(V_USERNAME)||'%')
                AND (V_HOTEN IS NULL OR ( (UPPER(NSD.HOTEN) LIKE '%'||UPPER(V_HOTEN)||'%')
                                          OR (UPPER(NSD.EMAIL) LIKE '%'||UPPER(V_HOTEN)||'%')
                                          OR (UPPER(NSD.DIENTHOAI) LIKE '%'||UPPER(V_HOTEN)||'%')
                                         )
                  )
               AND UPPER(NSD.USERNAME)!='ADMIN'   
            ORDER BY NSD.USERNAME;
 RETURN  V_CURSOR;   
END QT_NGUOIDUNG_SEARCH;

PROCEDURE DM_CANBO_SEARCH 
(
  vDV_TRUCTHUOC in varchar2,
  vPhongbanID in varchar2,
  vChucDanhID in varchar2,
  vChucVuID in varchar2,
  v_TrangThaiCongTac in varchar2,
  v_KeySearch in varchar2,
  CurrPageIndex in number,
  PageSize in number,
  CurReturn OUT sys_refcursor
) AS
  vmin_stt  number;  vmax_stt  number;vTotal  number;
BEGIN
    vmin_stt := (CurrPageIndex-1)*PageSize + 1;
	vmax_stt := CurrPageIndex*PageSize;
    ------
  OPEN CurReturn FOR
      SELECT D.TT,D.ID,D.MACANBO,D.HOTEN,D.CHUCDANH,D.CHUCVU,D.DONVI_TEN,D.TENPHONGBAN
       ,D.TOTAL,D.TRANGTHAI,D.NGUOITAO,D.NGUOISUA
                FROM 
                (SELECT COUNT(*) OVER()TOTAL,ROW_NUMBER() OVER(ORDER BY SUBSTR(A.HOTEN,INSTR(A.HOTEN,' ',-1)+ 1)) AS TT,A.ID,A.MACANBO,A.HOTEN,
                CD.TEN CHUCDANH,CV.TEN CHUCVU,DV.TEN_ALIAS DONVI_TEN,P.TENPHONGBAN
                ,(CASE A.HIEULUC WHEN 0 THEN u'Ngh\1ec9 c\00f4ng t\00e1c'  WHEN 1 THEN u'\0110ang c\00f4ng t\00e1c'  WHEN 2 THEN u'Ngh\1ec9 ph\00e9p'  WHEN 3 THEN u'D\1eebng x\00e9t x\1eed'  END) TRANGTHAI
                ,A.NGUOITAO,A.NGUOISUA
                FROM COVID_DM_CANBO A
                LEFT JOIN COVID_DV_TRUCTHUOC DV ON DV.ID=A.DV_TRUCTHUOC
                LEFT JOIN COVID_PHONGBAN P ON P.ID=A.PHONGBANID
                LEFT JOIN (SELECT B.ID,B.TEN FROM DM_DATAITEM B WHERE B.GROUPID = 12) CD ON A.CHUCDANHID=CD.ID
                LEFT JOIN (SELECT C.ID,C.TEN FROM DM_DATAITEM C WHERE C.GROUPID = 13) CV ON A.CHUCVUID=CV.ID
                WHERE (vDV_TRUCTHUOC IS NULL OR A.DV_TRUCTHUOC=vDV_TRUCTHUOC)
                AND (vChucDanhID IS NULL OR CD.ID=vChucDanhID)
                AND (vChucVuID IS NULL OR CV.ID=vChucVuID)
                AND (vPhongbanID IS NULL OR A.PHONGBANID=vPhongbanID)
                AND (v_TrangThaiCongTac IS NULL OR A.HIEULUC=v_TrangThaiCongTac)
                AND (v_KeySearch IS NULL 
                   OR(UPPER(A.HOTEN) LIKE '%'||UPPER(v_KeySearch)||'%')
                   OR(UPPER(A.MACANBO) LIKE '%'||UPPER(v_KeySearch)||'%')
                   OR(UPPER(A.DIACHI) LIKE '%'||UPPER(v_KeySearch)||'%')
                 )

       ) D WHERE D.TT BETWEEN VMIN_STT AND VMAX_STT;
END DM_CANBO_SEARCH;
PROCEDURE  DM_DATAITEM_GETBYGROUPNAME
( vGroupName in nvarchar2,
	curReturn    OUT       sys_refcursor
)
IS 
BEGIN
OPEN curReturn FOR  
    SELECT
        i.ID,i.MA,i.TEN,((Case SOCAP WHen 2 then '...' when 3 then '......' else '' End)||i.Ten) MA_TEN
    FROM DM_DATAITEM i
    inner join DM_DATAGROUP g on g.ID=i.GROUPID
    Where g.MA=vGroupName and i.HIEULUC=1
    Order By i.ARRTHUTU;
END DM_DATAITEM_GETBYGROUPNAME;
FUNCTION THONGKE_F_HOTEN
(
  V_CANBOID IN NVARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR
AS
V_CURSOR sys_refcursor; V_EXPORT_TEXT CLOB;  V_EXPORT_TEXT_ITEM CLOB;F0 NUMBER;F1 NUMBER;F2 NUMBER;F3 NUMBER;F4 NUMBER;
BEGIN
     DBMS_LOB.CREATETEMPORARY(V_EXPORT_TEXT,true);     DBMS_LOB.CREATETEMPORARY(V_EXPORT_TEXT_ITEM,true);    
    -----------
     DBMS_LOB.APPEND(V_EXPORT_TEXT,' 
            <ul class="thongke" style="text-align: left;">
      ');              
    FOR item in (
                 SELECT XD.ID,XD.TEN FROM COVID_XD_F XD
                 WHERE EXISTS (SELECT 'X' FROM COVID_DANGKY DK WHERE DK.XACDINH_F=XD.ID AND DK.NGAYTAO>TO_DATE('30/04/2021','dd/MM/yyyy'))
                 ORDER BY XD.ORDERS
                )
     LOOP
            DBMS_LOB.CREATETEMPORARY(V_EXPORT_TEXT_ITEM,true); 
            DBMS_LOB.APPEND(V_EXPORT_TEXT,'<li><span style="color: #ca2020">'||item.id||'</span>: ');  
           FOR item_a IN (SELECT CB.HOTEN||' - '||DV.TEN_ALIAS HOTEN FROM COVID_DANGKY DK 
                            LEFT JOIN COVID_DM_CANBO CB ON CB.ID=DK.CANBOID
                            LEFT JOIN COVID_DV_TRUCTHUOC DV ON DV.ID=CB.DV_TRUCTHUOC
                            WHERE DK.XACDINH_F=item.ID AND DK.NGAYTAO>TO_DATE('30/04/2021','dd/MM/yyyy')
                            GROUP BY CB.HOTEN,DV.TEN_ALIAS
                      )
            LOOP
                DBMS_LOB.APPEND(V_EXPORT_TEXT_ITEM,item_a.HOTEN||', ');  
            END LOOP;
            DBMS_LOB.APPEND(V_EXPORT_TEXT,RTRIM(V_EXPORT_TEXT_ITEM,', ')||'</li>'); 
     END LOOP;
     DBMS_LOB.APPEND(V_EXPORT_TEXT,'</ul>');  
    ----------
    OPEN V_CURSOR FOR
        SELECT V_EXPORT_TEXT TEXT_REPORT FROM dual;
         dbms_lob.freetemporary(V_EXPORT_TEXT);
        dbms_lob.freetemporary(V_EXPORT_TEXT_ITEM);
        RETURN V_CURSOR;  
END THONGKE_F_HOTEN;
FUNCTION THONGKE_F
(
  V_CANBOID IN NVARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR
AS
V_CURSOR sys_refcursor; V_EXPORT_TEXT CLOB; F0 NUMBER;F1 NUMBER;F2 NUMBER;F3 NUMBER;F4 NUMBER;
BEGIN
     DBMS_LOB.CREATETEMPORARY(V_EXPORT_TEXT,true);
     -----------------------
    SELECT COUNT(*) INTO F0 FROM (
             SELECT DK.XACDINH_F,DK.CANBOID FROM COVID_DANGKY DK 
             LEFT JOIN COVID_DM_CANBO CB ON DK.CANBOID=CB.ID
             WHERE DK.XACDINH_F='F0' AND DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy')
             GROUP BY DK.XACDINH_F,DK.CANBOID
          ) DK;
    SELECT COUNT(*) INTO F1 FROM (
             SELECT DK.XACDINH_F,DK.CANBOID FROM COVID_DANGKY DK 
             LEFT JOIN COVID_DM_CANBO CB ON DK.CANBOID=CB.ID
             WHERE DK.XACDINH_F='F1' AND DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy')
             GROUP BY DK.XACDINH_F,DK.CANBOID
          ) DK;
    SELECT COUNT(*) INTO F2 FROM (
             SELECT DK.XACDINH_F,DK.CANBOID FROM COVID_DANGKY DK 
             LEFT JOIN COVID_DM_CANBO CB ON DK.CANBOID=CB.ID
             WHERE DK.XACDINH_F='F2' AND DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy')
             GROUP BY DK.XACDINH_F,DK.CANBOID
          ) DK;
    SELECT COUNT(*) INTO F3 FROM (
             SELECT DK.XACDINH_F,DK.CANBOID FROM COVID_DANGKY DK 
             LEFT JOIN COVID_DM_CANBO CB ON DK.CANBOID=CB.ID
             WHERE DK.XACDINH_F='F3' AND DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy')
             GROUP BY DK.XACDINH_F,DK.CANBOID
          ) DK;
    SELECT COUNT(*) INTO F4 FROM (
             SELECT DK.XACDINH_F,DK.CANBOID FROM COVID_DANGKY DK 
             LEFT JOIN COVID_DM_CANBO CB ON DK.CANBOID=CB.ID
             WHERE DK.XACDINH_F='F4' AND DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy')
             GROUP BY DK.XACDINH_F,DK.CANBOID
          ) DK;
    -----------
     DBMS_LOB.APPEND(V_EXPORT_TEXT,' 
            <ul class="thongke panding_left" style="color: #0d7ce8; text-align: left;">
                <li><span style="color: #000000">F0:</span> '||F0||'</li>
                <li><span style="color: #000000">F1:</span> '||F1||'</li>
                <li><span style="color: #000000">F2:</span> '||F2||'</li>
                <li><span style="color: #000000">F3:</span> '||F3||'</li>
                <li><span style="color: #000000">F4:</span> '||F4||'</li>
           </ul>
        ');  
    ----------
    OPEN V_CURSOR FOR
        SELECT V_EXPORT_TEXT TEXT_REPORT FROM dual;
         dbms_lob.freetemporary(V_EXPORT_TEXT);
        RETURN V_CURSOR;  
END THONGKE_F;
FUNCTION COVID_DANGKY_DS 
(
  V_CANBOID IN NVARCHAR2 DEFAULT NULL,
  PageIndex	in	NUMBER,
  PageSize	in	NUMBER
)
RETURN SYS_REFCURSOR
AS
      MININDEX	number;  MAXINDEX	number;
      V_CURSOR sys_refcursor;
begin
  MININDEX := pagesize*(PAGEINDEX - 1) + 1;
  MAXINDEX := PAGEINDEX*pagesize ;
  OPEN v_cursor FOR
 select DS.* from (
                SELECT COUNT(*) OVER()COUNTALL,ROW_NUMBER() OVER (ORDER BY DK.NGAYTAO DESC) STT
                ,TO_CHAR(DK.NGAYTAO,'dd/MM/yyyy HH24:MI:SS') NGAYTAO,TO_CHAR(DK.NGAYSUA,'dd/MM/yyyy HH24:MI:SS') NGAYSUA,DK.NGUOITAO,DECODE(DK.TIEPXUCGAN_BN,0,'Không',1,'Có')TIEPXUCGAN_BN
                ,DECODE(DK.SOT,0,'Không','Có')SOT,DK.GHICHU
                ,( DECODE(TO_CHAR(DK.CACHLY_TUNGAY,'dd/MM/yyyy'),'01/01/0001',NULL,'Từ ngày '||TO_CHAR(DK.CACHLY_TUNGAY,'dd/MM/yyyy'))
                ||DECODE(TO_CHAR(DK.CACHLY_DENGAY,'dd/MM/yyyy'),'01/01/0001',NULL,'<br/> Đến ngày '||TO_CHAR(DK.CACHLY_DENGAY,'dd/MM/yyyy')) )TIME_CACHLY
                FROM COVID_DANGKY DK
                 INNER JOIN COVID_DM_CANBO CB ON CB.ID=DK.CANBOID  
                 LEFT JOIN COVID_DV_TRUCTHUOC TT ON TT.ID=CB.DV_TRUCTHUOC
                 LEFT JOIN COVID_PHONGBAN PB ON PB.ID=CB.PHONGBANID
                 --LEFT JOIN COVID_NGUOISUDUNG ND ON CO.CANBOID=ND.CANBOID
                WHERE (V_CANBOID IS NULL OR DK.CANBOID=V_CANBOID)  AND DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy')
        ) DS WHERE DS.STT>=MININDEX AND DS.STT<=MAXINDEX;
    RETURN v_cursor;   
END COVID_DANGKY_DS;
PROCEDURE GET_NHOMQUYEN_ID
(    
  V_ID	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
     SELECT NQ.* FROM COVID_NHOM_ND NQ
     WHERE NQ.ID=V_ID;
END;
PROCEDURE GET_ALL_NHOMQUYEN
(    
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
     SELECT NQ.* FROM COVID_NHOM_ND NQ ORDER BY NQ.ID DESC;
END;
PROCEDURE GET_BY_USERNAME
(    
  V_USERNAME	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
     SELECT ND.* FROM COVID_NGUOISUDUNG ND   WHERE ND.USERNAME=V_USERNAME;
END;
PROCEDURE GET_USERBYID
(    
  V_USERID	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
     SELECT ND.USERNAME,CB.HOTEN,CB.SODIENTHOAI,CB.EMAIL,CB.DIACHI,CB.DONVI_ID
     ,CB.DV_TRUCTHUOC,CB.PHONGBANID,ND.NHOM_ND_ID,ND.CANBOID,ND.HIEULUC
      FROM COVID_NGUOISUDUNG ND
     LEFT JOIN COVID_DM_CANBO CB ON CB.ID=ND.CANBOID
     WHERE ND.ID=V_USERID;
END;
PROCEDURE GET_DONVI_FULL
(    
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
       OPEN CurReturn FOR
        SELECT TA.ID,REPLACE(TA.MA_TEN,'Tòa án nhân dân')MA_TEN,TA.ARRTHUTU FROM DM_TOAAN TA
        WHERE TA.LOAITOA IN('CAPHUYEN') AND TA.HIEULUC=1
        ORDER BY TA.ARRTHUTU;
END;
PROCEDURE GET_PHONGBAN
(    
  V_TRUCTHUOC_ID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
       OPEN CurReturn FOR
        SELECT PB.* FROM COVID_PHONGBAN PB 
        WHERE (V_TRUCTHUOC_ID IS NULL OR PB.TRUCTHUOC_ID=V_TRUCTHUOC_ID);
END;
PROCEDURE GET_DV_TRUCTHUOC
(    
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
       OPEN CurReturn FOR
        SELECT DV.* FROM COVID_DV_TRUCTHUOC DV;
END;
PROCEDURE GET_CANBO_MA
(    
  V_MACANBO	IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
      SELECT CB.* FROM COVID_DM_CANBO CB
      WHERE CB.MACANBO=V_MACANBO;
END;
PROCEDURE GET_CANBO_ID
(    
  V_ID	IN	NUMBER,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
      SELECT CB.* FROM COVID_DM_CANBO CB  WHERE CB.ID=V_ID;
END;
PROCEDURE GET_CANBO_DV_PB
(    
  V_DV_TRUCTHUOC	IN	VARCHAR2,
  V_PHONGBANID IN	VARCHAR2,
  CurReturn OUT sys_refcursor 
)
AS  
BEGIN  
     OPEN CurReturn FOR
      SELECT CB.* FROM COVID_DM_CANBO CB  WHERE CB.DV_TRUCTHUOC=V_DV_TRUCTHUOC AND CB.HIEULUC=1 AND CB.HIEULUC IS NOT NULL
      AND (V_PHONGBANID IS NULL OR CB.PHONGBANID=V_PHONGBANID);
END;
PROCEDURE DELETE_CANBO_ID
(    
  V_ID	IN	NUMBER,
  V_THONGBAO OUT VARCHAR2
)
AS  
   COUNT_CANBO NUMBER;V_USERNAME_LIST VARCHAR2(1000);
BEGIN  
     SELECT COUNT(*)INTO COUNT_CANBO FROM COVID_NGUOISUDUNG ND WHERE ND.CANBOID=V_ID;
     IF(COUNT_CANBO>0) THEN
        SELECT LISTAGG(ND.USERNAME, ',')  WITHIN GROUP (ORDER BY ND.ID) INTO V_USERNAME_LIST  
        FROM COVID_NGUOISUDUNG ND
        WHERE ND.CANBOID=V_ID;
        V_THONGBAO:='Đã tồn tại tài khoản người dùng: (<b>'||V_USERNAME_LIST||'</b>), bạn phải xóa tài khoản người dùng trước.';
     ELSE
         DELETE COVID_DM_CANBO CB  WHERE CB.ID=V_ID;
     END IF;
END;
PROCEDURE DELETE_NGUOIDUNG_ID
(    
  V_ID	IN	NUMBER,
  V_THONGBAO OUT VARCHAR2
)
AS  
   COUNT_USER NUMBER;V_USERNAME_LIST VARCHAR2(1000);COUNT_QUANTRI NUMBER;
BEGIN  
     SELECT COUNT(*)INTO COUNT_QUANTRI FROM COVID_NGUOISUDUNG NSD WHERE NSD.NHOM_ND_ID=1 AND NSD.ID=V_ID;
     SELECT COUNT(*)INTO COUNT_USER FROM COVID_NGUOISUDUNG NSD 
     WHERE EXISTS (SELECT 'X' FROM COVID_DANGKY DK WHERE DK.NGUOITAO=NSD.USERNAME) AND NSD.ID=V_ID;
   IF(COUNT_QUANTRI>0) THEN
     V_THONGBAO:='Là tài khoản thuộc nhóm quản trị hệ thống, bạn không thể xóa!';
    ELSIF(COUNT_QUANTRI=0) THEN
         IF(COUNT_USER>0) THEN
            V_THONGBAO:='Tài khoản này đã được sử dụng để khai báo y tế, bạn không thể xóa, hãy liên hệ với quản trị.';
         ELSE
             DELETE COVID_NGUOISUDUNG NSD  WHERE NSD.ID=V_ID;
         END IF;
   END IF;  
END;
PROCEDURE USERS_CHANGE_PASSWORD
(    
  V_USERNAME	IN	VARCHAR2,
  V_PASSWORD IN	VARCHAR2
)
AS  
BEGIN  
      UPDATE COVID_NGUOISUDUNG
      SET                   
        PASSWORD=V_PASSWORD,NGUOISUA=V_USERNAME,NGAYSUA=sysdate
      WHERE USERNAME=V_USERNAME;      
END;
PROCEDURE USERS_CHANGE_PASSWORD_BYID
(    
  V_ID	IN	VARCHAR2,
  V_USERNAME	IN	VARCHAR2,
  V_PASSWORD IN	VARCHAR2
)
AS  
BEGIN  
      UPDATE COVID_NGUOISUDUNG
      SET                   
        PASSWORD=V_PASSWORD,NGUOISUA=V_USERNAME,NGAYSUA=sysdate
      WHERE ID=V_ID;      
END;
PROCEDURE UPDATE_USER_INFOR
(    
  V_CANBO_ID	IN	VARCHAR2,
  V_SODIENTHOAI IN	VARCHAR2,
  V_EMAIL  IN	VARCHAR2,
  V_DONVI_ID      IN	VARCHAR2,
  V_DIACHI      IN	VARCHAR2
)
AS  
BEGIN 
     UPDATE COVID_DM_CANBO
     SET SODIENTHOAI=V_SODIENTHOAI,EMAIL=V_EMAIL,DONVI_ID=V_DONVI_ID,DIACHI=V_DIACHI
     WHERE ID=V_CANBO_ID;
    -------
    UPDATE COVID_NGUOISUDUNG
      SET DIENTHOAI=V_SODIENTHOAI,EMAIL=V_EMAIL
    WHERE CANBOID=V_CANBO_ID;  
END;
PROCEDURE COVID_NGUOIDUNG_INS_UP
(
    V_ID	IN	NUMBER,
    V_USERNAME	IN	VARCHAR2,
    V_PASSWORD	IN	VARCHAR2,
    V_HOTEN	IN	VARCHAR2,
    V_CANBOID	IN	NUMBER,
    V_HIEULUC	IN	NUMBER,
    V_DIENTHOAI	IN	VARCHAR2,
    V_EMAIL	IN	VARCHAR2,
    V_NGUOITAO	IN	VARCHAR2,
    V_NGAYTAO	IN	DATE,
    V_NHOM_ND_ID	IN	NUMBER,
    V_DV_TRUCTHUOC	IN	NUMBER,
    V_PHONGBANID	IN	NUMBER,
    V_THONGBAO OUT VARCHAR2
)
AS
            V_COUNT_USER NUMBER;
BEGIN 
    IF v_ID=0 THEN
      SELECT COUNT(*) INTO V_COUNT_USER FROM COVID_NGUOISUDUNG ND WHERE ND.USERNAME=V_USERNAME;
        IF(V_COUNT_USER=0) THEN
              INSERT INTO COVID_NGUOISUDUNG
               (ID,USERNAME,PASSWORD,HOTEN,DONVIID,CANBOID,HIEULUC,DIENTHOAI,EMAIL,NGUOITAO,NGAYTAO,NGUOISUA,NGAYSUA
               ,NOT_IN_PMQLCB,NHOM_ND_ID,DV_TRUCTHUOC,PHONGBANID)
             VALUES  (COVID_NGUOISUDUNG_SEQ.NEXTVAL,V_USERNAME,V_PASSWORD,V_HOTEN,1,V_CANBOID,V_HIEULUC,V_DIENTHOAI,V_EMAIL,V_NGUOITAO,sysdate,V_NGUOITAO,sysdate
               ,1,V_NHOM_ND_ID,V_DV_TRUCTHUOC,V_PHONGBANID);
        ELSE
          V_THONGBAO:='Tài khoản này đã tồn tại, bạn phải chọn tài khoản khác.';
        END IF;
     ELSE 
          UPDATE COVID_NGUOISUDUNG
            SET  
                HOTEN= V_HOTEN,
                CANBOID= V_CANBOID,
                HIEULUC= V_HIEULUC,
                DIENTHOAI= V_DIENTHOAI,
                EMAIL= V_EMAIL,
                NGUOISUA= V_NGUOITAO,
                NGAYSUA= V_NGAYTAO,
                NHOM_ND_ID= V_NHOM_ND_ID,
                DV_TRUCTHUOC= V_DV_TRUCTHUOC,
                PHONGBANID= V_PHONGBANID
            WHERE ID=v_ID;
     END IF;     
END COVID_NGUOIDUNG_INS_UP;
PROCEDURE COVID_DM_CANBO_INS_UP
    (
        v_ID	in	NUMBER,
        v_TOAANID	in	NUMBER,
        v_MACANBO	in	VARCHAR2,
        v_HOTEN	in	VARCHAR2,
        v_SOCMND	in	VARCHAR2,
        v_HIEULUC	in	NUMBER,
        v_CHUCDANHID	in	NUMBER,
        v_CHUCVUID	in	NUMBER,
        v_DIACHI	in	VARCHAR2,
        v_NGAYNHANCONGTAC	in	DATE,
        v_NGAYSINH	in	DATE,
        v_SODIENTHOAI	in	VARCHAR2,
        v_NGAYTAO	in	DATE,
        v_NGUOITAO	in	VARCHAR2,
        v_NGAYBONHIEM	in	DATE,
        v_NGAYKETTHUC	in	DATE,
        v_GIOITINH	in	NUMBER,
        v_PHONGBANID	in	NUMBER,
        v_DV_TRUCTHUOC	in	NUMBER
    )
AS
BEGIN 
     IF v_ID=0 THEN
       INSERT INTO COVID_DM_CANBO
         (ID,TOAANID,MACANBO,HOTEN,SOCMND,HIEULUC,CHUCDANHID,CHUCVUID,DIACHI,NGAYSINH,SODIENTHOAI,
            NGAYTAO,NGUOITAO,NGAYSUA,NGUOISUA,NGAYBONHIEM,NGAYKETTHUC,GIOITINH,PHONGBANID,DV_TRUCTHUOC,NOT_IN_PMQLCB)--NOT_IN_PMQLCB =1 là những cán bộ không có trong pm quản lý cán bộ
         VALUES (COVID_DM_CANBO_SEQ.NEXTVAL,V_TOAANID,V_MACANBO,V_HOTEN,V_SOCMND,V_HIEULUC,V_CHUCDANHID,V_CHUCVUID,V_DIACHI,V_NGAYSINH,V_SODIENTHOAI,
            sysdate,V_NGUOITAO,sysdate,V_NGUOITAO,V_NGAYBONHIEM,V_NGAYKETTHUC,V_GIOITINH,V_PHONGBANID,V_DV_TRUCTHUOC,1);
     ELSE 
          UPDATE COVID_DM_CANBO
            SET    
                MACANBO=v_MACANBO,
                HOTEN=v_HOTEN,
                SOCMND=v_SOCMND,
                HIEULUC=v_HIEULUC,
                CHUCDANHID=v_CHUCDANHID,
                CHUCVUID=v_CHUCVUID,
                DIACHI=v_DIACHI,
                NGAYNHANCONGTAC=v_NGAYNHANCONGTAC,
                NGAYSINH=v_NGAYSINH,
                SODIENTHOAI=v_SODIENTHOAI,
                NGAYSUA=sysdate,
                NGUOISUA=v_NGUOITAO,
                NGAYBONHIEM=v_NGAYBONHIEM,
                NGAYKETTHUC=v_NGAYKETTHUC,
                GIOITINH=v_GIOITINH,
                PHONGBANID=v_PHONGBANID,
                DV_TRUCTHUOC=v_DV_TRUCTHUOC
            WHERE ID=v_ID;
     END IF;   
END COVID_DM_CANBO_INS_UP;
PROCEDURE COVID_DANGKY_INS_UP
    (
    V_ID	        IN	NUMBER,
    V_CANBOID	    IN	NUMBER,
    V_TOAANID	    IN	NUMBER,
    V_DV_TRUCTHUOC	IN	NUMBER,
    V_PHONGBANID	IN	NUMBER,
    V_SOT	        IN	NUMBER,
    V_HO	        IN	NUMBER,
    V_KHO_THO	    IN	NUMBER,
    V_DAU_HONG	    IN	NUMBER,
    V_NON_BUON_NON	IN	NUMBER,
    V_TIEU_CHAY	    IN	NUMBER,
    V_XUAT_HUYET_ND	IN	NUMBER,
    V_NOIBAN_ND	    IN	NUMBER,
    V_TIEPXUCGAN_BN	IN	NUMBER,
    V_XACDINH_F	    IN	VARCHAR2,
    V_TT_CACHLY     IN VARCHAR2,
    V_CACHLY_TUNGAY IN DATE,
    V_CACHLY_DENGAY IN DATE,
    V_LICHSU	    IN	VARCHAR2,
    V_GHICHU	    IN	VARCHAR2,
    V_NGUOITAO	    IN	VARCHAR2,
    V_NGUOISUA	    IN	VARCHAR2,
    V_SODIENTHOAI   IN	VARCHAR2,
    V_EMAIL         IN	VARCHAR2,
    V_DONVI_ID      IN	VARCHAR2,
    V_DIACHI      IN	VARCHAR2
    )
AS
    V_COUNTS NUMBER;V_ID_S NUMBER;
BEGIN 
    IF(V_SODIENTHOAI IS NOT NULL) THEN
        UPDATE COVID_DM_CANBO
        SET SODIENTHOAI=V_SODIENTHOAI
        WHERE ID=V_CANBOID;
        -------
        UPDATE COVID_NGUOISUDUNG
          SET DIENTHOAI=V_SODIENTHOAI
        WHERE CANBOID=V_CANBOID;  
    END IF;
     IF(V_EMAIL IS NOT NULL) THEN
        UPDATE COVID_DM_CANBO
        SET EMAIL=V_EMAIL
        WHERE ID=V_CANBOID;
         -------
        UPDATE COVID_NGUOISUDUNG
          SET EMAIL=V_EMAIL
        WHERE CANBOID=V_CANBOID;  
    END IF;
    IF(V_DIACHI IS NOT NULL) THEN
        UPDATE COVID_DM_CANBO
        SET DIACHI=V_DIACHI
        WHERE ID=V_CANBOID;
    END IF;
    ---
    UPDATE COVID_DM_CANBO
    SET DONVI_ID=V_DONVI_ID
    WHERE ID=V_CANBOID;
    --------------
     SELECT COUNT(*) INTO V_COUNTS FROM COVID_DANGKY DK WHERE DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy') 
      and DK.CANBOID=v_CANBOID AND TO_CHAR(DK.NGAYTAO,'dd/MM/yyyy')=TO_CHAR(SYSDATE,'dd/MM/yyyy') ;   
    --------------
    IF(v_ID=0) THEN  
      IF(V_COUNTS=0) THEN
        INSERT INTO COVID_DANGKY
          (ID,CANBOID,TOAANID,DV_TRUCTHUOC,PHONGBANID,SOT,HO,KHO_THO,DAU_HONG,NON_BUON_NON,TIEU_CHAY,XUAT_HUYET_ND,
          NOIBAN_ND,TIEPXUCGAN_BN,XACDINH_F,TT_CACHLY,CACHLY_TUNGAY,CACHLY_DENGAY,LICHSU,GHICHU,NGUOITAO,NGAYTAO,NGUOISUA,NGAYSUA)
        VALUES (COVID_DANGKY_SEQ.NEXTVAL,v_CANBOID,v_TOAANID,v_DV_TRUCTHUOC,v_PHONGBANID,v_SOT,v_HO,v_KHO_THO,v_DAU_HONG,v_NON_BUON_NON,v_TIEU_CHAY,v_XUAT_HUYET_ND,
          v_NOIBAN_ND,v_TIEPXUCGAN_BN,v_XACDINH_F,V_TT_CACHLY,V_CACHLY_TUNGAY,V_CACHLY_DENGAY,v_LICHSU,v_GHICHU,v_NGUOITAO,sysdate,v_NGUOISUA,sysdate);
       ELSE
      --V_ID_S
         SELECT DK.ID INTO V_ID_S FROM COVID_DANGKY DK WHERE DK.NGAYTAO>=TO_DATE('30/04/2021','dd/MM/yyyy') 
         and DK.CANBOID=v_CANBOID AND TO_CHAR(DK.NGAYTAO,'dd/MM/yyyy')=TO_CHAR(SYSDATE,'dd/MM/yyyy');
         UPDATE COVID_DANGKY
         SET 
         SOT=v_SOT,
         HO=v_HO,
         KHO_THO=v_KHO_THO,
         DAU_HONG=v_DAU_HONG,
         NON_BUON_NON=v_NON_BUON_NON,
         TIEU_CHAY=v_TIEU_CHAY,
         XUAT_HUYET_ND=v_XUAT_HUYET_ND,
         NOIBAN_ND=v_NOIBAN_ND,
         TIEPXUCGAN_BN=v_TIEPXUCGAN_BN,
         XACDINH_F=v_XACDINH_F,
         TT_CACHLY=v_TT_CACHLY,
         CACHLY_TUNGAY=v_CACHLY_TUNGAY,
         CACHLY_DENGAY=v_CACHLY_DENGAY,
         LICHSU=v_LICHSU,
         GHICHU=v_GHICHU,
         NGUOISUA=v_NGUOISUA,
         NGAYSUA=sysdate
         WHERE ID=V_ID_S;
      END IF;
    ELSE
         null;
    END IF;
END COVID_DANGKY_INS_UP;
PROCEDURE  USER_LOGIN
(
  V_USERNAME in VARCHAR2,
  V_PASSWORD in VARCHAR2,
  CurReturn OUT sys_refcursor 
) 
AS 
BEGIN
       open CurReturn for
           SELECT ND.ID USERID,ND.USERNAME,CB.ID CANBO_ID,CB.HOTEN,TT.ID DV_TRUCTHUOID,TT.TEN_ALIAS DV_TRUCTHUOC_TEN
           ,PB.ID PHONGBANID,PB.TENPHONGBAN,CB.SODIENTHOAI,CB.EMAIL ,ND.NHOM_ND_ID
           FROM COVID_NGUOISUDUNG ND
           LEFT JOIN COVID_DM_CANBO CB ON CB.ID=ND.CANBOID  
           LEFT JOIN COVID_DV_TRUCTHUOC TT ON TT.ID=CB.DV_TRUCTHUOC
           LEFT JOIN COVID_PHONGBAN PB ON PB.ID=CB.PHONGBANID
           WHERE LOWER(ND.USERNAME)=LOWER(V_USERNAME) AND ND.PASSWORD=LOWER(V_PASSWORD)
           AND ND.HIEULUC=1;
END USER_LOGIN;
END PKG_COVID;
