--------------------------------------------------------
--  DDL for Package Body PKG_MIENANPHI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "GSCM"."PKG_MIENANPHI" 
AS
-- Package body
	
	PROCEDURE UPSERT_MIENANPHI(
		N_ID  			IN NUMBER,
		N_ANPHI_ID 		IN NUMBER,
		N_DONID 		IN NUMBER,
		N_LOAIAN 		IN NUMBER,
		V_LYDO 			IN VARCHAR2,
		V_NGUOITAO 		IN NVARCHAR2,
		D_NGAYTAO 		IN DATE,
		V_NGUOISUA 		IN NVARCHAR2, 
		D_NGAYSUA 		IN DATE,
		N_SOTHONGBAO 	IN NVARCHAR2,
		D_NGAYTHONGBAO 	IN DATE,
		V_STB_PHU 		IN VARCHAR2,
		OUT_ID OUT NUMBER
	) 
	AS
		ID_NEW NUMBER;
		ID_UPDATE NUMBER;
	BEGIN 
		IF (N_ID IS NULL OR N_ID = 0) THEN
			SELECT DON_MIENANPHI_SEQ.NEXTVAL INTO ID_NEW FROM DUAL;

			INSERT INTO
				DON_MIENANPHI (ID,
				ANPHI_ID,
				DONID,
				LOAIAN,
				LYDO,
				NGUOITAO,
				NGAYTAO,
				NGUOISUA,
				NGAYSUA,
				SOTHONGBAO,
				NGAYTHONGBAO,
				STB_PHU)
				VALUES(ID_NEW,
				N_ANPHI_ID,
				N_DONID,
				N_LOAIAN,
				V_LYDO,
				V_NGUOITAO,
				D_NGAYTAO,
				V_NGUOISUA,
				D_NGAYSUA,
				N_SOTHONGBAO,
				D_NGAYTHONGBAO,
				V_STB_PHU);
			OUT_ID := ID_NEW;	
		ELSE
			ID_UPDATE := N_ID;
			UPDATE DON_MIENANPHI
				SET 
				ANPHI_ID = N_ANPHI_ID,
				DONID = N_DONID,
				LOAIAN = N_LOAIAN,
				LYDO = V_LYDO,
				NGUOISUA = V_NGUOISUA,
				NGAYSUA = D_NGAYSUA,
				SOTHONGBAO = N_SOTHONGBAO,
				NGAYTHONGBAO = D_NGAYTHONGBAO,
				STB_PHU = V_STB_PHU
			WHERE ID = ID_UPDATE;
			OUT_ID := ID_UPDATE;
		END IF;
	END UPSERT_MIENANPHI;

	PROCEDURE GET_DON_MIENANPHI_BY_ID(
		N_ID IN NUMBER,
		curReturn OUT sys_refcursor
	)
	AS
	BEGIN
		OPEN curReturn FOR
		SELECT * FROM DON_MIENANPHI dm WHERE dm.ID = N_ID;
	END GET_DON_MIENANPHI_BY_ID;

	PROCEDURE GET_DON_MIENANPHI_BY_ANPHI_ID(
		N_ANPHI_ID IN NUMBER,
		N_LOAIAN IN NUMBER,
		curReturn OUT sys_refcursor
	)
	AS
	BEGIN
		OPEN curReturn FOR
		SELECT * FROM DON_MIENANPHI dm WHERE dm.ANPHI_ID = N_ANPHI_ID AND dm.LOAIAN = N_LOAIAN;
	END GET_DON_MIENANPHI_BY_ANPHI_ID;

	PROCEDURE DELETE_MIENANPHI_BY_ID (
		N_ID IN NUMBER
	)
	AS
	BEGIN
		DELETE FROM DON_MIENANPHI WHERE ID = N_ID;
	END DELETE_MIENANPHI_BY_ID;


END PKG_MIENANPHI;

/
