--------------------------------------------------------
--  DDL for Package Body PKG_TUPHAP_ANPHI_JOB
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_TUPHAP_ANPHI_JOB" AS
PROCEDURE GET_SOLUONG_JOB
 IS
    V_CURSOR sys_refcursor;
    MA_LOAIAN  VARCHAR2(512);TEN_LOAIAN  VARCHAR2(512);COUNT_DANOP NUMBER;COUNT_CHUANOP NUMBER;               
    TIEN_DANOP NUMBER;TIEN_CHUANOP NUMBER;VUVIEC_HOANTRA NUMBER;TIEN_HOANTRA NUMBER;COUNT_DINHCHI NUMBER;                     
    TIEN_DINHCHI  NUMBER;DONVITHA_ID NUMBER; 
 BEGIN
     DELETE TUPHAP_ANPHI_TOTAL 
      WHERE  CREATE_DATE<=SYSDATE-2;
    COMMIT;
     V_CURSOR:=PKG_TUPHAP_ANPHI_JOB.GET_SOLUONG_CREATE_DATA(null);
      LOOP 
       FETCH V_CURSOR --chạy từng dòng dữ liệu gán vào các biến
          INTO MA_LOAIAN,TEN_LOAIAN,COUNT_DANOP,COUNT_CHUANOP,TIEN_DANOP
          ,TIEN_CHUANOP,VUVIEC_HOANTRA,TIEN_HOANTRA,COUNT_DINHCHI,TIEN_DINHCHI,DONVITHA_ID;
          EXIT WHEN V_CURSOR%NOTFOUND;
           insert into TUPHAP_ANPHI_TOTAL
                        (MA_LOAIAN,TEN_LOAIAN,COUNT_DANOP,COUNT_CHUANOP,TIEN_DANOP
                               ,TIEN_CHUANOP,VUVIEC_HOANTRA,TIEN_HOANTRA,COUNT_DINHCHI,TIEN_DINHCHI,DONVITHA_ID,CREATE_DATE,CREATE_USER)
                        values 
                        (MA_LOAIAN,TEN_LOAIAN,COUNT_DANOP,COUNT_CHUANOP,TIEN_DANOP
                               ,TIEN_CHUANOP,VUVIEC_HOANTRA,TIEN_HOANTRA,COUNT_DINHCHI,TIEN_DINHCHI,DONVITHA_ID,SYSDATE,'JOB_HETHONG');
                       COMMIT;          
         END LOOP;
      CLOSE V_CURSOR;
 END GET_SOLUONG_JOB;
 PROCEDURE GET_SOLUONG_JOB_APP
    (
     V_USERNAME IN VARCHAR2 DEFAULT NULL,
     V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
    )
 IS
    V_CURSOR sys_refcursor;
    MA_LOAIAN  VARCHAR2(512);TEN_LOAIAN  VARCHAR2(512);COUNT_DANOP NUMBER;COUNT_CHUANOP NUMBER;               
    TIEN_DANOP NUMBER;TIEN_CHUANOP NUMBER;VUVIEC_HOANTRA NUMBER;TIEN_HOANTRA NUMBER;COUNT_DINHCHI NUMBER;                     
    TIEN_DINHCHI  NUMBER;DONVITHA_ID NUMBER;V_LOAITOA VARCHAR2(150):=NULL;VV_USERNAME  VARCHAR2(512);
 BEGIN

     DELETE TUPHAP_ANPHI_TOTAL 
      WHERE (V_DONVITHA_ID is null or DONVITHA_ID=V_DONVITHA_ID) AND CREATE_DATE<=SYSDATE-2;
    COMMIT;
    ----------------------
     IF(V_DONVITHA_ID IS NOT NULL) THEN
        SELECT THA.LOAITOA INTO V_LOAITOA FROM DM_DONVITHIHANHAN THA WHERE THA.ID=V_DONVITHA_ID;
      END IF;
      if(V_LOAITOA='TOICAO')THEN
          VV_USERNAME:='JOB_HETHONG';
        ELSE
          VV_USERNAME:=V_USERNAME;
      END IF;
     ---------------------
     V_CURSOR:=PKG_TUPHAP_ANPHI_JOB.GET_SOLUONG_CREATE_DATA(V_DONVITHA_ID);
      LOOP 
       FETCH V_CURSOR --chạy từng dòng dữ liệu gán vào các biến
          INTO MA_LOAIAN,TEN_LOAIAN,COUNT_DANOP,COUNT_CHUANOP,TIEN_DANOP
          ,TIEN_CHUANOP,VUVIEC_HOANTRA,TIEN_HOANTRA,COUNT_DINHCHI,TIEN_DINHCHI,DONVITHA_ID;
          EXIT WHEN V_CURSOR%NOTFOUND;
           insert into TUPHAP_ANPHI_TOTAL
                        (MA_LOAIAN,TEN_LOAIAN,COUNT_DANOP,COUNT_CHUANOP,TIEN_DANOP
                               ,TIEN_CHUANOP,VUVIEC_HOANTRA,TIEN_HOANTRA,COUNT_DINHCHI,TIEN_DINHCHI,DONVITHA_ID,CREATE_DATE,CREATE_USER)
                        values 
                        (MA_LOAIAN,TEN_LOAIAN,COUNT_DANOP,COUNT_CHUANOP,TIEN_DANOP
                               ,TIEN_CHUANOP,VUVIEC_HOANTRA,TIEN_HOANTRA,COUNT_DINHCHI,TIEN_DINHCHI,DONVITHA_ID,SYSDATE,VV_USERNAME);
                       COMMIT;          
         END LOOP;
      CLOSE V_CURSOR;
 END GET_SOLUONG_JOB_APP;
FUNCTION GET_SOLUONG_CREATE_DATA
(
V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR
AS
       v_cursor SYS_REFCURSOR;V_COUNT_ALL NUMBER;V_COUNT_CHUANOP NUMBER;V_COUNT_DANOP NUMBER;
       V_TIEN_ALL NUMBER;V_TIEN_DANOP NUMBER;V_TIEN_CHUANOP NUMBER;V_TIEN_HOANTRA NUMBER:=0;V_VUVIEC_HOANTRA NUMBER:=0;
       V_EXPORT_TEXT CLOB; v_table T_TUPHAP_ANPHI_TOTAL;V_LOAITOA VARCHAR2(150):=NULL;
       V_COUNT_DINHCHI NUMBER;V_TIEN_DINHCHI NUMBER;
BEGIN
         DBMS_LOB.createtemporary(V_EXPORT_TEXT,TRUE);    
          v_table := T_TUPHAP_ANPHI_TOTAL(); --dung bang ding nghia-
          -----------------------------
        IF(V_DONVITHA_ID IS NOT NULL) THEN
        SELECT THA.LOAITOA INTO V_LOAITOA FROM DM_DONVITHIHANHAN THA WHERE THA.ID=V_DONVITHA_ID;
      END IF;
          ----------------------
          FOR item_tp IN 
            (
             SELECT COUNT(*) VUVIEC_HOANTRA,SUM(TA.ANPHIHOANTRA)ANPHIHOANTRA,THA.ID DONVITHA_ID
                FROM ADS_TONGDAT TD 
                INNER JOIN ADS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ADS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ADS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID
                INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ADS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN (SELECT QD.DONID FROM ADS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                LEFT JOIN DVCQG_THANH_TOAN TT ON tt.DUONGSU_ID=AI.DUONGSU_ID AND TT.MALOAIVUVIEC='2'
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID AND TA.DUONGSU_ID=TT.DUONGSU_ID 
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TA.ANPHIHOANTRA !=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381) 
                AND AI.TAMUNGANPHI !=0
                GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '2','Dân sự',0,0,0,0,item_tp.VUVIEC_HOANTRA,item_tp.ANPHIHOANTRA,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
         FOR item_tp IN 
            (
             SELECT COUNT(*) COUNT_DANOP,SUM(AI.TAMUNGANPHI)TIEN_DANOP,THA.ID DONVITHA_ID
             FROM ADS_TONGDAT TD 
                INNER JOIN ADS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ADS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ADS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID
                INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ADS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN (SELECT QD.DONID FROM ADS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                LEFT JOIN DVCQG_THANH_TOAN TT ON tt.DUONGSU_ID=AI.DUONGSU_ID  AND TT.MALOAIVUVIEC='2'
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID AND TA.DUONGSU_ID=TT.DUONGSU_ID 
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                 AND TT.TRANGTHAITHANHTOAN=1  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                 AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '2','Dân sự',item_tp.COUNT_DANOP,0,item_tp.TIEN_DANOP,0,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
              SELECT COUNT(*)COUNT_DINHCHI,SUM(AI.TAMUNGANPHI)TIEN_DINHCHI,THA.ID DONVITHA_ID
             FROM ADS_TONGDAT TD 
                INNER JOIN ADS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ADS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ADS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                 INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID
                INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ADS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                INNER JOIN (SELECT QD.DONID FROM ADS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                LEFT JOIN DVCQG_THANH_TOAN TT ON tt.DUONGSU_ID=AI.DUONGSU_ID AND TT.MALOAIVUVIEC='2'
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID AND TA.DUONGSU_ID=TT.DUONGSU_ID 
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '2','Dân sự',0,0,0,0,0,0,
        item_tp.COUNT_DINHCHI,item_tp.TIEN_DINHCHI,item_tp.DONVITHA_ID
        );  
    END LOOP;
     FOR item_tp IN 
            (
              SELECT COUNT(*) COUNT_CHUANOP,SUM(AI.TAMUNGANPHI)TIEN_CHUANOP ,THA.ID DONVITHA_ID
             FROM ADS_TONGDAT TD 
                INNER JOIN ADS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ADS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ADS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                 INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID
                INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ADS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN (SELECT QD.DONID FROM ADS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi    
                LEFT JOIN DVCQG_THANH_TOAN TT ON tt.DUONGSU_ID=AI.DUONGSU_ID AND TT.MALOAIVUVIEC='2'
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID AND TA.DUONGSU_ID=TT.DUONGSU_ID 
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                 AND TT.TRANGTHAITHANHTOAN=0  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381) 
                 AND AI.TAMUNGANPHI !=0
                  GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '02','Dân sự',0,item_tp.COUNT_CHUANOP,0,item_tp.TIEN_CHUANOP,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
     FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHN_ANPHI_DUONGSU DU LEFT JOIN AHN_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
            SELECT COUNT(*) VUVIEC_HOANTRA,SUM(TA.ANPHIHOANTRA)ANPHIHOANTRA ,THA.ID DONVITHA_ID
                FROM AHN_TONGDAT TD 
                INNER JOIN AHN_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHN_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHN_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AHN_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='3'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TA.ANPHIHOANTRA !=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '3','Hôn nhân',0,0,0,0,item_tp.VUVIEC_HOANTRA,item_tp.ANPHIHOANTRA,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
         FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHN_ANPHI_DUONGSU DU LEFT JOIN AHN_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
               SELECT COUNT(*) COUNT_DANOP,SUM(AI.TAMUNGANPHI)TIEN_DANOP ,THA.ID DONVITHA_ID
                FROM AHN_TONGDAT TD 
                INNER JOIN AHN_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHN_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHN_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AHN_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='3'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                LEFT JOIN(select decode(tts.NGAYNHANTONGDAT,null,tts.NGAYNHANTONGDATS,tts.NGAYNHANTONGDAT)NGAYNHANTONGDAT
                              ,decode(tts.NGAYPHATHANH,null,tts.NGAYPHATHANHS,tts.NGAYPHATHANH)NGAYPHATHANH
                              ,DECODE(TTS.DUONGSUID,NULL,TTS.DUONGSUIDS,TTS.DUONGSUID)DUONGSUID,TTS.tongdatid 
                              from(SELECT SUBSTR(TT.NGAYNHANTONGDATS,0,instr(TT.NGAYNHANTONGDATS,',')-1)NGAYNHANTONGDAT
                                 ,SUBSTR(TT.NGAYPHATHANHS,0,instr(TT.NGAYPHATHANHS,',')-1)NGAYPHATHANH
                                 ,SUBSTR(TT.DUONGSUIDS,0,instr(TT.DUONGSUIDS,',')-1)DUONGSUID
                                 ,TT.NGAYNHANTONGDATS
                                 ,TT.NGAYPHATHANHS
                                 ,TT.DUONGSUIDS,TT.tongdatid
                                  FROM (    select tongdatid,LISTAGG(DUONGSUID, ',')WITHIN GROUP (ORDER BY ID)DUONGSUIDS,
                                            LISTAGG(NGAYNHANTONGDAT,',')WITHIN GROUP (ORDER BY ID)NGAYNHANTONGDATS,
                                            LISTAGG(NGAYPHATHANH,',')WITHIN GROUP (ORDER BY ID)NGAYPHATHANHS 
                                            from AHN_TONGDAT_DOITUONG where NGAYPHATHANH is not null
                                            group by tongdatid 
                                        )TT 
                                 )tts
                          )DT on DT.tongdatid=TD.ID --and instr(','||TT.DUONGSU_IDS||',',','||DT.DUONGSUID||',')>0   
                WHERE((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 AND (DT.NGAYPHATHANH IS NOT NULL OR (DT.NGAYPHATHANH IS NULL AND TD.NGAYTAO<to_date('19/03/2025 23:59:59','dd/MM/yyyy hh24:mi:ss')) )
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '3','Hôn nhân',item_tp.COUNT_DANOP,0,item_tp.TIEN_DANOP,0,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
     FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHN_ANPHI_DUONGSU DU LEFT JOIN AHN_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
                SELECT COUNT(*) COUNT_DINHCHI,SUM(AI.TAMUNGANPHI)TIEN_DINHCHI ,THA.ID DONVITHA_ID
                FROM AHN_TONGDAT TD 
                INNER JOIN AHN_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHN_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHN_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                INNER JOIN (SELECT QD.DONID FROM AHN_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='3'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '3','Hôn nhân',0,0,0,0,0,0,
        item_tp.COUNT_DINHCHI,item_tp.TIEN_DINHCHI
        ,item_tp.DONVITHA_ID
        );  
    END LOOP;


      FOR item_tp IN 
            (
                with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHN_ANPHI_DUONGSU DU LEFT JOIN AHN_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID)
             SELECT COUNT(*) COUNT_CHUANOP,SUM(AI.TAMUNGANPHI)TIEN_CHUANOP,THA.ID DONVITHA_ID
                FROM AHN_TONGDAT TD 
                INNER JOIN AHN_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHN_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHN_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AHN_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='3'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=0  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '3','Hôn nhân',0,item_tp.COUNT_CHUANOP,0,item_tp.TIEN_CHUANOP,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
     FOR item_tp IN 
            (
               SELECT COUNT(*) VUVIEC_HOANTRA,SUM(TA.ANPHIHOANTRA)ANPHIHOANTRA,THA.ID DONVITHA_ID
                FROM AKT_TONGDAT TD 
                INNER JOIN AKT_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AKT_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN AKT_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN AKT_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AKT_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='4'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO'))
                 AND TA.ANPHIHOANTRA !=0   AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                 AND AI.TAMUNGANPHI !=0
                  GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '4','Kinh tế',0,0,0,0,item_tp.VUVIEC_HOANTRA,item_tp.ANPHIHOANTRA,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
               SELECT COUNT(*) COUNT_DANOP,SUM(AI.TAMUNGANPHI)TIEN_DANOP,THA.ID DONVITHA_ID
                FROM AKT_TONGDAT TD 
                INNER JOIN AKT_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AKT_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN AKT_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN AKT_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AKT_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='4'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '4','Kinh tế',item_tp.COUNT_DANOP,0,item_tp.TIEN_DANOP,0,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
               SELECT COUNT(*) COUNT_DINHCHI,SUM(AI.TAMUNGANPHI)TIEN_DINHCHI,THA.ID DONVITHA_ID 
                FROM AKT_TONGDAT TD 
                INNER JOIN AKT_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AKT_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN AKT_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN AKT_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                INNER JOIN (SELECT QD.DONID FROM AKT_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='4'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID

           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '4','Kinh tế',0,0,0,0,0,0,
         item_tp.COUNT_DINHCHI,item_tp.TIEN_DINHCHI
         ,item_tp.DONVITHA_ID
        );  
    END LOOP;
         FOR item_tp IN 
            (
                SELECT COUNT(*) COUNT_CHUANOP,SUM(AI.TAMUNGANPHI)TIEN_CHUANOP,THA.ID DONVITHA_ID
                FROM AKT_TONGDAT TD 
                INNER JOIN AKT_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AKT_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN AKT_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN AKT_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AKT_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='4'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=0  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '4','Kinh tế',0,item_tp.COUNT_CHUANOP,0,item_tp.TIEN_CHUANOP,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
     FOR item_tp IN 
            (
                SELECT COUNT(*) VUVIEC_HOANTRA,SUM(TA.ANPHIHOANTRA)ANPHIHOANTRA,THA.ID DONVITHA_ID
                FROM ALD_TONGDAT TD 
                INNER JOIN ALD_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ALD_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ALD_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ALD_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM ALD_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='5'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TA.ANPHIHOANTRA !=0   AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '5','Lao động',0,0,0,0,item_tp.VUVIEC_HOANTRA,item_tp.ANPHIHOANTRA,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
      FOR item_tp IN 
            (
              SELECT COUNT(*) COUNT_DANOP,SUM(AI.TAMUNGANPHI)TIEN_DANOP,THA.ID DONVITHA_ID
                FROM ALD_TONGDAT TD 
                INNER JOIN ALD_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ALD_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ALD_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ALD_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM ALD_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='5'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '5','Lao động',item_tp.COUNT_DANOP,0,item_tp.TIEN_DANOP,0,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
              SELECT COUNT(*) COUNT_DINHCHI,SUM(AI.TAMUNGANPHI)TIEN_DINHCHI,THA.ID DONVITHA_ID
                FROM ALD_TONGDAT TD 
                INNER JOIN ALD_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ALD_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ALD_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ALD_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                INNER JOIN (SELECT QD.DONID FROM ALD_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='5'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '5','Lao động',0,0,0,0,0,0,
        item_tp.COUNT_DINHCHI,item_tp.TIEN_DINHCHI
        ,item_tp.DONVITHA_ID
        );  
    END LOOP;
      FOR item_tp IN 
            (
            SELECT COUNT(*) COUNT_CHUANOP,SUM(AI.TAMUNGANPHI)TIEN_CHUANOP,THA.ID DONVITHA_ID
                FROM ALD_TONGDAT TD 
                INNER JOIN ALD_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN ALD_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN ALD_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN ALD_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM ALD_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='5'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE DU.TUCACHTOTUNG_MA='NGUYENDON'
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '5','Lao động',0,item_tp.COUNT_CHUANOP,0,item_tp.TIEN_CHUANOP,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHC_ANPHI_DUONGSU DU LEFT JOIN AHC_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
            SELECT COUNT(*) VUVIEC_HOANTRA,SUM(TA.ANPHIHOANTRA)ANPHIHOANTRA ,THA.ID DONVITHA_ID
            FROM AHC_TONGDAT TD 
                INNER JOIN AHC_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHC_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHC_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='6'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TA.ANPHIHOANTRA !=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID=121
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '6','Hành chính',0,0,0,0,item_tp.VUVIEC_HOANTRA,item_tp.ANPHIHOANTRA,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
         FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHC_ANPHI_DUONGSU DU LEFT JOIN AHC_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
            SELECT COUNT(*) COUNT_DANOP,SUM(AI.TAMUNGANPHI)TIEN_DANOP,THA.ID DONVITHA_ID
            FROM AHC_TONGDAT TD 
                INNER JOIN AHC_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHC_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHC_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='6'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID=121
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '6','Hành chính',item_tp.COUNT_DANOP,0,item_tp.TIEN_DANOP,0,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
       FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHC_ANPHI_DUONGSU DU LEFT JOIN AHC_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
            SELECT COUNT(*) COUNT_DINHCHI,SUM(AI.TAMUNGANPHI)TIEN_DINHCHI,THA.ID DONVITHA_ID
            FROM AHC_TONGDAT TD 
                INNER JOIN AHC_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHC_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHC_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                INNER JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='6'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID=121
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '6','Hành chính',0,0,0,0,0,0,
        item_tp.COUNT_DINHCHI,item_tp.TIEN_DINHCHI
        ,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
            with ap as (SELECT LISTAGG('Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>', '')
                                   WITHIN GROUP (ORDER BY 'Họ tên:<b> '||HN.TENDUONGSU||'</b><br/> Năm sinh: '||HN.NAMSINH||'<br/> CCCD: '||HN.SOCMND||'<br/> Điên thoại: '||HN.DIENTHOAI||'<br/> Email: '||HN.EMAIL||'<br/>') TENDUONGSU ,
                             DU.ANPHI_ID
                             FROM AHC_ANPHI_DUONGSU DU LEFT JOIN AHC_DON_DUONGSU HN ON HN.ID=DU.DUONGSU_ID
                             GROUP BY DU.ANPHI_ID
                          )
            SELECT COUNT(*) COUNT_CHUANOP,SUM(AI.TAMUNGANPHI)TIEN_CHUANOP,THA.ID DONVITHA_ID
            FROM AHC_TONGDAT TD 
                INNER JOIN AHC_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN AHC_ANPHI AI ON TD.DONID=AI.DONID
                LEFT JOIN AP ON AP.ANPHI_ID=AI.ID
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN AHC_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM AHC_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
                LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='6'
                LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
                WHERE ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TT.TRANGTHAITHANHTOAN=0  AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID=121
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '6','Hành chính',0,item_tp.COUNT_CHUANOP,0,item_tp.TIEN_CHUANOP,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
               SELECT COUNT(*) VUVIEC_HOANTRA,SUM(TA.ANPHIHOANTRA)ANPHIHOANTRA,THA.ID DONVITHA_ID
                FROM APS_TONGDAT TD 
                INNER JOIN APS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN APS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN APS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
               -- INNER JOIN APS_TONGDAT_DOITUONG DO ON DO.DUONGSUID =DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN APS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
--                LEFT JOIN APS_FILE FL ON FL.DONID=TD.DONID AND FL.BIEUMAUID=67
                LEFT JOIN (SELECT QD.DONID FROM APS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
               LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='7'
               LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
               WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
                AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
                AND TA.ANPHIHOANTRA !=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381) 
                AND AI.TAMUNGANPHI !=0
                 GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '7','Phá sản',0,0,0,0,item_tp.VUVIEC_HOANTRA,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
         FOR item_tp IN 
            (
               SELECT COUNT(*) COUNT_DANOP,SUM(AI.TAMUNGANPHI)TIEN_DANOP,THA.ID DONVITHA_ID
                FROM APS_TONGDAT TD 
                INNER JOIN APS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN APS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN APS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN APS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM APS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
               LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='7'
               LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
               WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
               AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
               AND TA.ANPHIHOANTRA !=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
               AND AI.TAMUNGANPHI !=0
                GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '7','Phá sản',item_tp.COUNT_DANOP,0,item_tp.TIEN_DANOP,0,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
              SELECT COUNT(*) COUNT_DINHCHI,SUM(AI.TAMUNGANPHI)TIEN_DINHCHI,THA.ID DONVITHA_ID
                FROM APS_TONGDAT TD 
                INNER JOIN APS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN APS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN APS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN APS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                INNER JOIN (SELECT QD.DONID FROM APS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
               LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='7'
               LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
               WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
               AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
              AND TT.TRANGTHAITHANHTOAN=1 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
              AND AI.TAMUNGANPHI !=0
              GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '7','Phá sản',0,0,0,0,0,0,
        item_tp.COUNT_DINHCHI,item_tp.TIEN_DINHCHI
        ,item_tp.DONVITHA_ID
        );  
    END LOOP;
    FOR item_tp IN 
            (
              SELECT COUNT(*) COUNT_CHUANOP,SUM(AI.TAMUNGANPHI)TIEN_CHUANOP,THA.ID DONVITHA_ID
                FROM APS_TONGDAT TD 
                INNER JOIN APS_DON DO ON TD.DONID=DO.ID     
                INNER JOIN DM_TOAAN TN ON TN.ID=DO.TOAANID
                INNER JOIN DM_BIEUMAU BM ON BM.ID=TD.BIEUMAUID
                INNER JOIN APS_ANPHI AI ON TD.DONID=AI.DONID
                INNER JOIN APS_DON_DUONGSU DU ON AI.DUONGSU_ID=DU.id
                INNER JOIN DM_TOAAN_THIHANHAN_MAP THM ON THM.TOAANID=TN.ID INNER JOIN DM_DONVITHIHANHAN THA ON THA.id=THM.THIHANHANID
                LEFT JOIN DM_HANHCHINH HC ON DU.TAMTRUID=HC.ID
                LEFT JOIN APS_DON_XULY DX ON DX.DONID=TD.DONID AND DX.LOAIGIAIQUYET=5 --DX.LOAIGIAIQUYET=5  Biện pháp GQ/YC-> thụ lý ->Thông báo nộp tiền tạm ứng án 
                LEFT JOIN TUPHAP_ANPHI TA ON TA.VUVIECID=TD.DONID
                LEFT JOIN (SELECT QD.DONID FROM APS_SOTHAM_QUYETDINH  QD 
                            INNER JOIN (SELECT QDA.* FROM DM_QD_QUYETDINH QDA WHERE QDA.LOAIID=3)DMQD ON DMQD.ID=QD.QUYETDINHID)DC ON DC.DONID=DO.ID --xac dinh xem co dinh chi nop an phi 
               LEFT JOIN DVCQG_THANH_TOAN TT ON TT.DONID=TD.DONID AND TT.MALOAIVUVIEC='7'
               LEFT JOIN DVCQG_FILE_BIENLAI BL ON BL.TP_THANH_TOAN_ID=TT.ID
               WHERE DU.TUCACHTOTUNG_MA='NGUYENDON' 
               AND ((THA.ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
               AND TT.TRANGTHAITHANHTOAN=0 AND TT.MA_THONGBAO IS NOT NULL AND TD.BIEUMAUID IN(67,381)
              AND AI.TAMUNGANPHI !=0
               GROUP BY THA.ID
           )
    LOOP
        v_table.extend;
        v_table(v_table.count) := R_TUPHAP_ANPHI_TOTAL(
        '7','Phá sản',0,item_tp.COUNT_CHUANOP,0,item_tp.TIEN_CHUANOP,0,0,
        0,0,item_tp.DONVITHA_ID
        );  
    END LOOP;
    ----------------------
      OPEN v_cursor FOR
       select * from TABLE(v_table);

        RETURN v_cursor;   
END GET_SOLUONG_CREATE_DATA;
END PKG_TUPHAP_ANPHI_JOB;

/
