--------------------------------------------------------
--  DDL for Package Body PKG_TUPHAP_ANPHI_CN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_TUPHAP_ANPHI_CN" AS
PROCEDURE TUPHAP_ANPHI_CN_INS_UP
    (
        V_TUPHAP_ANPHI_ID  in  NUMBER,
        V_NGUOI_TAO IN VARCHAR2,
        V_TRANG_THAI IN VARCHAR2
    )
AS 
           V_COUNT NUMBER;
BEGIN 
       SELECT COUNT(*) INTO V_COUNT  FROM TUPHAP_ANPHI_CN CN WHERE CN.TUPHAP_ANPHI_ID=V_TUPHAP_ANPHI_ID;
      ------------
       IF(V_COUNT=0)THEN --bảng TUPHAP_ANPHI_CN và TUPHAP_ANPHI quan hệ 1-1
            INSERT INTO TUPHAP_ANPHI_CN
             (ID,TUPHAP_ANPHI_ID,NGAY_TAO,NGUOI_TAO,TRANG_THAI)
            VALUES (TUPHAP_ANPHI_CN_SEQ.NEXTVAL,V_TUPHAP_ANPHI_ID,SYSDATE,V_NGUOI_TAO,'0');
            --V_TRANG_THAI 0 đang lưu,1 đã gửi,2 thu hồi
        ELSE 
         IF(V_TRANG_THAI='0') THEN
            UPDATE TUPHAP_ANPHI_CN
            SET NGAY_SUA=SYSDATE,NGUOI_SUA=V_NGUOI_TAO,TRANG_THAI='0'
            WHERE TUPHAP_ANPHI_ID=V_TUPHAP_ANPHI_ID;
         ELSIF(V_TRANG_THAI='1') THEN
            UPDATE TUPHAP_ANPHI_CN
            SET NGAY_CHUYEN=SYSDATE,NGUOI_CHUYEN=V_NGUOI_TAO,TRANG_THAI='1'
            WHERE TUPHAP_ANPHI_ID=V_TUPHAP_ANPHI_ID;
         ELSIF(V_TRANG_THAI='2') THEN
            UPDATE TUPHAP_ANPHI_CN
            SET NGAY_THUHOI=SYSDATE,NGUOI_THUHOI=V_NGUOI_TAO,TRANG_THAI='2'
            WHERE TUPHAP_ANPHI_ID=V_TUPHAP_ANPHI_ID;
         END IF;
        END IF;
END TUPHAP_ANPHI_CN_INS_UP;
PROCEDURE TUPHAP_ANPHI_CN_GET_ID
    (
        V_TUPHAP_ANPHI_ID  in  NUMBER,
        ITEMS_CURSOR OUT SYS_REFCURSOR
    )
AS 
    V_COUNT NUMBER;
BEGIN 
      OPEN ITEMS_CURSOR FOR
      SELECT CN.*,TT.TRANGTHAITHANHTOAN FROM TUPHAP_ANPHI_CN CN 
      LEFT JOIN TUPHAP_ANPHI TP ON TP.ID=CN.TUPHAP_ANPHI_ID
      LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID
      WHERE CN.TUPHAP_ANPHI_ID=V_TUPHAP_ANPHI_ID
      ;
END TUPHAP_ANPHI_CN_GET_ID;
PROCEDURE UPDATE_TUPHAP_ANPHI_CN
AS 
    V_COUNT NUMBER;
BEGIN 

begin
          for itemtt in(select * from DVCQG_THANH_TOAN  where TRANGTHAITHANHTOAN=1)
          loop
             for itemtp in (select * from tuphap_anphi where DVCQG_TT_ID=itemtt.id)
             loop
                  update TUPHAP_ANPHI_CN
                  set TRANG_THAI=1
                  where TUPHAP_ANPHI_ID=itemtp.id;
             end loop;
        end loop;
        commit;
        end;
--      INSERT INTO TUPHAP_ANPHI_CN
--     (ID,TUPHAP_ANPHI_ID,NGAY_TAO,NGUOI_TAO,TRANG_THAI,NGAY_CHUYEN,NGUOI_CHUYEN)
--      SELECT TUPHAP_ANPHI_CN_SEQ.NEXTVAL,TSP.ID,SYSDATE,'admin',TSP.TRANGTHAITHANHTOAN,DECODE(TSP.TRANGTHAITHANHTOAN,1,sysdate,0,NULL),DECODE(TSP.TRANGTHAITHANHTOAN,1,'admin',0,NULL) FROM 
--      --TSP.TRANGTHAITHANHTOAN (0 chưa thanh toán,1 đã thanh toán;)dùng gán cho TRANG_THAI của bảng TUPHAP_ANPHI_CN 
--      --định nghĩa lại TRANG_THAI (0 đang lưu,1 đã gửi ghán cho dữ liệu cũ là đã thanh toán)
--      (SELECT TP.ID,TT.TRANGTHAITHANHTOAN FROM TUPHAP_ANPHI TP LEFT JOIN DVCQG_THANH_TOAN TT ON TT.ID=TP.DVCQG_TT_ID)TSP
--      ;
END UPDATE_TUPHAP_ANPHI_CN;
END PKG_TUPHAP_ANPHI_CN;

/
