--------------------------------------------------------
--  DDL for Package Body PKG_DASHBOARD_STPT_APP
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "GSCM"."PKG_DASHBOARD_STPT_APP" AS
PROCEDURE DASHBOARD_CREATE_DATA_AUTO
 AS    
BEGIN
  DELETE DASHBOARD_STPT;COMMIT;  
  ---hs 
   PKG_DASHBOARD_STPT_HS_APP.DASHBOARD_CREATE_DATA_AHS_ST;
   PKG_DASHBOARD_STPT_HS_APP.DASHBOARD_CREATE_DATA_AHS_PT;
  ---ds ext st
  PKG_DASHBOARD_ST_APP.DASHBOARD_CREATE_DATA_ADS_ST;
  PKG_DASHBOARD_ST_APP.DASHBOARD_CREATE_DATA_AHN_ST;
  PKG_DASHBOARD_ST_APP.DASHBOARD_CREATE_DATA_AKT_ST;
  PKG_DASHBOARD_ST_APP.DASHBOARD_CREATE_DATA_ALD_ST;
  PKG_DASHBOARD_ST_APP.DASHBOARD_CREATE_DATA_AHC_ST;
  ---ds ext pt
  PKG_DASHBOARD_PT_APP.DASHBOARD_CREATE_DATA_ADS_PT;
  PKG_DASHBOARD_PT_APP.DASHBOARD_CREATE_DATA_AHN_PT;
  PKG_DASHBOARD_PT_APP.DASHBOARD_CREATE_DATA_AKT_PT;
  PKG_DASHBOARD_PT_APP.DASHBOARD_CREATE_DATA_ALD_PT;
  PKG_DASHBOARD_PT_APP.DASHBOARD_CREATE_DATA_AHC_PT;
END DASHBOARD_CREATE_DATA_AUTO;
END PKG_DASHBOARD_STPT_APP;

/
