--------------------------------------------------------
--  DDL for Package Body PKG_STPT_KHANGCAOQUAHAN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_STPT_KHANGCAOQUAHAN" AS

PROCEDURE SOTHULY_GETMAXTT
(      
    VTOAANID        IN NUMBER,
    VLOAIKHANGCAO   IN NUMBER,
    VNGAYTHULY      IN VARCHAR2,
	CURRETURN    OUT       SYS_REFCURSOR
)
IS 
    VVNGAYTHULY DATE;
    VYEAR NUMBER;
BEGIN
    if(VNGAYTHULY IS NOT NULL) then  VVNGAYTHULY:=to_date(trim(VNGAYTHULY)||' 00:00:00','dd/MM/yyyy HH24:MI:SS'); end if;

    --VVNGAYTHULY := TO_DATE(VNGAYTHULY,'DD/MM/YYYY');
    --SELECT EXTRACT(YEAR FROM TO_DATE('01/01/2022', 'DD/MM/YYYY')) INTO VYEAR FROM DUAL;
    SELECT EXTRACT(YEAR FROM VVNGAYTHULY) INTO VYEAR FROM DUAL;

--    IF(VLOAIKHANGCAO = 0) THEN
            OPEN CURRETURN FOR  
                SELECT MAX(TO_NUMBER(TT.SOTHULY)) SOTHULY FROM (
                    SELECT 
                        LOWER(DECODE(INSTR(D.SOTHULY,'/')
                                        ,0,DECODE(INSTR(D.SOTHULY,'0'),1,REGEXP_REPLACE(D.SOTHULY,'0','',1,1),D.SOTHULY),DECODE(INSTR(D.SOTHULY,'0')
                                        ,1,SUBSTR(REGEXP_REPLACE(D.SOTHULY,'0','',1,1),1,INSTR(REGEXP_REPLACE(D.SOTHULY,'0','',1,1),'/')-1),SUBSTR(D.SOTHULY,1,INSTR(D.SOTHULY,'/')-1) )
                                     )
                              ) SOTHULY
                    FROM KHANGCAOQUAHAN_THULY D
                    WHERE D.TOAANID= VTOAANID 
--                            AND D.LOAIKHANGCAO = 0
                            AND TRIM(D.SOTHULY) IS NOT NULL 
                            AND D.NGAYTHULY BETWEEN TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-01-01','YYYY-MM-DD') AND TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-12-31','YYYY-MM-DD')
                )TT;
--          ELSE
--              OPEN CURRETURN FOR  
--                SELECT MAX(TO_NUMBER(TT.SOTHULY)) SOTHULY FROM (
--                    SELECT 
--                        LOWER(DECODE(INSTR(D.SOTHULY,'/')
--                                        ,0,DECODE(INSTR(D.SOTHULY,'0'),1,REGEXP_REPLACE(D.SOTHULY,'0','',1,1),D.SOTHULY),DECODE(INSTR(D.SOTHULY,'0')
--                                        ,1,SUBSTR(REGEXP_REPLACE(D.SOTHULY,'0','',1,1),1,INSTR(REGEXP_REPLACE(D.SOTHULY,'0','',1,1),'/')-1),SUBSTR(D.SOTHULY,1,INSTR(D.SOTHULY,'/')-1) )
--                                    )
--                              ) SOTHULY
--                    FROM KHANGCAOQUAHAN_THULY D
--                    WHERE D.TOAANID= VTOAANID 
--                            AND D.LOAIKHANGCAO IN (1,2,3)
--                            AND TRIM(D.SOTHULY) IS NOT NULL 
--                            AND D.NGAYTHULY BETWEEN TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-01-01','YYYY-MM-DD') AND TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-12-31','YYYY-MM-DD')
--                )TT;
--        END IF;
END SOTHULY_GETMAXTT;

PROCEDURE SOTHULY_GETMAXTT_CHECK
( 
    VTOAANID IN NUMBER,
    VLOAIKHANGCAO   IN NUMBER,
    VSOTHULY        IN VARCHAR2,
    VNGAYTHULY      IN VARCHAR2,
	CURRETURN       OUT SYS_REFCURSOR
)
IS 
    VVNGAYTHULY DATE;
    VYEAR NUMBER;
BEGIN

    IF (VNGAYTHULY IS NOT NULL) THEN  VVNGAYTHULY := TO_DATE(TRIM(VNGAYTHULY)||' 00:00:00','dd/MM/yyyy HH24:MI:SS'); END IF;

    SELECT EXTRACT(YEAR FROM VVNGAYTHULY) INTO VYEAR FROM DUAL;

--    IF(VLOAIKHANGCAO = 0) THEN
          OPEN CURRETURN FOR  
              SELECT D.ID
              FROM KHANGCAOQUAHAN_THULY D 
              WHERE D.TOAANID=VTOAANID 
--                    AND D.LOAIKHANGCAO = 0 
                    AND D.SOTHULY = VSOTHULY 
                    AND D.NGAYTHULY BETWEEN TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-01-01','YYYY-MM-DD') AND TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-12-31','YYYY-MM-DD');  
--      ELSE
--          OPEN CURRETURN FOR  
--              SELECT D.ID
--              FROM KHANGCAOQUAHAN_THULY D 
--              WHERE D.TOAANID=VTOAANID 
--                    AND D.LOAIKHANGCAO IN (1,2,3) 
--                    AND D.SOTHULY = VSOTHULY 
--                    AND D.NGAYTHULY BETWEEN TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-01-01','YYYY-MM-DD') AND TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-12-31','YYYY-MM-DD');
--    END IF;
END SOTHULY_GETMAXTT_CHECK;

PROCEDURE SOQUYETDINH_GETMAXTT
(      
    VTOAANID        IN NUMBER,
    VNGAYQUYETDINH      IN VARCHAR2,
	CURRETURN    OUT       SYS_REFCURSOR
)
IS 
    VVNGAYQD DATE;
    VYEAR NUMBER;
BEGIN
    if(VNGAYQUYETDINH IS NOT NULL) THEN  VVNGAYQD := TO_DATE(TRIM(VNGAYQUYETDINH)||' 00:00:00','dd/MM/yyyy HH24:MI:SS'); END IF;

    SELECT EXTRACT(YEAR FROM VVNGAYQD) INTO VYEAR FROM DUAL;

    OPEN CURRETURN FOR  
        SELECT MAX(TO_NUMBER(TT.SOQD)) SOQD FROM (
            SELECT 
                LOWER(DECODE(INSTR(D.SOQD,'/')
                                ,0,DECODE(INSTR(D.SOQD,'0'),1,REGEXP_REPLACE(D.SOQD,'0','',1,1),D.SOQD),DECODE(INSTR(D.SOQD,'0')
                                ,1,SUBSTR(REGEXP_REPLACE(D.SOQD,'0','',1,1),1,INSTR(REGEXP_REPLACE(D.SOQD,'0','',1,1),'/')-1),SUBSTR(D.SOQD,1,INSTR(D.SOQD,'/')-1) )
                             )
                      ) SOQD
            FROM KHANGCAOQUAHAN_QUYETDINH D
            WHERE D.TOAANID= VTOAANID 
                    AND TRIM(D.SOQD) IS NOT NULL 
                    AND D.NGAYQD BETWEEN TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-01-01','YYYY-MM-DD') AND TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-12-31','YYYY-MM-DD')
        )TT;

END SOQUYETDINH_GETMAXTT;

PROCEDURE SOQUYETDINH_GETMAXTT_CHECK
( 
    VTOAANID IN NUMBER,
    VSOQUYETDINH        IN VARCHAR2,
    VNGAYQUYETDINH      IN VARCHAR2,
	CURRETURN       OUT SYS_REFCURSOR
)
IS 
    VVNGAYQD DATE;
    VYEAR NUMBER;
BEGIN

    IF (VNGAYQUYETDINH IS NOT NULL) THEN  VVNGAYQD := TO_DATE(TRIM(VNGAYQUYETDINH)||' 00:00:00','DD/MM/YYYY HH24:MI:SS'); END IF;

    SELECT EXTRACT(YEAR FROM VVNGAYQD) INTO VYEAR FROM DUAL;

    OPEN CURRETURN FOR  
        SELECT D.ID
        FROM KHANGCAOQUAHAN_QUYETDINH D 
        WHERE D.TOAANID=VTOAANID  
              AND D.SOQD = VSOQUYETDINH 
              AND D.NGAYQD BETWEEN TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-01-01','YYYY-MM-DD') AND TO_DATE(CAST((VYEAR) AS VARCHAR2(4))||'-12-31','YYYY-MM-DD');  

END SOQUYETDINH_GETMAXTT_CHECK;

PROCEDURE        "KHANGCAOQUAHAN_HDXX_GETBYID" 
( 
    VDONID          IN NUMBER,
    VTHULYID        IN NUMBER,
    VLOAIAN         IN NUMBER,
    VID_HDXX        IN NUMBER,
	CURRETURN       OUT SYS_REFCURSOR
)
IS 
BEGIN
    OPEN CURRETURN FOR  
    SELECT D.*
    FROM KHANGCAOQUAHAN_HDXX D 
    WHERE D.THULYID=VTHULYID AND D.LOAIAN = VLOAIAN AND D.ID = VID_HDXX;

END KHANGCAOQUAHAN_HDXX_GETBYID;

PROCEDURE        "KHANGCAOQUAHAN_QUYETDINH_GETLAST" 
( 
    VDONID          IN NUMBER,
    VTHULYID        IN NUMBER,
    VLOAIAN         IN NUMBER,
	CURRETURN       OUT SYS_REFCURSOR
)
IS 
BEGIN
OPEN CURRETURN FOR  
  SELECT D.*,
         NVL(TO_CHAR(D.NGAYSUA, 'DD/MM/YYYY'), NVL(TO_CHAR(D.NGAYTAO, 'DD/MM/YYYY'), '')) AS NGAYSUACUOI
  FROM KHANGCAOQUAHAN_QUYETDINH D 
  WHERE D.DONID = VDONID AND D.LOAIAN = VLOAIAN AND D.THULYID = VTHULYID
  ORDER BY D.ID;

END KHANGCAOQUAHAN_QUYETDINH_GETLAST;

PROCEDURE        "KHANGCAOQUAHAN_HDXX_GETLIST" 
( 
    VDONID IN NUMBER,
    VTHULYID IN NUMBER,
    VLOAIAN IN NUMBER,
	CURRETURN OUT SYS_REFCURSOR
)
IS 
BEGIN
OPEN CURRETURN FOR
  SELECT D.ID, D.LOAIAN, D.DONID, D.THULYID
        ,D.MAVAITRO
        ,C.GIOITINH
        ,(CASE D.MAVAITRO WHEN 'THAMPHAN' THEN 'Thẩm phán chủ tọa phiên tòa'
                             WHEN 'THAMPHANHDXX' THEN 'Thẩm phán thành viên hội đồng xét xử'
                             WHEN 'THAMPHANDUKHUYET' THEN 'Thẩm phán dự khuyết'
                             WHEN 'HTND' THEN 'Hội thẩm nhân dân'
                             WHEN 'THUKY' THEN 'Thư ký'
                             WHEN 'KSV' THEN 'Kiểm sát viên' END) AS TENVAITRO
        ,CASE WHEN D.MAVAITRO='KSV' THEN V.HOTEN ELSE C.HOTEN END AS TENNGUOITHTT
        ,D.NGAYPHANCONG,D.NGAYNHANPHANCONG
        ,D.NGUOITAO,D.NGAYTAO,E.HOTEN AS NGUOIPHANCONG
  FROM KHANGCAOQUAHAN_HDXX D
  LEFT JOIN DM_CANBO C ON C.ID=D.CANBOID
  LEFT JOIN DM_CANBO E ON E.ID=D.NGUOIPHANCONGID
  LEFT JOIN DM_CANBOVKS V ON V.ID=D.CANBOID
  WHERE D.THULYID=VTHULYID AND D.LOAIAN = VLOAIAN
  ORDER BY D.HIEULUC, D.ID;

END KHANGCAOQUAHAN_HDXX_GETLIST;

PROCEDURE        "KHANGCAOQUAHAN_THULY_GETLAST" 
( 
    VDONID          IN NUMBER,
    VLOAIAN         IN NUMBER,
    VKHANGCAOID     IN NUMBER,
	CURRETURN       OUT SYS_REFCURSOR
)
IS 
BEGIN
OPEN CURRETURN FOR  
  SELECT D.ID, D.SOTHULY, D.NGAYTHULY, D.NGUOITHULYID, E.HOTEN,
         NVL(TO_CHAR(D.NGAYSUA, 'DD/MM/YYYY'), NVL(TO_CHAR(D.NGAYTAO, 'DD/MM/YYYY'), '')) AS NGAYSUACUOI
  FROM KHANGCAOQUAHAN_THULY D 
    LEFT JOIN DM_CANBO E ON E.ID = D.NGUOITHULYID
  WHERE D.DONID = VDONID AND D.LOAIAN = VLOAIAN AND D.KHANGCAOID = VKHANGCAOID
  ORDER BY D.ID;

END KHANGCAOQUAHAN_THULY_GETLAST;

END PKG_STPT_KHANGCAOQUAHAN;

/
