CREATE OR REPLACE PACKAGE BODY GSCM.PKG_NOTINUMBER_VIEID
AS
-- Package body

	FUNCTION GEN_NOTINUMBER_CODE(p_prefix IN VARCHAR2)
	RETURN VARCHAR2
	IS
	    v_seq_val NUMBER;
	    v_year VARCHAR2(4) := TO_CHAR(SYSDATE, 'YYYY');
BEGIN
EXECUTE IMMEDIATE 'SELECT SEQ_NOTINUMBER_VNEID_' || p_prefix || '.NEXTVAL FROM DUAL' INTO v_seq_val;
RETURN p_prefix || v_year || LPAD(v_seq_val, 6, '0');
EXCEPTION
	    WHEN OTHERS THEN
	        RAISE_APPLICATION_ERROR(-20001, 'Sequence SEQ_NOTINUMBER_VNEID_' || p_prefix || ' không tìm thấy.');
END;


END PKG_NOTINUMBER_VIEID;