--------------------------------------------------------
--  DDL for Package Body PKG_HCTP_TRUNG_GIAN
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_HCTP_TRUNG_GIAN" AS
PROCEDURE SP_INSERT_GDTTT_DON
(
  V_GUID in varchar2,
  V_MA_HO_SO  in varchar2,  
  V_TOA_AN_CHUYEN in varchar2,
  V_NGUOI_CHUYEN in varchar2,
  V_TOA_AN_NHAN in varchar2,
  V_COUNT_RE OUT NUMBER
) 
IS 
  V_COUNT NUMBER;V_TOA_AN_XET_XU varchar2(100);V_TOA_AN_CHUYEN_MA varchar2(100);V_DONTRUNGID number;V_CD_SOCV varchar2(100);
  V_NGUOI_CHUYEN_MA varchar2(100);V_TOA_AN_NHAN_MA  varchar2(100);V_CAP_XET_XU varchar2(100);
BEGIN 
--    SELECT TA.MADONGBO,DECODE(DON.BAQD_CAPXETXU,2,'SOTHAM',3,'PHUCTHAM',4,'GĐT,TT') INTO V_TOA_AN_XET_XU,V_CAP_XET_XU FROM GDTTT_DON DON 
--    LEFT JOIN DM_TOAAN TA ON TA.ID=DON.BAQD_TOAANID
--    WHERE DON.ID=V_MA_HO_SO;
--    -------
--    SELECT DON.DONTRUNGID,DON.CD_SOCV INTO V_DONTRUNGID,V_CD_SOCV FROM GDTTT_DON DON WHERE  DON.ID=V_MA_HO_SO;
--    SELECT TA.MADONGBO INTO V_TOA_AN_CHUYEN_MA FROM DM_TOAAN TA WHERE TA.ID=V_TOA_AN_CHUYEN;
--    SELECT CB.MADONGBO INTO V_NGUOI_CHUYEN_MA FROM DM_CANBO CB WHERE CB.ID=(SELECT QT.CANBOID FROM QT_NGUOISUDUNG QT WHERE QT.USERNAME=V_NGUOI_CHUYEN);
--    SELECT TA.MADONGBO INTO V_TOA_AN_NHAN_MA FROM DM_TOAAN TA WHERE TA.ID=V_TOA_AN_NHAN;
--    ------
--    SELECT COUNT(*) INTO V_COUNT FROM DBUTILS.HOSO HS WHERE HS.GUID=V_GUID AND HS.MA_HO_SO=V_MA_HO_SO;
--    ----------------------
--  IF(V_COUNT=0)THEN
--    INSERT INTO DBUTILS.HOSO 
--    (GUID,MA_HO_SO,TOA_AN_XET_XU,TOA_AN_CHUYEN,NGAY_CHUYEN,NGUOI_CHUYEN,TOA_AN_NHAN,CAP_XET_XU,TRANG_THAI,DONTRUNGID,CD_SOCV)
--    VALUES(V_GUID,V_MA_HO_SO,V_TOA_AN_XET_XU,V_TOA_AN_CHUYEN_MA,SYSDATE,V_NGUOI_CHUYEN_MA,V_TOA_AN_NHAN_MA,V_CAP_XET_XU,1,V_DONTRUNGID,V_CD_SOCV);
--   END IF;
--   SELECT COUNT(*) INTO V_COUNT_RE FROM DBUTILS.HOSO HS WHERE HS.MA_HO_SO=V_MA_HO_SO;
   V_COUNT_RE:=1;
END;




END PKG_HCTP_TRUNG_GIAN;

/
