--------------------------------------------------------
--  DDL for Package Body PKG_STPT_TONGDAT_ANPHI
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "GSCM"."PKG_STPT_TONGDAT_ANPHI" 
AS

PROCEDURE ADS_TONGDATDOITUONG_ANPHI_GETBY(
    vDonID in Decimal,
    vToaAnID in Decimal, 
    vBieuMauID in Decimal,
    vIsOnLyNKK in Decimal,
    vANPHIID in Decimal,
    curReturn out SYS_REFCURSOR)
IS 
BEGIN 
    OPEN curReturn FOR  
    Select d.ID, d.TENDUONGSU, d.TUCACHTOTUNG_MA, i.TEN as TENTCTT, td.NGAYGUI, td.TRANGTHAI, td.HINHTHUCGUI, 
        (d.TAMTRUCHITIET || 
            (CASE WHEN d.TAMTRUCHITIET IS NULL OR d.TAMTRUID = 0 THEN '' ELSE ', ' END) || 
            (SELECT MA_TEN FROM DM_HANHCHINH WHERE ID = d.TAMTRUID)) AS DIACHI,
        td.NGAYPHATHANH, td.IS_UTTP, td.UTTP, td.NOINHAN, d.ID DUONGSUID, td.BIEUMAUID, 
        td.NGAYNHANTONGDAT, td.QUOCGIA,  td.COQUAN, td.NOIDUNG, td.KETQUAUTTP, td.ID TONGDAT_DOITUONG,
        ap.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, ap.SOTHONGBAO || ap.STB_PHU ) AS SOTHONGBAO, dtt.MA_THONGBAO
    From ADS_DON_DUONGSU d
    INNER JOIN ADS_ANPHI ap ON d.ID = ap.DUONGSU_ID  -- 10/06/2025 VNPT tong dat mien an phi
    LEFT JOIN DVCQG_THANH_TOAN dtt ON ap.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 2 -- 10/06/2025 VNPT tong dat mien an phi
    LEFT JOIN DON_MIENANPHI dm ON ap.ID = dm.ANPHI_ID AND dm.LOAIAN = 2
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    left join (Select dt.ID, dt.NGAYGUI, dt.NGAYPHATHANH, dt.IS_UTTP, dt.UTTP, dt.NOINHAN, dt.DIACHI,
                    dt.TRANGTHAI, dt.HINHTHUCGUI, dt.DUONGSUID, t.BIEUMAUID, dt.NGAYNHANTONGDAT,
                    dt.QUOCGIA, dt.COQUAN, dt.NOIDUNG, dt.KETQUAUTTP
              from ADS_TONGDAT_DOITUONG dt inner join ADS_TONGDAT t on t.ID = dt.TONGDATID
              where t.DONID = vDONID and t.TOAANID = vTOAANID and t.BIEUMAUID = vBIEUMAUID
              ) td on td.DUONGSUID = d.ID
    Where d.DONID = vDONID 
        And 1=(Case WHEN vIsOnlyNKK=1 And d.TUCACHTOTUNG_MA='NGUYENDON' THEN 1 
                    WHEN vIsOnlyNKK=0 THEN 1 ELSE 0 END)
        AND (ap.TINHTRANG = 1 OR dm.ID IS NOT null) AND ap.MAGIAIDOAN = 2 AND ap.ID = vANPHIID -- 10/06/2025 VNPT tong dat mien an phi
        AND NOT EXISTS (SELECT 1 FROM ADS_TONGDAT atd WHERE atd.MAPID = ap.ID) -- 10/06/2025 VNPT tong dat mien an phi
    ORder by d.ISDAIDIEN desc, d.TENDUONGSU;
END ADS_TONGDATDOITUONG_ANPHI_GETBY;

 PROCEDURE ADS_TONGDATDOITUONG_ANPHI_GETBYTONGDATID(
    vTONGDATID in number , 
    curReturn out SYS_REFCURSOR
 )
 IS
 BEGIN
    open curReturn for 
    select td.*, a.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, a.SOTHONGBAO || a.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO, at1.MAPID
   	from ads_tongdat_doituong td
   	LEFT JOIN ADS_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN ADS_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DON_MIENANPHI dm ON a.ID = dm.ANPHI_ID AND dm.LOAIAN = 2
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 2
   	where td.tongdatid = vTONGDATID AND db.MABM = '100-DS' AND a.MAGIAIDOAN = 2;
 END ADS_TONGDATDOITUONG_ANPHI_GETBYTONGDATID; 

  PROCEDURE ADS_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID(
    vDONID in number , 
    vANPHIID IN NUMBER,
    curReturn out SYS_REFCURSOR
 )
 IS
 BEGIN
    open curReturn for 
    select td.*
   	from ads_tongdat_doituong td
   	LEFT JOIN ADS_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN ADS_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 2
   	where a.DONID = vDONID AND db.MABM = '100-DS' AND a.ID = vANPHIID AND a.MAGIAIDOAN = 2;
 END ADS_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID; 

  -- Án hôn nhân gia đình
PROCEDURE AHN_TONGDATDOITUONG_GETBY(
    vDonID in Decimal ,
    vToaAnID in Decimal , 
    vBieuMauID in Decimal ,
    vIsOnLyNKK in Decimal ,
    vANPHIID in Decimal,
    curReturn out SYS_REFCURSOR)
IS 
BEGIN 
    OPEN curReturn FOR
        SELECT d.ID, d.TENDUONGSU, d.TUCACHTOTUNG_MA, i.TEN as TENTCTT, td.NGAYGUI, td.TRANGTHAI, td.HINHTHUCGUI,
            (d.TAMTRUCHITIET || 
                (CASE WHEN d.TAMTRUCHITIET IS NULL OR d.TAMTRUID = 0 THEN '' ELSE ', ' END) || 
                (SELECT MA_TEN FROM DM_HANHCHINH WHERE ID = d.TAMTRUID)) AS DIACHI,
            td.NGAYPHATHANH, td.IS_UTTP, td.UTTP, td.NOINHAN, d.ID DUONGSUID, td.BIEUMAUID,
            td.NGAYNHANTONGDAT, td.QUOCGIA, td.COQUAN, td.NOIDUNG, td.KETQUAUTTP, td.ID TONGDAT_DOITUONG,
            ap.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, ap.SOTHONGBAO || ap.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
        FROM AHN_ANPHI ap  -- 10/06/2025 VNPT tong dat mien an phi
			JOIN TABLE(split_string(ap.DUONGSU_IDS, ',')) b ON 1 = 1
        	INNER JOIN AHN_DON_DUONGSU d ON b.COLUMN_VALUE = d.ID
        	-- 10/06/2025 VNPT tong dat mien an phi
        	LEFT JOIN DVCQG_THANH_TOAN dtt ON ap.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 3 -- 10/06/2025 VNPT tong dat mien an phi
        	LEFT JOIN DON_MIENANPHI dm ON ap.ID = dm.ANPHI_ID AND dm.LOAIAN = 3
            LEFT JOIN DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA  
            LEFT JOIN (SELECT dt.ID, dt.NGAYGUI, dt.NGAYPHATHANH, dt.IS_UTTP, dt.UTTP, dt.NOINHAN, dt.DIACHI ,
                            dt.TRANGTHAI, dt.HINHTHUCGUI, dt.DUONGSUID, t.BIEUMAUID, dt.NGAYNHANTONGDAT, dt.QUOCGIA,
                            dt.COQUAN, dt.NOIDUNG, dt.KETQUAUTTP
                        FROM AHN_TONGDAT_DOITUONG dt INNER JOIN AHN_TONGDAT t on t.ID = dt.TONGDATID
                        WHERE t.DONID = vDONID AND t.TOAANID = vTOAANID AND t.BIEUMAUID = vBIEUMAUID
                        ) td on td.DUONGSUID = d.ID
        WHERE d.DONID = vDONID
        AND 1 = (CASE WHEN vIsOnlyNKK = 1 AND d.TUCACHTOTUNG_MA = 'NGUYENDON' THEN 1 
                    WHEN vIsOnlyNKK = 0 THEN 1 ELSE 0 END)
        AND (ap.TINHTRANG = 1 OR dm.ID IS NOT null) AND ap.MAGIAIDOAN = 2 AND ap.ID = vANPHIID -- 10/06/2025 VNPT tong dat mien an phi
        AND NOT EXISTS (SELECT 1 FROM AHN_TONGDAT atd WHERE atd.MAPID = ap.ID) -- 10/06/2025 VNPT tong dat mien an phi
        ORDER BY d.ISDAIDIEN desc, d.TENDUONGSU;
END AHN_TONGDATDOITUONG_GETBY;

PROCEDURE AHN_TONGDATDOITUONG_ANPHI_GETBYTONGDATID(
    vTONGDATID in number,
    curReturn out SYS_REFCURSOR
)
IS
BEGIN
    OPEN curReturn for 
    SELECT td.*, a.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, a.SOTHONGBAO || a.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    FROM AHN_TONGDAT_DOITUONG td
    LEFT JOIN AHN_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN AHN_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DON_MIENANPHI dm ON a.ID = dm.ANPHI_ID AND dm.LOAIAN = 3
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 3
   	where td.tongdatid = vTONGDATID AND db.MABM = '100-DS' AND a.MAGIAIDOAN = 2;
END AHN_TONGDATDOITUONG_ANPHI_GETBYTONGDATID;

 PROCEDURE AHN_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID(
    vDONID in number , 
    vANPHIID IN NUMBER,
    curReturn out SYS_REFCURSOR
 )
 IS
 BEGIN
    open curReturn for 
    select td.*
   	from ahn_tongdat_doituong td
   	LEFT JOIN AHN_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN AHN_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 3
   	where a.DONID = vDONID AND db.MABM = '100-DS' AND a.ID = vANPHIID AND a.MAGIAIDOAN = 2;
 END AHN_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID; 

  -- Án Lao động

PROCEDURE ALD_TONGDATDOITUONG_GETBY(
    vDonID in Decimal,
    vToaAnID in Decimal, 
    vBieuMauID in Decimal,
    vIsOnLyNKK in Decimal,
    vANPHIID in Decimal,
    curReturn out SYS_REFCURSOR)
IS 
BEGIN 
    OPEN curReturn FOR  
    SELECT d.ID, d.TENDUONGSU, d.TUCACHTOTUNG_MA, i.TEN as TENTCTT, td.NGAYGUI, td.TRANGTHAI, td.HINHTHUCGUI, 
        (d.TAMTRUCHITIET || 
            (CASE WHEN d.TAMTRUCHITIET IS NULL OR d.TAMTRUID = 0 THEN '' ELSE ', ' END) || 
            (SELECT MA_TEN FROM DM_HANHCHINH WHERE ID = d.TAMTRUID)) AS DIACHI,
        td.NGAYPHATHANH, td.IS_UTTP, td.UTTP, td.NOINHAN, d.ID DUONGSUID, td.BIEUMAUID, 
        td.NGAYNHANTONGDAT, td.QUOCGIA, td.COQUAN, td.NOIDUNG, td.KETQUAUTTP, td.ID TONGDAT_DOITUONG,
        ap.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, ap.SOTHONGBAO || ap.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    FROM ALD_DON_DUONGSU d
    INNER JOIN ALD_ANPHI ap ON d.ID = ap.DUONGSU_ID
    LEFT JOIN DVCQG_THANH_TOAN dtt ON ap.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 5
    LEFT JOIN DON_MIENANPHI dm ON ap.ID = dm.ANPHI_ID AND dm.LOAIAN = 5
    LEFT JOIN DM_DATAITEM i ON i.MA = d.TUCACHTOTUNG_MA
    LEFT JOIN (
        SELECT dt.ID, dt.NGAYGUI, dt.NGAYPHATHANH, dt.IS_UTTP, dt.UTTP, dt.NOINHAN, dt.DIACHI,
               dt.TRANGTHAI, dt.HINHTHUCGUI, dt.DUONGSUID, t.BIEUMAUID, dt.NGAYNHANTONGDAT,
               dt.QUOCGIA, dt.COQUAN, dt.NOIDUNG, dt.KETQUAUTTP
        FROM ALD_TONGDAT_DOITUONG dt 
        INNER JOIN ALD_TONGDAT t ON t.ID = dt.TONGDATID
        WHERE t.DONID = vDonID AND t.TOAANID = vToaAnID AND t.BIEUMAUID = vBieuMauID
    ) td ON td.DUONGSUID = d.ID
    WHERE d.DONID = vDonID
        AND 1 = (CASE WHEN vIsOnlyNKK = 1 AND d.TUCACHTOTUNG_MA = 'NGUYENDON' THEN 1 
                      WHEN vIsOnlyNKK = 0 THEN 1 ELSE 0 END)
        AND (ap.TINHTRANG = 1 OR dm.ID IS NOT NULL)  AND ap.MAGIAIDOAN = 2 AND ap.ID = vANPHIID
        AND NOT EXISTS (SELECT 1 FROM ALD_TONGDAT atd WHERE atd.MAPID = ap.ID)
    ORDER BY d.ISDAIDIEN DESC, d.TENDUONGSU;
END ALD_TONGDATDOITUONG_GETBY;


PROCEDURE ALD_TONGDATDOITUONG_ANPHI_GETBYTONGDATID(
    vTONGDATID in NUMBER, 
    curReturn out SYS_REFCURSOR
)
IS
BEGIN
    OPEN curReturn FOR 
    SELECT td.*, a.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, a.SOTHONGBAO || a.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    FROM ALD_TONGDAT_DOITUONG td
    LEFT JOIN ALD_TONGDAT at1 ON td.TONGDATID = at1.ID
    LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
    LEFT JOIN ALD_ANPHI a ON a.ID = at1.MAPID 
    LEFT JOIN DON_MIENANPHI dm ON a.ID = dm.ANPHI_ID AND dm.LOAIAN = 5
    LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 5
    WHERE td.TONGDATID = vTONGDATID AND db.MABM = '100-DS' AND a.MAGIAIDOAN = 2;
END ALD_TONGDATDOITUONG_ANPHI_GETBYTONGDATID;


PROCEDURE ALD_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID(
    vDONID in NUMBER, 
    vANPHIID IN NUMBER,
    curReturn out SYS_REFCURSOR
)
IS
BEGIN
    OPEN curReturn FOR 
    SELECT td.*
    FROM ALD_TONGDAT_DOITUONG td
    LEFT JOIN ALD_TONGDAT at1 ON td.TONGDATID = at1.ID
    LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
    LEFT JOIN ALD_ANPHI a ON a.ID = at1.MAPID 
    LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 5
    WHERE a.DONID = vDONID AND db.MABM = '100-DS' AND a.ID = vANPHIID AND a.MAGIAIDOAN = 2;
END ALD_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID;

  -- Án kinh tế
PROCEDURE AKT_TONGDATDOITUONG_GETBY(
    vDonID in Decimal,
    vToaAnID in Decimal, 
    vBieuMauID in Decimal,
    vIsOnLyNKK in Decimal,
    vANPHIID in Decimal,
    curReturn out SYS_REFCURSOR)
IS 
BEGIN 
    OPEN curReturn FOR  
    Select d.ID, d.TENDUONGSU, d.TUCACHTOTUNG_MA, i.TEN as TENTCTT, td.NGAYGUI, td.TRANGTHAI, td.HINHTHUCGUI, 
        (d.TAMTRUCHITIET || 
            (CASE WHEN d.TAMTRUCHITIET IS NULL OR d.TAMTRUID = 0 THEN '' ELSE ', ' END) || 
            (SELECT MA_TEN FROM DM_HANHCHINH WHERE ID = d.TAMTRUID)) AS DIACHI,
        td.NGAYPHATHANH, td.IS_UTTP, td.UTTP, td.NOINHAN, d.ID DUONGSUID, td.BIEUMAUID, 
        td.NGAYNHANTONGDAT, td.QUOCGIA,  td.COQUAN, td.NOIDUNG, td.KETQUAUTTP, td.ID TONGDAT_DOITUONG,
        ap.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, ap.SOTHONGBAO || ap.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    From AKT_DON_DUONGSU d
    INNER JOIN AKT_ANPHI ap ON d.ID = ap.DUONGSU_ID  -- 10/06/2025 VNPT tong dat mien an phi
    LEFT JOIN DVCQG_THANH_TOAN dtt ON ap.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 4 -- 10/06/2025 VNPT tong dat mien an phi
    LEFT JOIN DON_MIENANPHI dm ON ap.ID = dm.ANPHI_ID AND dm.LOAIAN = 4
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    left join (Select dt.ID, dt.NGAYGUI, dt.NGAYPHATHANH, dt.IS_UTTP, dt.UTTP, dt.NOINHAN, dt.DIACHI,
                    dt.TRANGTHAI, dt.HINHTHUCGUI, dt.DUONGSUID, t.BIEUMAUID, dt.NGAYNHANTONGDAT,
                    dt.QUOCGIA, dt.COQUAN, dt.NOIDUNG, dt.KETQUAUTTP
              from AKT_TONGDAT_DOITUONG dt inner join AKT_TONGDAT t on t.ID = dt.TONGDATID
              where t.DONID = vDONID and t.TOAANID = vTOAANID and t.BIEUMAUID = vBIEUMAUID
              ) td on td.DUONGSUID = d.ID
    Where d.DONID = vDONID
        And 1=(Case WHEN vIsOnlyNKK=1 And d.TUCACHTOTUNG_MA='NGUYENDON' THEN 1 
                    WHEN vIsOnlyNKK=0 THEN 1 ELSE 0 END)
        AND (ap.TINHTRANG = 1 OR dm.ID IS NOT null) AND ap.MAGIAIDOAN = 2 AND ap.ID = vANPHIID -- 10/06/2025 VNPT tong dat mien an phi
        AND NOT EXISTS (SELECT 1 FROM AKT_TONGDAT atd WHERE atd.MAPID = ap.ID) -- 10/06/2025 VNPT tong dat mien an phi
    ORder by d.ISDAIDIEN desc, d.TENDUONGSU;
END AKT_TONGDATDOITUONG_GETBY;

PROCEDURE AKT_TONGDATDOITUONG_ANPHI_GETBYTONGDATID(
    vTONGDATID in number , 
    curReturn out SYS_REFCURSOR
 )
 IS
 BEGIN
    open curReturn for 
    select td.*, a.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, a.SOTHONGBAO || a.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO, at1.MAPID
   	from akt_tongdat_doituong td
   	LEFT JOIN AKT_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN AKT_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DON_MIENANPHI dm ON a.ID = dm.ANPHI_ID AND dm.LOAIAN = 4
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 4
   	where td.tongdatid = vTONGDATID AND db.MABM = '100-DS' AND a.MAGIAIDOAN = 2;
 END AKT_TONGDATDOITUONG_ANPHI_GETBYTONGDATID; 

  PROCEDURE AKT_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID(
    vDONID in number , 
    vANPHIID IN NUMBER,
    curReturn out SYS_REFCURSOR
 )
 IS
 BEGIN
    open curReturn for 
    select td.*
   	from akt_tongdat_doituong td
   	LEFT JOIN AKT_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN AKT_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 4
   	where a.DONID = vDONID AND db.MABM = '100-DS' AND a.ID = vANPHIID AND a.MAGIAIDOAN = 2;
 END AKT_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID;

-- Án Hành chính
PROCEDURE AHC_TONGDATDOITUONG_ANPHI_GETBY(
    vDonID in Decimal ,
    vToaAnID in Decimal , 
    vBieuMauID in Decimal ,
    vIsOnLyNKK in Decimal ,
     vANPHIID in Decimal,
    curReturn out SYS_REFCURSOR)
IS 
BEGIN 
    OPEN curReturn FOR
        SELECT d.ID, d.TENDUONGSU, d.TUCACHTOTUNG_MA, i.TEN as TENTCTT, td.NGAYGUI, td.TRANGTHAI, td.HINHTHUCGUI,
            (d.TAMTRUCHITIET || 
                (CASE WHEN d.TAMTRUCHITIET IS NULL OR d.TAMTRUID = 0 THEN '' ELSE ', ' END) || 
                (SELECT MA_TEN FROM DM_HANHCHINH WHERE ID = d.TAMTRUID)) AS DIACHI,
            td.NGAYPHATHANH, td.IS_UTTP, td.UTTP, td.NOINHAN, d.ID DUONGSUID, td.BIEUMAUID,
            td.NGAYNHANTONGDAT, td.QUOCGIA, td.COQUAN, td.NOIDUNG, td.KETQUAUTTP, td.ID TONGDAT_DOITUONG,
            ap.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, ap.SOTHONGBAO || ap.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
        FROM AHC_ANPHI ap  -- 10/06/2025 VNPT tong dat mien an phi
			JOIN TABLE(split_string(ap.DUONGSU_IDS, ',')) b ON 1 = 1
        	INNER JOIN AHC_DON_DUONGSU d ON b.COLUMN_VALUE = d.ID
        	-- 10/06/2025 VNPT tong dat mien an phi
        	LEFT JOIN DVCQG_THANH_TOAN dtt ON ap.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 6 -- 10/06/2025 VNPT tong dat mien an phi
        	LEFT JOIN DON_MIENANPHI dm ON ap.ID = dm.ANPHI_ID AND dm.LOAIAN = 6
            LEFT JOIN DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA  
            LEFT JOIN (SELECT dt.ID, dt.NGAYGUI, dt.NGAYPHATHANH, dt.IS_UTTP, dt.UTTP, dt.NOINHAN, dt.DIACHI ,
                            dt.TRANGTHAI, dt.HINHTHUCGUI, dt.DUONGSUID, t.BIEUMAUID, dt.NGAYNHANTONGDAT, dt.QUOCGIA,
                            dt.COQUAN, dt.NOIDUNG, dt.KETQUAUTTP
                        FROM AHC_TONGDAT_DOITUONG dt INNER JOIN AHC_TONGDAT t on t.ID = dt.TONGDATID
                        WHERE t.DONID = vDONID AND t.TOAANID = vTOAANID AND t.BIEUMAUID = vBIEUMAUID
                        ) td on td.DUONGSUID = d.ID
        WHERE d.DONID = vDONID
        AND 1 = (CASE WHEN vIsOnlyNKK = 1 AND d.TUCACHTOTUNG_MA = 'NGUYENDON' THEN 1 
                    WHEN vIsOnlyNKK = 0 THEN 1 ELSE 0 END)
        AND (ap.TINHTRANG = 1 OR dm.ID IS NOT null) AND ap.MAGIAIDOAN = 2 AND ap.ID = vANPHIID -- 10/06/2025 VNPT tong dat mien an phi
        AND NOT EXISTS (SELECT 1 FROM AHC_TONGDAT atd WHERE atd.MAPID = ap.ID) -- 10/06/2025 VNPT tong dat mien an phi
        ORDER BY d.ISDAIDIEN desc, d.TENDUONGSU;
END AHC_TONGDATDOITUONG_ANPHI_GETBY;

PROCEDURE AHC_TONGDATDOITUONG_ANPHI_GETBYTONGDATID(
    vTONGDATID in number,
    curReturn out SYS_REFCURSOR
)
IS
BEGIN
    OPEN curReturn for 
    SELECT td.*, a.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, a.SOTHONGBAO || a.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    FROM AHC_TONGDAT_DOITUONG td
    LEFT JOIN AHC_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN AHC_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DON_MIENANPHI dm ON a.ID = dm.ANPHI_ID AND dm.LOAIAN = 6
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 6
   	where td.tongdatid = vTONGDATID AND db.MABM = '100-DS' AND a.MAGIAIDOAN = 2;
END AHC_TONGDATDOITUONG_ANPHI_GETBYTONGDATID;

 PROCEDURE AHC_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID(
    vDONID in number , 
    vANPHIID IN NUMBER,
    curReturn out SYS_REFCURSOR
 )
 IS
 BEGIN
    open curReturn for 
    select td.*
   	from ahc_tongdat_doituong td
   	LEFT JOIN AHC_TONGDAT at1 ON td.TONGDATID = at1.ID
   	LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
   	LEFT JOIN AHC_ANPHI a ON a.ID = at1.MAPID 
   	LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 6
   	where a.DONID = vDONID AND db.MABM = '100-DS'AND a.ID = vANPHIID AND a.MAGIAIDOAN = 2;
 END AHC_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID; 

-- án phá sản

PROCEDURE APS_TONGDATDOITUONG_GETBY(
    vDonID in Decimal,
    vToaAnID in Decimal, 
    vBieuMauID in Decimal,
    vIsOnLyNKK in Decimal,
    vANPHIID in Decimal,
    curReturn out SYS_REFCURSOR)
IS 
BEGIN 
    OPEN curReturn FOR  
    SELECT d.ID, d.TENDUONGSU, d.TUCACHTOTUNG_MA, i.TEN as TENTCTT, td.NGAYGUI, td.TRANGTHAI, td.HINHTHUCGUI, 
        (d.TAMTRUCHITIET || 
            (CASE WHEN d.TAMTRUCHITIET IS NULL OR d.TAMTRUID = 0 THEN '' ELSE ', ' END) || 
            (SELECT MA_TEN FROM DM_HANHCHINH WHERE ID = d.TAMTRUID)) AS DIACHI,
        td.NGAYPHATHANH, td.IS_UTTP, td.UTTP, td.NOINHAN, d.ID DUONGSUID, td.BIEUMAUID, 
        td.NGAYNHANTONGDAT, td.QUOCGIA, td.COQUAN, td.NOIDUNG, td.KETQUAUTTP, td.ID TONGDAT_DOITUONG,
        ap.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, ap.SOTHONGBAO || ap.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    FROM APS_DON_DUONGSU d
    INNER JOIN APS_ANPHI ap ON d.ID = ap.DUONGSU_ID
    LEFT JOIN DVCQG_THANH_TOAN dtt ON ap.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 7
    LEFT JOIN DON_MIENANPHI dm ON ap.ID = dm.ANPHI_ID AND dm.LOAIAN = 7
    LEFT JOIN DM_DATAITEM i ON i.MA = d.TUCACHTOTUNG_MA
    LEFT JOIN (
        SELECT dt.ID, dt.NGAYGUI, dt.NGAYPHATHANH, dt.IS_UTTP, dt.UTTP, dt.NOINHAN, dt.DIACHI,
               dt.TRANGTHAI, dt.HINHTHUCGUI, dt.DUONGSUID, t.BIEUMAUID, dt.NGAYNHANTONGDAT,
               dt.QUOCGIA, dt.COQUAN, dt.NOIDUNG, dt.KETQUAUTTP
        FROM APS_TONGDAT_DOITUONG dt 
        INNER JOIN APS_TONGDAT t ON t.ID = dt.TONGDATID
        WHERE t.DONID = vDonID AND t.TOAANID = vToaAnID AND t.BIEUMAUID = vBieuMauID
    ) td ON td.DUONGSUID = d.ID
    WHERE d.DONID = vDonID
        AND 1 = (CASE WHEN vIsOnlyNKK = 1 AND d.TUCACHTOTUNG_MA = 'NGUYENDON' THEN 1 
                      WHEN vIsOnlyNKK = 0 THEN 1 ELSE 0 END)
        AND (ap.TINHTRANG = 1 OR dm.ID IS NOT NULL)  AND ap.MAGIAIDOAN = 2 AND ap.ID = vANPHIID
        AND NOT EXISTS (SELECT 1 FROM APS_TONGDAT atd WHERE atd.MAPID = ap.ID)
    ORDER BY d.ISDAIDIEN DESC, d.TENDUONGSU;
END APS_TONGDATDOITUONG_GETBY;

PROCEDURE APS_TONGDATDOITUONG_ANPHI_GETBYTONGDATID(
    vTONGDATID in NUMBER, 
    curReturn out SYS_REFCURSOR
)
IS
BEGIN
    OPEN curReturn FOR 
    SELECT td.*, a.ID ANPHI_ID, NVL(dm.SOTHONGBAO || dm.STB_PHU, a.SOTHONGBAO || a.STB_PHU) AS SOTHONGBAO, dtt.MA_THONGBAO
    FROM APS_TONGDAT_DOITUONG td
    LEFT JOIN APS_TONGDAT at1 ON td.TONGDATID = at1.ID
    LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
    LEFT JOIN APS_ANPHI a ON a.ID = at1.MAPID 
    LEFT JOIN DON_MIENANPHI dm ON a.ID = dm.ANPHI_ID AND dm.LOAIAN = 7
    LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 7
    WHERE td.TONGDATID = vTONGDATID AND db.MABM = '100-DS' AND a.MAGIAIDOAN = 2;
END APS_TONGDATDOITUONG_ANPHI_GETBYTONGDATID;

PROCEDURE APS_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID(
    vDONID in NUMBER, 
    vANPHIID IN NUMBER,
    curReturn out SYS_REFCURSOR
)
IS
BEGIN
    OPEN curReturn FOR 
    SELECT td.*
    FROM APS_TONGDAT_DOITUONG td
    LEFT JOIN APS_TONGDAT at1 ON td.TONGDATID = at1.ID
    LEFT JOIN DM_BIEUMAU db ON at1.BIEUMAUID = db.ID
    LEFT JOIN APS_ANPHI a ON a.ID = at1.MAPID 
    LEFT JOIN DVCQG_THANH_TOAN dtt ON a.ID = dtt.ANPHI_ID AND dtt.MALOAIVUVIEC = 7
    WHERE a.DONID = vDONID AND db.MABM = '100-DS' AND a.ID = vANPHIID AND a.MAGIAIDOAN = 2;
END APS_TONGDATDOITUONG_ANPHI_GETBYANPHIID_TONGDATID;

-- Package body
END PKG_STPT_TONGDAT_ANPHI;

/
