--------------------------------------------------------
--  DDL for Package Body PKG_DUONGSU_ANPHI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_DUONGSU_ANPHI" AS

PROCEDURE ADS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN ADS_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 2) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 2
    LEFT JOIN ADS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 2
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=5 OR ct.LOAIDON=6)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUYENDON' AND ds.id is not null AND ct.id is not null;
  END ADS_DON_DUONGSU_ANPHI;

PROCEDURE AHC_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AHC_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 6) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 6
    LEFT JOIN AHC_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 6
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=5 OR ct.LOAIDON=6)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUYENDON' AND ds.id is not null AND ct.id is not null;
  END AHC_DON_DUONGSU_ANPHI;

PROCEDURE AHN_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AHN_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 3) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 3
    LEFT JOIN AHN_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 3
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=8 OR ct.LOAIDON=9)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUYENDON' AND ds.id is not null AND ct.id is not null;
  END AHN_DON_DUONGSU_ANPHI;
PROCEDURE AKT_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AKT_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 4) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 4
    LEFT JOIN AKT_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 4
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=5 OR ct.LOAIDON=6)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUYENDON' AND ds.id is not null AND ct.id is not null;
  END AKT_DON_DUONGSU_ANPHI;

PROCEDURE ALD_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN ALD_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 5) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 5
    LEFT JOIN ALD_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 5
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=5 OR ct.LOAIDON=6)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUYENDON' AND ds.id is not null;
  END ALD_DON_DUONGSU_ANPHI;

PROCEDURE APS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN APS_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 7) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 7
    LEFT JOIN APS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 7
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=5 OR ct.LOAIDON=6)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUYENDON' AND ds.id is not null;
END APS_DON_DUONGSU_ANPHI;
PROCEDURE ADS_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU 
      FROM ADS_ANPHI a      
      INNER JOIN ADS_DON_DUONGSU d ON d.ID = a.DUONGSU_ID
      left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
      WHERE a.DONID = vDONID AND a.TINHTRANG = 0;
  END ADS_DON_DUONGSU_BIENLAI;

PROCEDURE AKT_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU 
      FROM AKT_ANPHI a      
      INNER JOIN AKT_DON_DUONGSU d ON d.ID = a.DUONGSU_ID
      left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
      WHERE a.DONID = vDONID AND a.TINHTRANG = 0;
  END AKT_DON_DUONGSU_BIENLAI;

PROCEDURE ALD_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU 
      FROM ALD_ANPHI a      
      INNER JOIN ALD_DON_DUONGSU d ON d.ID = a.DUONGSU_ID
      left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
      WHERE a.DONID = vDONID AND a.TINHTRANG = 0;
  END ALD_DON_DUONGSU_BIENLAI;

  PROCEDURE APS_DON_DUONGSU_BIENLAI
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU 
      FROM APS_ANPHI a      
      INNER JOIN APS_DON_DUONGSU d ON d.ID = a.DUONGSU_ID
      left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
      WHERE a.DONID = vDONID AND a.TINHTRANG = 0;
END APS_DON_DUONGSU_BIENLAI;

PROCEDURE CHECK_ADS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN ADS_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=2
    LEFT JOIN ADS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 2) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 2
    LEFT JOIN ADS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=2
    LEFT JOIN ADS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_ADS_DON_DUONGSU_ANPHI;
PROCEDURE CHECK_AHC_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AHC_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=6
    LEFT JOIN AHC_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 6) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 6
    LEFT JOIN AHC_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=6
    LEFT JOIN AHC_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_AHC_DON_DUONGSU_ANPHI;
PROCEDURE CHECK_AHN_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AHN_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=3
    LEFT JOIN AHN_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 3) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 3
    LEFT JOIN AHN_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=3
    LEFT JOIN AHN_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_AHN_DON_DUONGSU_ANPHI;
PROCEDURE CHECK_AKT_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AKT_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=4
    LEFT JOIN AKT_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 4) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 4
    LEFT JOIN AKT_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=4
    LEFT JOIN AKT_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_AKT_DON_DUONGSU_ANPHI;
PROCEDURE CHECK_ALD_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN ALD_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=5
    LEFT JOIN ALD_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 5) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 5
    LEFT JOIN ALD_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=5
    LEFT JOIN ALD_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_ALD_DON_DUONGSU_ANPHI;
PROCEDURE CHECK_APS_DON_DUONGSU_ANPHI
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN APS_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=7
    LEFT JOIN APS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 7) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 7
    LEFT JOIN APS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=7
    LEFT JOIN APS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_APS_DON_DUONGSU_ANPHI;

PROCEDURE APS_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN APS_DON_XULY xl on xl.DONID = d.DONID
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUOIYEUCAUPS' 
    --AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 7) 
    AND xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 7
    LEFT JOIN APS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUOIYEUCAUPS' AND ds.id is not null AND xl.ID is not null
    UNION 
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU,d.TENDUONGSU TENDUONGSUS FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 7
    LEFT JOIN DON_CHITIET ct on ct.ID=ds.DONCHITIETID AND (ct.LOAIDON=5 OR ct.LOAIDON=6)
    WHERE d.DONID = vDONID AND d.TUCACHTOTUNG_MA!='NGUOIYEUCAUPS' AND ds.id is not null;
END APS_DON_DUONGSU_ANPHI_V2;
PROCEDURE CHECK_ADS_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN ADS_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=2
    LEFT JOIN ADS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 2) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM ADS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 2
    LEFT JOIN ADS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=2
    LEFT JOIN ADS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_ADS_DON_DUONGSU_ANPHI_V2;
  PROCEDURE CHECK_AHC_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AHC_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=6
    LEFT JOIN AHC_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 6) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM AHC_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 6
    LEFT JOIN AHC_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=6
    LEFT JOIN AHC_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_AHC_DON_DUONGSU_ANPHI_V2;
 PROCEDURE CHECK_AHN_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AHN_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=3
    LEFT JOIN AHN_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 3) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM AHN_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 3
    LEFT JOIN AHN_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=3
    LEFT JOIN AHN_ANPHI p on p.DUONGSU_IDS like '%' || d.ID || '%' and p.donid = vDONID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_AHN_DON_DUONGSU_ANPHI_V2;
  PROCEDURE CHECK_AKT_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN AKT_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=4
    LEFT JOIN AKT_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 4) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM AKT_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 4
    LEFT JOIN AKT_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=4
    LEFT JOIN AKT_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
END CHECK_AKT_DON_DUONGSU_ANPHI_V2;
PROCEDURE CHECK_ALD_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN ALD_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=5
    LEFT JOIN ALD_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 5) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM ALD_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 5
    LEFT JOIN ALD_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=5
    LEFT JOIN ALD_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUYENDON' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_ALD_DON_DUONGSU_ANPHI_V2;
  PROCEDURE CHECK_APS_DON_DUONGSU_ANPHI_V2
(
  vDONID IN VARCHAR2,
  vDONCHITIETID IN VARCHAR2,
  vISDONCHITIET IN VARCHAR2,
  CurReturn OUT sys_refcursor 
) IS 
BEGIN
OPEN curReturn FOR  
      SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN APS_DON_XULY xl on xl.DONID = d.DONID
    LEFT JOIN DON_YEUCAUBOSUNG y on y.DONID = d.DONID AND y.LOAIAN=7
    LEFT JOIN APS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 0 AND d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUOIYEUCAUPS' 
    AND NOT EXISTS(SELECT 'X' FROM DON_DUONGSU_CHITIET ct WHERE ct.DUONGSUID = d.ID AND ct.loaian = 7) 
    AND ((xl.DONID = vDONID AND xl.LOAIGIAIQUYET = 5) OR (y.DONID = vDONID AND y.LOAIGIAIQUYET = 5)) AND p.ID is not null
    UNION
    SELECT d.ID, d.TENDUONGSU || ' - ' || i.TEN AS TENDUONGSU, p.SOBIENLAI FROM APS_DON_DUONGSU d
    left join DM_DATAITEM i on i.MA=d.TUCACHTOTUNG_MA
    LEFT JOIN DON_DUONGSU_CHITIET ds on d.ID=ds.duongsuid AND ds.loaian = 7
    LEFT JOIN APS_DON_XULY xl on xl.don_chitietid = ds.DONCHITIETID AND xl.LOAIGIAIQUYET = 5
    LEFT JOIN DON_YEUCAUBOSUNG y on y.don_chitietid = ds.DONCHITIETID AND y.LOAIGIAIQUYET = 5 AND y.LOAIAN=7
    LEFT JOIN APS_ANPHI p on p.DUONGSU_ID = d.ID
    WHERE vISDONCHITIET = 1 and d.DONID = vDONID AND d.TUCACHTOTUNG_MA='NGUOIYEUCAUPS' AND ds.id is not null AND (xl.ID is not null OR y.ID is not null)
    AND p.ID is not null;
  END CHECK_APS_DON_DUONGSU_ANPHI_V2;

END PKG_DUONGSU_ANPHI;

/
