--------------------------------------------------------
--  DDL for Package Body PKG_TUPHAP_ANPHI_GET
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_TUPHAP_ANPHI_GET" AS
FUNCTION GET_SOLUONG
(
   V_USERNAME IN VARCHAR2 DEFAULT NULL,
   V_DONVITHA_ID  IN VARCHAR2 DEFAULT NULL
)
RETURN SYS_REFCURSOR
AS
       v_cursor SYS_REFCURSOR;V_COUNT_ALL NUMBER;V_COUNT_CHUANOP NUMBER;V_COUNT_DANOP NUMBER;
       V_TIEN_ALL NUMBER;V_TIEN_DANOP NUMBER;V_TIEN_CHUANOP NUMBER;V_TIEN_HOANTRA NUMBER:=0;V_VUVIEC_HOANTRA NUMBER:=0;
       v_table TUPHAP_ANPHI_COUNT;V_LOAITOA VARCHAR2(150):=NULL;
       V_COUNT_DINHCHI NUMBER;V_TIEN_DINHCHI NUMBER;
       V_CREATE_DATE DATE; VV_CREATE_DATE  DATE;
       V_CREATE_DATE_HETONG DATE;--VV_USERNAME  VARCHAR2(512);
BEGIN
    IF(V_DONVITHA_ID IS NOT NULL) THEN
        SELECT THA.LOAITOA INTO V_LOAITOA FROM DM_DONVITHIHANHAN THA WHERE THA.ID=V_DONVITHA_ID;
      END IF;
    ----------------------
      BEGIN
      --lấy ngày mới nhất khi chạy job của hệ thống
       SELECT TT.CREATE_DATE INTO V_CREATE_DATE_HETONG FROM(
            SELECT TH.CREATE_DATE FROM TUPHAP_ANPHI_TOTAL TH 
            WHERE (V_DONVITHA_ID IS NULL OR (V_LOAITOA='TOICAO' or TH.DONVITHA_ID=V_DONVITHA_ID))
            AND TH.CREATE_USER='JOB_HETHONG'
            ORDER BY TH.CREATE_DATE DESC
            )TT WHERE ROWNUM=1;
       --lấy ngày mới nhất nếu chạy thủ công     
        SELECT TT.CREATE_DATE INTO V_CREATE_DATE FROM(
            SELECT TH.CREATE_DATE FROM TUPHAP_ANPHI_TOTAL TH 
            WHERE (V_DONVITHA_ID IS NULL OR (V_LOAITOA='TOICAO' or TH.DONVITHA_ID=V_DONVITHA_ID))
            AND TH.CREATE_USER=V_USERNAME
            ORDER BY TH.CREATE_DATE DESC
            )TT WHERE ROWNUM=1;
        EXCEPTION
              WHEN NO_DATA_FOUND THEN
                 SELECT NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL INTO V_COUNT_ALL,V_COUNT_DANOP,V_COUNT_CHUANOP
                 ,V_VUVIEC_HOANTRA,V_COUNT_DINHCHI,V_TIEN_ALL,V_TIEN_DANOP,V_TIEN_CHUANOP,V_TIEN_HOANTRA,V_TIEN_DINHCHI
                FROM DUAL;
        END;
        --so sánh chạy thủ công và chạy job ngày nào mới hơn thì lấy
        if(V_CREATE_DATE is null) then 
             VV_CREATE_DATE:=V_CREATE_DATE_HETONG;
        ELSIF(V_CREATE_DATE_HETONG is null) THEN
             VV_CREATE_DATE:=V_CREATE_DATE;
        ELSIF(V_CREATE_DATE<V_CREATE_DATE_HETONG) THEN
             VV_CREATE_DATE:=V_CREATE_DATE_HETONG;
         ELSIF(V_CREATE_DATE>V_CREATE_DATE_HETONG) THEN
             VV_CREATE_DATE:=V_CREATE_DATE;
        END IF;
       
         ---------------
         SELECT SUM(TP.COUNT_DANOP+TP.COUNT_CHUANOP),SUM(TP.COUNT_DANOP),SUM(TP.COUNT_CHUANOP),
                 SUM(TP.TIEN_DANOP+TP.TIEN_CHUANOP),SUM(TP.TIEN_DANOP),SUM(TP.TIEN_CHUANOP),SUM(TP.VUVIEC_HOANTRA),SUM(TP.TIEN_HOANTRA),
                 SUM(TP.COUNT_DINHCHI),SUM(TP.TIEN_DINHCHI)
                 INTO V_COUNT_ALL,V_COUNT_DANOP,V_COUNT_CHUANOP,V_TIEN_ALL,V_TIEN_DANOP,V_TIEN_CHUANOP,V_VUVIEC_HOANTRA,V_TIEN_HOANTRA,
                 V_COUNT_DINHCHI,V_TIEN_DINHCHI
         FROM TUPHAP_ANPHI_TOTAL TP
         WHERE  TP.CREATE_DATE=VV_CREATE_DATE
         AND ((TP.DONVITHA_ID=V_DONVITHA_ID AND V_DONVITHA_ID IS NOT NULL AND V_LOAITOA!='TOICAO') OR (V_DONVITHA_ID IS NULL OR V_LOAITOA='TOICAO')) 
         ;

     OPEN v_cursor FOR
         SELECT V_COUNT_ALL V_COUNT_ALL,V_COUNT_DANOP V_COUNT_DANOP,V_COUNT_CHUANOP V_COUNT_CHUANOP
         ,V_VUVIEC_HOANTRA V_VUVIEC_HOANTRA,V_COUNT_DINHCHI V_COUNT_DINHCHI
         ,rtrim(to_char(V_TIEN_ALL, 'FM9G999G999G999G999G999D999', 'NLS_NUMERIC_CHARACTERS='',.'''),',')V_TIEN_ALL
         ,rtrim(to_char(V_TIEN_DANOP, 'FM9G999G999G999G999G999D999', 'NLS_NUMERIC_CHARACTERS='',.'''),',')V_TIEN_DANOP
         ,rtrim(to_char(V_TIEN_CHUANOP, 'FM9G999G999G999G999G999D999', 'NLS_NUMERIC_CHARACTERS='',.'''),',')V_TIEN_CHUANOP
         ,rtrim(to_char(V_TIEN_HOANTRA, 'FM9G999G999G999G999G999D999', 'NLS_NUMERIC_CHARACTERS='',.'''),',')V_TIEN_HOANTRA
         ,rtrim(to_char(V_TIEN_DINHCHI, 'FM9G999G999G999G999G999D999', 'NLS_NUMERIC_CHARACTERS='',.'''),',')V_TIEN_DINHCHI
         FROM DUAL;

        RETURN v_cursor;   
END GET_SOLUONG;
END PKG_TUPHAP_ANPHI_GET;

/
