--------------------------------------------------------
--  DDL for Package Body PKG_GSTP_DELETE
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "GSCM"."PKG_GSTP_DELETE" AS

FUNCTION HISTORY_DELETE_HOSO_AN_SOTHAM_VUANID
(
  in_VUANID IN NUMBER,
  in_LOAIANID IN NUMBER,
  in_NGUOIXOAID IN VARCHAR2,
  in_TAIKHOANXOA IN VARCHAR2,
  in_TENCHUCNANG IN VARCHAR2,
  in_HANHDONG     IN VARCHAR2,
  in_OBJECT     IN CLOB
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	vMAVUVIEC VARCHAR2(1000):=''; vTENVUVIEC VARCHAR2(1000):='';
    vTENTOAAN VARCHAR2(1000):=''; vTOAAN_ID number:=null;
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
    IF (in_LOAIANID = 1) THEN
        SELECT  d.MAVUAN,d.TENVUAN,T.TEN,t.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN,vTOAAN_ID  
                    FROM AHS_VUAN d 
                    LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
    ELSIF (in_LOAIANID = 2) THEN
        SELECT  d.MAVUVIEC,d.TENVUVIEC,T.TEN,T.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID  
                    FROM ADS_DON d 
                    LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
    ELSIF (in_LOAIANID = 3) THEN
        SELECT  d.MAVUVIEC,d.TENVUVIEC,T.TEN,T.ID  
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID  
                    FROM AHN_DON d 
                      LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
    ELSIF (in_LOAIANID = 4) THEN
        SELECT  d.MAVUVIEC,d.TENVUVIEC,T.TEN,T.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID   
                    FROM AKT_DON d 
                       LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
     ELSIF (in_LOAIANID = 5) THEN
        SELECT  d.MAVUVIEC,d.TENVUVIEC,T.TEN,T.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID   
                    FROM ALD_DON d 
                       LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
     ELSIF (in_LOAIANID = 6) THEN
        SELECT  d.MAVUVIEC,d.TENVUVIEC,T.TEN,T.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID   
                    FROM AHC_DON d 
                        LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
     ELSIF (in_LOAIANID = 7) THEN
        SELECT  d.MAVUVIEC,d.TENVUVIEC,T.TEN,T.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID   
                    FROM APS_DON d 
                        LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
        WHERE d.ID = in_VUANID;
     ELSIF (in_LOAIANID = 8) THEN
          SELECT  d.ID,DECODE(D.LOAIDON,4,KS.TEN,6,d.CV_TENDONVI,9,d.CV_TENDONVI,d.DONGKHIEUNAI)
         ,T.TEN,T.ID 
            into vMAVUVIEC, vTENVUVIEC, vTENTOAAN, vTOAAN_ID   
            
                    FROM GDTTT_DON d 
                        LEFT JOIN DM_TOAAN t on t.id = d.TOAANID
                        LEFT JOIN DM_VKS KS ON KS.ID=D.DONVICHUYEN_HSKN
        WHERE d.ID = in_VUANID;
    END IF;
	--
	SAVEPOINT P1;
	-- Lưu thong tin co ban Hô so án xoa
    INSERT INTO HISTORY_DELETE_HOSO_AN_SOTHAM 
                    (ID,LOAIAN,MAVUVIEC,TENVUVIEC,TENTOAAN,TOAAN_ID,TAIKHOANXOA,NGUOIXOA,NGAYXOA,
                    TENCHUCNANG,HANHDONG,NOIDUNG) 
            values (HISTORY_DELETE_HOSO_AN_SOTHAM_SEQ.NEXTVAL,in_LOAIANID,vMAVUVIEC,vTENVUVIEC,vTENTOAAN,vTOAAN_ID,in_TAIKHOANXOA,in_NGUOIXOAID,SYSDATE,
                    in_TENCHUCNANG,in_HANHDONG,in_OBJECT);
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR AHS: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_AHS_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Án hình sự 	
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM AHS_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM AHS_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_NGUOIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM AHS_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM AHS_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM AHS_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	--
	SAVEPOINT P1;
	DELETE FROM AHS_BICANBICAO WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_BICAN_NHANTHAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_NGUOITHAMGIATOTUNG_TUCACH WHERE TO_CHAR(NGUOIID) IN (v_NGUOIID);
    DELETE FROM AHS_NGUOI_DAIDIEN WHERE TO_CHAR(NGUOI_TGTT_ID) IN (v_NGUOIID);
	DELETE FROM AHS_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_BANAN_BICAO WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_BANAN_DIEU_CT WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_BICANBICAO WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_QUYETDINH_BICAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_QUYETDINH_VUAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM HOSO_PT WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    
    --PTKCKN QDK --TOANCAU
	DELETE FROM AHS_KCKNQDK_PHUCTHAM_BICANBICAO WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_KCKNQDK_PHUCTHAM_QUYETDINH_BICAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_KCKNQDK_PHUCTHAM_QUYETDINH_VUAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM AHS_KCKNQDK_PHUCTHAM_XULY_KCKNST WHERE INSTR(v_VUANID,TO_CHAR(','||VUANPT_ID||','))>0;
    --PTKCKN QDK
    
	DELETE FROM AHS_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_BANAN_BICAO WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHS_SOTHAM_BANAN_DIEU_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_BANAN_DIEU_TONGHOP WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHS_SOTHAM_BIENPHAPNGANCHAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM AHS_BIENPHAPNGANCHAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_CAOTRANG_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_KHANGCAO_YEUCAU WHERE INSTR(v_KHANGCAOID,TO_CHAR(','||KHANGCAOID||','))>0;
	DELETE FROM AHS_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_KHANGNGHI_YEUCAU WHERE INSTR(v_KHANGNGHIID,TO_CHAR(','||KHANGNGHIID||','))>0;
	DELETE FROM AHS_SOTHAM_QUYETDINH_BICAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_QUYETDINH_VUAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_SOTHAM_RUTKHANGCAO WHERE INSTR(v_KHANGCAOID,TO_CHAR(','||KHANGCAOID||','))>0;
	DELETE FROM AHS_SOTHAM_RUTKHANGNGHI WHERE INSTR(v_KHANGNGHIID,TO_CHAR(','||KHANGNGHIID||','))>0;
	DELETE FROM AHS_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_THAMPHANGIAIQUYET WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM AHS_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHS_VUAN WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM AHS_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM AHS_VUAN_GIAIDOAN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR AHS: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_ADS_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Án dân sự
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM ADS_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM ADS_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM ADS_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM ADS_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
    --Xoá hoà giải
    FOR R_HGD IN (SELECT ID FROM HOAGIAI_DON WHERE INSTR(v_VUANID,TO_CHAR(','||VUVIECID||','))>0 AND LOAIANID = 2)
    LOOP
        DELETE HOAGIAI_DENGHI_KIENNGHI_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DENGHI_KIENNGHI WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_QUYETDINH WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_GHINHANKETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THAMPHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON_GIAONHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_DUONGSU WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON WHERE ID = R_HGD.ID;
    END LOOP;
    --Xoá hoà giải
	DELETE FROM ADS_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM ADS_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM ADS_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_DON_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM ADS_PHUCTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;	
    --PTKCKN QDK --TOANCAU
	DELETE FROM ADS_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK
	DELETE FROM ADS_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM ADS_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_BANAN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_BANAN_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ADS_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM ADS_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM ADS_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM ADS_DON_GIAIDOAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=2);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=2;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR ADS: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_AHN_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Án hôn nhân
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM AHN_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM AHN_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_NGUOIID:='';
	--SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM AHN_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM AHN_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM AHN_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
    --Xoá hoà giải
    FOR R_HGD IN (SELECT ID FROM HOAGIAI_DON WHERE INSTR(v_VUANID,TO_CHAR(','||VUVIECID||','))>0 AND LOAIANID = 3)
    LOOP
        DELETE HOAGIAI_DENGHI_KIENNGHI_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DENGHI_KIENNGHI WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_QUYETDINH WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_GHINHANKETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THAMPHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON_GIAONHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_DUONGSU WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON WHERE ID = R_HGD.ID;
    END LOOP;
    --Xoá hoà giải
	DELETE FROM AHN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHN_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM AHN_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_DON_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHN_PHUCTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK --TOANCAU
	DELETE FROM AHN_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK
    DELETE FROM AHN_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHN_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_BANAN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_BANAN_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHN_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM AHN_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHN_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM AHN_DON_GIAIDOAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=3);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=3;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR AHN: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_AKT_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Án kinh tế 
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM AKT_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM AKT_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_NGUOIID:='';
	--SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM AKT_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM AKT_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM AKT_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
    --Xoá hoà giải
    FOR R_HGD IN (SELECT ID FROM HOAGIAI_DON WHERE INSTR(v_VUANID,TO_CHAR(','||VUVIECID||','))>0 AND LOAIANID = 3)
    LOOP
        DELETE HOAGIAI_DENGHI_KIENNGHI_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DENGHI_KIENNGHI WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_QUYETDINH WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_GHINHANKETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THAMPHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON_GIAONHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_DUONGSU WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON WHERE ID = R_HGD.ID;
    END LOOP;
    --Xoá hoà giải
	DELETE FROM AKT_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AKT_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM AKT_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_DON_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AKT_PHUCTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK --TOANCAU
	DELETE FROM AKT_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK
    DELETE FROM AKT_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AKT_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_BANAN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_BANAN_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AKT_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM AKT_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AKT_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM AKT_DON_GIAIDOAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=4);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=4;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR AKT: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;		
END;

FUNCTION DELETE_DATA_ALD_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Án lao động 
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM ALD_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM ALD_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_NGUOIID:='';
	--SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM ALD_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM ALD_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM ALD_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
    --Xoá hoà giải
    FOR R_HGD IN (SELECT ID FROM HOAGIAI_DON WHERE INSTR(v_VUANID,TO_CHAR(','||VUVIECID||','))>0 AND LOAIANID = 5)
    LOOP
        DELETE HOAGIAI_DENGHI_KIENNGHI_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DENGHI_KIENNGHI WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_QUYETDINH WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_GHINHANKETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THAMPHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON_GIAONHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_DUONGSU WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON WHERE ID = R_HGD.ID;
    END LOOP;
    --Xoá hoà giải
	DELETE FROM ALD_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM ALD_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM ALD_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_DON_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM ALD_PHUCTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK --TOANCAU
	DELETE FROM ALD_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK
    DELETE FROM ALD_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM ALD_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_BANAN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_BANAN_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM ALD_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM ALD_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM ALD_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM ALD_DON_GIAIDOAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=5);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=5;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR ALD: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;		
END;

FUNCTION DELETE_DATA_AHC_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Xử lý hành chính
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM AHC_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM AHC_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_NGUOIID:='';
	--SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM AHC_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM AHC_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM AHC_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
    --Xoá hoà giải
    FOR R_HGD IN (SELECT ID FROM HOAGIAI_DON WHERE INSTR(v_VUANID,TO_CHAR(','||VUVIECID||','))>0 AND LOAIANID = 6)
    LOOP
        DELETE HOAGIAI_DENGHI_KIENNGHI_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DENGHI_KIENNGHI WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_QUYETDINH WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_GHINHANKETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THAMPHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON_GIAONHAN WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_KETQUA WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO_DUONGSU WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_THONGBAO WHERE HOAGIAIID = R_HGD.ID;
        DELETE HOAGIAI_DON WHERE ID = R_HGD.ID;
    END LOOP;
    --Xoá hoà giải
	DELETE FROM AHC_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHC_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM AHC_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_DON_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM AHC_PHUCTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_DOITHOAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK --TOANCAU
	DELETE FROM AHC_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK
    DELETE FROM AHC_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHC_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_BANAN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_BANAN_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_DOITHOAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_HOAGIAI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM AHC_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM AHC_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM AHC_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM AHC_DON_GIAIDOAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=6);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=6;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR AHC: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_APS_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Tuyên bố phá sản 
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM APS_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM APS_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_NGUOIID:='';
	--SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM APS_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM APS_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM APS_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
	DELETE FROM APS_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM APS_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM APS_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_DON_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM APS_PHUCTHAM_BANAN_TGTT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--PTKCKN QDK --TOANCAU
	DELETE FROM APS_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
    --PTKCKN QDK
    DELETE FROM APS_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM APS_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_BANAN_ANPHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_BANAN_DIEULUAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_HN_CHUNO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM APS_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM APS_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM APS_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=7);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=7;
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR APS: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_XLHC_BY_VUANID
(
  in_VUANID IN NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_BANANID NVARCHAR2(4000):='';
	v_TONGDATID NVARCHAR2(4000):='';
	v_NGUOIID NVARCHAR2(4000):='';
	v_KHANGCAOID NVARCHAR2(4000):='';
	v_KHANGNGHIID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID VỤ ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_VUANID:=regexp_replace(in_VUANID, '[[:space:]]+', '');
	v_VUANID:=','||v_VUANID||',';
	--
	--Án hành chính 
	v_BANANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_BANANID FROM XLHC_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_TONGDATID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TONGDATID FROM XLHC_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_NGUOIID:='';
	--SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_NGUOIID FROM XLHC_NGUOITHAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	v_KHANGCAOID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGCAOID FROM XLHC_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	v_KHANGNGHIID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_KHANGNGHIID FROM XLHC_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	--
	SAVEPOINT P1;
	DELETE FROM XLHC_CHUYEN_NHAN_AN WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM XLHC_DON WHERE INSTR(v_VUANID,TO_CHAR(','||ID||','))>0;
	DELETE FROM XLHC_DONXIN_HOAN_MIEN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_DON_BANGIAO_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_DON_TAILIEU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_DON_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_DON_THAMPHAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_DON_XULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_BANAN_FILE WHERE INSTR(v_BANANID,TO_CHAR(','||BANANID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_DUONGSU WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SAUXETXU WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM XLHC_SOTHAM_BANAN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_BANAN_FILE WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_KHANGCAO WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_KHANGNGHI WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_RUTKCKN WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_SOTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_TONGDAT WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
	DELETE FROM XLHC_TONGDAT_DOITUONG WHERE INSTR(v_TONGDATID,TO_CHAR(','||TONGDATID||','))>0;
	DELETE FROM XLHC_TRUNGCAU_GIAMDINH WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
	DELETE FROM XLHC_XULY_VIPHAMHC WHERE INSTR(v_VUANID,TO_CHAR(','||VUANID||','))>0;
    DELETE FROM DON_CHITIET_DUONGSU DS WHERE INSTR(v_VUANID,TO_CHAR(','||DS.DONID||','))>0 
    AND EXISTS(SELECT 'X' FROM DON_CHITIET CT WHERE CT.ID=DS.DONID AND CT.LOAIANID=8);
    DELETE FROM DON_CHITIET WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0 AND LOAIANID=8;
   	--PTQDK vnpt 26/06/2025: xoa bang kckcqdk
    DELETE FROM XLHC_KCKNQDK_PHUCTHAM_THAMGIATOTUNG WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
  	DELETE FROM XLHC_KCKNQDK_PHUCTHAM_HDXX WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
  	DELETE FROM XLHC_KCKNQDK_PHUCTHAM_QUYETDINH WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
  	DELETE FROM XLHC_KCKNQDK_PHUCTHAM_THULY WHERE INSTR(v_VUANID,TO_CHAR(','||DONID||','))>0;
  	--PTQDK vnpt 26/06/2025: xoa bang kckcqdk
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=SUBSTR(SQLERRM, 1, 4000);
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR XLHC: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_BY_TOAANID
(
  in_TOAANID IN NVARCHAR2,
  in_TOAANCAPCON IN BOOLEAN,--giá trị là:'true/false' sẽ xóa các dữ liệu của các tòa cấp con
  out_RESULT OUT NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
	v_TOAANID NVARCHAR2(4000):='';
	v_TOAANCAPCONID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->ID TÒA ÁN CÓ THỂ TRUYỀN VÀO DANH SÁCH CÁCH NHAU BỞI DẤU PHẨY
	-->LẤY DANH SÁCH ID VỤ ÁN TỪ TÒA ÁN, GỌI HÀM XÓA DỮ LIỆU THEO TỪNG LOẠI VỤ ÁN
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	v_TOAANID:=regexp_replace(in_TOAANID, '[[:space:]]+', '');
	v_TOAANID:=','||v_TOAANID||',';
	--
	--TÒA ÁN CẤP CON
	IF (in_TOAANCAPCON) THEN
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_TOAANCAPCONID FROM DM_TOAAN WHERE CAPCHAID=cast(in_TOAANID as number);
		v_TOAANID:=v_TOAANID||v_TOAANCAPCONID;
	END IF;
	--
	--Án hình sự
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AHS_VUAN WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_AHS_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'AHS:SUCESSFUL;';
        COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'AHS:FAILED;';
	END IF;
	--
	--Án dân sự 
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM ADS_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_ADS_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'ADS:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'ADS:FAILED;';
	END IF;
	--Án hôn nhân 
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AHN_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_AHN_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'AHN:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'AHN:FAILED;';
	END IF;
	--
	--Án kinh tế 
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AKT_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_AKT_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'AKT:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'AKT:FAILED;';
	END IF;
	--
	--Án lao động 
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM ALD_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_ALD_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'ALD:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'ALD:FAILED;';
	END IF;
	--
	--Án hành chính 
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AHC_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_AHC_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'AHC:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'AHC:FAILED;';
	END IF;	
	--
	--Tuyên bố phá sản 
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM APS_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_APS_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'APS:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'APS:FAILED;';
	END IF;	
	--
	--Xử lý hành chính
	v_VUANID:='';
	SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM XLHC_DON WHERE INSTR(v_TOAANID,TO_CHAR(','||TOAANID||','))>0;
	IF (DELETE_DATA_XLHC_BY_VUANID(v_VUANID)=1) THEN
		v_ERROR:=v_ERROR||'XLHC:SUCESSFUL;';
         COMMIT;
	ELSE
		v_ERROR:=v_ERROR||'XLHC:FAILED;';
	END IF;
	--
	--THÔNG BÁO CHI TIẾT KẾT QUẢ XÓA
	out_RESULT:=v_ERROR;	
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=v_ERROR||SUBSTR(SQLERRM, 1, 4000);
	out_RESULT:=v_ERROR;
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_BY_LOAIAN
(
  in_LOAIAN IN NVARCHAR2,
  out_RESULT OUT NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(4000):='';
BEGIN
	-->GHI CHÚ: 
	-->LOẠI ÁN: AHS, ADS, AHN, AKT, ALD, AHC, APS, XLHC
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	--Án hình sự
	IF (in_LOAIAN='AHS') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AHS_VUAN;
		IF (DELETE_DATA_AHS_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AHS:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AHS:FAILED;';
		END IF;
	END IF;
	--
	--Án dân sự 
	IF (in_LOAIAN='ADS') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM ADS_DON;
		IF (DELETE_DATA_ADS_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'ADS:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'ADS:FAILED;';
		END IF;
	END IF;
	--
	--Án hôn nhân  
	IF (in_LOAIAN='AHN') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AHN_DON;
		IF (DELETE_DATA_AHN_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AHN:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AHN:FAILED;';
		END IF;
	END IF;
	--
	--Án kinh tế  
	IF (in_LOAIAN='AKT') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AKT_DON;
		IF (DELETE_DATA_AKT_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AKT:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AKT:FAILED;';
		END IF;
	END IF;
	--
	--Án lao động  
	IF (in_LOAIAN='ALD') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM ALD_DON;
		IF (DELETE_DATA_ALD_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'ALD:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'ALD:FAILED;';
		END IF;
	END IF;
	--
	--Án hành chính  
	IF (in_LOAIAN='AHC') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM AHC_DON;
		IF (DELETE_DATA_AHC_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AHC:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AHC:FAILED;';
		END IF;	
	END IF;
	--
	--Tuyên bố phá sản  
	IF (in_LOAIAN='APS') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM APS_DON;
		IF (DELETE_DATA_APS_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'APS:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'APS:FAILED;';
		END IF;	
	END IF;
	--
	--Xử lý hành chính 
	IF (in_LOAIAN='XLHC') THEN
		v_VUANID:='';
		SELECT LISTAGG(','||ID||',', '') WITHIN GROUP (ORDER BY ID) INTO v_VUANID FROM XLHC_DON;
		IF (DELETE_DATA_XLHC_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'XLHC:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'XLHC:FAILED;';
		END IF;
	END IF;
	--
	--THÔNG BÁO CHI TIẾT KẾT QUẢ XÓA
	out_RESULT:=v_ERROR;	
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=v_ERROR||SUBSTR(SQLERRM, 1, 4000);
	out_RESULT:=v_ERROR;
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

FUNCTION DELETE_DATA_BY_VUANID
(
  in_VUANID IN NVARCHAR2,
  in_LOAIAN IN NVARCHAR2,
  out_RESULT OUT NVARCHAR2
) RETURN NUMBER AS
	v_ERROR NVARCHAR2(4000):='';
	v_VUANID NVARCHAR2(20):=in_VUANID;
BEGIN
	-->GHI CHÚ: 
	-->LOẠI ÁN: AHS, ADS, AHN, AKT, ALD, AHC, APS, XLHC
	-->HÀM TRẢ VỀ 1 LÀ XÓA THÀNH CÔNG KHÔNG CÓ LỖI
	-->HÀM TRẢ VỀ -1 LÀ CÓ LỖI XẢY RA TRONG KHI XÓA
	--
	--Án hình sự
	IF (in_LOAIAN='AHS') THEN
		IF (DELETE_DATA_AHS_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AHS:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AHS:FAILED;';
		END IF;
	END IF;
	--
	--Án dân sự 
	IF (in_LOAIAN='ADS') THEN
		IF (DELETE_DATA_ADS_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'ADS:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'ADS:FAILED;';
		END IF;
	END IF;
	--
	--Án hôn nhân  
	IF (in_LOAIAN='AHN') THEN
		IF (DELETE_DATA_AHN_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AHN:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AHN:FAILED;';
		END IF;
	END IF;
	--
	--Án kinh tế  
	IF (in_LOAIAN='AKT') THEN
		IF (DELETE_DATA_AKT_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AKT:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AKT:FAILED;';
		END IF;
	END IF;
	--
	--Án lao động  
	IF (in_LOAIAN='ALD') THEN
		IF (DELETE_DATA_ALD_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'ALD:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'ALD:FAILED;';
		END IF;
	END IF;
	--
	--Án hành chính  
	IF (in_LOAIAN='AHC') THEN
		IF (DELETE_DATA_AHC_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'AHC:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'AHC:FAILED;';
		END IF;	
	END IF;
	--
	--Tuyên bố phá sản  
	IF (in_LOAIAN='APS') THEN
		IF (DELETE_DATA_APS_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'APS:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'APS:FAILED;';
		END IF;	
	END IF;
	--
	--Xử lý hành chính 
	IF (in_LOAIAN='XLHC') THEN
		IF (DELETE_DATA_XLHC_BY_VUANID(v_VUANID)=1) THEN
			v_ERROR:=v_ERROR||'XLHC:SUCESSFUL;';
		ELSE
			v_ERROR:=v_ERROR||'XLHC:FAILED;';
		END IF;
	END IF;
	--
	--THÔNG BÁO CHI TIẾT KẾT QUẢ XÓA
	out_RESULT:=v_ERROR;	
	--
	RETURN 1;
	--
EXCEPTION
WHEN OTHERS THEN
	v_ERROR:=v_ERROR||SUBSTR(SQLERRM, 1, 4000);
	out_RESULT:=v_ERROR;
	--SET SERVEROUTPUT ON
	DBMS_OUTPUT.PUT_LINE ('ERROR: ' || v_ERROR);
	ROLLBACK TO SAVEPOINT P1;
	RETURN -1;	
END;

END PKG_GSTP_DELETE;

/
