CREATE OR REPLACE PACKAGE BODY GSCM.PKG_THA_BIEUMAU
AS
  -- Package body

  PROCEDURE DELETE_THA_FILE_VUANIDBIAN_QUYETDINH(
      v_vuanID   IN NUMBER,
      v_bianID   IN NUMBER,
      v_listMABM IN VARCHAR2  -- danh sách mã BM, ví dụ: 'THA-01,THA-02,THA-03'
  )
  AS
BEGIN
DELETE FROM THA_FILE
WHERE VUANID = v_vuanID
  AND BIANID = v_bianID
  AND BIEUMAUID IN (
    SELECT ID
    FROM DM_BIEUMAU db
    WHERE INSTR(',' || v_listMABM || ',', ',' || db.MABM || ',') > 0
);
COMMIT;
END DELETE_THA_FILE_VUANIDBIAN_QUYETDINH;

END PKG_THA_BIEUMAU;